#!/usr/bin/env python3
"""Generate medical-assisting.html from dental-science.html template."""
import os, re

BASE = '/home/user/hosa-prep-hub'
SRC  = os.path.join(BASE, 'dental-science.html')
DST  = os.path.join(BASE, 'medical-assisting.html')

with open(SRC, 'r', encoding='utf-8') as f:
    html = f.read()

TERMS_JS = '''const TERMS = [
  // ── Administrative Skills ────────────────────────────────────
  { term: "SOAP Note", type: "concept", category: "administrative", meaning: "A structured documentation format: Subjective (patient's complaint in their words), Objective (measured findings — vitals, exam), Assessment (diagnosis or differential), Plan (treatment, referrals, follow-up).", example: "The MA documented the visit in SOAP format: S — chest pain for 2 days; O — BP 148/92, HR 96; A — hypertension, uncontrolled; P — increase lisinopril, recheck in 2 weeks." },
  { term: "ICD-10-CM", type: "concept", category: "administrative", meaning: "The International Classification of Diseases, 10th Revision, Clinical Modification — the code set used to report diagnoses on insurance claims. Codes are alphanumeric up to 7 characters (e.g., E11.9 = Type 2 diabetes, uncontrolled).", example: "The MA assigned ICD-10 code J06.9 (upper respiratory infection, unspecified) to the chart before billing the patient's insurance." },
  { term: "CPT Code", type: "concept", category: "administrative", meaning: "Current Procedural Terminology — 5-digit numeric codes maintained by the AMA that describe medical, surgical, and diagnostic procedures billed to insurance (e.g., 99213 = established patient office visit, moderate complexity).", example: "The MA selected CPT 99213 for the 20-minute established-patient visit and CPT 36415 for the routine venipuncture." },
  { term: "HIPAA Privacy Rule", type: "concept", category: "administrative", meaning: "Requires covered entities to protect patients' PHI (Protected Health Information) and sets rules for use and disclosure. Patients have the right to access their records, request corrections, and receive a Notice of Privacy Practices.", example: "When a patient's family member called asking for lab results, the MA confirmed no release authorization was on file and declined to share the information per HIPAA." },
  { term: "Electronic Health Record (EHR)", type: "concept", category: "administrative", meaning: "A digital version of a patient's paper chart that contains medical history, diagnoses, medications, allergies, lab results, and provider notes; must meet Meaningful Use criteria for Medicare/Medicaid reimbursement.", example: "The MA pulled up the patient's EHR, verified current medications and allergies, and pre-loaded vital sign fields before the physician entered the exam room." },
  { term: "Prior Authorization", type: "concept", category: "administrative", meaning: "Advance approval required from an insurance company before certain services, medications, or referrals will be covered; the MA submits clinical documentation to the payer to obtain approval.", example: "The MA submitted the radiologist's MRI order with supporting documentation to the insurance company for prior authorization before scheduling the scan." },
  { term: "Referral vs Consultation", type: "concept", category: "administrative", meaning: "A referral transfers care to a specialist; a consultation seeks specialist opinion while the original provider retains primary care. Many insurance plans require a primary care referral for specialist visits.", example: "The PCP wrote a referral to cardiology for ongoing management, not just a consultation, because the patient's arrhythmia required specialist-led care." },
  { term: "Superbill", type: "concept", category: "administrative", meaning: "A detailed invoice generated after a visit listing all diagnosis codes (ICD-10), procedure codes (CPT), and provider information used to submit an insurance claim or bill the patient.", example: "After the visit the MA generated the superbill with codes E11.9 and 99213 and sent it to the billing department for claim submission." },
  { term: "Appointment Scheduling Systems", type: "concept", category: "administrative", meaning: "Methods such as stream scheduling (one per slot), wave scheduling (multiple per hour), double-booking, and open access used to manage patient flow and minimize wait times in ambulatory care.", example: "The clinic used wave scheduling — two patients booked at the top of each half-hour — so if one arrived late the MA could begin with the other." },
  { term: "Medical Records Release", type: "concept", category: "administrative", meaning: "Records may only be released with a signed patient authorization specifying recipient, records, purpose, and expiration; exceptions include court orders, public health reporting, and treatment continuity.", example: "The patient signed a release form authorizing the MA to send records to the new specialist; the MA verified all required fields were complete before faxing." },

  // ── Clinical Skills ──────────────────────────────────────────
  { term: "Surgical Asepsis vs Medical Asepsis", type: "concept", category: "clinical-skills", meaning: "Medical asepsis reduces pathogen count (clean technique — hand hygiene, gloves). Surgical asepsis eliminates all microorganisms (sterile technique) required for invasive procedures, wound care, and catheter insertion.", example: "The MA used sterile technique to lay out the suture tray — surgical asepsis — while routine wound care after suture removal used clean (medical asepsis) technique." },
  { term: "Sterile Field", type: "concept", category: "clinical-skills", meaning: "A microorganism-free area created with sterile drapes and equipment; anything below waist level, outside the field, or touched by non-sterile hands is considered contaminated and cannot be brought into the field.", example: "When a sterile gauze fell below the table edge, the MA discarded it — below waist = contaminated — and opened a new one into the sterile field." },
  { term: "Wound Irrigation and Packing", type: "concept", category: "clinical-skills", meaning: "Wound irrigation uses saline or antiseptic solution under pressure to remove debris; packing fills a cavity wound with moist gauze to promote healing by secondary intention and prevent abscess formation.", example: "The MA irrigated the 3 cm puncture wound with 50 mL of normal saline from a 35 mL syringe, then loosely packed it with iodoform gauze per the physician's order." },
  { term: "Suture Removal", type: "concept", category: "clinical-skills", meaning: "Sutures are removed after adequate healing: face 3–5 days, scalp 7–10 days, extremity 10–14 days. The MA grasps the knot with forceps, cuts the suture close to the skin, and lifts out to avoid pulling contaminated material through tissue.", example: "On post-op day 10 the MA removed the patient's forearm sutures by grasping each knot, cutting with suture scissors, and pulling the stitch through cleanly." },
  { term: "Electrocardiogram (ECG/EKG) Leads", type: "concept", category: "clinical-skills", meaning: "A 12-lead ECG uses 10 electrodes (4 limb, 6 precordial) to generate 12 views of cardiac electrical activity. Limb leads: RA, LA, RL (ground), LL. Precordial: V1–V6 in specific chest positions.", example: "The MA attached electrodes in correct positions — V1 right sternal border 4th ICS, V4 midclavicular 5th ICS — before running the 12-lead ECG for the patient with chest pain." },
  { term: "Peak Flow Meter", type: "concept", category: "clinical-skills", meaning: "A portable device measuring maximal expiratory flow rate (L/min); used to monitor asthma severity. Values compared to personal best: green ≥80%, yellow 50–79%, red <50%.", example: "The asthmatic patient blew into the peak flow meter three times; the best reading of 320 L/min was 65% of personal best, placing them in the yellow zone." },
  { term: "Spirometry", type: "concept", category: "clinical-skills", meaning: "A pulmonary function test measuring FVC (forced vital capacity), FEV1 (forced expiratory volume in 1 second), and FEV1/FVC ratio; values compared to predicted values based on age, sex, and height.", example: "Spirometry revealed FEV1/FVC of 68% (below 70% threshold), consistent with obstructive lung disease, which the MA documented for the physician's review." },
  { term: "Urinalysis (UA)", type: "concept", category: "clinical-skills", meaning: "A routine test of urine involving physical exam (color, clarity), chemical dipstick (pH, glucose, protein, blood, nitrites, leukocytes), and microscopy (WBCs, RBCs, casts, bacteria).", example: "The in-office UA dipstick showed 3+ leukocytes and positive nitrites, suggesting a urinary tract infection, which the MA flagged for the physician." },
  { term: "Guaiac Fecal Occult Blood Test (gFOBT)", type: "concept", category: "clinical-skills", meaning: "A colorimetric test detecting hidden blood in stool via guaiac-impregnated cards; blue color change after hydrogen peroxide application indicates a positive result warranting further workup.", example: "The MA developed the fecal occult blood card — positive blue color change in both smear windows — and flagged the chart for the physician to order colonoscopy." },
  { term: "Autoclave Sterilization", type: "concept", category: "clinical-skills", meaning: "The most common method of sterilization using steam under pressure (121°C, 15 psi, 15–20 min) to destroy all microorganisms including spores; validated by biological indicators (Geobacillus stearothermophilus spores).", example: "After each surgery the MA loaded wrapped instruments into the autoclave and ran a 30-minute cycle; a biological indicator was tested weekly to verify sterilization efficacy." },

  // ── Vital Signs ──────────────────────────────────────────────
  { term: "Blood Pressure Classification (JNC)", type: "concept", category: "vital-signs", meaning: "Normal: <120/<80; Elevated: 120–129/<80; Stage 1 HTN: 130–139/80–89; Stage 2 HTN: ≥140/≥90; Hypertensive Crisis: >180/>120. Measured in mmHg with patient seated, rested 5 min.", example: "The patient's BP of 158/94 placed them in Stage 2 hypertension; the MA repeated the reading in the other arm and documented both values for the physician." },
  { term: "Korotkoff Sounds", type: "concept", category: "vital-signs", meaning: "Sounds heard through a stethoscope during BP measurement: Phase I (first sound = systolic), II–IV (muffling), Phase V (disappearance = diastolic). The auscultatory gap (silence between phases) must be recognized to avoid underestimating systolic.", example: "The MA overinflated the cuff to 180 mmHg to detect the auscultatory gap, ensuring Phase I Korotkoff sound was not missed and the systolic was accurately identified at 152 mmHg." },
  { term: "Pulse Oximetry", type: "concept", category: "vital-signs", meaning: "Non-invasive measurement of arterial oxygen saturation (SpO2) using infrared/red light absorption through a peripheral tissue (usually fingertip). Normal SpO2 ≥95%; values <90% indicate hypoxemia.", example: "The MA placed the probe on the patient's index finger and recorded SpO2 of 93% — below normal — and alerted the physician immediately for respiratory assessment." },
  { term: "Respiratory Rate Assessment", type: "concept", category: "vital-signs", meaning: "Normal adult RR is 12–20 breaths/min. Counted for a full 60 seconds (or 30 sec × 2) without informing the patient, who may alter breathing if aware of observation.", example: "The MA counted respirations for 60 seconds while appearing to take the pulse so the patient would not consciously alter their breathing pattern." },
  { term: "Temperature Routes and Normal Ranges", type: "concept", category: "vital-signs", meaning: "Oral: 98.6°F (37°C) ±1°. Axillary: ~97.6°F (add 1° to compare oral). Rectal: ~99.6°F (subtract 1°). Tympanic and temporal artery: approximately oral-equivalent. Fever: >100.4°F (38°C).", example: "The infant's rectal temperature was 100.8°F, which — after recognizing the rectal route reads ~1° above oral — indicated an oral-equivalent fever above 100.4°F." },
  { term: "Orthostatic Vital Signs", type: "concept", category: "vital-signs", meaning: "BP and pulse measured supine, then after 1 min standing; a drop in systolic ≥20 mmHg or diastolic ≥10 mmHg with standing suggests orthostatic hypotension from dehydration, blood loss, or autonomic dysfunction.", example: "Supine BP was 130/82; standing it dropped to 108/66 with HR rise from 72 to 96 — orthostatic hypotension confirmed; the MA assisted the patient back to the table immediately." },
  { term: "BMI Calculation", type: "concept", category: "vital-signs", meaning: "Body Mass Index = weight (kg) / height² (m²), or [weight (lb) / height² (in²)] × 703. Categories: underweight <18.5, normal 18.5–24.9, overweight 25–29.9, obese ≥30.", example: "The MA calculated BMI for a 5 ft 6 in, 185 lb patient: [185 / (66²)] × 703 = 29.9, classifying the patient as overweight." },
  { term: "Pain Scale Documentation", type: "concept", category: "vital-signs", meaning: "Numeric Rating Scale (NRS) 0–10 is standard for adults; FACES scale (Wong-Baker) for children or nonverbal patients. Pain is documented as the 5th vital sign with location, quality, and radiation.", example: "The MA asked the patient to rate pain 0–10; the patient chose 7/10 sharp right flank pain radiating to the groin — documented and flagged as the probable renal colic." },

  // ── Pharmacology & Injections ────────────────────────────────
  { term: "Rights of Medication Administration", type: "concept", category: "pharmacology", meaning: "The seven rights: Right Patient, Right Drug, Right Dose, Right Route, Right Time, Right Documentation, Right to Refuse. Every administration is verified against all seven to prevent medication errors.", example: "Before injecting the influenza vaccine, the MA verified all seven rights — confirmed the patient's identity, the correct vaccine lot, the 0.5 mL dose, the deltoid IM route, today's date, the chart entry, and informed the patient of the right to refuse." },
  { term: "Intramuscular (IM) Injection Sites", type: "concept", category: "pharmacology", meaning: "Common IM sites: deltoid (preferred for adults, vaccines), vastus lateralis (preferred for infants/toddlers), ventrogluteal (safest for volume > 1 mL). Dorsogluteal now avoided due to sciatic nerve risk.", example: "The MA administered the hepatitis B vaccine IM into the deltoid at a 90° angle, using a 1-inch, 23-gauge needle." },
  { term: "Subcutaneous (SC) Injection", type: "concept", category: "pharmacology", meaning: "Injection into the hypodermis (fat layer) at 45° angle using ½–⅝ inch needle; slower absorption than IM. Sites: abdomen, outer thigh, back of arm. Used for insulin, heparin, allergy injections.", example: "The diabetic patient's insulin was injected subcutaneously into the abdomen at a 45° angle, rotating from the previous site to prevent lipodystrophy." },
  { term: "Intradermal (ID) Injection", type: "concept", category: "pharmacology", meaning: "Injection into the dermis (inner skin layers) at a 10–15° angle with bevel up, using a 25–27g, ⅜–½ inch needle; produces a wheal (bleb). Used for TB skin test (Mantoux) and allergy testing.", example: "The MA injected 0.1 mL of tuberculin intradermally on the volar forearm at 15°; a 6–10 mm wheal confirmed correct placement." },
  { term: "Controlled Substance Schedules (DEA)", type: "concept", category: "pharmacology", meaning: "DEA Schedule I: no accepted medical use, high abuse (heroin, LSD). II: high abuse, accepted use (oxycodone, amphetamine). III–IV: moderate/lower abuse (codeine combos, benzodiazepines). V: lowest (cough preps with codeine).", example: "The MA verified the patient's opioid prescription was for a Schedule II substance and confirmed the physician had a valid DEA number before calling in the prescription." },
  { term: "Anaphylaxis and Epinephrine", type: "concept", category: "pharmacology", meaning: "Anaphylaxis is a severe systemic allergic reaction with urticaria, bronchospasm, hypotension. First-line treatment is epinephrine 0.3 mg IM in the lateral thigh (auto-injector); antihistamines and steroids are adjuncts.", example: "Five minutes after the penicillin injection, the patient developed hives and wheezing — the MA administered 0.3 mg epinephrine IM, called 911, and placed the patient supine with legs elevated." },
  { term: "Z-Track Injection Technique", type: "concept", category: "pharmacology", meaning: "The skin is pulled laterally 1–1.5 inches before IM injection and held until the needle is withdrawn; the tract is sealed when skin is released, preventing medication from leaking into subcutaneous tissue. Required for irritating drugs like iron dextran.", example: "The MA pulled the skin laterally for the iron dextran injection, inserted the needle at 90°, injected slowly, withdrew the needle, then released the skin to prevent tracking." },
  { term: "Medication Reconstitution", type: "concept", category: "pharmacology", meaning: "Adding diluent (sterile water or normal saline) to a powdered medication according to instructions to achieve the prescribed concentration; requires calculating the correct volume to draw after mixing.", example: "The MA reconstituted 500 mg amoxicillin powder by adding 5 mL sterile water to yield 100 mg/mL, then withdrew 2.5 mL for the 250 mg ordered dose." },

  // ── Laboratory Skills ─────────────────────────────────────────
  { term: "Hematocrit (Spun)", type: "concept", category: "laboratory", meaning: "The percentage of whole blood volume occupied by red blood cells; measured by centrifuging a capillary tube. Normal: men 41–53%, women 36–46%. Decreased in anemia; elevated in dehydration or polycythemia.", example: "The MA spun the capillary tube at 10,000 RPM for 5 minutes; the buffy coat was identified, and hematocrit was read at the 38% line — low-normal for an adult female." },
  { term: "Point-of-Care Testing (POCT)", type: "concept", category: "laboratory", meaning: "Diagnostic testing performed at or near the patient's location (office, bedside) using handheld analyzers; includes glucose meters, rapid strep, influenza, pregnancy tests. Results guide immediate clinical decisions.", example: "The MA ran a rapid strep POCT from the throat swab — positive result in 5 minutes — allowing the physician to prescribe antibiotics during the same visit." },
  { term: "Rapid Streptococcal Antigen Test", type: "concept", category: "laboratory", meaning: "A POCT immunoassay detecting Group A Streptococcus antigen from a throat swab; sensitivity ~85–90%, so a negative result should be confirmed with a throat culture in high-pretest-probability patients.", example: "The rapid strep test was negative, but because the patient had 4/4 Centor criteria, the MA also collected a throat swab for backup culture per protocol." },
  { term: "Glucose Meter (Glucometer) QC", type: "concept", category: "laboratory", meaning: "Quality control requires running low and high control solutions daily and with each new test strip vial to verify the meter is functioning correctly; out-of-range controls mean patient results cannot be reported.", example: "The MA ran high and low glucose controls first thing each morning; both fell within range, validating the glucometer for the day's patient testing." },
  { term: "CLIA Waived Tests", type: "concept", category: "laboratory", meaning: "Under the Clinical Laboratory Improvement Amendments, waived tests (e.g., dipstick UA, blood glucose, rapid strep, hemoglobin, INR home kits) may be performed in physician offices without complex laboratory certification.", example: "The MA confirmed the office held a CLIA Certificate of Waiver before adding urine hCG pregnancy tests to the point-of-care menu." },
  { term: "Capillary (Fingerstick) Blood Collection", type: "concept", category: "laboratory", meaning: "A lancet puncture to the lateral fingertip (or heel in infants) to collect capillary blood for POC testing; the first drop is wiped away (tissue fluid contamination), and subsequent drops are used for collection.", example: "The MA cleaned the patient's ring finger, used a spring-loaded lancet, wiped the first drop, then touched the glucometer strip to the next drop for the fasting glucose reading." },

  // ── Patient Care ──────────────────────────────────────────────
  { term: "Patient-Centered Communication", type: "concept", category: "patient-care", meaning: "An approach that includes active listening, open-ended questions, empathy, clear jargon-free explanations, and teach-back (patient repeats instructions) to ensure understanding and shared decision-making.", example: "After explaining the new medication, the MA used teach-back: 'Can you tell me in your own words when you'll take this and why?' — the patient's response confirmed full understanding." },
  { term: "Informed Consent", type: "concept", category: "patient-care", meaning: "A patient's voluntary, competent agreement to a procedure or treatment after receiving clear information about risks, benefits, alternatives, and consequences of refusal. MAs may witness signatures but not obtain consent.", example: "The physician obtained informed consent for the excision; the MA then witnessed the patient's signature on the consent form and placed it in the chart." },
  { term: "Advance Directives", type: "concept", category: "patient-care", meaning: "Legal documents specifying a patient's wishes for medical care if unable to communicate: Living Will (treatment preferences), Durable Power of Attorney for Healthcare (designates surrogate), and DNR (do not resuscitate).", example: "The MA noted the patient's advance directive was on file — a DNR and living will specifying no mechanical ventilation — and placed the DNR form at the front of the chart." },
  { term: "Therapeutic Communication Techniques", type: "concept", category: "patient-care", meaning: "Techniques include active listening, reflection, open-ended questions, silence, and restating. Non-therapeutic responses include false reassurance, giving advice, changing the subject, or minimizing patient concerns.", example: "When the patient expressed fear about the diagnosis, the MA used reflection: 'It sounds like you're feeling worried about what this means for your daily life' — inviting the patient to share more." },
  { term: "Cultural Competence", type: "concept", category: "patient-care", meaning: "Awareness of and respect for cultural differences in health beliefs, communication styles, dietary practices, and gender-specific care preferences; includes using trained interpreters (not family members) for non-English speakers.", example: "The MA arranged a professional Spanish interpreter for the patient's visit rather than asking the patient's child to translate, preserving accuracy and confidentiality per HIPAA." },
  { term: "Mandatory Reporting", type: "concept", category: "patient-care", meaning: "Healthcare workers are required by law to report certain conditions: child abuse/neglect, elder abuse, domestic violence, gunshot wounds, certain infectious diseases, and impaired drivers in some states.", example: "The MA observed unexplained bruises on the elderly patient and, per mandatory reporting law, completed the elder abuse report and notified the physician for further evaluation." },
  { term: "Scope of Practice (Medical Assistant)", type: "concept", category: "patient-care", meaning: "MAs perform administrative tasks and clinical duties delegated by a licensed provider, but may NOT diagnose, prescribe, interpret lab results independently, or perform procedures not within their training/state law.", example: "When the patient asked the MA if her rash was ringworm, the MA responded, 'I'm not able to diagnose — the physician will examine you and let you know' — staying within scope of practice." },
  { term: "Emergency Preparedness in the Office", type: "concept", category: "patient-care", meaning: "MAs must know the location of crash carts, emergency medications (epinephrine, nitroglycerin, oxygen, aspirin, glucose), AED, and how to activate 911 and perform BLS for in-office cardiac or respiratory emergencies.", example: "When the patient in exam room 2 became unresponsive, the MA called for help, retrieved the AED from the hall, and began BLS compressions while waiting for the physician and 911." },
];'''

m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
if not m: raise SystemExit('TERMS not found')
html = html[:m.start()] + TERMS_JS + html[m.end():]

CAT = """const categoryLabel = c => ({
  'administrative':  'Administrative Skills',
  'clinical-skills': 'Clinical Skills',
  'vital-signs':     'Vital Signs',
  'pharmacology':    'Pharmacology & Injections',
  'laboratory':      'Laboratory Skills',
  'patient-care':    'Patient Care',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)

html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'medical-assisting';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>',
                    '<title>HOSA Prep Hub — Medical Assisting</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>',
                    '<h1>Medical<br><em>Assisting</em>.</h1>', 1)
html = html.replace(
    'A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
    'A study companion for administrative skills, clinical procedures, vital signs, pharmacology and injections, laboratory testing, and patient care — built for HOSA competitors.',
    1
)
html = html.replace('//  DATA — HOSA Emergency Medical Science',
                    '//  DATA — HOSA Medical Assisting', 1)

with open(DST, 'w', encoding='utf-8') as f:
    f.write(html)

count = TERMS_JS.count('{ term:')
print(f'Wrote {DST} — {count} terms')
