#!/usr/bin/env python3
"""Generate radiologic-science.html from dental-science.html template."""
import os, re

BASE = '/home/user/hosa-prep-hub'
SRC  = os.path.join(BASE, 'dental-science.html')
DST  = os.path.join(BASE, 'radiologic-science.html')

with open(SRC, 'r', encoding='utf-8') as f:
    html = f.read()

TERMS_JS = '''const TERMS = [
  // ── Imaging Modalities ───────────────────────────────────────
  { term: "Radiograph (X-ray)", type: "concept", category: "modalities", meaning: "An image produced by passing X-ray photons through the body; dense structures (bone) absorb more photons and appear white (radiopaque), while less dense structures (air, fat) transmit more photons and appear dark (radiolucent).", example: "The PA chest radiograph showed a white opacity in the right lower lobe consistent with pneumonia — the dense fluid absorbed X-rays, appearing radiopaque on the film." },
  { term: "Computed Tomography (CT)", type: "concept", category: "modalities", meaning: "Rotating X-ray tube and detectors produce cross-sectional axial images reconstructed by computer; far better soft-tissue contrast and detail than plain films. Hounsfield Units (HU) quantify tissue density: air = −1000, water = 0, bone = +400 to +1000.", example: "The abdominal CT without contrast showed a 6 mm hyperdense stone in the right ureter (approximately +300 HU), confirming urolithiasis." },
  { term: "Magnetic Resonance Imaging (MRI)", type: "concept", category: "modalities", meaning: "Uses a strong magnetic field and radiofrequency pulses to excite hydrogen nuclei; emitted energy is used to construct images with excellent soft-tissue contrast. No ionizing radiation. T1 shows anatomy (fat = bright); T2 shows pathology (fluid = bright).", example: "The knee MRI T2 sequence showed a bright signal in the medial meniscus, indicating a tear filled with fluid — MRI superior to CT for cartilage and ligament assessment." },
  { term: "Fluoroscopy", type: "concept", category: "modalities", meaning: "Real-time continuous X-ray imaging displayed on a monitor; used for dynamic studies (barium swallow, upper GI series, arthrography, cardiac catheterization) and image-guided procedures. Highest radiation dose of conventional modalities.", example: "During the upper GI series, the radiologist used fluoroscopy to watch the barium column in real time and identified an irregular filling defect in the stomach body." },
  { term: "Ultrasound (Sonography)", type: "concept", category: "modalities", meaning: "High-frequency sound waves (2–15 MHz) are emitted by a transducer; echoes returning from tissue interfaces create images. Excellent for soft tissue, fluid-filled structures, and obstetrics. No ionizing radiation. Bone and air block transmission.", example: "The pelvic ultrasound confirmed a 6-week intrauterine pregnancy with fetal cardiac activity — safe first-line imaging in pregnancy because no ionizing radiation is used." },
  { term: "Nuclear Medicine (Scintigraphy)", type: "concept", category: "modalities", meaning: "Radiopharmaceuticals (radioisotope + pharmaceutical carrier) are injected and detected by gamma cameras as they accumulate in target organs; provides functional (metabolic) rather than anatomic information. PET uses positron-emitting tracers (F-18 FDG).", example: "The bone scan used Tc-99m MDP to detect increased osteoblastic activity — metastatic lesions appeared as 'hot spots' due to elevated bone turnover." },
  { term: "Interventional Radiology", type: "concept", category: "modalities", meaning: "Minimally invasive procedures guided by real-time imaging (fluoroscopy, US, CT): angiography, angioplasty, stenting, biopsy, drain placement, and embolization. Performed in a sterile suite with sedation.", example: "Under fluoroscopic guidance, the interventional radiologist advanced a catheter to the renal artery and embolized the bleeding vessel with coils, avoiding open surgery." },
  { term: "Contrast Media — Iodinated", type: "concept", category: "modalities", meaning: "Water-soluble iodine-based agents injected IV for CT angiography, urography, and myelography or orally/rectally for GI studies; iodine's high atomic number absorbs X-rays. Nephrotoxic — check creatinine; risk of iodine allergy.", example: "Before CT of the chest with contrast, the MA verified the patient's creatinine was < 1.5 mg/dL and documented no prior iodine contrast reaction." },
  { term: "Gadolinium (MRI Contrast)", type: "concept", category: "modalities", meaning: "A paramagnetic rare earth metal chelate injected IV to shorten T1 relaxation; enhances areas of blood–brain barrier breakdown or hypervascular lesions. Risk of NSF (nephrogenic systemic fibrosis) in severe renal failure.", example: "The brain MRI with gadolinium showed a ring-enhancing lesion in the temporal lobe — the breakdown of the blood–brain barrier allowed gadolinium to accumulate at the tumor margin." },
  { term: "Digital Radiography (DR) vs CR", type: "concept", category: "modalities", meaning: "CR (computed radiography) uses a photostimulable phosphor plate that is read by a laser scanner; DR (direct/indirect digital radiography) captures the image electronically in real time. Both allow image manipulation and PACS transfer.", example: "The hospital replaced CR plates with DR flat-panel detectors, reducing acquisition time from 90 seconds to near-instantaneous and improving workflow for trauma patients." },

  // ── Patient Positioning ──────────────────────────────────────
  { term: "PA vs AP Projection", type: "concept", category: "positioning", meaning: "PA (posteroanterior): X-ray beam travels posterior to anterior — patient faces the detector; heart magnification minimized. AP (anteroposterior): beam goes anterior to posterior — patient faces the tube; heart appears larger due to greater OFD.", example: "The radiographer took a PA chest X-ray with the patient standing upright against the detector, minimizing cardiac magnification compared to a portable AP projection." },
  { term: "Lateral Position", type: "concept", category: "positioning", meaning: "The patient stands or lies with one side closest to the detector; left lateral (LLat) keeps the left side down/nearest the film and is standard for chest (to reduce heart magnification). Right or left is specified.", example: "The left lateral chest was taken with the patient's left side against the detector to profile the heart, aorta, and retrosternal space." },
  { term: "Oblique Projections", type: "concept", category: "positioning", meaning: "The patient is rotated 45° or another specified angle to profile structures not visible on true AP/PA or lateral; RAO, LAO, RPO, LPO are the four obliques — named for the part closest to the detector (O) or away from it (O).", example: "The RAO oblique of the sternum placed the sternum to the left of the spine by rotating the patient right-anterior-down, removing bony overlap." },
  { term: "Central Ray (CR) and SID", type: "concept", category: "positioning", meaning: "The central ray is the center of the X-ray beam, directed perpendicular to the detector or angled as specified. SID (source-to-image distance) is typically 40 in (100 cm) for routine exams and 72 in (180 cm) for chest to reduce magnification.", example: "For the PA chest, the SID was set to 72 inches and the CR directed horizontally to the level of T7, placing the beam at the center of the lung fields." },
  { term: "Object-to-Film Distance (OFD) and Magnification", type: "concept", category: "positioning", meaning: "The distance between the object and the image receptor; greater OFD increases magnification and geometric unsharpness. Minimizing OFD (part closest to detector) reduces magnification and improves recorded detail.", example: "The surgeon asked why the cardiac silhouette looked larger on the portable AP vs. the PA; the radiographer explained that the AP's greater OFD (tube in front, heart farther from detector) increased cardiac magnification." },
  { term: "Collimation and Field Size", type: "concept", category: "positioning", meaning: "Restricting the X-ray beam to the area of clinical interest using lead shutters (collimators); reduces scatter radiation reaching the detector, improves image contrast, and decreases patient and staff dose.", example: "The radiographer tightened the collimators to the area of the wrist joint, reducing scatter and improving bone trabecular detail on the wrist series." },
  { term: "Gonadal Shielding", type: "concept", category: "positioning", meaning: "Lead shields placed over reproductive organs when they are within 5 cm of the primary beam and shielding will not obscure the area of clinical interest; required for patients with reproductive potential to reduce genetic dose.", example: "The radiographer applied a contact shield over the patient's testes before the AP pelvis — they were close to the primary field and would not obstruct the hip joint view." },
  { term: "Chest X-ray Anatomy Landmarks", type: "concept", category: "positioning", meaning: "On PA chest: CR at T7; top of film at top of shoulders; lateral borders at skin edge; include both costophrenic angles. Adequate inspiration = 10 posterior ribs visible above the diaphragm.", example: "The radiographer reviewed the chest film: 10 posterior ribs visible, both CP angles included, no rotation (clavicle heads equidistant from spinous process), adequate density — a diagnostic study." },
  { term: "Hand and Wrist Positioning", type: "concept", category: "positioning", meaning: "Standard hand series: PA, lateral, oblique. PA: hand flat on detector, fingers together. Lateral: thumb up, thumb in profile. Oblique: 45° rotation. Wrist: PA, lateral, scaphoid view (ulnar deviation) for navicular fracture.", example: "For a suspected scaphoid fracture, the radiographer added the ulnar deviation (scaphoid) view to the wrist series — this position projects the scaphoid free of overlap." },

  // ── Radiation Safety ─────────────────────────────────────────
  { term: "ALARA Principle", type: "concept", category: "radiation-safety", meaning: "As Low As Reasonably Achievable — the guiding principle of radiation protection; minimize dose through optimization without compromising diagnostic quality. Applied by adjusting kVp, mAs, SID, collimation, and shielding.", example: "The radiographer lowered mAs by 20% after quality reviews showed acceptable image quality, applying ALARA to reduce patient dose without degrading diagnostic information." },
  { term: "kVp and mAs Effects", type: "concept", category: "radiation-safety", meaning: "kVp (kilovoltage peak) controls photon energy (penetrating power) and image contrast — higher kVp reduces contrast, increases penetration, reduces patient dose. mAs (milliampere-seconds) controls quantity of photons and image density/noise.", example: "To reduce patient dose for the pediatric chest, the radiographer increased kVp to 90 and reduced mAs by half — maintaining density while delivering lower dose." },
  { term: "Personnel Dosimetry (Film Badge / TLD / OSL)", type: "concept", category: "radiation-safety", meaning: "Workers wear dosimeters to monitor occupational dose. TLD (thermoluminescent dosimeter) heats to release light proportional to dose. OSL (optically stimulated luminescence) uses laser. Film badges are largely obsolete. All logged against annual limits.", example: "The radiographer wore their OSL badge at collar level and submitted it monthly for reading; the quarterly report confirmed dose was well below the annual 50 mSv occupational limit." },
  { term: "Annual Dose Limits (NRC)", type: "concept", category: "radiation-safety", meaning: "NRC limits for radiation workers: whole body 50 mSv/year (5 rem), lens of eye 150 mSv/year, extremities 500 mSv/year. Public: 1 mSv/year. Declared pregnant worker fetal limit: 5 mSv/gestational term.", example: "A declared pregnant radiographer was reassigned to scheduling duties to keep fetal dose well below the 5 mSv gestational limit." },
  { term: "Time, Distance, Shielding", type: "concept", category: "radiation-safety", meaning: "The three cardinal principles of radiation protection: minimize time in the radiation field, maximize distance from the source (dose ∝ 1/distance²), and use lead shielding between source and person.", example: "During fluoroscopy the radiographer stood behind the protective leaded drape (shielding), 3 feet from the table (distance), and left the room during exposures (time) — applying all three cardinal principles." },
  { term: "Inverse Square Law", type: "concept", category: "radiation-safety", meaning: "Radiation intensity is inversely proportional to the square of the distance from the source: I₁/I₂ = (D₂)²/(D₁)². Doubling the distance reduces intensity to one-quarter; tripling reduces it to one-ninth.", example: "Moving from 1 m to 2 m from the fluoroscopy tube reduced scatter dose from 2 mSv/hr to 0.5 mSv/hr — exactly one-quarter, confirming the inverse square law." },
  { term: "Radiation Units — Gy vs Sv", type: "concept", category: "radiation-safety", meaning: "Gray (Gy) measures absorbed dose (energy deposited per kilogram of tissue). Sievert (Sv) measures effective dose — absorbed dose × radiation weighting factor × tissue weighting factor; accounts for biological risk. For X-rays, 1 Gy ≈ 1 Sv.", example: "The radiologist reported a skin dose of 3 Gy for the lengthy interventional case — because X-ray has a weighting factor of 1, the equivalent dose was also 3 Sv, exceeding the tissue reaction threshold." },
  { term: "Stochastic vs Deterministic Effects", type: "concept", category: "radiation-safety", meaning: "Stochastic effects (cancer, hereditary) are probabilistic — no threshold, higher dose → higher probability, but severity is fixed. Deterministic effects (erythema, cataracts, infertility) have a threshold; severity increases above it.", example: "The radiologist explained that the patient's CT scan carried a small stochastic cancer risk (no threshold), while the red skin patch (erythema) from fluoroscopy was a deterministic effect from threshold-exceeding skin dose." },
  { term: "Pediatric Radiation Considerations (Image Gently)", type: "concept", category: "radiation-safety", meaning: "Children are more radiosensitive (longer life to express cancer, more rapidly dividing cells); protocols mandate reduced kVp and mAs (pediatric-specific techniques), strict collimation, shielding, and clinical justification for each exam.", example: "The radiographer applied the Image Gently pediatric chest protocol — lowering mAs by 50% from adult settings and tightening the collimator to the lung fields only." },

  // ── Anatomy on Imaging ───────────────────────────────────────
  { term: "Radiopaque vs Radiolucent", type: "concept", category: "anatomy-imaging", meaning: "Radiopaque structures absorb X-rays and appear white on film (bone, metal, contrast, barium). Radiolucent structures transmit X-rays and appear dark (air, fat). Soft tissues are intermediate gray.", example: "The abdominal KUB showed a radiopaque calcification in the right ureter (white stone) superimposed on the gray soft-tissue background — consistent with ureterolithiasis." },
  { term: "Cardiothoracic Ratio", type: "concept", category: "anatomy-imaging", meaning: "The ratio of maximum cardiac diameter to maximum thoracic diameter on a PA chest X-ray; normal < 0.5. Ratio ≥ 0.5 suggests cardiomegaly. Inaccurate on AP projections due to magnification.", example: "Measuring the PA chest: cardiac width 14 cm, thoracic width 30 cm; CTR = 0.47 — within normal limits, ruling out cardiomegaly." },
  { term: "Air Bronchogram Sign", type: "concept", category: "anatomy-imaging", meaning: "Air-filled bronchi visible within an otherwise opacified (consolidated) lung region; indicates the consolidation is within the parenchyma (pneumonia, pulmonary edema) rather than a pleural effusion or atelectasis.", example: "The right lower lobe opacity showed air bronchograms — branching dark air lucencies within white consolidation — confirming alveolar (not pleural) pathology in the pneumonia." },
  { term: "Silhouette Sign", type: "concept", category: "anatomy-imaging", meaning: "Loss of the normal border between two adjacent structures of different density when one becomes the same density as the other; localizes consolidation — right heart border loss = right middle lobe; left heart border loss = lingula.", example: "The right heart border was obscured on the chest X-ray — the silhouette sign, caused by right middle lobe consolidation, which is the same gray density as the cardiac border." },
  { term: "Pleural Effusion on Imaging", type: "concept", category: "anatomy-imaging", meaning: "Blunting of the costophrenic angle (>175 mL) or layering opacity on upright PA; a lateral decubitus view confirms free fluid by layering along the dependent chest wall. CT shows layering hyperdense (exudate) or hypodense (transudate) fluid.", example: "The upright PA showed blunting of the right costophrenic angle; the right lateral decubitus confirmed free-flowing pleural effusion layering along the right chest wall." },
  { term: "Bone Density and Trabecular Pattern", type: "concept", category: "anatomy-imaging", meaning: "Normal bone shows a regular trabecular lattice on X-ray. Osteoporosis causes thinned cortex and coarse sparse trabeculae. Metastases appear as lytic (dark) or blastic (bright) lesions disrupting normal pattern.", example: "The spine X-ray showed thin cortices, biconcave 'fish-mouth' vertebrae, and coarse vertical trabeculae — radiographic signs of osteoporosis without acute fracture." },
  { term: "Pneumothorax on CXR", type: "concept", category: "anatomy-imaging", meaning: "Absence of lung markings peripheral to a visible visceral pleural line; air in the pleural space causes partial or total lung collapse. Tension pneumothorax: tracheal deviation away from the affected side, mediastinal shift.", example: "The left PA chest showed a distinct pleural line with absent lung markings beyond it and 20% volume loss in the left lung — a moderate left pneumothorax." },

  // ── Procedures & Equipment ───────────────────────────────────
  { term: "X-ray Tube Components", type: "concept", category: "procedures", meaning: "Key components: cathode (tungsten filament emits electrons by thermionic emission), anode (tungsten target converts electron energy to X-rays — 1% X-ray, 99% heat), glass/metal envelope (vacuum housing), oil bath (heat dissipation).", example: "The tube failure occurred when the tungsten anode cracked after excessive heat load — the radiographer confirmed the anode cooling-down indicator before the next high-mAs skull series." },
  { term: "Grids and Bucky", type: "concept", category: "procedures", meaning: "A grid consists of alternating lead strips and interspaces; absorbs scatter radiation before it reaches the detector to improve contrast. Used for body parts > 10 cm thick. The Bucky reciprocates the grid to prevent grid line artifact.", example: "The radiographer used the wall Bucky for the AP abdomen — the reciprocating grid absorbed scatter from the 22 cm of abdominal tissue, producing a high-contrast image." },
  { term: "Image Receptor and Cassette", type: "concept", category: "procedures", meaning: "In CR, the image receptor is a photostimulable phosphor plate inside a cassette that stores latent image from X-ray exposure; in DR, the flat-panel detector directly converts photons to an electronic signal.", example: "The CR plate was placed in the cassette behind the patient's chest, exposed, then processed through the reader to produce the digital radiograph on the PACS workstation." },
  { term: "PACS (Picture Archiving and Communication System)", type: "concept", category: "procedures", meaning: "A digital network for storing, retrieving, distributing, and displaying medical images; integrates with RIS (Radiology Information System) and HIS (Hospital Information System) using DICOM format.", example: "After the CT was acquired, images were automatically sent to PACS via DICOM and immediately available to the radiologist and ordering physician on any workstation in the hospital." },
  { term: "Radiographic Technique Chart", type: "concept", category: "procedures", meaning: "A reference chart listing standardized kVp and mAs settings for each body part and projection based on patient size and equipment; ensures consistent image quality and reproducible dose.", example: "The radiographer consulted the technique chart for an AP knee on a 23 cm measurement and selected 65 kVp, 8 mAs — within the departmental protocol for knee radiography." },
  { term: "Radiation Protection During Pregnancy", type: "concept", category: "procedures", meaning: "Elective studies should be postponed until after delivery. If clinically necessary, shield uterus, use the lowest feasible technique, and strictly collimate. Fetal dose from most routine exams (chest, extremity) is negligible (<0.01 mSv).", example: "The 14-week pregnant patient needed a chest X-ray for pneumonia — the radiographer applied a lead apron over the abdomen, noting that the fetal chest dose is less than 0.01 mSv and the benefit outweighs risk." },
  { term: "Quality Control in Radiology", type: "concept", category: "procedures", meaning: "Systematic testing of equipment (kVp accuracy, mAs reproducibility, focal spot size, field/beam alignment, artifact checks) to ensure consistent image quality and compliance with accreditation standards (ACR, Joint Commission).", example: "Monthly QC testing showed the fluoroscopy unit's kVp was 4% above calibration — the radiographer submitted a service request before the equipment was used for further procedures." },
];'''

m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
if not m: raise SystemExit('TERMS not found')
html = html[:m.start()] + TERMS_JS + html[m.end():]

CAT = """const categoryLabel = c => ({
  'modalities':       'Imaging Modalities',
  'positioning':      'Patient Positioning',
  'radiation-safety': 'Radiation Safety',
  'anatomy-imaging':  'Anatomy on Imaging',
  'procedures':       'Procedures & Equipment',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)

html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'radiologic-science';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>',
                    '<title>HOSA Prep Hub — Radiologic Science</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>',
                    '<h1>Radiologic<br><em>Science</em>.</h1>', 1)
html = html.replace(
    'A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
    'A study companion for imaging modalities, patient positioning, radiation safety, anatomy on imaging, and radiographic procedures and equipment — built for HOSA competitors.',
    1
)
html = html.replace('//  DATA — HOSA Emergency Medical Science',
                    '//  DATA — HOSA Radiologic Science', 1)

with open(DST, 'w', encoding='utf-8') as f:
    f.write(html)

count = TERMS_JS.count('{ term:')
print(f'Wrote {DST} — {count} terms')
