#!/usr/bin/env python3
"""Generate hematology.html from dental-science.html template."""
import os, re
BASE = '/home/user/hosa-prep-hub'
SRC, DST = os.path.join(BASE, 'dental-science.html'), os.path.join(BASE, 'hematology.html')
with open(SRC, 'r', encoding='utf-8') as f: html = f.read()
TERMS_JS = '''const TERMS = [
  // ── Blood Cells ──────────────────────────────────────────────
  { term: "Hematopoiesis", type: "concept", category: "blood-cells", meaning: "Production of blood cells from hematopoietic stem cells in bone marrow. Differentiation into myeloid (RBC, granulocytes, monocytes, platelets) and lymphoid (T, B, NK cells) lineages. EPO drives RBC, TPO drives platelet, G-CSF drives neutrophil production.", example: "After chemotherapy-induced neutropenia, G-CSF (filgrastim) stimulated myeloid hematopoiesis, accelerating neutrophil recovery." },
  { term: "Red Blood Cells (Erythrocytes)", type: "concept", category: "blood-cells", meaning: "Biconcave anucleate cells (~5 million/µL) carrying hemoglobin for O2/CO2 transport. Lifespan ~120 days. Production stimulated by EPO (kidney) in response to hypoxia. Removed by spleen.", example: "The CKD patient's anemia from decreased EPO production was treated with darbepoetin alfa to stimulate erythropoiesis." },
  { term: "White Blood Cell Differential", type: "concept", category: "blood-cells", meaning: "Neutrophils 50–70% (bacterial); lymphocytes 20–40% (viral); monocytes 2–8%; eosinophils 1–4% (allergy/parasites); basophils 0–1%. 'Never Let Monkeys Eat Bananas' for relative abundance.", example: "The CBC differential of 80% lymphocytes and atypical lymphs prompted EBV testing — positive heterophile confirmed mononucleosis." },
  { term: "Platelets (Thrombocytes)", type: "concept", category: "blood-cells", meaning: "Small anucleate cell fragments from megakaryocytes (150,000–400,000/µL); essential for primary hemostasis (platelet plug). Stimulated by TPO. Thrombocytopenia: <150K; severe: <50K with bleeding risk.", example: "The ITP patient's platelet count of 22K with petechiae required corticosteroid therapy to suppress autoimmune platelet destruction." },
  { term: "Hemoglobin Structure", type: "concept", category: "blood-cells", meaning: "Tetramer of 2α + 2β chains in adult HbA (97%); each chain binds heme with iron (Fe²⁺) center carrying one O2. HbA2 (α2δ2) ~2%, HbF (α2γ2) <1%. Disorders alter chain synthesis or structure.", example: "Hemoglobin electrophoresis showing 80% HbS and 20% HbF confirmed sickle cell disease with elevated fetal hemoglobin." },

  // ── Anemias ──────────────────────────────────────────────────
  { term: "Iron Deficiency Anemia", type: "concept", category: "anemia", meaning: "Most common anemia worldwide; microcytic, hypochromic (low MCV, low MCH); low ferritin, high TIBC. Causes: blood loss (GI, menstrual), poor intake, malabsorption. Treated with oral iron and underlying cause.", example: "The patient's MCV 72, ferritin 8, and positive FOBT identified iron deficiency anemia from occult GI bleeding; colonoscopy revealed colon adenocarcinoma." },
  { term: "Vitamin B12 / Folate Deficiency", type: "concept", category: "anemia", meaning: "Macrocytic megaloblastic anemia (MCV >100). B12: pernicious anemia (anti-intrinsic factor antibodies), vegan diet, ileal disease — also causes neurological deficits. Folate: poor intake (alcoholism), pregnancy — no neuro deficits.", example: "The patient's macrocytic anemia with peripheral neuropathy and positive anti-IF antibodies indicated B12 deficiency from pernicious anemia." },
  { term: "Anemia of Chronic Disease", type: "concept", category: "anemia", meaning: "Normocytic (sometimes microcytic) anemia from inflammation (chronic infection, autoimmune, cancer); hepcidin sequesters iron, suppresses EPO. Iron studies: low serum iron, low TIBC, NORMAL/HIGH ferritin (distinguishes from IDA).", example: "The RA patient's anemia with low iron but normal ferritin reflected anemia of chronic disease — iron supplementation alone would not correct it." },
  { term: "Sickle Cell Disease", type: "concept", category: "anemia", meaning: "Autosomal recessive HbS (Glu→Val on β-chain); sickling under hypoxia → vaso-occlusive crises, hemolysis, autosplenectomy, infections. Treated with hydroxyurea (increases HbF), transfusions, voxelotor, gene therapy.", example: "The patient's severe pain crisis with HbSS on electrophoresis was managed with IV opioids, hydration, and oxygen; hydroxyurea was continued for prevention." },
  { term: "Thalassemia", type: "concept", category: "anemia", meaning: "Inherited reduced production of α or β globin chains → microcytic anemia. α-thalassemia (chromosome 16): 1–4 gene deletions. β-thalassemia (chromosome 11): minor (asymptomatic) to major (Cooley anemia — transfusion-dependent).", example: "The Mediterranean patient's microcytic anemia with normal iron and elevated HbA2 on electrophoresis confirmed β-thalassemia minor." },
  { term: "Hemolytic Anemia", type: "concept", category: "anemia", meaning: "RBC destruction faster than production. Lab: elevated indirect bilirubin, LDH, reticulocytes, low haptoglobin. Inherited (G6PD, hereditary spherocytosis, sickle cell) vs acquired (autoimmune AIHA, microangiopathic TTP/HUS, drug-induced).", example: "The patient's anemia, jaundice, elevated LDH, low haptoglobin, and positive direct Coombs confirmed warm autoimmune hemolytic anemia." },
  { term: "Aplastic Anemia", type: "concept", category: "anemia", meaning: "Pancytopenia from bone marrow failure; causes include autoimmune, drug/toxin (chloramphenicol, benzene), radiation, viral (parvovirus B19, hepatitis). Treated with immunosuppression (ATG, cyclosporine) or stem cell transplant.", example: "The patient's pancytopenia with hypocellular bone marrow and absence of leukemic blasts confirmed aplastic anemia; ATG plus cyclosporine was initiated." },

  // ── Coagulation ──────────────────────────────────────────────
  { term: "Hemostasis (Primary vs Secondary)", type: "concept", category: "coagulation", meaning: "Primary: platelet plug formation after vessel injury (vWF, GpIb, GpIIb/IIIa). Secondary: coagulation cascade producing fibrin mesh to stabilize plug. Both required for definitive clot.", example: "The patient's mucocutaneous bleeding with normal PT/PTT but prolonged bleeding time pointed to a primary hemostasis defect — von Willebrand disease was confirmed." },
  { term: "Coagulation Cascade", type: "concept", category: "coagulation", meaning: "Intrinsic (PTT — factors XII, XI, IX, VIII), extrinsic (PT — factor VII), common (X, V, II/thrombin, I/fibrin). Final fibrin clot stabilized by factor XIII. Vitamin K-dependent: II, VII, IX, X, protein C, S.", example: "The patient on warfarin had an INR of 3.5 — therapeutic anticoagulation through inhibition of vitamin K-dependent factors II, VII, IX, X." },
  { term: "PT/INR vs PTT", type: "concept", category: "coagulation", meaning: "PT measures extrinsic pathway (factor VII) and common pathway; expressed as INR for warfarin monitoring (target 2–3 for AFib/DVT). PTT measures intrinsic and common pathways; monitors heparin therapy.", example: "The patient on continuous heparin infusion had aPTT at 65 seconds (target 60–80) — therapeutic anticoagulation in the intrinsic pathway." },
  { term: "Hemophilia A and B", type: "concept", category: "coagulation", meaning: "X-linked recessive; Hemophilia A: factor VIII deficiency (most common). Hemophilia B (Christmas): factor IX deficiency. Both cause hemarthrosis, deep muscle bleeding, prolonged PTT (normal PT). Treated with factor concentrate.", example: "The 5-year-old boy's recurrent knee hemarthroses and prolonged aPTT correcting with factor VIII confirmed hemophilia A." },
  { term: "von Willebrand Disease", type: "concept", category: "coagulation", meaning: "Most common inherited bleeding disorder (autosomal dominant usually); vWF deficiency impairs platelet adhesion AND stabilizes factor VIII. Mucocutaneous bleeding, menorrhagia, prolonged bleeding time. Treated with desmopressin or vWF concentrate.", example: "The young woman's heavy menses, easy bruising, and low vWF antigen with low factor VIII confirmed type 1 von Willebrand disease." },
  { term: "DVT and Pulmonary Embolism", type: "concept", category: "coagulation", meaning: "Virchow triad: stasis, endothelial injury, hypercoagulability. DVT: unilateral leg swelling/pain, calf tenderness. PE: sudden dyspnea, pleuritic chest pain, hypoxia. Treated with anticoagulation (heparin → DOAC or warfarin).", example: "After hip surgery the patient developed unilateral calf swelling — DVT confirmed by ultrasound — and was started on enoxaparin then rivaroxaban." },
  { term: "Disseminated Intravascular Coagulation (DIC)", type: "concept", category: "coagulation", meaning: "Pathologic systemic activation of coagulation consuming clotting factors and platelets; widespread microthrombi AND bleeding. Labs: low platelets, prolonged PT/PTT, low fibrinogen, elevated D-dimer. Treat underlying cause (sepsis, OB emergency, malignancy).", example: "The septic patient's DIC with platelet count 50K, fibrinogen 90, and D-dimer >10,000 required platelet/cryoprecipitate transfusion and source control." },
  { term: "Heparin-Induced Thrombocytopenia (HIT)", type: "concept", category: "coagulation", meaning: "Type II: immune-mediated, antibodies to heparin-PF4 complex → paradoxical thrombosis with thrombocytopenia (>50% drop) 5–10 days after heparin start. Stop ALL heparin; use argatroban or fondaparinux.", example: "On day 8 of heparin the patient's platelet count fell from 280K to 90K with new DVT — HIT diagnosed; heparin stopped and argatroban started." },

  // ── Blood Cancers & Transfusion ──────────────────────────────
  { term: "Leukemia Overview", type: "concept", category: "cancers-transfusion", meaning: "Acute (blasts >20% in marrow): AML (adults), ALL (children). Chronic (mature cells): CML (Philadelphia chromosome BCR-ABL → imatinib), CLL (older adults, often asymptomatic). Diagnosed by peripheral smear, bone marrow biopsy, flow cytometry.", example: "The child's lymphoblasts on peripheral smear with TdT positivity confirmed B-cell ALL; intensive multi-agent chemotherapy with >85% cure rate was started." },
  { term: "Lymphoma (Hodgkin vs NHL)", type: "concept", category: "cancers-transfusion", meaning: "Hodgkin: Reed-Sternberg cells, contiguous nodal spread, B symptoms (fever, weight loss, night sweats), highly curable. Non-Hodgkin: heterogeneous (DLBCL most common aggressive; follicular indolent); often widespread at diagnosis. Treated with R-CHOP, etc.", example: "The cervical lymph node biopsy showing Reed-Sternberg cells confirmed classical Hodgkin lymphoma; ABVD achieved complete remission." },
  { term: "Multiple Myeloma", type: "concept", category: "cancers-transfusion", meaning: "Plasma cell malignancy producing monoclonal IgG/IgA (M-spike) and Bence-Jones light chains. CRAB features: hyperCalcemia, Renal failure, Anemia, lytic Bone lesions. Treated with proteasome inhibitors, IMiDs, autologous SCT.", example: "The patient's bone pain, hypercalcemia, M-spike on SPEP, and lytic skull lesions confirmed multiple myeloma; bortezomib-based induction was started." },
  { term: "Blood Typing (ABO and Rh)", type: "concept", category: "cancers-transfusion", meaning: "ABO antigens on RBCs; corresponding antibodies in plasma. Type O: universal donor (no antigens), recipient with anti-A and anti-B. Type AB: universal recipient (no antibodies). Rh-negative pregnant women receive RhoGAM.", example: "The hemorrhaging trauma patient received O-negative emergency blood — universal donor RBCs — before her blood type was determined." },
  { term: "Blood Components", type: "concept", category: "cancers-transfusion", meaning: "Whole blood separated into: packed RBCs (anemia, hemorrhage — 1 unit raises Hb ~1 g/dL), platelets (severe thrombocytopenia), FFP (coagulopathy — all factors), cryoprecipitate (factor VIII, vWF, fibrinogen).", example: "The DIC patient received PRBCs for anemia, platelets for thrombocytopenia, cryoprecipitate for low fibrinogen, and FFP for global coagulopathy." },
  { term: "Transfusion Reactions", type: "concept", category: "cancers-transfusion", meaning: "Acute hemolytic (ABO mismatch — fever, flank pain, hemoglobinuria, shock). Febrile non-hemolytic (most common). Allergic (urticaria, anaphylaxis if IgA-deficient). TRALI (acute lung injury). Stop transfusion immediately for any reaction.", example: "When the patient developed fever, back pain, and dark urine 10 min into transfusion, the nurse stopped infusion — acute hemolytic ABO reaction was confirmed." },
];'''
m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
html = html[:m.start()] + TERMS_JS + html[m.end():]
CAT = """const categoryLabel = c => ({
  'blood-cells':         'Blood Cells',
  'anemia':              'Anemias',
  'coagulation':         'Coagulation',
  'cancers-transfusion': 'Blood Cancers & Transfusion',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'hematology';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>', '<title>HOSA Prep Hub — Hematology</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>', '<h1>Hemato<em>logy</em>.</h1>', 1)
html = html.replace('A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
                    'A study companion for blood cell biology, anemias, coagulation and bleeding disorders, and blood cancers and transfusion medicine — built for HOSA competitors.', 1)
html = html.replace('//  DATA — HOSA Emergency Medical Science', '//  DATA — HOSA Hematology', 1)
with open(DST, 'w', encoding='utf-8') as f: f.write(html)
print(f'Wrote {DST} — {TERMS_JS.count("{ term:")} terms')
