#!/usr/bin/env python3
"""Generate neurology.html from dental-science.html template."""
import os, re
BASE = '/home/user/hosa-prep-hub'
SRC, DST = os.path.join(BASE, 'dental-science.html'), os.path.join(BASE, 'neurology.html')
with open(SRC, 'r', encoding='utf-8') as f: html = f.read()
TERMS_JS = '''const TERMS = [
  // ── CNS Anatomy & Function ───────────────────────────────────
  { term: "Cerebral Lobes and Function", type: "concept", category: "anatomy", meaning: "Frontal: motor, executive function, personality, Broca's (speech production). Parietal: somatosensory, spatial orientation. Temporal: auditory, memory, Wernicke's (comprehension). Occipital: vision.", example: "The patient's expressive aphasia after a left middle cerebral artery stroke localized to Broca's area in the left frontal lobe." },
  { term: "Cerebellum", type: "concept", category: "anatomy", meaning: "Coordinates motor activity, balance, and posture. Damage produces ataxia, dysmetria, intention tremor, dysdiadochokinesia, scanning speech (cerebellar signs are ipsilateral to lesion).", example: "The patient's wide-based gait and intention tremor on finger-to-nose testing localized to right cerebellar hemisphere damage." },
  { term: "Brainstem (Midbrain, Pons, Medulla)", type: "concept", category: "anatomy", meaning: "Houses cranial nerve nuclei (III–XII) and reticular activating system (consciousness). Cardiorespiratory centers in medulla. Compression causes pupillary abnormalities, coma, posturing, respiratory arrest.", example: "Uncal herniation compressed the midbrain, producing a blown right pupil and decerebrate posturing in the head-injured patient." },
  { term: "Cranial Nerves I–XII", type: "concept", category: "anatomy", meaning: "I olfactory; II optic; III oculomotor (most eye movements + pupillary constriction); IV trochlear; V trigeminal (face sensation + chewing); VI abducens (lateral gaze); VII facial; VIII vestibulocochlear; IX glossopharyngeal; X vagus; XI accessory; XII hypoglossal.", example: "Right-sided facial droop with preserved forehead movement indicated CN VII upper motor neuron lesion (central) rather than Bell palsy." },
  { term: "Spinal Cord Pathways", type: "concept", category: "anatomy", meaning: "Corticospinal: descending motor (decussates in medulla). Dorsal columns: ipsilateral proprioception/vibration (cross in medulla). Spinothalamic: contralateral pain/temperature (crosses immediately at cord). Hemisection = Brown-Séquard syndrome.", example: "Brown-Séquard from a stab wound caused ipsilateral weakness and proprioception loss with contralateral pain/temperature loss below the lesion." },
  { term: "Meninges and CSF", type: "concept", category: "anatomy", meaning: "Three layers: dura, arachnoid, pia. CSF produced by choroid plexus, flows through ventricles, absorbed by arachnoid granulations. Normal CSF: clear, ~140 mL volume. LP samples L3-L4 or L4-L5 (below cord termination).", example: "The LP at L4-L5 returned clear CSF; opening pressure was 18 cm H2O — within normal limits — ruling out elevated ICP." },
  { term: "Blood-Brain Barrier (BBB)", type: "concept", category: "anatomy", meaning: "Tight junctions of brain capillaries limit passage to lipid-soluble, small, uncharged molecules; excludes most drugs and pathogens. Breakdown in inflammation, tumor allows contrast enhancement on MRI.", example: "Gadolinium normally cannot cross the BBB; ring enhancement around the brain mass indicated tumor-induced BBB breakdown." },

  // ── Stroke & Vascular ────────────────────────────────────────
  { term: "Ischemic vs Hemorrhagic Stroke", type: "concept", category: "stroke", meaning: "Ischemic (~85%): thrombotic, embolic, or lacunar occlusion → focal neurological deficit. Hemorrhagic (~15%): intracerebral or subarachnoid bleed. CT distinguishes (blood appears white). Treatment differs critically.", example: "Non-contrast head CT showed hyperdense blood in the right basal ganglia — hemorrhagic stroke; tPA was contraindicated." },
  { term: "tPA (Tissue Plasminogen Activator)", type: "concept", category: "stroke", meaning: "Thrombolytic for acute ischemic stroke within 4.5 hours of symptom onset; restores cerebral perfusion. Exclusions: recent surgery, anticoagulation, bleeding, BP >185/110, hemorrhage on CT.", example: "The patient with NIHSS 12 arriving 2 hours after stroke onset met all criteria and received IV alteplase, with significant deficit improvement." },
  { term: "Mechanical Thrombectomy", type: "concept", category: "stroke", meaning: "Endovascular clot retrieval for large-vessel occlusion (LVO) up to 24 hours from onset in selected patients; combined with or used after tPA. Dramatic outcome improvements in eligible patients.", example: "The patient's CT angiography showed M1 MCA occlusion; mechanical thrombectomy at hour 4 restored TICI 2b flow and led to near-complete recovery." },
  { term: "NIHSS (NIH Stroke Scale)", type: "concept", category: "stroke", meaning: "Standardized assessment scoring level of consciousness, gaze, visual fields, facial palsy, motor, ataxia, sensation, language, dysarthria, and neglect. Range 0–42. Guides treatment decisions and outcome prediction.", example: "The patient's NIHSS of 14 (moderate to severe stroke) and small infarct on imaging supported tPA administration." },
  { term: "Transient Ischemic Attack (TIA)", type: "concept", category: "stroke", meaning: "Transient focal neurological deficit lasting <24 hours (typically <1 hour) from temporary cerebral ischemia; no permanent injury. High short-term stroke risk — requires urgent workup and secondary prevention.", example: "The patient's transient right-arm weakness for 30 minutes was diagnosed as TIA; carotid Doppler revealed 80% stenosis and CEA was scheduled." },
  { term: "Subarachnoid Hemorrhage (SAH)", type: "concept", category: "stroke", meaning: "Bleeding into subarachnoid space, usually from ruptured berry aneurysm. 'Worst headache of life,' meningismus, photophobia. CT shows blood; LP shows xanthochromia if CT negative. Treated by coiling/clipping.", example: "The patient's thunderclap headache and neck stiffness with negative CT was diagnosed by LP showing xanthochromia — subarachnoid hemorrhage." },

  // ── Seizures & Movement Disorders ────────────────────────────
  { term: "Focal vs Generalized Seizures", type: "concept", category: "seizures-movement", meaning: "Focal: arise from one hemisphere; aware (formerly 'simple') or impaired awareness (formerly 'complex'). Generalized: bilateral from onset; types include absence, tonic-clonic, myoclonic, atonic.", example: "The patient's staring spells with lip smacking and unresponsiveness lasting 30 seconds were focal seizures with impaired awareness from the temporal lobe." },
  { term: "Status Epilepticus", type: "concept", category: "seizures-movement", meaning: "Seizure ≥5 minutes or repeated seizures without recovery; neurological emergency causing neuronal injury. Treat: ABC, IV benzodiazepine (lorazepam) → IV antiepileptic (levetiracetam, fosphenytoin) → intubation/general anesthesia if refractory.", example: "The patient's continuous tonic-clonic seizing for 10 minutes met criteria for status epilepticus; IV lorazepam terminated the seizure within 2 minutes." },
  { term: "Antiepileptic Drugs (AEDs)", type: "concept", category: "seizures-movement", meaning: "First-line vary by seizure type: levetiracetam (broad spectrum, well-tolerated), valproate (broad spectrum, teratogenic), lamotrigine (broad spectrum, slow titration for SJS), carbamazepine (focal), ethosuximide (absence).", example: "Levetiracetam was selected for the new-onset focal epilepsy because of broad efficacy, minimal interactions, and tolerability." },
  { term: "Parkinson Disease", type: "concept", category: "seizures-movement", meaning: "Loss of dopaminergic neurons in substantia nigra → resting tremor, rigidity (cogwheel), bradykinesia, postural instability. Treated with levodopa/carbidopa, dopamine agonists, MAO-B inhibitors. Deep brain stimulation for advanced disease.", example: "The patient's pill-rolling tremor at rest, masked facies, and shuffling gait were classic Parkinson disease; carbidopa-levodopa improved symptoms dramatically." },
  { term: "Multiple Sclerosis (MS)", type: "concept", category: "seizures-movement", meaning: "Autoimmune CNS demyelination → relapsing-remitting (most common) or progressive course. Optic neuritis, paresthesias, weakness, ataxia. MRI: ovoid periventricular white matter lesions ('Dawson's fingers'). Disease-modifying therapy.", example: "The young woman's optic neuritis, internuclear ophthalmoplegia, and Dawson's fingers on MRI confirmed MS; she was started on ocrelizumab." },
  { term: "Myasthenia Gravis", type: "concept", category: "seizures-movement", meaning: "Autoantibodies to nicotinic acetylcholine receptors at neuromuscular junction → fatigable weakness, ptosis, diplopia, dysphagia worse with activity. Diagnosed by AChR antibodies, EMG (decrement), ice-pack test. Treated with pyridostigmine, thymectomy.", example: "The patient's ptosis and diplopia worse at end of day with positive AChR antibodies confirmed myasthenia gravis; pyridostigmine improved strength." },

  // ── Other Neurology ──────────────────────────────────────────
  { term: "Meningitis", type: "concept", category: "other", meaning: "Inflammation of meninges; bacterial (life-threatening — S. pneumoniae most common adult; N. meningitidis in young) vs viral. Triad: fever, neck stiffness, altered mental status. LP for diagnosis; empiric IV antibiotics + dexamethasone.", example: "The college student's fever, neck stiffness, photophobia, and Brudzinski sign with CSF showing high neutrophils and low glucose confirmed bacterial meningitis." },
  { term: "Encephalitis", type: "concept", category: "other", meaning: "Inflammation of brain parenchyma; HSV most common sporadic cause; presents with altered mental status, seizures, focal deficits, fever. MRI shows temporal lobe enhancement; LP shows lymphocytic pleocytosis. Empiric IV acyclovir.", example: "The patient's altered mental status, seizures, and right temporal lobe enhancement on MRI prompted empiric IV acyclovir for suspected HSV encephalitis." },
  { term: "Glasgow Coma Scale (GCS)", type: "concept", category: "other", meaning: "Quantifies level of consciousness: Eye opening (1–4) + Verbal (1–5) + Motor (1–6). Range 3–15. GCS ≤8 indicates severe TBI and need for intubation to protect airway.", example: "The trauma patient's GCS of 7 (E2 V2 M3) indicated severe head injury; the airway was intubated and CT head was ordered." },
  { term: "Increased Intracranial Pressure", type: "concept", category: "other", meaning: "Normal ICP <20 mmHg. Cushing triad of elevated ICP: hypertension, bradycardia, irregular respirations. Management: head elevation 30°, hyperventilation (transient), mannitol/hypertonic saline, surgical decompression.", example: "The patient with severe TBI developed Cushing triad — BP 220/110, HR 48, irregular breathing — prompting emergency hypertonic saline and decompressive craniectomy." },
  { term: "Dementia (Alzheimer Disease)", type: "concept", category: "other", meaning: "Most common dementia (60–70%). Progressive cognitive decline with amyloid plaques, neurofibrillary tangles, cortical atrophy (especially hippocampus). Treated with cholinesterase inhibitors (donepezil), memantine (NMDA antagonist), supportive care.", example: "The patient's progressive memory loss over 2 years with hippocampal atrophy on MRI was consistent with Alzheimer disease; donepezil was started." },
  { term: "Peripheral Neuropathy", type: "concept", category: "other", meaning: "Damage to peripheral nerves causing distal symmetric sensory loss ('stocking-glove'), pain, weakness. Common causes: diabetes (most common), alcohol, B12 deficiency, chemotherapy. Treatment: address cause + symptomatic (gabapentin, duloxetine).", example: "The diabetic's distal symmetric burning in feet and decreased vibratory sense was diabetic peripheral neuropathy; duloxetine was started for symptomatic relief." },
];'''
m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
html = html[:m.start()] + TERMS_JS + html[m.end():]
CAT = """const categoryLabel = c => ({
  'anatomy':           'CNS Anatomy & Function',
  'stroke':            'Stroke & Vascular',
  'seizures-movement': 'Seizures & Movement Disorders',
  'other':             'Other Neurology',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'neurology';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>', '<title>HOSA Prep Hub — Neurology</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>', '<h1>Neuro<em>logy</em>.</h1>', 1)
html = html.replace('A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
                    'A study companion for CNS anatomy and function, stroke and cerebrovascular disease, seizures and movement disorders, and other neurological conditions — built for HOSA competitors.', 1)
html = html.replace('//  DATA — HOSA Emergency Medical Science', '//  DATA — HOSA Neurology', 1)
with open(DST, 'w', encoding='utf-8') as f: f.write(html)
print(f'Wrote {DST} — {TERMS_JS.count("{ term:")} terms')
