#!/usr/bin/env python3
"""Generate epidemiology.html from dental-science.html template."""
import os, re

BASE = '/home/user/hosa-prep-hub'
SRC  = os.path.join(BASE, 'dental-science.html')
DST  = os.path.join(BASE, 'epidemiology.html')

with open(SRC, 'r', encoding='utf-8') as f:
    html = f.read()

TERMS_JS = '''const TERMS = [
  // ── Foundations ──────────────────────────────────────────────
  { term: "Epidemiology", type: "concept", category: "foundations", meaning: "The study of the distribution and determinants of health-related states or events in specified populations, and the application of this study to control health problems.", example: "Epidemiology revealed that hand-washing, not miasma, was the cause of puerperal fever in John Snow's cholera investigation." },
  { term: "Incidence", type: "concept", category: "foundations", meaning: "The number of new cases of a disease occurring in a population at risk during a specified time period; measures the rate at which healthy people develop disease.", example: "An incidence of 50 new tuberculosis cases per 100,000 people per year indicates the probability that a disease-free person will develop TB that year." },
  { term: "Prevalence", type: "concept", category: "foundations", meaning: "The total number of existing cases (new and old) of a disease in a population at a specific point in time (point prevalence) or over a period (period prevalence); a snapshot, not a rate.", example: "The prevalence of diabetes in the U.S. is about 11% of the adult population, including newly diagnosed and long-standing cases." },
  { term: "Incidence vs Prevalence", type: "concept", category: "foundations", meaning: "Incidence reflects risk of getting a disease; prevalence reflects burden of disease. Prevalence ≈ incidence × duration. Long-duration diseases (HIV, diabetes) have high prevalence relative to incidence.", example: "HIV has lower annual incidence than influenza but far higher prevalence because people live with HIV for decades." },
  { term: "Case Definition", type: "concept", category: "foundations", meaning: "A set of standard criteria for deciding whether a person has a particular disease or health condition; includes clinical criteria plus person, place, and time qualifiers.", example: "During an outbreak the case definition was: fever > 38.5°C + rash + exposure to the festival in the preceding 14 days." },
  { term: "Index Case vs Primary Case", type: "concept", category: "foundations", meaning: "The index case is the first identified (reported) case in an investigation. The primary case is the first person actually infected, who may differ from the index case if others were infected earlier but identified later.", example: "The index case of the restaurant outbreak was reported Thursday, but a primary case infected two days earlier was identified during contact tracing." },
  { term: "Endemic, Epidemic, Pandemic", type: "concept", category: "foundations", meaning: "Endemic: the baseline level of disease constantly present in a region. Epidemic: occurrence substantially above expected (baseline) levels. Pandemic: an epidemic spread across multiple countries or continents.", example: "Malaria is endemic in sub-Saharan Africa; COVID-19 reached pandemic status when it spread to all inhabited continents." },
  { term: "Herd Immunity", type: "concept", category: "foundations", meaning: "Indirect protection from infection conferred to susceptible individuals when a sufficient proportion of a population is immune, interrupting chains of transmission.", example: "Measles requires approximately 95% population immunity to achieve herd immunity because of its extremely high R0 of 12–18." },
  { term: "R0 (Basic Reproduction Number)", type: "concept", category: "foundations", meaning: "The average number of secondary infections produced by a single infectious case in a fully susceptible population; if R0 > 1 an epidemic will grow, if < 1 it will die out.", example: "Measles has an R0 of 12–18, meaning one infectious person infects 12–18 others on average in an unvaccinated population." },
  { term: "Infectious Period and Incubation Period", type: "concept", category: "foundations", meaning: "Incubation period: time from exposure to symptom onset. Infectious period: the window during which a person can transmit the disease. These may overlap (pre-symptomatic transmission).", example: "COVID-19's pre-symptomatic infectious period — the overlap before symptom onset — made containment by symptom-based isolation alone impossible." },
  { term: "Attack Rate", type: "concept", category: "foundations", meaning: "The proportion of exposed persons who develop the disease during a specific outbreak; used instead of incidence when investigating a circumscribed outbreak with a defined exposure.", example: "Of 48 people who ate the potato salad at the picnic, 36 developed diarrhea — an attack rate of 75%." },
  { term: "Mortality Rate vs Case Fatality Rate", type: "concept", category: "foundations", meaning: "Mortality rate: deaths per 100,000 population per year. Case fatality rate (CFR): proportion of diagnosed cases who die; CFR = deaths / confirmed cases. CFR reflects disease severity.", example: "Ebola has a CFR of 25–90%, indicating extremely high lethality among those with confirmed disease." },

  // ── Study Designs ────────────────────────────────────────────
  { term: "Randomized Controlled Trial (RCT)", type: "concept", category: "study-design", meaning: "Participants are randomly allocated to receive an intervention or control; randomization eliminates confounding, making the RCT the gold standard for causal inference.", example: "A double-blind RCT with 10,000 participants demonstrated that the vaccine reduced severe disease by 95% versus placebo." },
  { term: "Cohort Study", type: "concept", category: "study-design", meaning: "A longitudinal observational study that follows two groups — exposed and unexposed — over time and compares incidence of outcomes; can be prospective or retrospective (historical cohort).", example: "The Framingham Heart Study is a landmark prospective cohort that identified smoking, hypertension, and hyperlipidemia as cardiovascular risk factors." },
  { term: "Case-Control Study", type: "concept", category: "study-design", meaning: "An observational study comparing cases (people with the disease) to matched controls (without disease) to identify past exposures; efficient for rare diseases and produces an odds ratio.", example: "A case-control study comparing lung cancer patients to matched controls found that smokers had 20× higher odds of the disease." },
  { term: "Cross-Sectional Study", type: "concept", category: "study-design", meaning: "A study that measures disease and exposure simultaneously in a population at a single point in time; produces prevalence data and prevalence ratios but cannot establish temporality.", example: "A cross-sectional survey of 5,000 adults found a 30% prevalence of hypertension and that it was associated with high sodium intake." },
  { term: "Ecological Study", type: "concept", category: "study-design", meaning: "A study in which the units of analysis are populations or groups rather than individuals; useful for hypothesis generation but susceptible to the ecological fallacy.", example: "Countries with higher per-capita fat intake had higher breast cancer rates — an ecological association that cannot prove individual-level causation." },
  { term: "Ecological Fallacy", type: "concept", category: "study-design", meaning: "The erroneous assumption that associations observed at the group (population) level apply to individuals within those groups.", example: "Concluding that because wealthy countries have more cancer all wealthy individuals have higher cancer rates commits the ecological fallacy." },
  { term: "Systematic Review and Meta-Analysis", type: "concept", category: "study-design", meaning: "A systematic review comprehensively identifies and critically appraises all relevant studies on a question. Meta-analysis quantitatively pools results using statistical methods for a summary effect estimate.", example: "A meta-analysis of 30 RCTs confirmed that statins reduce major cardiovascular events by 22% per 1 mmol/L reduction in LDL." },
  { term: "Bias", type: "concept", category: "study-design", meaning: "Systematic error that results in incorrect estimates of exposure-disease associations; major types are selection bias (flawed sampling), information/measurement bias, and confounding.", example: "Healthy worker bias (selecting employed individuals who are healthier than the general population) can falsely make an occupational exposure look protective." },
  { term: "Confounding", type: "concept", category: "study-design", meaning: "A distortion of an exposure-outcome association caused by a third variable (confounder) that is associated with both the exposure and the outcome; controlled by randomization or statistical adjustment.", example: "In a study linking coffee to heart disease, smoking was a confounder — smokers drink more coffee and also have higher cardiac risk." },
  { term: "Bradford Hill Criteria", type: "concept", category: "study-design", meaning: "Nine criteria (strength, consistency, specificity, temporality, biological gradient, plausibility, coherence, experiment, analogy) used to evaluate whether an observed epidemiological association is causal.", example: "Temporality (exposure precedes disease) is the only Bradford Hill criterion that is absolutely required for causation." },

  // ── Epidemiological Measures ──────────────────────────────────
  { term: "Relative Risk (Risk Ratio)", type: "concept", category: "measures", meaning: "The ratio of the incidence of disease in the exposed group to the incidence in the unexposed group; used in cohort studies. RR = 1 means no association, > 1 increased risk, < 1 protective.", example: "A relative risk of 3.0 for lung cancer among smokers means smokers develop lung cancer at 3× the rate of non-smokers." },
  { term: "Odds Ratio (OR)", type: "concept", category: "measures", meaning: "The ratio of the odds of exposure among cases to the odds of exposure among controls; used in case-control studies. Approximates relative risk when the disease is rare.", example: "An OR of 8 for asbestos exposure and mesothelioma means exposed individuals have 8× the odds of developing mesothelioma." },
  { term: "Attributable Risk (Risk Difference)", type: "concept", category: "measures", meaning: "The difference in incidence between exposed and unexposed groups; represents the excess risk due to the exposure and estimates how many cases could be prevented if exposure were eliminated.", example: "If smokers have a CHD rate of 300/100,000 and non-smokers 100/100,000, the attributable risk is 200 — those extra cases are attributable to smoking." },
  { term: "Population Attributable Risk (PAR)", type: "concept", category: "measures", meaning: "The proportion of disease in the entire population attributable to a specific exposure; accounts for the prevalence of exposure and is the relevant measure for public health decision-making.", example: "Even though the RR for obesity and heart disease is moderate, obesity has a high PAR because so much of the population is obese." },
  { term: "Sensitivity and Specificity", type: "concept", category: "measures", meaning: "Sensitivity: the probability a test is positive given disease is present (true positive rate). Specificity: the probability a test is negative given no disease (true negative rate).", example: "A screening test with high sensitivity but lower specificity catches most true cases but produces many false positives requiring confirmatory testing." },
  { term: "Positive Predictive Value (PPV) and Negative Predictive Value (NPV)", type: "concept", category: "measures", meaning: "PPV: the probability a positive test result truly has the disease. NPV: the probability a negative result truly lacks the disease. Both depend heavily on disease prevalence in the population tested.", example: "In a low-prevalence population, a positive HIV test by ELISA has low PPV and requires Western blot confirmation." },
  { term: "Number Needed to Treat (NNT)", type: "concept", category: "measures", meaning: "The number of patients who must receive a treatment to prevent one additional adverse outcome; NNT = 1 / absolute risk reduction. Lower NNT = more effective treatment.", example: "If a drug reduces cardiac events from 10% to 8%, the ARR is 2% and the NNT is 50 — treat 50 people to prevent one event." },
  { term: "Confidence Interval", type: "concept", category: "measures", meaning: "A range of values that, with a specified probability (usually 95%), contains the true population parameter. If a 95% CI for a relative risk does not cross 1.0, the result is statistically significant.", example: "A relative risk of 2.5 (95% CI 1.8–3.4) is statistically significant — the CI does not include 1.0 (the null value)." },
  { term: "P-Value", type: "concept", category: "measures", meaning: "The probability of observing results at least as extreme as those found, assuming the null hypothesis (no association) is true; P < 0.05 conventionally indicates statistical significance.", example: "A P-value of 0.03 means there is a 3% probability of seeing this association by chance alone if the null hypothesis were true." },
  { term: "Epidemic Curve (Epi Curve)", type: "concept", category: "measures", meaning: "A histogram of the number of cases by date of illness onset during an outbreak; the shape reveals the mode of transmission (point source, propagated) and the incubation period.", example: "A narrow, bell-shaped epi curve with cases clustering within one incubation period indicates a point-source outbreak (like a shared food item)." },

  // ── Surveillance & Outbreak Investigation ────────────────────
  { term: "Passive vs Active Surveillance", type: "concept", category: "surveillance", meaning: "Passive surveillance: healthcare providers voluntarily report cases to public health agencies — the most common but underestimates true burden. Active surveillance: health authorities actively seek out cases through direct contact.", example: "Sentinel surveillance of influenza-like illness at selected clinics is a form of active surveillance providing early warning of flu season trends." },
  { term: "Notifiable (Reportable) Disease", type: "concept", category: "surveillance", meaning: "A disease that healthcare providers are legally required to report to public health authorities upon diagnosis; the list is set by each state and federally by the CDC for nationally notifiable conditions.", example: "Tuberculosis, HIV, salmonellosis, and measles are all nationally notifiable diseases that must be reported to the CDC." },
  { term: "Outbreak Investigation Steps", type: "concept", category: "surveillance", meaning: "The systematic CDC ten-step process: (1) prepare, (2) verify diagnosis, (3) confirm outbreak exists, (4) define and identify cases, (5) describe (person/place/time), (6) hypothesize, (7) test hypotheses, (8) refine/implement control, (9) communicate, (10) report.", example: "Investigators confirmed the restaurant outbreak by verifying lab-confirmed Salmonella, generating an epi curve, and tracing the source to contaminated eggs via a case-control study." },
  { term: "Food-Borne Outbreak Investigation", type: "concept", category: "surveillance", meaning: "Epidemiological investigation of GI disease linked to food consumption; key tools are food-specific attack rates (comparing attack rates by item consumed) and laboratory confirmation of stool cultures.", example: "The attack rate for potato salad was 80% among those who ate it versus 10% who did not — strong evidence it was the vehicle." },
  { term: "Contact Tracing", type: "concept", category: "surveillance", meaning: "The process of identifying and notifying individuals who may have been exposed to a case of communicable disease, assessing their risk, and linking them to testing, quarantine, and treatment.", example: "Contact tracers identified 47 exposures from the index case and quarantined 12 unvaccinated close contacts who later developed disease." },
  { term: "Quarantine vs Isolation", type: "concept", category: "surveillance", meaning: "Isolation separates ill, infectious persons from the healthy. Quarantine restricts the movement of people who have been exposed but are not yet ill, to prevent potential spread during the incubation period.", example: "Confirmed COVID-19 cases were isolated for 10 days; their exposed household contacts were quarantined for 14 days." },
  { term: "Sentinel Surveillance", type: "concept", category: "surveillance", meaning: "A monitoring system using a selected network of reporting sites (sentinel sites) to track disease trends; efficient but not representative of the full population.", example: "The WHO uses a global sentinel influenza surveillance network of labs to track circulating strains and guide annual vaccine formulation." },
  { term: "MMWR (Morbidity and Mortality Weekly Report)", type: "concept", category: "surveillance", meaning: "A weekly public health bulletin published by the CDC containing surveillance data on diseases, injury, and public health conditions; the primary U.S. public health surveillance publication.", example: "The first reports of what would become the AIDS epidemic appeared in the MMWR in June 1981 as unusual Pneumocystis pneumonia in young gay men." },
  { term: "Syndromic Surveillance", type: "concept", category: "surveillance", meaning: "Early warning surveillance using pre-diagnostic data (ER chief complaints, pharmacy sales, school absenteeism) to detect unusual patterns before confirmed diagnoses are made.", example: "BioSense monitored emergency department visits for influenza-like illness, providing 1–2 weeks of earlier warning than traditional flu surveillance." },
  { term: "Vector and Reservoir", type: "concept", category: "surveillance", meaning: "A vector is a living organism (usually arthropod) that transmits an infectious agent. A reservoir is the host or environment in which the pathogen normally lives and multiplies.", example: "Aedes aegypti mosquitoes are the vector for dengue and Zika; humans are the reservoir for measles; rodents are the reservoir for plague." },

  // ── Historical Epidemics ──────────────────────────────────────
  { term: "John Snow and Cholera (1854)", type: "concept", category: "historical", meaning: "British physician John Snow mapped cholera cases in Soho, London and traced them to the Broad Street water pump, establishing the waterborne transmission of cholera and founding the field of epidemiology — before germ theory.", example: "By removing the handle from the Broad Street pump Snow interrupted the outbreak, demonstrating that epidemiological evidence could guide public health action without knowing the causative organism." },
  { term: "The 1918 Influenza Pandemic", type: "concept", category: "historical", meaning: "The most deadly infectious disease outbreak in recorded history, infecting ~500 million people (one-third of the world population) and killing an estimated 50–100 million; notable for its unusual W-shaped mortality curve hitting young adults hardest.", example: "The 1918 pandemic killed more soldiers in WWI than combat and accelerated the end of the war due to troop depletion." },
  { term: "HIV/AIDS Epidemic", type: "concept", category: "historical", meaning: "First identified in 1981 among MSM in the U.S., then IDUs, hemophiliacs, and Haitian immigrants — the \\"4-H\\" groups. Caused by HIV, a retrovirus; global pandemic with ~40 million deaths since onset.", example: "The discovery of the common transmission route across the initial risk groups led to the identification of HIV as a bloodborne and sexually transmitted pathogen." },
  { term: "Smallpox Eradication (1980)", type: "concept", category: "historical", meaning: "The first and only human disease to be globally eradicated; achieved through the WHO\\'s Intensified Eradication Programme using ring vaccination (vaccinating contacts of cases) rather than mass vaccination.", example: "Smallpox eradication is the landmark achievement of public health — the last natural case occurred in Somalia in 1977." },
  { term: "SARS-CoV-2 / COVID-19 Pandemic", type: "concept", category: "historical", meaning: "A coronavirus pandemic beginning in late 2019 caused by SARS-CoV-2; characterized by respiratory transmission (droplet and airborne), pre-symptomatic spread, and rapid global dissemination; led to unprecedented non-pharmaceutical interventions.", example: "SARS-CoV-2\\'s combination of moderate CFR (~1–2%) with high transmissibility (R0 of 2–3) produced a far greater total burden than SARS-1, which had higher CFR but lower spread." },
  { term: "Tuskegee Syphilis Study (1932–1972)", type: "concept", category: "historical", meaning: "A 40-year U.S. PHS study on the natural history of untreated syphilis in Black men in Alabama who were not informed of their diagnosis and were deliberately denied penicillin after it became standard of care.", example: "The Tuskegee scandal led directly to the Belmont Report (1979) and the establishment of federal requirements for informed consent and IRB oversight." },
  { term: "Framingham Heart Study", type: "concept", category: "historical", meaning: "A landmark prospective cohort study begun in 1948 in Framingham, MA; identified major cardiovascular risk factors (smoking, hypertension, hypercholesterolemia, diabetes, age, sex) and introduced the concept of \\"risk factor.\\"", example: "Before Framingham, clinicians did not know which patient characteristics predicted heart disease; the study created the foundation of preventive cardiology." },
  { term: "Doll and Hill Smoking and Lung Cancer (1950)", type: "concept", category: "historical", meaning: "The landmark case-control study by Richard Doll and Austin Bradford Hill demonstrating a strong association between cigarette smoking and lung cancer; helped establish the Bradford Hill criteria for causation.", example: "Doll, a smoker himself, was so convinced by the data that he quit smoking immediately after analyzing the results." },

  // ── Prevention & Control ──────────────────────────────────────
  { term: "Levels of Prevention", type: "concept", category: "prevention", meaning: "Primary prevention: preventing disease before it occurs (vaccination, tobacco cessation). Secondary prevention: early detection and treatment (screening). Tertiary prevention: reducing disability and complications (rehabilitation).", example: "Flu vaccination is primary prevention; mammography screening for breast cancer is secondary; cardiac rehab after MI is tertiary prevention." },
  { term: "Primordial Prevention", type: "concept", category: "prevention", meaning: "The most upstream level of prevention — addressing the social, economic, and environmental determinants of risk factors before they develop; population-level policy interventions.", example: "Taxing sugary beverages and subsidizing fruits and vegetables are primordial prevention strategies targeting obesity before it develops." },
  { term: "Social Determinants of Health", type: "concept", category: "prevention", meaning: "The conditions in which people are born, grow, live, work, and age — including income, education, employment, social support, and neighborhood environment — that powerfully shape health outcomes.", example: "Zip code is a stronger predictor of life expectancy than genetic code in many cities, reflecting the power of social determinants." },
  { term: "Non-Pharmaceutical Interventions (NPIs)", type: "concept", category: "prevention", meaning: "Actions other than vaccines and medicines to slow transmission during outbreaks: social distancing, masking, hand hygiene, school closure, quarantine, and travel restrictions.", example: "During the 1918 pandemic, cities that implemented NPIs early had lower peak mortality — a finding replicated during COVID-19." },
  { term: "Screening Criteria (Wilson-Jungner)", type: "concept", category: "prevention", meaning: "Ten classical criteria for a disease to be suitable for population screening, including: the condition must be an important health problem, there must be a detectable latent stage, and an effective treatment must be available.", example: "Cervical cancer meets Wilson-Jungner criteria: it is common, has a detectable precancerous stage (CIN), and Pap smear is a feasible, acceptable screening test." },
  { term: "Vaccine-Preventable Diseases and Immunization Schedule", type: "concept", category: "prevention", meaning: "Standardized schedules (published annually by the CDC/ACIP) specifying which vaccines are recommended for which ages; designed to provide protection before age of risk.", example: "The MMR vaccine is given at 12–15 months and again at 4–6 years — the two-dose schedule achieves 97% effectiveness against measles." },
  { term: "One Health", type: "concept", category: "prevention", meaning: "A collaborative, transdisciplinary approach recognizing that human health, animal health, and environmental/ecosystem health are inextricably linked; critical for addressing zoonotic diseases, antimicrobial resistance, and food safety.", example: "A One Health team of physicians, veterinarians, and ecologists identified deforestation as the driver of increased bat-to-human spillover of Nipah virus." },
  { term: "Antimicrobial Resistance (AMR)", type: "concept", category: "prevention", meaning: "The ability of microorganisms to resist antimicrobial treatments to which they were previously susceptible; driven by overuse in humans and agriculture; a major global public health threat.", example: "MRSA emerged from overuse of methicillin and now causes healthcare-associated infections that require vancomycin or newer agents." },
];'''

# Replace the TERMS array
old_terms_block = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
if not old_terms_block:
    raise SystemExit('Could not find TERMS array')
html = html[:old_terms_block.start()] + TERMS_JS + html[old_terms_block.end():]

# Replace categoryLabel
CAT_LABEL = """const categoryLabel = c => ({
  'foundations':   'Foundations',
  'study-design':  'Study Designs',
  'measures':      'Measures & Stats',
  'surveillance':  'Surveillance',
  'historical':    'Historical Epidemics',
  'prevention':    'Prevention & Control',
})[c] || c;"""

html = re.sub(
    r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;",
    CAT_LABEL,
    html,
    count=1,
    flags=re.DOTALL
)

# Replace DB_PATH, title, heading, subtitle
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'epidemiology';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>',
                    '<title>HOSA Prep Hub — Epidemiology</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>',
                    '<h1>Epi<em>demiology</em>.</h1>', 1)
html = html.replace(
    'A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
    'A study companion for epidemiological foundations, study design, measures and statistics, disease surveillance, outbreak investigation, historical epidemics, and levels of prevention — built for HOSA competitors.',
    1
)
html = html.replace('//  DATA — HOSA Emergency Medical Science',
                    '//  DATA — HOSA Epidemiology', 1)

with open(DST, 'w', encoding='utf-8') as f:
    f.write(html)

count = TERMS_JS.count('{ term:')
print(f'Wrote {DST} — {count} terms')
