#!/usr/bin/env python3
"""Generate obstetrics-gynecology.html from dental-science.html template."""
import os, re
BASE = '/home/user/hosa-prep-hub'
SRC, DST = os.path.join(BASE, 'dental-science.html'), os.path.join(BASE, 'obstetrics-gynecology.html')
with open(SRC, 'r', encoding='utf-8') as f: html = f.read()
TERMS_JS = '''const TERMS = [
  // ── Female Reproductive Anatomy & Physiology ─────────────────
  { term: "Menstrual Cycle Phases", type: "concept", category: "anatomy", meaning: "Follicular (days 1-13): FSH stimulates follicle growth, rising estrogen. Ovulation (~day 14): LH surge. Luteal (days 15-28): corpus luteum produces progesterone. Cycle length ~28 days. Without conception, hormones drop → menses.", example: "The patient's basal body temperature rise on day 15 confirmed ovulation occurred — luteal phase progesterone rise." },
  { term: "Female Reproductive Anatomy", type: "concept", category: "anatomy", meaning: "External: vulva, labia, clitoris. Internal: vagina, cervix, uterus (corpus + fundus), fallopian tubes, ovaries. Pelvic ligaments support. Blood supply: uterine and ovarian arteries.", example: "Pelvic exam visualizing the cervix through speculum, then bimanual exam palpating uterus and adnexa — routine GYN evaluation." },
  { term: "Hormonal Regulation (HPO Axis)", type: "concept", category: "anatomy", meaning: "Hypothalamus → GnRH (pulsatile) → pituitary FSH/LH → ovaries → estrogen/progesterone. Negative feedback throughout. Positive feedback of estrogen at mid-cycle triggers LH surge.", example: "The patient's PCOS disrupted normal HPO axis pulsatility, causing chronic anovulation and infertility." },

  // ── Pregnancy & Prenatal Care ────────────────────────────────
  { term: "Naegele's Rule (EDD)", type: "concept", category: "pregnancy", meaning: "Estimated due date: LMP + 7 days - 3 months + 1 year. Typical pregnancy 40 weeks from LMP (38 from conception). Term: 37-42 weeks. Preterm: <37. Post-term: >42.", example: "Patient's LMP was March 1; Naegele's rule estimated EDD of December 8 — 40 weeks gestation." },
  { term: "Trimesters and Fetal Development", type: "concept", category: "pregnancy", meaning: "1st trimester (1-12 wk): organogenesis, highest teratogen risk. 2nd (13-27 wk): fetal movement felt, viability ~24 wk. 3rd (28-40 wk): rapid growth, lung maturity. Quickening at 16-20 wk.", example: "The patient felt quickening at 18 weeks — first fetal movement — confirming continued pregnancy progression." },
  { term: "Prenatal Visits and Screening", type: "concept", category: "pregnancy", meaning: "Initial visit: history, exam, labs (CBC, blood type/Rh, antibody screen, HIV, syphilis, rubella, urine). Monthly until 28 wk, biweekly until 36, then weekly. Genetic screening: NIPT (10+ wk), nuchal translucency (11-14), quad screen (16-18).", example: "The 32-week patient received GBS screening, GDM 1-hour glucose, and CBC at her routine prenatal visit." },
  { term: "Common Pregnancy Complications", type: "concept", category: "pregnancy", meaning: "Hyperemesis gravidarum (severe nausea with weight loss, dehydration). Gestational diabetes (insulin resistance, screened 24-28 wk). Preeclampsia (BP >140/90 after 20 wk + proteinuria). Placenta previa (placenta covers cervix — painless bleeding).", example: "The patient's 26-week BP of 152/96 with 1.2 g/24h proteinuria diagnosed preeclampsia; magnesium sulfate and delivery planning ensued." },
  { term: "Preeclampsia and Eclampsia", type: "concept", category: "pregnancy", meaning: "Preeclampsia: HTN + proteinuria or end-organ damage after 20 wk. Severe: BP ≥160/110, low platelets, HELLP, neuro symptoms. Eclampsia: seizures. Treated with magnesium sulfate (seizure prophylaxis), antihypertensives, delivery (definitive).", example: "The patient's severe preeclampsia at 34 wk with platelets 60K and headache prompted magnesium sulfate and urgent delivery." },

  // ── Labor & Delivery ─────────────────────────────────────────
  { term: "Stages of Labor", type: "concept", category: "labor-delivery", meaning: "Stage 1 (onset to full dilation 10 cm): latent (0-6 cm), active (6-10 cm). Stage 2 (full dilation to delivery): pushing. Stage 3 (delivery to placenta): typically 5-30 min. Stage 4 (postpartum recovery 1-4 hr).", example: "The primigravida's 12-hour stage 1 progressed to active phase 6 cm with regular strong contractions every 3 minutes." },
  { term: "Cardinal Movements of Labor", type: "concept", category: "labor-delivery", meaning: "Engagement → descent → flexion → internal rotation → extension (head delivery) → external rotation (restitution) → expulsion. Mechanism of fetal passage through pelvis.", example: "After full dilation, the fetal head completed internal rotation to OA position, then delivered by extension under the symphysis." },
  { term: "Fetal Heart Rate Monitoring", type: "concept", category: "labor-delivery", meaning: "Baseline 110-160 bpm. Accelerations (reassuring, fetal well-being). Decelerations: early (head compression — benign), variable (cord compression), late (uteroplacental insufficiency — worrisome).", example: "Recurrent late decelerations on the monitor prompted intrauterine resuscitation and ultimately emergent cesarean for non-reassuring tracing." },
  { term: "Vaginal vs Cesarean Delivery", type: "concept", category: "labor-delivery", meaning: "Vaginal: faster recovery, lower infection, preferred. Cesarean (~30% US rate): indicated for malpresentation, non-reassuring tracing, failure to progress, previous CS (sometimes), placenta previa. Higher morbidity but lifesaving.", example: "After 4 hours of arrest of descent at +1 station despite adequate contractions, the patient underwent cesarean delivery." },
  { term: "Postpartum Hemorrhage", type: "concept", category: "labor-delivery", meaning: "Blood loss >500 mL (vaginal) or >1000 mL (CS) within 24 hr. Causes 'four Ts': Tone (atony — #1), Trauma, Tissue (retained placenta), Thrombin (coagulopathy). Treated with uterotonics (oxytocin, methergine, hemabate), fluid, blood products.", example: "After delivery the patient developed atonic uterus and 1500 mL blood loss; oxytocin and methergine restored uterine tone." },

  // ── GYN Conditions ───────────────────────────────────────────
  { term: "Polycystic Ovary Syndrome (PCOS)", type: "concept", category: "gyn-conditions", meaning: "Rotterdam criteria (2 of 3): hyperandrogenism (hirsutism, acne), oligo/anovulation, polycystic ovaries. Insulin resistance common. Treated with OCPs, metformin, lifestyle, ovulation induction for fertility.", example: "The 24-year-old's irregular menses, hirsutism, and polycystic ovaries met Rotterdam criteria — combined OCP and metformin were initiated." },
  { term: "Endometriosis", type: "concept", category: "gyn-conditions", meaning: "Endometrial tissue outside uterus (ovaries, pelvic peritoneum, bowel). Causes cyclical pain, dyspareunia, infertility. Diagnosed by laparoscopy. Treated with NSAIDs, OCPs/GnRH agonists, surgical excision.", example: "The patient's severe dysmenorrhea and dyspareunia worsening over years led to diagnostic laparoscopy confirming endometriosis." },
  { term: "Uterine Fibroids (Leiomyomas)", type: "concept", category: "gyn-conditions", meaning: "Benign smooth muscle uterine tumors; very common (~70% women by 50). Symptoms: heavy menses, pelvic pressure, infertility. Treated with NSAIDs, OCPs, tranexamic acid, myomectomy, hysterectomy, UAE.", example: "The patient's heavy menses with anemia and 6 cm intramural fibroid on ultrasound was managed with tranexamic acid and myomectomy referral." },
  { term: "Pelvic Inflammatory Disease (PID)", type: "concept", category: "gyn-conditions", meaning: "Ascending infection of upper genital tract; usually polymicrobial (gonorrhea, chlamydia). Symptoms: pelvic pain, cervical motion tenderness, fever, discharge. Complications: tubo-ovarian abscess, infertility, ectopic. Treated with ceftriaxone + doxycycline + metronidazole.", example: "The patient's pelvic pain, fever, and cervical motion tenderness with positive gonorrhea/chlamydia NAAT confirmed PID; outpatient triple antibiotics were prescribed." },
  { term: "Cervical Cancer Screening", type: "concept", category: "gyn-conditions", meaning: "Pap smear ± HPV testing. Start at 21 (Pap q3y); 30-65 (co-testing q5y or Pap q3y); stop at 65 if prior negatives. HPV vaccination prevents most. Abnormal Pap → colposcopy with biopsy.", example: "The 32-year-old's high-risk HPV positive and ASCUS Pap led to colposcopy showing CIN II — LEEP procedure was performed." },
  { term: "Breast Cancer Screening (Mammography)", type: "concept", category: "gyn-conditions", meaning: "USPSTF: biennial mammogram age 50-74. ACS: annual age 45-54, then biennial. High-risk (BRCA, family history): start earlier with MRI + mammogram. BI-RADS 4-5 requires biopsy.", example: "The 52-year-old's screening mammogram showed BI-RADS 4 calcifications; stereotactic biopsy confirmed ductal carcinoma in situ." },
  { term: "Contraception Methods", type: "concept", category: "gyn-conditions", meaning: "Reversible: combined OCPs (estrogen contraindications: VTE history, smoker >35, migraine with aura), POPs, patch, ring, depot, IUD (copper or hormonal), implant. Permanent: tubal ligation, vasectomy. Emergency: levonorgestrel, ulipristal.", example: "The 28-year-old breastfeeding mother chose the copper IUD for long-acting reversible contraception — no estrogen, lasts 10 years." },
  { term: "Menopause", type: "concept", category: "gyn-conditions", meaning: "Permanent cessation of menses (12 mo amenorrhea), average age 51. Symptoms: hot flashes, night sweats, vaginal dryness, mood, sleep. Treated with hormone therapy (HT) for severe symptoms; risks (VTE, breast cancer) considered.", example: "The 52-year-old's hot flashes 20×/day responded to low-dose transdermal estradiol + progesterone — duration of HT individualized to risk." },
];'''
m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
html = html[:m.start()] + TERMS_JS + html[m.end():]
CAT = """const categoryLabel = c => ({
  'anatomy':         'Female Reproductive A&P',
  'pregnancy':       'Pregnancy & Prenatal Care',
  'labor-delivery':  'Labor & Delivery',
  'gyn-conditions':  'GYN Conditions',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'obstetrics-gynecology';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>', '<title>HOSA Prep Hub — Obstetrics &amp; Gynecology</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>', '<h1>Obstetrics<br>&amp; <em>Gynecology</em>.</h1>', 1)
html = html.replace('A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
                    'A study companion for female reproductive anatomy and physiology, pregnancy and prenatal care, labor and delivery, and gynecologic conditions — built for HOSA competitors.', 1)
html = html.replace('//  DATA — HOSA Emergency Medical Science', '//  DATA — HOSA Obstetrics & Gynecology', 1)
with open(DST, 'w', encoding='utf-8') as f: f.write(html)
print(f'Wrote {DST} — {TERMS_JS.count("{ term:")} terms')
