#!/usr/bin/env python3
"""Generate veterinary-science.html from dental-science.html template."""
import os, re

BASE = '/home/user/hosa-prep-hub'
SRC = os.path.join(BASE, 'dental-science.html')
DST = os.path.join(BASE, 'veterinary-science.html')

with open(SRC, 'r', encoding='utf-8') as f:
    html = f.read()

# Veterinary Science TERMS — 68 terms across 6 categories
TERMS_JS = '''const TERMS = [
  // ── Anatomy & Physiology ─────────────────────────────────────
  { term: "Ruminant Digestive System", type: "concept", category: "anatomy", meaning: "A four-compartment stomach (rumen, reticulum, omasum, abomasum) found in cattle, sheep, goats, and deer that ferments fibrous plant material via microbial action before true gastric digestion.", example: "Because of the rumen, cattle can extract nutrients from grass that monogastric animals like dogs cannot digest." },
  { term: "Withers", type: "concept", category: "anatomy", meaning: "The ridge between the shoulder blades of horses and dogs; the standard anatomical point at which horse height is measured.", example: "The Thoroughbred stood 16.2 hands at the withers — about 66 inches from ground to ridge." },
  { term: "Hock", type: "concept", category: "anatomy", meaning: "The tarsal joint of the hind limb in horses, cattle, dogs, and other quadrupeds; anatomically equivalent to the human ankle.", example: "A swollen hock in a racehorse often indicates bog spavin or thoroughpin and warrants a soundness exam." },
  { term: "Cannon Bone", type: "concept", category: "anatomy", meaning: "The large metacarpal (forelimb) or metatarsal (hindlimb) bone between the knee/hock and fetlock in horses, supporting the entire weight of the animal during stance and gait.", example: "Stress fractures of the cannon bone are common in young racehorses with heavy training schedules." },
  { term: "Frog", type: "concept", category: "anatomy", meaning: "The V-shaped, rubbery structure on the underside of a horse's hoof that absorbs shock, aids circulation, and provides traction.", example: "Thrush is a bacterial infection of the frog that produces a foul-smelling black discharge." },
  { term: "Crop", type: "concept", category: "anatomy", meaning: "A dilated, thin-walled pouch of the esophagus in birds where food is softened and stored before passing to the proventriculus.", example: "Crop stasis in a parrot — failure of the crop to empty — is an emergency that can lead to fermentation and sepsis." },
  { term: "Gizzard (Ventriculus)", type: "concept", category: "anatomy", meaning: "The muscular stomach of birds that grinds food mechanically with the aid of swallowed grit; performs the equivalent of mammalian chewing.", example: "Chickens swallow small stones that lodge in the gizzard to help grind whole grain into a digestible paste." },
  { term: "Nictitating Membrane", type: "concept", category: "anatomy", meaning: "The third eyelid; a translucent fold of conjunctiva in the medial canthus that sweeps across the cornea to protect and moisten the eye in dogs, cats, birds, and reptiles.", example: "A prolapsed nictitans (\\"cherry eye\\") in a young Bulldog requires surgical replacement of the gland, not excision." },
  { term: "Dewclaw", type: "concept", category: "anatomy", meaning: "The vestigial first digit on the medial side of a dog's leg, attached by skin (rear) or with bone (front); analogous to a thumb but non-weight-bearing.", example: "Rear dewclaws are often removed in puppyhood because they can catch and tear on rough terrain." },
  { term: "Estrous Cycle", type: "concept", category: "anatomy", meaning: "The reproductive cycle of non-primate mammals consisting of proestrus, estrus (heat), metestrus (diestrus), and anestrus; the period of sexual receptivity is called estrus.", example: "Bitches typically cycle twice a year and stand to be bred only during the 5- to 9-day estrus phase." },
  { term: "Cecum", type: "concept", category: "anatomy", meaning: "A blind-ended sac at the junction of the small and large intestine; massively enlarged in horses and rabbits as the primary site of microbial fermentation of fiber.", example: "The horse's 1-meter-long cecum allows hindgut fermentation of forage in a non-ruminant herbivore." },
  { term: "Carapace and Plastron", type: "concept", category: "anatomy", meaning: "The dorsal (carapace) and ventral (plastron) bony shells of turtles and tortoises, fused to the ribs and vertebrae; cannot be \\"shed\\" or removed.", example: "Pyramiding of the carapace in young tortoises indicates dietary or husbandry problems, often excess protein and low humidity." },

  // ── Diseases & Conditions ────────────────────────────────────
  { term: "Canine Parvovirus", type: "concept", category: "diseases", meaning: "A highly contagious DNA virus causing severe hemorrhagic enteritis, vomiting, and immunosuppression in unvaccinated puppies; transmitted via fecal-oral route and extremely environmentally stable.", example: "The 8-week-old Lab puppy presented with bloody diarrhea and dehydration; a fecal SNAP test confirmed parvovirus and aggressive IV fluid therapy was started." },
  { term: "Canine Distemper", type: "concept", category: "diseases", meaning: "A paramyxovirus (related to measles) causing multisystemic disease — respiratory, GI, and neurologic — in unvaccinated dogs; high mortality and survivors often have permanent neurologic deficits.", example: "Hard pad disease (hyperkeratosis of the footpads and nose) is a classic late sign of canine distemper." },
  { term: "Feline Leukemia Virus (FeLV)", type: "concept", category: "diseases", meaning: "A retrovirus transmitted between cats via saliva (grooming, shared bowls, bites) that causes immunosuppression, anemia, and lymphoma; persistently infected cats shed virus for life.", example: "Outdoor cats should be tested with a SNAP combo test for FeLV and FIV before introduction to a multi-cat household." },
  { term: "Feline Immunodeficiency Virus (FIV)", type: "concept", category: "diseases", meaning: "A lentivirus (related to HIV) transmitted primarily through bite wounds that causes progressive immune suppression in cats; not transmissible to humans.", example: "FIV-positive cats can live many years with supportive care and should be kept indoors to prevent secondary infections and spread." },
  { term: "Kennel Cough (Infectious Tracheobronchitis)", type: "concept", category: "diseases", meaning: "A complex of contagious upper respiratory infections in dogs, most commonly caused by Bordetella bronchiseptica, parainfluenza virus, and canine adenovirus-2; produces a harsh honking cough.", example: "A dog returning from boarding with a dry honking cough was diagnosed with kennel cough and isolated from other patients." },
  { term: "Gastric Dilatation-Volvulus (GDV / Bloat)", type: "concept", category: "diseases", meaning: "An acute, life-threatening condition in deep-chested dogs where the stomach distends with gas and rotates on its axis, cutting off blood supply; requires emergency decompression and surgery.", example: "The Great Dane with a distended abdomen, retching without producing vomitus, and shock was rushed to surgery for GDV." },
  { term: "Equine Colic", type: "concept", category: "diseases", meaning: "A clinical sign — not a specific disease — of abdominal pain in horses caused by gas, impactions, displacements, torsions, or enteritis; the leading medical cause of death in horses.", example: "Pawing, flank-watching, and rolling are signs of colic that warrant immediate veterinary evaluation due to risk of intestinal torsion." },
  { term: "Laminitis (Founder)", type: "concept", category: "diseases", meaning: "Inflammation of the sensitive laminae that bond the hoof wall to the coffin bone in horses; severe cases cause rotation or sinking of the coffin bone and can end a career.", example: "A pony allowed unrestricted spring pasture developed acute laminitis with a sawhorse stance and bounding digital pulses." },
  { term: "Mastitis", type: "concept", category: "diseases", meaning: "Inflammation of the mammary gland, almost always bacterial, that reduces milk yield and quality; the most economically significant disease in dairy cattle.", example: "The cow's quarter was hot, swollen, and produced clotted milk — a California Mastitis Test confirmed clinical mastitis." },
  { term: "Foot-and-Mouth Disease (FMD)", type: "concept", category: "diseases", meaning: "A highly contagious viral vesicular disease of cloven-hoofed animals (cattle, pigs, sheep, deer) causing fever, lameness, and vesicles on the mouth and feet; not present in the U.S. and a reportable foreign animal disease.", example: "Suspected FMD requires immediate notification of state and federal animal health authorities — no treatment is attempted." },
  { term: "Bovine Spongiform Encephalopathy (BSE)", type: "concept", category: "diseases", meaning: "A prion disease (\\"mad cow disease\\") causing progressive neurodegeneration in cattle; transmissible to humans as variant Creutzfeldt-Jakob disease through consumption of contaminated tissue.", example: "BSE surveillance and a feed ban on ruminant-derived protein dramatically reduced incidence after the UK epidemic of the 1990s." },
  { term: "Canine Hip Dysplasia", type: "concept", category: "diseases", meaning: "A heritable, multifactorial developmental disorder of the hip joint in which the femoral head and acetabulum fit poorly, leading to laxity, subluxation, and osteoarthritis; common in large breeds.", example: "PennHIP and OFA radiographs are used to evaluate breeding dogs for hip dysplasia before they reproduce." },
  { term: "Feline Hyperthyroidism", type: "concept", category: "diseases", meaning: "The most common endocrine disease of older cats, caused by a benign functional thyroid adenoma producing excess thyroxine; presents with weight loss despite a ravenous appetite.", example: "A 14-year-old cat with weight loss, polyphagia, vocalization, and an elevated T4 was diagnosed with hyperthyroidism and started on methimazole." },
  { term: "Diabetes Mellitus (Feline/Canine)", type: "concept", category: "diseases", meaning: "A disorder of insulin deficiency or resistance causing hyperglycemia, glucosuria, and the classic signs of polyuria, polydipsia, polyphagia, and weight loss; dogs typically Type 1, cats often Type 2-like.", example: "The obese 11-year-old cat with PU/PD and a blood glucose of 380 was diagnosed with diabetes and started on glargine insulin." },

  // ── Parasites & Zoonotic Diseases ────────────────────────────
  { term: "Heartworm Disease (Dirofilaria immitis)", type: "concept", category: "parasites", meaning: "A parasitic nematode transmitted by mosquitoes that lives in the pulmonary arteries and right heart of dogs (and less commonly cats), causing pulmonary hypertension, right-sided heart failure, and death.", example: "A heartworm-positive dog with cough and exercise intolerance was treated with melarsomine in a careful staged protocol with strict cage rest." },
  { term: "Hookworms (Ancylostoma)", type: "concept", category: "parasites", meaning: "Blood-sucking intestinal nematodes that attach to the small intestinal mucosa and cause anemia, dark tarry stool, and poor growth; transmitted via ingestion, skin penetration, transmammary, and transplacental routes.", example: "A neonatal puppy with severe pale mucous membranes and bloody stool was diagnosed with transplacentally acquired Ancylostoma and received deworming and a blood transfusion." },
  { term: "Roundworms (Toxocara)", type: "concept", category: "parasites", meaning: "Large white intestinal nematodes (Toxocara canis in dogs, T. cati in cats) commonly transmitted to neonates transplacentally and via milk; cause potbellied appearance and visceral larva migrans in humans.", example: "Children should not handle puppy feces — Toxocara canis is a zoonotic cause of visceral and ocular larva migrans." },
  { term: "Tapeworms (Dipylidium / Taenia)", type: "concept", category: "parasites", meaning: "Segmented intestinal cestodes whose proglottids (segments) are passed in feces and resemble grains of rice; Dipylidium is transmitted by flea ingestion, Taenia by rodent or ruminant ingestion.", example: "Rice-like segments around the cat's anus and in bedding indicated Dipylidium caninum — treatment required both praziquantel and flea control." },
  { term: "Coccidia (Cystoisospora)", type: "concept", category: "parasites", meaning: "An intracellular protozoan parasite of the intestinal epithelium that causes watery, sometimes bloody diarrhea in young or stressed animals; diagnosed by oocysts on fecal flotation.", example: "A puppy from a high-density rescue with persistent diarrhea was treated with sulfadimethoxine for coccidiosis." },
  { term: "Giardia", type: "concept", category: "parasites", meaning: "A flagellated intestinal protozoan transmitted through cysts in contaminated water or feces, causing soft, foul-smelling diarrhea; diagnosed by SNAP antigen test or zinc sulfate flotation; has zoonotic potential.", example: "Hikers should not let dogs drink from streams — Giardia from wild ruminants infects both dogs and people." },
  { term: "Fleas (Ctenocephalides felis)", type: "concept", category: "parasites", meaning: "Wingless hematophagous insects that cause pruritus, flea-allergy dermatitis, anemia in heavy infestations, and serve as the intermediate host for Dipylidium caninum.", example: "A cat with severe pruritus over the dorsal lumbar region was diagnosed with flea-allergy dermatitis and started on monthly isoxazoline preventive." },
  { term: "Ticks (Ixodes, Rhipicephalus)", type: "concept", category: "parasites", meaning: "Hematophagous arachnids that transmit Lyme disease, ehrlichiosis, anaplasmosis, Rocky Mountain spotted fever, and babesiosis; should be removed promptly with fine-tipped forceps grasping at the head.", example: "The hunting dog presented with shifting lameness and fever, and a 4Dx test confirmed Anaplasma exposure from tick bite." },
  { term: "Sarcoptic Mange", type: "concept", category: "parasites", meaning: "A highly contagious, intensely pruritic skin disease caused by the burrowing mite Sarcoptes scabiei; transmissible to humans (scabies) and other mammals.", example: "A stray dog with severe pruritus, alopecia, and crusted lesions on the ears, elbows, and ventral abdomen had Sarcoptes mites confirmed by skin scraping." },
  { term: "Demodectic Mange", type: "concept", category: "parasites", meaning: "Skin disease caused by overgrowth of Demodex canis, a normal hair follicle inhabitant; juvenile-onset is often immunologically self-limiting, adult-onset suggests immunosuppression or endocrinopathy.", example: "Generalized demodicosis in a 6-month-old Shar-Pei was treated with daily oral isoxazoline and resolved over four months." },
  { term: "Rabies", type: "concept", category: "parasites", meaning: "A zoonotic rhabdovirus transmitted through bites of infected mammals; causes fatal encephalitis with virtually 100% mortality once clinical signs develop. Vaccination is the cornerstone of prevention.", example: "Any unvaccinated dog bitten by a wildlife reservoir species must be quarantined or euthanized under state rabies law." },
  { term: "Toxoplasmosis (Toxoplasma gondii)", type: "concept", category: "parasites", meaning: "A protozoan parasite for which cats are the definitive host; humans become infected via ingestion of oocysts in cat feces or tissue cysts in undercooked meat — particularly dangerous in pregnancy.", example: "Pregnant women should avoid handling cat litter to prevent congenital toxoplasmosis, which can cause fetal malformations." },

  // ── Animal Nutrition & Husbandry ─────────────────────────────
  { term: "Obligate Carnivore", type: "concept", category: "nutrition", meaning: "An animal physiologically dependent on a diet of animal tissue; cats are obligate carnivores and require dietary taurine, arginine, vitamin A, and arachidonic acid that they cannot synthesize.", example: "Feeding a vegetarian diet to a cat causes taurine-deficient dilated cardiomyopathy and retinal degeneration." },
  { term: "Herbivore", type: "concept", category: "nutrition", meaning: "An animal whose diet consists exclusively of plant material; includes ruminants (cattle, sheep) and hindgut fermenters (horses, rabbits) that rely on microbial fermentation of fiber.", example: "Rabbits are strict herbivores and require unlimited grass hay to maintain GI motility and dental health." },
  { term: "Omnivore", type: "concept", category: "nutrition", meaning: "An animal that consumes both plant and animal material; includes dogs, pigs, bears, and humans, with digestive anatomy adapted to a mixed diet.", example: "Dogs are facultative omnivores and can digest carbohydrates well, unlike obligate carnivore cats." },
  { term: "Body Condition Score (BCS)", type: "concept", category: "nutrition", meaning: "A subjective 1–9 (or 1–5) scale assessing the amount of subcutaneous fat by palpation of the ribs, spine, and waist; the standard tool for monitoring weight in clinical practice.", example: "A BCS of 7/9 in a Beagle indicates overweight — ribs are difficult to palpate and there is no visible waist." },
  { term: "Taurine", type: "concept", category: "nutrition", meaning: "A sulfur-containing amino acid essential in feline diets (cats cannot synthesize it in sufficient amounts); deficiency causes dilated cardiomyopathy and central retinal degeneration.", example: "Commercial cat foods are required to be supplemented with taurine to prevent feline dilated cardiomyopathy." },
  { term: "Stable Vices (Cribbing)", type: "concept", category: "nutrition", meaning: "Stereotypic behaviors in confined horses (cribbing, weaving, stall-walking) that develop from boredom, frustration, or insufficient forage and turnout; difficult to reverse once established.", example: "Increased turnout and free-choice hay reduced the gelding's cribbing significantly over two months." },
  { term: "Colostrum", type: "concept", category: "nutrition", meaning: "The first milk produced after parturition, rich in maternal immunoglobulins (especially IgG); critical for passive immunity in foals, calves, and puppies that are born without circulating antibodies.", example: "Newborn calves must receive colostrum within the first 12–24 hours, after which intestinal absorption of IgG closes." },
  { term: "Roughage (Forage)", type: "concept", category: "nutrition", meaning: "High-fiber plant material (hay, pasture, silage) that is essential to maintain rumen function in cattle and hindgut function in horses; lack of roughage causes acidosis and ulcers.", example: "Horses on high-grain diets without adequate hay are at risk for gastric ulcers and laminitis." },
  { term: "AAFCO", type: "concept", category: "nutrition", meaning: "The Association of American Feed Control Officials; the body that establishes nutrient profiles and labeling standards for pet foods sold in the United States.", example: "A pet food labeled \\"complete and balanced for all life stages\\" must meet AAFCO nutrient profiles either by formulation or feeding trial." },
  { term: "Grain Overload (Rumen Acidosis)", type: "concept", category: "nutrition", meaning: "A serious metabolic disease in ruminants caused by sudden ingestion of large amounts of fermentable carbohydrate, producing lactic acid that drops rumen pH and damages the rumen wall.", example: "A steer that broke into the grain bin developed acute rumen acidosis with dehydration, depression, and required emergency rumenotomy." },

  // ── Pharmacology & Anesthesia ────────────────────────────────
  { term: "NSAIDs (Carprofen, Meloxicam)", type: "concept", category: "pharmacology", meaning: "Nonsteroidal anti-inflammatory drugs used for pain and inflammation in dogs; toxic to cats at most doses and contraindicated with corticosteroids or in dehydrated patients due to GI/renal effects.", example: "Carprofen was prescribed for the post-operative spay patient — but only after pre-anesthetic bloodwork confirmed normal liver and kidney function." },
  { term: "Ivermectin", type: "concept", category: "pharmacology", meaning: "A macrocyclic lactone antiparasitic active against many nematodes and arthropods; certain collie-type breeds carry an MDR1 gene mutation that causes severe neurotoxicity at standard doses.", example: "An MDR1-positive Australian Shepherd developed ataxia and blindness after receiving an ivermectin dose meant for a horse." },
  { term: "Acepromazine", type: "concept", category: "pharmacology", meaning: "A phenothiazine tranquilizer used for sedation, restraint, and as a pre-anesthetic in dogs and horses; causes hypotension and is contraindicated in seizure-prone or hypovolemic patients.", example: "Acepromazine was avoided in the Boxer puppy due to breed predisposition to syncope and instead trazodone was used for travel anxiety." },
  { term: "Isoflurane", type: "concept", category: "pharmacology", meaning: "A volatile inhalant anesthetic delivered via precision vaporizer and breathing circuit; provides rapid induction and recovery and is the most common maintenance anesthetic in small animal practice.", example: "After IV propofol induction the cat was intubated and maintained on isoflurane in oxygen for the dental cleaning." },
  { term: "Ketamine", type: "concept", category: "pharmacology", meaning: "A dissociative anesthetic producing a cataleptic state with maintained reflexes; commonly combined with a benzodiazepine or alpha-2 agonist to provide complete anesthesia in cats and exotic species.", example: "A ketamine–dexmedetomidine combination provided 30 minutes of anesthesia for the feral cat's neuter." },
  { term: "Atropine", type: "concept", category: "pharmacology", meaning: "An anticholinergic (muscarinic antagonist) used pre-anesthetically to reduce salivation and prevent bradycardia, and in emergency drug protocols for organophosphate toxicity and CPR.", example: "Atropine was administered IV after pre-anesthetic dexmedetomidine produced clinically significant bradycardia." },
  { term: "Xylazine and Dexmedetomidine", type: "concept", category: "pharmacology", meaning: "Alpha-2 adrenergic agonists that produce profound sedation, analgesia, and muscle relaxation; reversible with the antagonist atipamezole (or yohimbine).", example: "After surgery the patient was given atipamezole IM to reverse residual dexmedetomidine and speed recovery." },
  { term: "Penicillin", type: "concept", category: "pharmacology", meaning: "A bactericidal beta-lactam antibiotic commonly used in food animals against gram-positive organisms; requires strict adherence to withdrawal periods to prevent residues in meat and milk.", example: "The dairy cow treated with procaine penicillin for mastitis was tagged with a withdrawal time of 96 hours for milk and 10 days for meat." },
  { term: "Lidocaine", type: "concept", category: "pharmacology", meaning: "A local anesthetic and class IB antiarrhythmic; used for local nerve blocks, epidurals, line blocks (cattle laparotomy), and IV treatment of ventricular arrhythmias; toxic to cats at high doses.", example: "An inverted-L lidocaine line block was used to perform a left-flank cesarean section on a Holstein in lateral recumbency." },
  { term: "Withdrawal Period", type: "concept", category: "pharmacology", meaning: "The legally required time between the last administration of a drug in a food animal and slaughter or sale of milk/eggs; ensures drug residues fall below safe limits for human consumption.", example: "Extra-label use under AMDUCA requires the veterinarian to establish an extended withdrawal time to ensure no residues enter the food supply." },

  // ── Clinical Procedures & Nursing ────────────────────────────
  { term: "Ovariohysterectomy (Spay)", type: "concept", category: "procedures", meaning: "Surgical removal of the ovaries and uterus in female animals; eliminates heat cycles, prevents pyometra and most mammary cancer, and is the standard of population control.", example: "The 6-month-old kitten was admitted fasted for a routine ovariohysterectomy and microchip placement." },
  { term: "Castration (Neuter)", type: "concept", category: "procedures", meaning: "Surgical removal of the testes in male animals to prevent reproduction, reduce roaming and aggression, and eliminate testicular cancer; in horses called \\"gelding.\\"", example: "The young colt was gelded standing under sedation and local anesthesia with an emasculator for hemostasis." },
  { term: "Core vs Non-Core Vaccination", type: "concept", category: "procedures", meaning: "Core vaccines are recommended for every animal of a species (e.g., rabies, DAPP for dogs, FVRCP for cats). Non-core vaccines are given based on lifestyle risk (e.g., Lyme, leptospirosis, bordetella).", example: "The indoor cat received only the core FVRCP and rabies vaccines, with FeLV recommended only if she would later go outdoors." },
  { term: "Fecal Flotation", type: "concept", category: "procedures", meaning: "An in-house parasitology test in which a fecal sample is mixed with a high-specific-gravity solution (zinc sulfate or sugar) so that parasite eggs float to a coverslip for microscopic identification.", example: "Routine fecal flotation revealed Toxocara cati ova in a 3-month-old kitten and deworming was started." },
  { term: "Heartworm Antigen Test (SNAP)", type: "concept", category: "procedures", meaning: "A rapid in-clinic ELISA detecting heartworm antigen produced by adult female Dirofilaria immitis in dog blood; performed annually as part of preventive care before refilling heartworm preventive.", example: "A positive 4Dx SNAP test was confirmed with a microfilaria check and chest radiographs before staging treatment." },
  { term: "Radiograph (Animal X-ray)", type: "concept", category: "procedures", meaning: "A diagnostic imaging modality producing a 2D shadow image of body tissues using ionizing radiation; standard views include lateral and ventrodorsal (VD) or dorsoventral (DV).", example: "Right lateral and VD thoracic radiographs of the coughing dog revealed an interstitial pattern consistent with heartworm disease." },
  { term: "Restraint", type: "concept", category: "procedures", meaning: "The act of safely holding an animal for examination or procedures; uses the minimum amount of pressure needed (low-stress handling) and varies by species — towel wraps for cats, lateral recumbency for dogs.", example: "The fractious cat was restrained in a burrito towel wrap to allow safe jugular blood draw without escalation." },
  { term: "Packed Cell Volume (PCV / Hematocrit)", type: "concept", category: "procedures", meaning: "The percentage of red blood cells in whole blood, measured by centrifuging a microhematocrit tube; a fast bedside indicator of anemia, dehydration, or polycythemia.", example: "A PCV of 18% and total protein of 4.5 g/dL in a tick-exposed dog suggested IMHA and prompted urgent further workup." },
  { term: "Dental Prophylaxis (COHAT)", type: "concept", category: "procedures", meaning: "A Comprehensive Oral Health Assessment and Treatment performed under general anesthesia, including scaling above and below the gumline, polishing, charting, and full-mouth radiographs.", example: "The 8-year-old Yorkie was scheduled for COHAT with extractions of three mobile teeth identified on the awake oral exam." },
  { term: "Humane Euthanasia", type: "concept", category: "procedures", meaning: "The ending of life by humane means, typically via IV administration of a barbiturate overdose (pentobarbital) preceded by sedation; the only AVMA-accepted method for companion animals in most contexts.", example: "After confirming the family's decision the cat was sedated, an IV catheter was placed, and pentobarbital was administered slowly until the heart stopped." },
];'''

# Replace the TERMS array
old_terms_block = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
if not old_terms_block:
    raise SystemExit('Could not find TERMS array in dental-science.html')
html = html[:old_terms_block.start()] + TERMS_JS + html[old_terms_block.end():]

# Replace categoryLabel block
CAT_LABEL = '''const categoryLabel = c => ({
  'anatomy':      'Anatomy & Physiology',
  'diseases':     'Diseases',
  'parasites':    'Parasites & Zoonotic',
  'nutrition':    'Nutrition & Husbandry',
  'pharmacology': 'Pharmacology',
  'procedures':   'Procedures & Nursing',
})[c] || c;'''

html = re.sub(
    r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;",
    CAT_LABEL,
    html,
    count=1,
    flags=re.DOTALL
)

# Replace DB_PATH
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'veterinary-science';", 1)

# Replace title, headline, subtitle
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>',
                    '<title>HOSA Prep Hub — Veterinary Science</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>',
                    '<h1>Veterinary<br><em>Science</em>.</h1>', 1)
html = html.replace(
    'A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
    'A study companion for animal anatomy, common diseases, parasitology and zoonotic disease, animal nutrition, veterinary pharmacology, and clinical procedures — built for HOSA competitors.',
    1
)

# Replace stray "DATA — HOSA Emergency Medical Science" comment header
html = html.replace('//  DATA — HOSA Emergency Medical Science',
                    '//  DATA — HOSA Veterinary Science', 1)

with open(DST, 'w', encoding='utf-8') as f:
    f.write(html)

print(f'Wrote {DST}')
print(f'Total terms in TERMS_JS: {TERMS_JS.count("{ term:")}')
