#!/usr/bin/env python3
"""Generate urology.html from dental-science.html template."""
import os, re
BASE = '/home/user/hosa-prep-hub'
SRC, DST = os.path.join(BASE, 'dental-science.html'), os.path.join(BASE, 'urology.html')
with open(SRC, 'r', encoding='utf-8') as f: html = f.read()
TERMS_JS = '''const TERMS = [
  // ── Lower Urinary Tract ──────────────────────────────────────
  { term: "Urinary Bladder Anatomy", type: "concept", category: "lower-tract", meaning: "Muscular reservoir; trigone formed by ureteral and urethral openings. Detrusor (parasympathetic — contracts) and internal sphincter (sympathetic — contracts to retain) coordinate micturition. External sphincter under voluntary control (somatic).", example: "Anticholinergic medication for overactive bladder blocked parasympathetic detrusor contraction, reducing urge incontinence." },
  { term: "UTI (Lower vs Upper)", type: "concept", category: "lower-tract", meaning: "Cystitis (lower): dysuria, frequency, urgency, suprapubic pain. Pyelonephritis (upper): fever, flank pain, vomiting, sepsis risk. E. coli most common. Uncomplicated cystitis: nitrofurantoin or TMP-SMX 3-5 days; pyelonephritis: fluoroquinolone 7 days.", example: "The patient's dysuria and frequency with positive nitrites on UA was treated as uncomplicated cystitis with nitrofurantoin." },
  { term: "Urinary Incontinence Types", type: "concept", category: "lower-tract", meaning: "Stress (cough, sneeze — pelvic floor weakness, common in women). Urge (overactive bladder — detrusor overactivity). Mixed. Overflow (BPH, neurogenic). Functional (mobility/cognitive). Treatment varies by type.", example: "The postmenopausal woman's leakage with cough was stress incontinence; pelvic floor exercises and midurethral sling repair were options." },
  { term: "Benign Prostatic Hyperplasia (BPH)", type: "concept", category: "lower-tract", meaning: "Enlarged prostate common in men >50. LUTS: weak stream, hesitancy, incomplete emptying, nocturia, frequency. Treated with alpha-blockers (tamsulosin), 5-alpha reductase inhibitors (finasteride), TURP for refractory cases.", example: "The 68-year-old's nocturia, hesitancy, and enlarged prostate on DRE improved with tamsulosin 0.4 mg nightly." },
  { term: "Acute Urinary Retention", type: "concept", category: "lower-tract", meaning: "Sudden inability to void with painful distended bladder. Causes: BPH, medications (anticholinergics, opioids), postop, neurogenic. Treated with immediate catheterization; alpha-blocker initiated, treat underlying cause.", example: "The post-op patient unable to void with palpable distended bladder required Foley catheterization for 800 mL urine; tamsulosin was started." },

  // ── Stones, Tumors & Kidney ──────────────────────────────────
  { term: "Nephrolithiasis (Kidney Stones)", type: "concept", category: "stones-tumors-kidney", meaning: "Calcium oxalate most common (75%). Severe flank-to-groin pain (renal colic), hematuria, nausea. CT non-contrast diagnostic. Treatment: fluids, NSAIDs, opioids; tamsulosin for stones <10 mm. Larger: shockwave lithotripsy or ureteroscopy.", example: "The patient's severe flank-to-groin pain with hematuria and 5 mm distal ureteral stone on CT was managed with tamsulosin and pain control for spontaneous passage." },
  { term: "Kidney Stone Types", type: "concept", category: "stones-tumors-kidney", meaning: "Calcium oxalate (75%, radiopaque). Uric acid (10%, radiolucent — gout, low urinary pH). Struvite (10%, staghorn — infection with urease-producing bacteria like Proteus). Cystine (1%, hereditary). Workup: stone analysis + 24-hr urine.", example: "The patient with recurrent uric acid stones had urinary pH 5.2; potassium citrate alkalinized urine and dramatically reduced recurrence." },
  { term: "Bladder Cancer", type: "concept", category: "stones-tumors-kidney", meaning: "Most common transitional cell (urothelial) carcinoma. Risk factors: smoking (#1), occupational chemicals (aromatic amines). Painless hematuria — must evaluate. Cystoscopy + biopsy for diagnosis. Treated with TURBT, intravesical BCG, cystectomy, chemotherapy.", example: "The smoker's painless gross hematuria prompted cystoscopy revealing papillary urothelial carcinoma; TURBT and intravesical BCG were performed." },
  { term: "Prostate Cancer", type: "concept", category: "stones-tumors-kidney", meaning: "Most common cancer in men. Usually adenocarcinoma of peripheral zone. PSA screening controversial. Gleason score grades aggressiveness. Management: active surveillance (low-risk), prostatectomy, radiation, androgen deprivation.", example: "The patient's elevated PSA (8.4) led to biopsy showing Gleason 7 adenocarcinoma; robotic prostatectomy was performed." },
  { term: "Renal Cell Carcinoma (RCC)", type: "concept", category: "stones-tumors-kidney", meaning: "Most common kidney cancer in adults. Classic triad (rare): hematuria, flank pain, palpable mass. Often incidental finding on imaging. Smoking, obesity, dialysis are risk factors. Treated with partial or radical nephrectomy; immunotherapy for metastatic.", example: "The patient's incidental 4 cm renal mass on CT for abdominal pain was diagnosed as clear cell RCC; partial nephrectomy was performed." },
  { term: "Testicular Cancer", type: "concept", category: "stones-tumors-kidney", meaning: "Most common solid cancer in men 15-35. Germ cell tumors: seminoma (radiosensitive, lower stage) and non-seminoma (more aggressive). Painless testicular mass. Tumor markers: AFP (NSGCT), βhCG, LDH. Highly curable with orchiectomy + chemotherapy.", example: "The 25-year-old's painless testicular mass with elevated AFP and βhCG was diagnosed as non-seminomatous germ cell tumor; radical orchiectomy and BEP chemotherapy achieved cure." },

  // ── Andrology, Trauma & Pediatric ────────────────────────────
  { term: "Erectile Dysfunction (ED)", type: "concept", category: "andrology-misc", meaning: "Persistent inability to achieve/maintain erection. Causes: vascular (most common — diabetes, atherosclerosis), neurogenic (post-prostatectomy, MS), hormonal (low T), medications (SSRIs, beta-blockers), psychogenic. Treated with PDE5 inhibitors (sildenafil), vacuum devices, injections, implants.", example: "The diabetic patient's ED improved with sildenafil 50 mg as needed; cardiovascular risk factors were also addressed." },
  { term: "Hypogonadism (Male)", type: "concept", category: "andrology-misc", meaning: "Low testosterone causing low libido, ED, fatigue, decreased muscle mass, depression. Primary (testicular failure — high LH/FSH) vs secondary (pituitary/hypothalamic — low LH/FSH). Treated with testosterone replacement (gel, injection, pellet) after evaluation.", example: "The patient's morning testosterone of 180 ng/dL with low libido confirmed hypogonadism; testosterone gel was initiated with monitoring for prostate effects and erythrocytosis." },
  { term: "Hematuria Workup", type: "concept", category: "andrology-misc", meaning: "Microscopic (≥3 RBC/HPF on 2 specimens) or gross hematuria warrants workup: history (smoking, exposures), exam, urine cytology, CT urogram or US, cystoscopy in adults. Rule out malignancy especially in smokers and >35.", example: "The 60-year-old smoker's microscopic hematuria prompted CT urogram and cystoscopy — diagnosed early-stage bladder cancer." },
  { term: "Testicular Torsion", type: "concept", category: "andrology-misc", meaning: "Surgical emergency — twisting of spermatic cord cuts blood supply; usually in adolescent males. Sudden severe testicular pain, swelling, absent cremasteric reflex, horizontal lie. Doppler shows no flow. Immediate surgical detorsion within 6 hours to save testis.", example: "The 14-year-old's sudden severe testicular pain with absent cremasteric reflex prompted emergent OR — detorsion within 4 hours preserved the testis." },
  { term: "Cryptorchidism", type: "concept", category: "andrology-misc", meaning: "Undescended testis at birth. Most descend within 6 months; if not, surgical orchiopexy by 12-18 months to reduce infertility and malignancy risk. Unilateral most common; bilateral cases require genetic workup.", example: "The 9-month-old's right cryptorchidism was followed; at 12 months orchiopexy was scheduled to bring the testis into the scrotum." },
  { term: "Vasectomy", type: "concept", category: "andrology-misc", meaning: "Outpatient sterilization procedure cutting and sealing the vas deferens. Highly effective contraception (~99.9%). Not immediately effective — semen analysis at 3 months confirms azoospermia before discontinuing other contraception. Reversal expensive and not always successful.", example: "The patient underwent in-office vasectomy; condom use continued until 3-month semen analysis confirmed azoospermia." },
  { term: "Common Urology Tests", type: "concept", category: "andrology-misc", meaning: "Urinalysis (dipstick + microscopy). Urine culture (UTI diagnosis, sensitivities). PSA (prostate cancer screening). Cystoscopy (visualizing bladder/urethra). Urodynamic studies (incontinence/voiding dysfunction). KUB, US, CT urogram, MRI for imaging.", example: "The patient's urology workup combined PSA (4.2), DRE (firm nodule), and transrectal US-guided biopsy — diagnostic of prostate cancer." },
];'''
m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
html = html[:m.start()] + TERMS_JS + html[m.end():]
CAT = """const categoryLabel = c => ({
  'lower-tract':           'Lower Urinary Tract',
  'stones-tumors-kidney':  'Stones, Tumors & Kidney',
  'andrology-misc':        'Andrology, Trauma & Pediatric',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'urology';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>', '<title>HOSA Prep Hub — Urology</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>', '<h1>Uro<em>logy</em>.</h1>', 1)
html = html.replace('A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
                    'A study companion for the lower urinary tract, kidney stones and urologic tumors, and male andrology and pediatric urologic emergencies — built for HOSA competitors.', 1)
html = html.replace('//  DATA — HOSA Emergency Medical Science', '//  DATA — HOSA Urology', 1)
with open(DST, 'w', encoding='utf-8') as f: f.write(html)
print(f'Wrote {DST} — {TERMS_JS.count("{ term:")} terms')
