#!/usr/bin/env python3
"""Generate dermatology.html from dental-science.html template."""
import os, re
BASE = '/home/user/hosa-prep-hub'
SRC, DST = os.path.join(BASE, 'dental-science.html'), os.path.join(BASE, 'dermatology.html')
with open(SRC, 'r', encoding='utf-8') as f: html = f.read()
TERMS_JS = '''const TERMS = [
  // ── Skin Anatomy ─────────────────────────────────────────────
  { term: "Epidermis Layers", type: "concept", category: "anatomy", meaning: "From base to surface: stratum basale (basal cells, melanocytes), stratum spinosum, granulosum, lucidum (palms/soles only), corneum (dead keratinized cells). Avascular — receives nutrients by diffusion from dermis.", example: "The patient's basal cell carcinoma arose from the deepest epidermal layer — stratum basale — where stem cells reside." },
  { term: "Dermis", type: "concept", category: "anatomy", meaning: "Layer beneath epidermis containing collagen, elastin, blood vessels, nerves, hair follicles, sebaceous and sweat glands. Papillary dermis (superficial) and reticular dermis (deeper). Provides skin strength and elasticity.", example: "The patient's keloid showed excessive collagen production in the reticular dermis — exaggerated wound healing." },
  { term: "Hypodermis (Subcutaneous)", type: "concept", category: "anatomy", meaning: "Adipose and connective tissue layer beneath the dermis; provides insulation, energy storage, and cushioning. Site for SC injections (insulin, heparin).", example: "Insulin injections rotated through different hypodermis sites to prevent lipodystrophy from repeated subcutaneous insulin administration." },
  { term: "Skin Appendages", type: "concept", category: "anatomy", meaning: "Hair follicles, sebaceous glands (sebum), eccrine sweat glands (thermoregulation, hypotonic), apocrine glands (axilla/groin, oily secretion, source of body odor), nails. Originate from epidermis but reside in dermis.", example: "Acne develops when sebaceous glands become blocked and infected by Cutibacterium acnes — sebum accumulation in the pilosebaceous unit." },
  { term: "Skin Functions", type: "concept", category: "anatomy", meaning: "Barrier (physical and immunological), thermoregulation (sweating, vasodilation/constriction), sensation (mechanoreceptors, nociceptors, thermoreceptors), vitamin D synthesis (UV converts 7-dehydrocholesterol), excretion, immunologic surveillance.", example: "Severe burns disrupt skin barrier function, causing massive fluid loss, hypothermia, infection risk, and impaired immune function." },

  // ── Skin Lesions ─────────────────────────────────────────────
  { term: "Primary Lesions", type: "concept", category: "lesions", meaning: "Macule (flat, ≤1 cm), patch (flat, >1 cm), papule (raised, ≤1 cm), plaque (raised, >1 cm), nodule (deeper, raised >1 cm), vesicle (fluid-filled, ≤1 cm), bulla (fluid >1 cm), pustule (pus), wheal (transient edema).", example: "The patient's pruritic 3 cm wheal that resolved within hours was urticaria — a primary lesion of transient dermal edema." },
  { term: "Secondary Lesions", type: "concept", category: "lesions", meaning: "Develop from primary lesions: scale, crust, erosion (loss of epidermis), ulcer (loss into dermis), fissure (linear crack), excoriation (scratch), lichenification (thickening from chronic rubbing), scar.", example: "The chronically scratched eczematous plaque developed lichenification — thickened, leathery skin with accentuated skin markings." },
  { term: "Lesion Configuration", type: "concept", category: "lesions", meaning: "Annular (ring-shaped — tinea, granuloma annulare), linear (contact dermatitis to plant), grouped (herpetic vesicles), dermatomal (varicella zoster), reticular (livedo, lichen planus), nummular (coin-shaped — nummular eczema).", example: "The vesicular eruption in a T6 dermatomal distribution was characteristic of herpes zoster (shingles)." },
  { term: "ABCDE of Pigmented Lesions", type: "concept", category: "lesions", meaning: "Melanoma warning: Asymmetry, Border irregularity, Color variegation, Diameter >6 mm, Evolution (change). Any concerning features warrant biopsy.", example: "The 9 mm asymmetric mole with irregular borders and recent color change met all ABCDE criteria — excisional biopsy confirmed melanoma." },

  // ── Inflammatory & Infectious Conditions ─────────────────────
  { term: "Atopic Dermatitis (Eczema)", type: "concept", category: "conditions", meaning: "Chronic relapsing pruritic eczema; often starts in childhood with personal/family atopy. Acute: erythematous papules and vesicles. Chronic: lichenified plaques in flexural areas. Treated with emollients, topical corticosteroids, calcineurin inhibitors.", example: "The child's pruritic, erythematous plaques in the antecubital fossae with family atopy history were treated with emollients and low-potency topical steroid." },
  { term: "Contact Dermatitis", type: "concept", category: "conditions", meaning: "Irritant (chemical/mechanical injury — soaps, solvents) or allergic (Type IV hypersensitivity — poison ivy, nickel, fragrances). Patch testing identifies specific allergen. Treated by avoidance and topical corticosteroids.", example: "The linear vesicular eruption on the hiker's leg was allergic contact dermatitis from poison ivy (Toxicodendron) urushiol — Type IV hypersensitivity." },
  { term: "Psoriasis", type: "concept", category: "conditions", meaning: "Chronic autoimmune T-cell-driven hyperproliferation; well-demarcated erythematous plaques with silvery scale on extensor surfaces, scalp, nails. Auspitz sign: pinpoint bleeding on scale removal. Treated with topicals, phototherapy, biologics (TNF, IL-17, IL-23 inhibitors).", example: "The patient's silver-scaled plaques on bilateral elbows and pitted nails confirmed plaque psoriasis; methotrexate and adalimumab were initiated for severe disease." },
  { term: "Acne Vulgaris", type: "concept", category: "conditions", meaning: "Multifactorial pilosebaceous disorder: follicular hyperkeratinization, sebum, Cutibacterium acnes, inflammation. Comedones (whitehead/blackhead), papules, pustules, cysts. Treated with topical retinoids, benzoyl peroxide, antibiotics, isotretinoin (severe).", example: "The teenager's moderate inflammatory acne with comedones and pustules was treated with topical adapalene plus benzoyl peroxide and oral doxycycline." },
  { term: "Cellulitis", type: "concept", category: "conditions", meaning: "Acute bacterial infection of dermis and subcutaneous tissue, usually from skin breach. Streptococcus pyogenes and S. aureus are most common. Erythema, warmth, swelling, tenderness — usually unilateral, expanding. Treated with cephalexin or clindamycin (MRSA coverage).", example: "The patient's expanding erythema, warmth, and tenderness of the left lower leg with no fluctuance was diagnosed as cellulitis; oral cephalexin was prescribed." },
  { term: "Impetigo", type: "concept", category: "conditions", meaning: "Superficial bacterial infection by S. aureus or S. pyogenes; characteristic honey-colored crusted erosions on face/extremities. Highly contagious, common in children. Treated with topical mupirocin or oral antibiotics for widespread disease.", example: "The child's honey-crusted lesions around the nose were classic impetigo; topical mupirocin three times daily resolved the infection." },
  { term: "Tinea Infections", type: "concept", category: "conditions", meaning: "Superficial dermatophyte infections: capitis (scalp), corporis (body — annular with central clearing), cruris (groin — 'jock itch'), pedis (athlete's foot), unguium (nails — onychomycosis). KOH prep shows hyphae. Treated with topical or oral antifungals.", example: "The annular plaque with central clearing and active scaly border on the patient's trunk was tinea corporis; topical terbinafine cleared the infection." },
  { term: "Herpes Simplex (Cold Sores/Genital)", type: "concept", category: "conditions", meaning: "HSV-1 (mostly oral/facial) and HSV-2 (mostly genital); grouped vesicles on erythematous base, recurrent at same site, latency in sensory ganglia. Diagnosed by Tzanck smear (multinucleated giant cells), PCR. Treated with acyclovir.", example: "The painful grouped vesicles on the patient's lip with positive Tzanck smear was recurrent herpes labialis (HSV-1); valacyclovir shortened the outbreak." },
  { term: "Scabies", type: "concept", category: "conditions", meaning: "Infestation by mite Sarcoptes scabiei; intensely pruritic rash worse at night with burrows in finger webs, wrists, axillae, genitalia. Treated with topical permethrin 5%; all close contacts treated and bedding washed.", example: "The patient's intense nocturnal pruritus, burrows in finger webs, and similarly affected family members confirmed scabies; whole-household permethrin treatment was initiated." },

  // ── Skin Cancers & Misc ──────────────────────────────────────
  { term: "Basal Cell Carcinoma (BCC)", type: "concept", category: "cancers-misc", meaning: "Most common skin cancer; arises from basal keratinocytes. Pearly papule with rolled borders, telangiectasias, central ulceration ('rodent ulcer'). Locally invasive but rarely metastasizes. Treated with excision, Mohs surgery, electrodessication.", example: "The 65-year-old farmer's pearly papule with telangiectasias on the nasal tip was biopsied — basal cell carcinoma — and excised with Mohs micrographic surgery." },
  { term: "Squamous Cell Carcinoma (SCC)", type: "concept", category: "cancers-misc", meaning: "Second most common skin cancer; arises from suprabasal keratinocytes. Often from actinic keratoses on sun-exposed areas. Scaly, ulcerated, indurated plaque. Can metastasize (especially on lip, ear). Treated with excision, Mohs, radiation.", example: "The chronic actinic keratosis on the patient's ear transformed into a firm, ulcerated nodule — SCC — and wide local excision was performed." },
  { term: "Melanoma", type: "concept", category: "cancers-misc", meaning: "Malignancy of melanocytes; most lethal skin cancer. Subtypes: superficial spreading (most common), nodular, lentigo maligna, acral lentiginous. Breslow depth determines prognosis. Modern immunotherapy (pembrolizumab) and BRAF-targeted therapy.", example: "The Breslow 1.5 mm nodular melanoma on the patient's back was excised with wide margins and sentinel lymph node biopsy was performed for staging." },
  { term: "Actinic Keratosis", type: "concept", category: "cancers-misc", meaning: "Premalignant lesion from chronic UV exposure; scaly erythematous patches on sun-exposed areas. ~5–10% progress to SCC. Treated with cryotherapy, topical 5-FU, imiquimod, photodynamic therapy.", example: "The patient's multiple scaly erythematous lesions on the face and forearms were actinic keratoses; field treatment with topical 5-FU was prescribed." },
  { term: "Pressure Injury (Pressure Ulcer)", type: "concept", category: "cancers-misc", meaning: "Skin/tissue damage from prolonged pressure over bony prominences. Stages: I (non-blanchable erythema), II (partial-thickness, blister), III (full-thickness fat visible), IV (muscle/bone exposed), unstageable (slough/eschar). Prevent with repositioning every 2 hours.", example: "The bedridden patient's sacral stage II pressure injury required pressure-redistribution mattress, q2h repositioning, and hydrocolloid dressing." },
  { term: "Burns Classification", type: "concept", category: "cancers-misc", meaning: "Superficial (1st degree — epidermis only, red, painful, sunburn). Partial thickness (2nd — into dermis, blisters, very painful). Full thickness (3rd — through dermis, leathery, painless). %TBSA estimated by rule of nines.", example: "The patient's bilateral leg scalds with blistering were partial-thickness (2nd degree) burns covering 18% TBSA — admission for fluid resuscitation indicated." },
  { term: "Vitiligo", type: "concept", category: "cancers-misc", meaning: "Acquired autoimmune destruction of melanocytes producing well-demarcated depigmented patches; often symmetric, on hands, face, body folds. Associated with other autoimmune diseases. Treated with topical steroids, calcineurin inhibitors, phototherapy.", example: "The patient's symmetric depigmented patches on the dorsum of both hands and around the eyes were diagnosed as vitiligo; topical tacrolimus produced partial repigmentation." },
];'''
m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
html = html[:m.start()] + TERMS_JS + html[m.end():]
CAT = """const categoryLabel = c => ({
  'anatomy':       'Skin Anatomy',
  'lesions':       'Skin Lesions',
  'conditions':    'Inflammatory & Infectious',
  'cancers-misc':  'Skin Cancers & Misc',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'dermatology';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>', '<title>HOSA Prep Hub — Dermatology</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>', '<h1>Derma<em>tology</em>.</h1>', 1)
html = html.replace('A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
                    'A study companion for skin anatomy, primary and secondary skin lesions, inflammatory and infectious dermatologic conditions, and skin cancers — built for HOSA competitors.', 1)
html = html.replace('//  DATA — HOSA Emergency Medical Science', '//  DATA — HOSA Dermatology', 1)
with open(DST, 'w', encoding='utf-8') as f: f.write(html)
print(f'Wrote {DST} — {TERMS_JS.count("{ term:")} terms')
