#!/usr/bin/env python3
"""Generate rheumatology.html from dental-science.html template."""
import os, re
BASE = '/home/user/hosa-prep-hub'
SRC, DST = os.path.join(BASE, 'dental-science.html'), os.path.join(BASE, 'rheumatology.html')
with open(SRC, 'r', encoding='utf-8') as f: html = f.read()
TERMS_JS = '''const TERMS = [
  // ── Autoimmune Joint Disease ─────────────────────────────────
  { term: "Rheumatoid Arthritis (RA)", type: "concept", category: "autoimmune-joint", meaning: "Symmetric chronic inflammatory polyarthritis affecting small joints (MCP, PIP, wrists). Morning stiffness >1 hour. RF and anti-CCP positive. Erosive joint damage. Treated with methotrexate ± biologics (TNF inhibitors).", example: "The patient's symmetric MCP/PIP swelling with morning stiffness 2 hours and positive anti-CCP confirmed RA; methotrexate plus folic acid was started." },
  { term: "Osteoarthritis (OA)", type: "concept", category: "autoimmune-joint", meaning: "Most common arthritis. Cartilage degeneration from wear; asymmetric, weight-bearing joints (knees, hips, hands DIP/PIP/CMC). Crepitus, stiffness <30 min, worse with use. X-ray: joint space narrowing, osteophytes. Treated with NSAIDs, PT, weight loss, joint replacement.", example: "The 68-year-old's knee pain worse with activity, crepitus, and X-ray showing joint space narrowing were diagnostic of knee osteoarthritis." },
  { term: "Psoriatic Arthritis", type: "concept", category: "autoimmune-joint", meaning: "Seronegative spondyloarthritis with psoriasis. Patterns: asymmetric oligoarthritis, DIP-predominant, arthritis mutilans, spondylitis. Nail changes (pitting, onycholysis), dactylitis (sausage digit), enthesitis. Treated with NSAIDs, methotrexate, biologics.", example: "The patient's psoriasis plaques and asymmetric DIP joint involvement with dactylitis confirmed psoriatic arthritis; adalimumab achieved disease control." },
  { term: "Ankylosing Spondylitis", type: "concept", category: "autoimmune-joint", meaning: "Inflammatory back pain in young men, HLA-B27 associated. Morning stiffness improving with exercise. Sacroiliitis, eventual spinal fusion ('bamboo spine'). Reduced chest expansion. Treated with NSAIDs, TNF inhibitors.", example: "The 28-year-old man's chronic inflammatory back pain, HLA-B27 positivity, and sacroiliitis on MRI confirmed ankylosing spondylitis." },
  { term: "Reactive Arthritis", type: "concept", category: "autoimmune-joint", meaning: "Post-infectious arthritis 1-4 weeks after GI (Salmonella, Shigella) or GU (Chlamydia) infection. Classic triad: arthritis, urethritis, conjunctivitis ('can't see, can't pee, can't bend the knee'). HLA-B27 association. Self-limited weeks-months.", example: "The patient's acute arthritis 3 weeks after Chlamydia infection plus urethritis and conjunctivitis confirmed reactive arthritis; symptoms resolved over 3 months." },

  // ── Connective Tissue Diseases ───────────────────────────────
  { term: "Systemic Lupus Erythematosus (SLE)", type: "concept", category: "connective-tissue", meaning: "Multisystem autoimmune disease; predominantly young women. SOAP BRAIN MD mnemonic for features. Antibodies: ANA (sensitive), anti-dsDNA and anti-Smith (specific). Treated with hydroxychloroquine, steroids, immunosuppressants.", example: "The young woman's malar rash, photosensitivity, arthritis, and positive ANA + anti-dsDNA confirmed SLE; hydroxychloroquine was started." },
  { term: "Sjögren Syndrome", type: "concept", category: "connective-tissue", meaning: "Autoimmune lymphocytic infiltration of exocrine glands causing dry eyes (keratoconjunctivitis sicca) and dry mouth (xerostomia). Anti-Ro/SSA, anti-La/SSB antibodies. Increased lymphoma risk. Treated symptomatically.", example: "The patient's chronic dry eyes and mouth with positive anti-Ro/SSA and Schirmer test confirmed primary Sjögren syndrome." },
  { term: "Systemic Sclerosis (Scleroderma)", type: "concept", category: "connective-tissue", meaning: "Fibrosis of skin and internal organs. Limited (CREST: Calcinosis, Raynaud, Esophageal dysmotility, Sclerodactyly, Telangiectasia — anti-centromere). Diffuse (rapid progression, internal organ involvement — anti-Scl-70). Pulmonary HTN, renal crisis serious.", example: "The patient's progressive skin tightening, Raynaud, and esophageal dysmotility with positive anti-Scl-70 confirmed diffuse systemic sclerosis." },
  { term: "Polymyositis and Dermatomyositis", type: "concept", category: "connective-tissue", meaning: "Autoimmune inflammatory myopathies. Symmetric proximal muscle weakness. Dermatomyositis adds skin findings (heliotrope rash, Gottron papules, V-sign). Elevated CK and aldolase. Treated with corticosteroids, immunosuppressants. Cancer screening (paraneoplastic).", example: "The patient's proximal weakness, elevated CK, heliotrope rash, and Gottron papules confirmed dermatomyositis; cancer screening was negative." },

  // ── Crystal Arthropathies & Other ────────────────────────────
  { term: "Gout", type: "concept", category: "crystal-other", meaning: "Acute monoarthritis from MSU crystal deposition. Classic: 1st MTP joint (podagra). Triggered by alcohol, meat, thiazides. Synovial fluid: negatively birefringent needle-shaped crystals. Acute: NSAIDs, colchicine, steroids. Chronic: allopurinol, febuxostat.", example: "The patient's acute great toe pain with negatively birefringent MSU crystals on arthrocentesis confirmed gout; indomethacin treated the acute attack." },
  { term: "Pseudogout (CPPD)", type: "concept", category: "crystal-other", meaning: "Acute monoarthritis from calcium pyrophosphate crystals. Typically affects knees, wrists in elderly. Synovial fluid: positively birefringent rhomboid crystals. Chondrocalcinosis on X-ray. Treated with NSAIDs, colchicine, intra-articular steroids.", example: "The 80-year-old's acute knee pain with chondrocalcinosis on X-ray and positively birefringent crystals confirmed pseudogout (CPPD)." },
  { term: "Polymyalgia Rheumatica (PMR)", type: "concept", category: "crystal-other", meaning: "Inflammatory condition of elderly (>50) with bilateral shoulder and hip girdle pain and stiffness. Elevated ESR/CRP. Dramatic response to low-dose prednisone. Associated with giant cell arteritis (~15%).", example: "The 72-year-old's bilateral shoulder and hip stiffness with ESR 85 responded dramatically to prednisone 15 mg — diagnostic of PMR." },
  { term: "Giant Cell Arteritis (Temporal Arteritis)", type: "concept", category: "crystal-other", meaning: "Vasculitis of medium-large arteries in elderly. New headache, jaw claudication, scalp tenderness, visual changes. Elevated ESR. Temporal artery biopsy confirms. Treat IMMEDIATELY with high-dose steroids to prevent blindness — do not wait for biopsy.", example: "The 75-year-old's new temporal headache, jaw claudication, and ESR 110 prompted immediate prednisone 60 mg before biopsy — diagnostic for GCA." },
  { term: "Vasculitis Overview", type: "concept", category: "crystal-other", meaning: "Inflammation of blood vessels classified by size. Large: GCA, Takayasu. Medium: PAN, Kawasaki. Small: ANCA-associated (GPA, MPA, EGPA), IgA vasculitis (Henoch-Schönlein), cryoglobulinemic. Variable presentation; treated with steroids ± immunosuppression.", example: "The patient's pulmonary-renal syndrome with positive c-ANCA (PR3) confirmed granulomatosis with polyangiitis; rituximab and steroids achieved remission." },
  { term: "Fibromyalgia", type: "concept", category: "crystal-other", meaning: "Chronic widespread pain syndrome with sleep disturbance, fatigue, cognitive symptoms ('fibro fog'). Tender points. Diagnosed by 2016 ACR criteria. Treated with exercise, CBT, duloxetine, milnacipran, pregabalin, gabapentin.", example: "The patient's widespread pain >3 months, fatigue, and unrefreshing sleep met fibromyalgia criteria; aerobic exercise and duloxetine were initiated." },
  { term: "Osteoporosis", type: "concept", category: "crystal-other", meaning: "Reduced bone mass and microarchitectural deterioration → fragility fractures. DEXA T-score ≤-2.5 = osteoporosis; -1 to -2.5 = osteopenia. Screen women ≥65, men ≥70. Treated with calcium, vitamin D, weight-bearing exercise, bisphosphonates (alendronate), denosumab.", example: "The 68-year-old's DEXA T-score of -2.8 confirmed osteoporosis; alendronate 70 mg weekly was started with calcium and vitamin D." },
  { term: "Common Rheum Labs (ANA, RF, anti-CCP, ESR/CRP)", type: "concept", category: "crystal-other", meaning: "ANA: screening for lupus, autoimmune. RF: rheumatoid arthritis (sensitive, less specific). Anti-CCP: specific for RA, predicts erosive disease. ESR/CRP: nonspecific acute phase reactants, monitor disease activity.", example: "Although positive in many conditions, the patient's high-titer ANA prompted further testing — positive anti-dsDNA confirmed SLE." },
];'''
m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
html = html[:m.start()] + TERMS_JS + html[m.end():]
CAT = """const categoryLabel = c => ({
  'autoimmune-joint':  'Autoimmune Joint Disease',
  'connective-tissue': 'Connective Tissue Diseases',
  'crystal-other':     'Crystal Arthropathies & Other',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'rheumatology';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>', '<title>HOSA Prep Hub — Rheumatology</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>', '<h1>Rheuma<em>tology</em>.</h1>', 1)
html = html.replace('A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
                    'A study companion for autoimmune joint disease, connective tissue diseases including lupus and scleroderma, and crystal arthropathies and other rheumatologic conditions — built for HOSA competitors.', 1)
html = html.replace('//  DATA — HOSA Emergency Medical Science', '//  DATA — HOSA Rheumatology', 1)
with open(DST, 'w', encoding='utf-8') as f: f.write(html)
print(f'Wrote {DST} — {TERMS_JS.count("{ term:")} terms')
