#!/usr/bin/env python3
"""Generate psychiatry.html from dental-science.html template."""
import os, re
BASE = '/home/user/hosa-prep-hub'
SRC, DST = os.path.join(BASE, 'dental-science.html'), os.path.join(BASE, 'psychiatry.html')
with open(SRC, 'r', encoding='utf-8') as f: html = f.read()
TERMS_JS = '''const TERMS = [
  // ── Mood Disorders ───────────────────────────────────────────
  { term: "Major Depressive Disorder (MDD)", type: "concept", category: "mood", meaning: "DSM-5: ≥5 symptoms for ≥2 weeks including depressed mood or anhedonia — SIG E CAPS (Sleep, Interest, Guilt, Energy, Concentration, Appetite, Psychomotor, Suicidality). Treated with SSRIs/SNRIs first-line; psychotherapy (CBT, IPT) equally effective for mild-moderate.", example: "The patient's 3-week history of anhedonia, insomnia, weight loss, and poor concentration with 5 DSM-5 criteria met was diagnosed as MDD; sertraline was started." },
  { term: "Bipolar Disorder (Types I & II)", type: "concept", category: "mood", meaning: "Type I: ≥1 manic episode (elevated/expansive/irritable mood, ↑ energy, ≥3 of DIGFAST, ≥7 days or hospitalization). Type II: hypomanic + depressive episodes; no full mania. Treated with mood stabilizers (lithium, valproate, lamotrigine, atypical antipsychotics).", example: "The patient's week of decreased sleep, grandiosity, racing thoughts, and increased goal-directed activity without hospitalization met criteria for hypomania — Bipolar II." },
  { term: "Persistent Depressive Disorder (Dysthymia)", type: "concept", category: "mood", meaning: "Chronic depressed mood ≥2 years (≥1 year in children) with ≥2 of: poor appetite/overeating, insomnia/hypersomnia, low energy, low self-esteem, poor concentration, hopelessness. Less severe but more chronic than MDD. Treated with antidepressants + therapy.", example: "The patient's 3-year history of low-grade depression with poor energy and self-esteem, never meeting full MDD criteria, was diagnosed as persistent depressive disorder." },

  // ── Anxiety & Related Disorders ─────────────────────────────
  { term: "Generalized Anxiety Disorder (GAD)", type: "concept", category: "anxiety", meaning: "Excessive worry about multiple domains ≥6 months, difficult to control + ≥3 of: restlessness, fatigue, difficulty concentrating, irritability, muscle tension, sleep disturbance. First-line: SSRI/SNRI + CBT; buspirone adjunct.", example: "The patient's uncontrollable worry about work, health, and family for 8 months with muscle tension and insomnia was diagnosed as GAD; escitalopram and CBT were initiated." },
  { term: "Panic Disorder", type: "concept", category: "anxiety", meaning: "Recurrent unexpected panic attacks (abrupt surge to peak in minutes: palpitations, sweating, trembling, shortness of breath, chest pain, derealization, fear of dying) + ≥1 month of worry about attacks or avoidance. Treated with SSRIs; CBT with interoceptive exposure.", example: "The patient's recurrent unexpected episodes of palpitations, chest pain, and fear of dying with anticipatory anxiety for 6 weeks met criteria for panic disorder." },
  { term: "Social Anxiety Disorder", type: "concept", category: "anxiety", meaning: "Marked fear of social situations due to potential scrutiny/embarrassment, leading to avoidance or endurance with distress ≥6 months, causing impairment. Treated with SSRIs/SNRIs; CBT the most effective. Beta-blockers for performance anxiety.", example: "The student's intense fear of speaking in class, avoidance of social events, and significant academic impairment for 1 year was diagnosed as social anxiety disorder." },
  { term: "PTSD and Trauma-Related Disorders", type: "concept", category: "anxiety", meaning: "Exposure to traumatic event → intrusion (flashbacks, nightmares), avoidance, negative cognitions/mood, hyperarousal ≥1 month causing impairment. First-line: trauma-focused CBT (Prolonged Exposure, CPT), EMDR; SSRIs (sertraline, paroxetine) FDA-approved.", example: "The combat veteran's intrusive war flashbacks, hypervigilance, emotional numbing, and avoidance of reminders for 6 months was diagnosed as PTSD; Prolonged Exposure therapy was started." },
  { term: "OCD and Related Disorders", type: "concept", category: "anxiety", meaning: "OCD: obsessions (intrusive thoughts) → compulsions (repetitive behaviors to reduce anxiety), time-consuming >1 hr/day, ego-dystonic. Treatment: ERP (exposure and response prevention) + SSRIs (high dose). Related: BDD, hoarding, trichotillomania.", example: "The patient's contamination obsessions driving 3-hour daily handwashing rituals causing significant distress was OCD; high-dose fluvoxamine + ERP were started." },

  // ── Psychotic Disorders ──────────────────────────────────────
  { term: "Schizophrenia Spectrum", type: "concept", category: "psychosis", meaning: "≥2 of (delusions, hallucinations, disorganized speech, disorganized/catatonic behavior, negative symptoms) ≥1 month + social/occupational dysfunction ≥6 months. Positive symptoms (hallucinations, delusions) and negative symptoms (alogia, avolition, anhedonia, flat affect). Treated with antipsychotics.", example: "The 22-year-old's auditory hallucinations, paranoid delusions, flat affect, and social withdrawal for 8 months with declining function was diagnosed as schizophrenia." },
  { term: "Antipsychotic Medications", type: "concept", category: "psychosis", meaning: "1st gen (typical): haloperidol, chlorpromazine — block D2; risk EPS (akathisia, dystonia, parkinsonism, tardive dyskinesia). 2nd gen (atypical): risperidone, olanzapine, quetiapine, clozapine — fewer EPS, more metabolic SE. Clozapine for refractory; weekly CBC for agranulocytosis.", example: "The patient switched from haloperidol (causing severe akathisia) to quetiapine — an atypical antipsychotic with lower EPS risk — with improved tolerability." },

  // ── Substance Use & Personality ───────────────────────────────
  { term: "Substance Use Disorders", type: "concept", category: "substance", meaning: "DSM-5: problematic pattern with ≥2 of 11 criteria in 12 months (tolerance, withdrawal, loss of control, cravings, continued use despite harm). Alcohol use disorder: naltrexone, acamprosate, disulfiram, thiamine. Opioid: MAT with methadone or buprenorphine/naloxone.", example: "The patient meeting 6 DSM-5 criteria for alcohol use disorder was started on naltrexone 50 mg daily plus motivational enhancement therapy." },
  { term: "Personality Disorders", type: "concept", category: "substance", meaning: "Enduring inflexible patterns causing distress/impairment. Cluster A (odd): paranoid, schizoid, schizotypal. Cluster B (dramatic): antisocial, borderline, histrionic, narcissistic. Cluster C (anxious): avoidant, dependent, OCPD. BPD: DBT most effective. ASPD: recidivism risk.", example: "The patient's unstable relationships, fear of abandonment, impulsivity, and self-harm — classic BPD features — improved significantly with 1 year of DBT." },

  // ── Neurodevelopmental & Child Psychiatry ─────────────────────
  { term: "ADHD", type: "concept", category: "neurodevelopmental", meaning: "Inattention and/or hyperactivity-impulsivity in ≥2 settings, onset <12 years, causing impairment. Three presentations: inattentive, hyperactive-impulsive, combined. Stimulants (methylphenidate, amphetamine salts) first-line in children ≥6; atomoxetine non-stimulant option.", example: "The 9-year-old's inattention, difficulty following instructions at school and home, and academic underperformance since age 6 met criteria for ADHD; methylphenidate improved performance." },
  { term: "Suicide Risk Assessment", type: "concept", category: "neurodevelopmental", meaning: "Risk factors: prior attempts, hopelessness, access to means, male sex, psychiatric illness, substance use, social isolation. IS PATH WARM mnemonic. Assess ideation (frequency, intensity, plan, intent, means). Safety planning, lethal means counseling; hospitalize for imminent risk.", example: "The patient with SI, a specific plan, access to firearms, and prior attempt was admitted involuntarily — high acute risk requiring inpatient stabilization." },
  { term: "Psychotherapy Modalities", type: "concept", category: "neurodevelopmental", meaning: "CBT (cognitive-behavioral therapy): maladaptive thoughts → behaviors; evidence-based for depression, anxiety, OCD. DBT (dialectical behavior therapy): borderline PD, self-harm. IPT (interpersonal therapy): depression. Psychodynamic: insight-oriented. MI (motivational interviewing): substance use.", example: "The patient with refractory MDD not responding to SSRIs showed significant improvement after 16 sessions of CBT targeting negative automatic thoughts." },
];'''
m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
html = html[:m.start()] + TERMS_JS + html[m.end():]
CAT = """const categoryLabel = c => ({
  'mood':             'Mood Disorders',
  'anxiety':          'Anxiety & Related Disorders',
  'psychosis':        'Psychotic Disorders',
  'substance':        'Substance Use & Personality',
  'neurodevelopmental':'Neurodevelopmental & Child Psychiatry',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'psychiatry';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>', '<title>HOSA Prep Hub — Psychiatry</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>', '<h1>Psychi<em>atry</em>.</h1>', 1)
html = html.replace('A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
                    'A study companion for mood disorders, anxiety and trauma-related disorders, psychotic disorders, substance use and personality disorders, and neurodevelopmental conditions — built for HOSA competitors.', 1)
html = html.replace('//  DATA — HOSA Emergency Medical Science', '//  DATA — HOSA Psychiatry', 1)
with open(DST, 'w', encoding='utf-8') as f: f.write(html)
print(f'Wrote {DST} — {TERMS_JS.count("{ term:")} terms')
