#!/usr/bin/env python3
"""Generate nursing-assisting.html from dental-science.html template."""
import os, re
BASE = '/home/user/hosa-prep-hub'
SRC, DST = os.path.join(BASE, 'dental-science.html'), os.path.join(BASE, 'nursing-assisting.html')
with open(SRC, 'r', encoding='utf-8') as f: html = f.read()
TERMS_JS = '''const TERMS = [
  // ── CNA Scope & Professionalism ──────────────────────────────
  { term: "CNA Scope of Practice", type: "concept", category: "scope", meaning: "A Certified Nursing Assistant provides basic care under RN supervision: ADLs, vital signs, repositioning, ambulation, intake/output, and documentation. CNAs CANNOT administer medications, perform sterile procedures, or interpret data — those exceed scope.", example: "When the resident asked about her new medication, the CNA explained 'I'll have the nurse come speak with you' — staying within scope of practice." },
  { term: "Chain of Command", type: "concept", category: "scope", meaning: "Reporting hierarchy: CNA → RN/LPN → Charge Nurse → Nurse Manager → DON → Administrator. Concerns about resident care, unsafe assignments, or unethical conduct should be escalated through this chain, not skipped.", example: "When the CNA noticed a resident's worsening pressure ulcer, she reported it to the charge nurse immediately rather than waiting until shift change." },
  { term: "Patient Bill of Rights", type: "concept", category: "scope", meaning: "Residents in long-term care have rights protected by OBRA: dignity, privacy, freedom from abuse and restraint, informed consent, refusal of treatment, access to records, voicing grievances, personal property, and participation in care planning.", example: "The CNA closed the door and pulled the privacy curtain before assisting the resident with toileting, respecting her right to privacy and dignity." },
  { term: "Mandatory Reporting", type: "concept", category: "scope", meaning: "CNAs are legally required to report suspected abuse, neglect, or exploitation to the supervising nurse and state agencies. Signs: unexplained bruises, weight loss, withdrawal, fear of caregivers, soiled clothing, untreated injuries.", example: "After noticing handprint-shaped bruises on a resident's arm, the CNA documented findings, reported to the charge nurse, and a formal abuse investigation was opened." },

  // ── ADLs & Personal Care ─────────────────────────────────────
  { term: "Bathing — Bed Bath", type: "concept", category: "adls", meaning: "Complete bath given in bed for residents unable to be moved; wash from clean to dirty (eyes → face → arms → chest → abdomen → legs → back → perineum last). Change water as needed; check water temp (105–110°F).", example: "The CNA performed a complete bed bath for the bedridden resident, washing perineal area last and changing water after washing the lower body." },
  { term: "Perineal Care (Peri Care)", type: "concept", category: "adls", meaning: "Cleansing the perineum and surrounding area to prevent infection and skin breakdown. Female: wipe front to back, separating labia. Male: retract foreskin if uncircumcised, clean tip, replace foreskin. Always wear gloves.", example: "After the incontinent resident was changed, the CNA performed peri care from front to back to prevent UTIs and skin irritation." },
  { term: "Oral Care (Unconscious Patient)", type: "concept", category: "adls", meaning: "Position resident on side to prevent aspiration. Use small amount of solution and suction. Provide oral care every 2 hours for unconscious residents to prevent dental caries, infection, and pneumonia.", example: "The CNA turned the unconscious resident on her side, used oral swabs with mouthwash, and suctioned excess fluid to prevent aspiration." },
  { term: "Feeding Assistance", type: "concept", category: "adls", meaning: "Position resident upright (≥45°), check tray for correct diet, identify resident, offer fluids between bites, allow time. Stay with resident throughout meal. Document intake (% eaten) and any swallowing difficulty.", example: "The CNA raised the head of the bed to 60°, identified the resident, and noted she ate 75% of her meal — documenting in the meal intake record." },
  { term: "Dressing and Grooming", type: "concept", category: "adls", meaning: "Allow resident choice when possible; dress weakest side first, undress strong side first ('dress the worst, undress the best'). Encourage independence with adaptive equipment. Promotes dignity and self-esteem.", example: "After the stroke, the CNA dressed the resident's affected left arm first into the sleeve, then the unaffected right arm — applying the 'dress the worst first' rule." },

  // ── Vital Signs & Measurements ───────────────────────────────
  { term: "Temperature Routes", type: "concept", category: "vitals", meaning: "Oral: 97.6–99.6°F (avoid if confused, post-op, oxygen). Axillary: 96.6–98.6°F (least accurate). Rectal: 98.6–100.6°F (most accurate; contraindicated in cardiac, rectal surgery). Tympanic: quick, ear canal. Temporal: across forehead.", example: "The CNA used a tympanic thermometer on the confused resident who couldn't safely hold an oral probe, recording 99.2°F." },
  { term: "Pulse Assessment", type: "concept", category: "vitals", meaning: "Adult normal 60–100 bpm. Radial pulse routine; apical (5th ICS, midclavicular) for irregular pulse or before cardiac meds — counted for full minute with stethoscope. Document rate, rhythm, strength (0–4+ scale).", example: "Because the resident's pulse felt irregular at the radial, the CNA reassessed apically for a full minute and reported 76 bpm with irregular rhythm." },
  { term: "Respiratory Rate", type: "concept", category: "vitals", meaning: "Normal adult 12–20/min. Count without resident's awareness (often while keeping fingers on radial pulse) since people unconsciously alter breathing when watched. Note depth (shallow/normal/deep) and effort (labored/easy).", example: "The CNA observed the resident's chest rise while still palpating the radial pulse, counting 18 respirations of normal depth and effort." },
  { term: "Blood Pressure Measurement", type: "concept", category: "vitals", meaning: "Cuff bladder 80% of arm circumference; position at heart level. Inflate 20–30 mmHg above palpated systolic; deflate 2–3 mmHg/sec. First Korotkoff sound = systolic; disappearance = diastolic. Normal <120/<80.", example: "The CNA verified an appropriately sized cuff and seated position; BP was 132/84 — Stage 1 hypertension — and reported to the nurse." },
  { term: "Intake and Output (I&O)", type: "concept", category: "vitals", meaning: "Tracking of all fluids consumed (oral, IV, tube feeding) and excreted (urine, emesis, drainage, liquid stool). Recorded in mL. Critical for residents with CHF, renal disease, dehydration, IV therapy, or after surgery.", example: "The CNA recorded 240 mL juice, 180 mL water, and 350 mL of urine output; cumulative 8-hr totals helped identify dehydration." },
  { term: "Pulse Oximetry", type: "concept", category: "vitals", meaning: "Non-invasive measure of arterial O2 saturation; normal ≥95%. Inaccurate with cold extremities, dark nail polish, motion, low perfusion. Report SpO2 <90% immediately to the nurse.", example: "The CNA removed dark nail polish before applying the pulse oximeter; SpO2 of 88% prompted immediate notification of the nurse." },

  // ── Mobility & Safety ────────────────────────────────────────
  { term: "Body Mechanics", type: "concept", category: "mobility", meaning: "Proper alignment, balance, and use of body to prevent injury: feet shoulder-width apart, bend knees not back, hold load close, push rather than pull, ask for help with heavy lifts. Prevents CNA back injury.", example: "Before transferring the resident, the CNA widened her stance, bent her knees, and kept the resident close to her body — proper body mechanics." },
  { term: "Transfer Techniques", type: "concept", category: "mobility", meaning: "Stand-pivot (weight-bearing resident with gait belt), slide-board (sitting transfer), mechanical lift (Hoyer for non-weight-bearing). Lock wheelchair, lower bed, use gait belt, count to three together before lifting.", example: "The CNA used a gait belt for the stand-pivot transfer of the partially weight-bearing resident, locking the wheelchair brakes first." },
  { term: "Gait Belt", type: "concept", category: "mobility", meaning: "A canvas belt placed around the resident's waist over clothing to provide a secure handhold during transfers and ambulation; reduces fall risk and allows CNA to guide the resident safely. Never place over bare skin.", example: "Before walking the resident to the bathroom, the CNA applied a gait belt snugly above the hips for safe ambulation support." },
  { term: "Fall Prevention", type: "concept", category: "mobility", meaning: "Strategies: bed in low position with brakes locked, call light within reach, non-skid footwear, clear pathways, adequate lighting, reach assistance for high-risk residents, bed/chair alarms, and frequent rounding.", example: "After the resident's fall risk score increased, the CNA placed a bed alarm, kept the call light within reach, and rounded every hour." },
  { term: "Restraints (Restraint-Free Care)", type: "concept", category: "mobility", meaning: "Physical or chemical restraints restrict resident movement; require a physician order, time limits, and frequent monitoring. Federal regulations (OBRA) require restraint-free care whenever possible. Side rails 4-up may count as restraint.", example: "The team chose a low bed with floor mats instead of side rails for the high-fall-risk resident, supporting restraint-free care." },
  { term: "Range of Motion (ROM) Exercises", type: "concept", category: "mobility", meaning: "Passive (CNA moves joint without resident effort) prevents contractures in immobile residents. Active (resident moves) and active-assisted (some help) maintain joint mobility. Always work from proximal to distal, support above and below joint.", example: "The CNA performed passive ROM exercises on the bed-bound resident every shift to prevent contractures and maintain joint flexibility." },

  // ── Infection Control & Special Care ─────────────────────────
  { term: "Standard Precautions", type: "concept", category: "infection", meaning: "Applied to ALL residents regardless of diagnosis: hand hygiene, gloves for blood/body fluid contact, gown/mask/eye protection for splash risk, sharps safety, and disposing of contaminated items in biohazard bags.", example: "The CNA donned gloves before changing a soiled brief — standard precautions applied to every resident regardless of known infection." },
  { term: "Isolation Precautions (Transmission-Based)", type: "concept", category: "infection", meaning: "Added to standard precautions: Contact (MRSA, C. diff — gown + gloves); Droplet (flu, pertussis — surgical mask within 6 ft); Airborne (TB, measles — N95 + negative pressure room).", example: "The CNA donned a gown and gloves before entering the C. diff isolation room, and washed hands with soap and water on exit (alcohol gel does not kill spores)." },
  { term: "Pressure Ulcer Prevention", type: "concept", category: "infection", meaning: "Reposition every 2 hours, keep skin clean and dry, use pressure-reducing surfaces, encourage hydration/nutrition, inspect bony prominences (sacrum, heels, elbows) daily. Stage I redness signals immediate intervention.", example: "The CNA repositioned the bedridden resident every 2 hours and noted persistent redness on the sacrum — early stage I pressure injury reported to the nurse." },
  { term: "Toileting and Incontinence Care", type: "concept", category: "infection", meaning: "Offer toileting every 2 hours for incontinent residents. Change briefs immediately when soiled. Cleanse skin gently, apply barrier cream, allow skin to dry. Document continence patterns for bladder retraining.", example: "The CNA toileted the resident on a schedule every 2 hours, reducing incontinence episodes and protecting fragile perineal skin." },
  { term: "End-of-Life Care", type: "concept", category: "infection", meaning: "Comfort-focused care: pain control, position changes, oral/skin care, family support. Signs of approaching death: Cheyne-Stokes breathing, mottling, decreased intake, withdrawal. Honor cultural and spiritual preferences. Postmortem care follows facility protocol.", example: "The CNA provided gentle mouth care and repositioning for the actively dying resident while the family sat at the bedside." },
  { term: "Cognitive Impairment Care", type: "concept", category: "infection", meaning: "Use simple short sentences, approach calmly from the front, allow extra time, maintain routine, validate feelings rather than correct, reduce environmental stimuli, redirect agitation. Avoid arguing or testing memory.", example: "When the resident with dementia insisted her deceased husband was visiting, the CNA validated her emotion ('You miss him') rather than correcting her." },
];'''
m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
html = html[:m.start()] + TERMS_JS + html[m.end():]
CAT = """const categoryLabel = c => ({
  'scope':     'CNA Scope & Professionalism',
  'adls':      'ADLs & Personal Care',
  'vitals':    'Vital Signs & Measurements',
  'mobility':  'Mobility & Safety',
  'infection': 'Infection Control & Special Care',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'nursing-assisting';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>', '<title>HOSA Prep Hub — Nursing Assisting</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>', '<h1>Nursing<br><em>Assisting</em>.</h1>', 1)
html = html.replace('A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
                    'A study companion for CNA scope and professionalism, ADLs and personal care, vital signs, mobility and safety, and infection control and special-population care — built for HOSA competitors.', 1)
html = html.replace('//  DATA — HOSA Emergency Medical Science', '//  DATA — HOSA Nursing Assisting', 1)
with open(DST, 'w', encoding='utf-8') as f: f.write(html)
print(f'Wrote {DST} — {TERMS_JS.count("{ term:")} terms')
