#!/usr/bin/env python3
"""Generate cardiovascular-science.html from dental-science.html template."""
import os, re
BASE = '/home/user/hosa-prep-hub'
SRC, DST = os.path.join(BASE, 'dental-science.html'), os.path.join(BASE, 'cardiovascular-science.html')
with open(SRC, 'r', encoding='utf-8') as f: html = f.read()
TERMS_JS = '''const TERMS = [
  // ── Cardiac Anatomy & Physiology ─────────────────────────────
  { term: "Chambers and Valves", type: "concept", category: "anatomy", meaning: "Four chambers: right atrium, right ventricle, left atrium, left ventricle. AV valves: tricuspid (right), mitral/bicuspid (left). Semilunar valves: pulmonic (RV→PA), aortic (LV→aorta). Valves prevent backflow.", example: "Mitral regurgitation allowed backflow from the left ventricle into the left atrium, producing a holosystolic murmur at the apex." },
  { term: "Coronary Circulation", type: "concept", category: "anatomy", meaning: "Two main coronary arteries arise from the aortic sinuses. RCA supplies right ventricle, SA node (60%), AV node (90%), inferior LV. LCA splits into LAD (anterior wall, septum) and circumflex (lateral and posterior LV).", example: "LAD occlusion caused anterior STEMI with ST elevation in leads V1–V4; LAD is sometimes called the 'widow maker'." },
  { term: "Cardiac Cycle (Systole vs Diastole)", type: "concept", category: "anatomy", meaning: "Systole: ventricles contract, AV valves close (S1), blood ejected through semilunar valves. Diastole: ventricles relax, semilunar valves close (S2), AV valves open, chambers fill. Diastole is ~⅔ of cycle at normal HR.", example: "S1 (lub) signals ventricular systole onset; S2 (dub) signals diastole onset — basic heart sounds heard on auscultation." },
  { term: "Cardiac Output (CO)", type: "concept", category: "anatomy", meaning: "Volume of blood ejected per minute: CO = stroke volume × heart rate. Normal adult CO ~5 L/min. Stroke volume depends on preload (venous return), afterload (vascular resistance), and contractility.", example: "In hypovolemic shock, decreased preload reduced stroke volume; tachycardia attempted to maintain cardiac output but eventually failed." },
  { term: "Ejection Fraction (EF)", type: "concept", category: "anatomy", meaning: "Percentage of left ventricular end-diastolic volume ejected per beat: normal 55–70%. HFrEF (heart failure with reduced EF) ≤40%; HFpEF (preserved EF) ≥50% with diastolic dysfunction. Measured by echocardiogram.", example: "The patient's echocardiogram showed EF of 28% — severe systolic heart failure with reduced ejection fraction (HFrEF)." },
  { term: "Cardiac Conduction System", type: "concept", category: "anatomy", meaning: "SA node (pacemaker, 60–100 bpm) → AV node (delay) → Bundle of His → right and left bundle branches → Purkinje fibers. Coordinated electrical activity produces synchronized contractions.", example: "Complete heart block disrupted AV node conduction; the ventricular escape rhythm at 35 bpm required pacemaker placement." },
  { term: "Frank-Starling Law", type: "concept", category: "anatomy", meaning: "Increased ventricular end-diastolic volume (preload) stretches cardiac muscle fibers, producing more forceful contraction and greater stroke volume — up to a point. Beyond this, contractility decreases (failing heart).", example: "Volume resuscitation in the hypovolemic patient improved cardiac output via Frank-Starling — increased preload yielded stronger contraction." },

  // ── EKG & Arrhythmias ────────────────────────────────────────
  { term: "EKG Waveforms (P-QRS-T)", type: "concept", category: "ekg", meaning: "P wave = atrial depolarization. QRS = ventricular depolarization. T = ventricular repolarization. PR interval (0.12–0.20 s): AV conduction. QRS (<0.12 s): ventricular conduction. QT: ventricular activation + recovery.", example: "Prolonged QT >500 ms increased risk of torsades de pointes; the offending QT-prolonging medication was discontinued." },
  { term: "Normal Sinus Rhythm", type: "concept", category: "ekg", meaning: "Rhythm originating from the SA node: rate 60–100 bpm, regular, upright P before every QRS, QRS <0.12 s, PR 0.12–0.20 s. Standard baseline for comparison.", example: "The rhythm strip showed NSR at 72 bpm with normal intervals — no further intervention indicated." },
  { term: "Atrial Fibrillation", type: "concept", category: "ekg", meaning: "Irregularly irregular rhythm with no discernible P waves; chaotic atrial activity. Risks: stroke (thrombus in left atrial appendage), heart failure. Treated with rate control (beta-blocker, CCB), rhythm control, and anticoagulation.", example: "The patient's irregularly irregular pulse and ECG without P waves confirmed atrial fibrillation; apixaban was started for stroke prevention." },
  { term: "Atrial Flutter", type: "concept", category: "ekg", meaning: "Atrial rate ~250–350 bpm with characteristic 'sawtooth' flutter waves, often with 2:1 or 4:1 AV conduction producing ventricular rates of ~150 or ~75. Managed similar to AFib with rate control and anticoagulation.", example: "The patient's regular tachycardia at 150 bpm with sawtooth flutter waves indicated atrial flutter with 2:1 conduction." },
  { term: "Ventricular Tachycardia (VT)", type: "concept", category: "ekg", meaning: "Three or more consecutive ventricular beats >100 bpm; wide QRS (>0.12 s). Sustained VT (>30 sec) is life-threatening. Stable VT: amiodarone. Unstable (hypotension, AMS, chest pain): synchronized cardioversion.", example: "The patient with monomorphic VT at 180 bpm and hypotension was emergently cardioverted with 100J synchronized shock." },
  { term: "Ventricular Fibrillation (VF)", type: "concept", category: "ekg", meaning: "Chaotic, disorganized ventricular electrical activity with no effective cardiac output — pulseless arrest. Immediate unsynchronized defibrillation (200J biphasic) and ACLS CPR are required. Most common rhythm in sudden cardiac death.", example: "The patient went into VF on the monitor; CPR was started and defibrillation at 200J restored a perfusing rhythm." },
  { term: "STEMI vs NSTEMI", type: "concept", category: "ekg", meaning: "STEMI: ST elevation in ≥2 contiguous leads — complete coronary occlusion → emergent PCI within 90 min. NSTEMI: ST depression or T inversion + elevated troponin; partial occlusion → risk stratification, often delayed PCI.", example: "ST elevation in V1–V4 with chest pain confirmed anterior STEMI; the cath lab was activated for primary PCI within 90 minutes." },
  { term: "Heart Block (1°, 2°, 3°)", type: "concept", category: "ekg", meaning: "1°: PR >0.20 s, every P conducts. 2° Mobitz I (Wenckebach): progressive PR lengthening until dropped beat. 2° Mobitz II: constant PR, intermittent dropped QRS. 3°: complete AV dissociation — P and QRS independent.", example: "The patient's complete heart block with ventricular rate 35 required transcutaneous pacing then permanent pacemaker placement." },

  // ── Cardiac Pathology ────────────────────────────────────────
  { term: "Atherosclerosis", type: "concept", category: "pathology", meaning: "Progressive lipid-rich plaque accumulation in arterial intima with fibrous cap; underlies coronary artery disease, stroke, and PAD. Risk factors: hypertension, dyslipidemia, smoking, diabetes, family history.", example: "Coronary angiography revealed atherosclerotic plaque with 90% stenosis in the LAD; a drug-eluting stent was placed during PCI." },
  { term: "Myocardial Infarction (MI)", type: "concept", category: "pathology", meaning: "Myocardial cell death from prolonged ischemia, most commonly from coronary thrombosis on a ruptured plaque. Symptoms: substernal chest pressure, radiation to arm/jaw, dyspnea, diaphoresis, nausea. Diagnosed by ECG + troponin.", example: "The patient's crushing chest pain radiating to the left arm, ST elevation in II, III, aVF, and troponin of 8 ng/mL confirmed inferior STEMI." },
  { term: "Heart Failure", type: "concept", category: "pathology", meaning: "Inability of heart to pump enough to meet metabolic demands. Left-sided: pulmonary congestion (dyspnea, orthopnea, PND, crackles). Right-sided: systemic congestion (JVD, hepatomegaly, edema). Often bilateral over time.", example: "The patient's bilateral lower extremity edema, JVD, and crackles indicated biventricular heart failure; furosemide and ACE inhibitor were started." },
  { term: "Hypertension (HTN)", type: "concept", category: "pathology", meaning: "Sustained BP ≥130/80 (Stage 1) or ≥140/90 (Stage 2) per ACC/AHA 2017. Often asymptomatic but causes LVH, CAD, stroke, CKD. Treated with lifestyle + ACEi/ARB, thiazide diuretic, CCB, beta-blocker.", example: "The patient's repeated BP of 156/96 confirmed Stage 2 HTN; lisinopril and amlodipine were initiated with lifestyle counseling." },
  { term: "Valvular Heart Disease", type: "concept", category: "pathology", meaning: "Stenosis (narrowed) or regurgitation (leaking). Aortic stenosis: harsh systolic murmur radiating to carotids, syncope, angina, dyspnea. Mitral regurgitation: holosystolic apex murmur. Replacement or repair when symptomatic.", example: "The elderly patient's harsh systolic murmur radiating to the carotids and syncope on exertion confirmed severe aortic stenosis; TAVR was scheduled." },
  { term: "Cardiomyopathy", type: "concept", category: "pathology", meaning: "Dilated: enlarged weak ventricles, reduced EF (alcohol, viral, idiopathic). Hypertrophic: thick LV with outflow obstruction (genetic; sudden cardiac death in young athletes). Restrictive: stiff ventricles (amyloid, sarcoid).", example: "The young athlete's syncope during sports and echo finding of asymmetric septal hypertrophy diagnosed hypertrophic cardiomyopathy." },
  { term: "Pericarditis", type: "concept", category: "pathology", meaning: "Inflammation of the pericardial sac causing sharp pleuritic chest pain (worse supine, better leaning forward), pericardial friction rub, diffuse ST elevation and PR depression on ECG. Usually viral; treated with NSAIDs + colchicine.", example: "The young man's sharp chest pain relieved by sitting forward and friction rub on auscultation, with diffuse ST elevation, confirmed viral pericarditis." },

  // ── Cardiac Drugs & Interventions ────────────────────────────
  { term: "Antiplatelet Therapy", type: "concept", category: "drugs-interventions", meaning: "Aspirin (irreversible COX-1 inhibitor) — standard for CAD. P2Y12 inhibitors: clopidogrel, ticagrelor — added for ACS and post-stent. Dual antiplatelet therapy (DAPT) is standard for 6–12 months after drug-eluting stent.", example: "After PCI with drug-eluting stent, the patient was discharged on DAPT with aspirin 81 mg and clopidogrel 75 mg daily for 12 months." },
  { term: "Beta-Blockers", type: "concept", category: "drugs-interventions", meaning: "Block β-adrenergic receptors → reduce HR, contractility, BP. Mortality benefit in MI, HFrEF (metoprolol succinate, carvedilol, bisoprolol). Caution in asthma, bradycardia. Names end in -olol.", example: "Post-MI the patient was started on metoprolol succinate 25 mg daily — proven to reduce mortality in heart failure with reduced EF." },
  { term: "ACE Inhibitors / ARBs", type: "concept", category: "drugs-interventions", meaning: "Block angiotensin → reduce afterload, prevent remodeling. ACEi (-pril): mortality benefit in HFrEF, post-MI, CKD. Side effect: dry cough, hyperkalemia, angioedema. ARB (-sartan) if cough.", example: "The patient with HFrEF and EF 30% was started on lisinopril 10 mg daily; switched to losartan after persistent cough." },
  { term: "Diuretics", type: "concept", category: "drugs-interventions", meaning: "Loop (furosemide): potent, for acute decompensation. Thiazide (HCTZ): mild, first-line for HTN. K-sparing (spironolactone): aldosterone antagonist, mortality benefit in HFrEF. Monitor K+, renal function.", example: "The acute pulmonary edema patient received IV furosemide 40 mg with rapid diuresis and resolution of dyspnea." },
  { term: "Statins", type: "concept", category: "drugs-interventions", meaning: "HMG-CoA reductase inhibitors (atorvastatin, rosuvastatin) reduce LDL by 20–60%. High-intensity statin standard for ASCVD, post-MI, diabetes >40 years. Side effects: myalgia, rare rhabdomyolysis.", example: "Post-MI the patient was started on high-intensity atorvastatin 80 mg daily — LDL dropped from 145 to 65 mg/dL." },
  { term: "Anticoagulants (AFib & VTE)", type: "concept", category: "drugs-interventions", meaning: "Warfarin (vitamin K antagonist, monitored by INR 2–3). DOACs (apixaban, rivaroxaban — factor Xa inhibitors; dabigatran — direct thrombin) preferred — no INR monitoring, fewer interactions. Used for AFib stroke prevention and VTE.", example: "The AFib patient with CHADS-VASc of 4 was started on apixaban 5 mg BID for stroke prevention — preferred over warfarin." },
  { term: "Percutaneous Coronary Intervention (PCI)", type: "concept", category: "drugs-interventions", meaning: "Cardiac catheterization with balloon angioplasty and stent placement to restore coronary blood flow; primary treatment for STEMI (door-to-balloon ≤90 min) and NSTEMI in unstable patients.", example: "The STEMI patient underwent emergent PCI with drug-eluting stent placement in the LAD within 65 minutes of arrival." },
  { term: "Coronary Artery Bypass Grafting (CABG)", type: "concept", category: "drugs-interventions", meaning: "Surgical revascularization using LIMA (left internal mammary artery), saphenous vein, or radial artery grafts to bypass coronary obstructions. Preferred over PCI in left main disease, multivessel CAD, diabetes.", example: "Triple-vessel disease and diabetes led the heart team to recommend CABG over PCI; LIMA-LAD plus two saphenous vein grafts were placed." },
];'''
m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
html = html[:m.start()] + TERMS_JS + html[m.end():]
CAT = """const categoryLabel = c => ({
  'anatomy':            'Cardiac Anatomy & Physiology',
  'ekg':                'EKG & Arrhythmias',
  'pathology':          'Cardiac Pathology',
  'drugs-interventions':'Cardiac Drugs & Interventions',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'cardiovascular-science';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>', '<title>HOSA Prep Hub — Cardiovascular Science</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>', '<h1>Cardiovascular<br><em>Science</em>.</h1>', 1)
html = html.replace('A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
                    'A study companion for cardiac anatomy and physiology, EKG and arrhythmias, cardiovascular pathology, and cardiac drugs and interventions — built for HOSA competitors.', 1)
html = html.replace('//  DATA — HOSA Emergency Medical Science', '//  DATA — HOSA Cardiovascular Science', 1)
with open(DST, 'w', encoding='utf-8') as f: f.write(html)
print(f'Wrote {DST} — {TERMS_JS.count("{ term:")} terms')
