#!/usr/bin/env python3
"""Generate phlebotomy.html from dental-science.html template."""
import os, re

BASE = '/home/user/hosa-prep-hub'
SRC  = os.path.join(BASE, 'dental-science.html')
DST  = os.path.join(BASE, 'phlebotomy.html')

with open(SRC, 'r', encoding='utf-8') as f:
    html = f.read()

TERMS_JS = '''const TERMS = [
  // ── Venous Anatomy ───────────────────────────────────────────
  { term: "Median Cubital Vein", type: "concept", category: "anatomy", meaning: "A superficial vein in the antecubital fossa that connects the cephalic and basilic veins; the preferred site for routine venipuncture because it is large, well-anchored, and lies away from arteries and nerves.", example: "The phlebotomist palpated the median cubital vein on the patient's right antecubital fossa and selected it as the primary draw site." },
  { term: "Cephalic Vein", type: "concept", category: "anatomy", meaning: "A superficial vein on the lateral (thumb) side of the antecubital fossa and forearm; a second-choice site after the median cubital, often more visible in obese patients but more prone to rolling.", example: "When the median cubital wasn't palpable, the phlebotomist drew from the cephalic vein, anchoring it firmly with the thumb." },
  { term: "Basilic Vein", type: "concept", category: "anatomy", meaning: "A superficial vein on the medial (pinky) side of the antecubital fossa; a last-choice site because of its proximity to the brachial artery and median nerve, which raises the risk of accidental puncture.", example: "Drawing from the basilic vein is avoided when possible due to the nearby brachial artery and median nerve in the medial antecubital fossa." },
  { term: "Antecubital Fossa", type: "concept", category: "anatomy", meaning: "The triangular hollow at the anterior bend of the elbow that contains the major superficial veins (median cubital, cephalic, basilic) used for venipuncture.", example: "The patient was asked to extend the arm so the antecubital fossa could be inspected and palpated for an appropriate draw site." },
  { term: "Tunica Intima, Media, and Adventitia", type: "concept", category: "anatomy", meaning: "The three layers of a vein wall: tunica intima (inner endothelial lining), tunica media (middle smooth muscle), and tunica adventitia (outer connective tissue). Veins have a thinner media than arteries.", example: "Repeated venipuncture causes scarring of the tunica intima, which is why phlebotomists rotate sites in patients with frequent draws." },
  { term: "Venous Valves", type: "concept", category: "anatomy", meaning: "One-way leaflet folds of the tunica intima that prevent backflow of blood and propel it toward the heart; can be palpated as small bumps and should be avoided when puncturing.", example: "The phlebotomist felt a hard nodule on palpation, recognized it as a venous valve, and selected a site distal to it for the draw." },
  { term: "Vein vs Artery (Palpation)", type: "concept", category: "anatomy", meaning: "Veins are soft, springy, non-pulsatile, and superficial. Arteries are deeper, pulsatile, and elastic. Inadvertent arterial puncture produces bright red, rapidly pulsing blood and requires immediate firm pressure.", example: "When the blood drawn was bright red and pulsing, the phlebotomist recognized accidental arterial puncture and applied 5 minutes of firm pressure." },
  { term: "Brachial Artery", type: "concept", category: "anatomy", meaning: "The major artery of the upper arm, running medially in the antecubital fossa; lies deep to the basilic vein and is the main reason the basilic is the last-choice draw site.", example: "Vigorous pulsation medial to the basilic vein indicated the brachial artery, prompting the phlebotomist to choose a different site." },
  { term: "Median Nerve", type: "concept", category: "anatomy", meaning: "The major nerve traveling through the antecubital fossa medially, alongside the brachial artery; accidental contact during basilic draws can cause shooting pain, paresthesia, or permanent nerve injury.", example: "When the patient reported an electric-shock sensation down the arm, the phlebotomist withdrew the needle immediately — likely contact with the median nerve." },
  { term: "Hand and Wrist Veins", type: "concept", category: "anatomy", meaning: "Smaller superficial veins on the dorsum of the hand, used as alternates when antecubital sites are inaccessible; require a smaller gauge needle (21–23g) and lower vacuum collection (butterfly).", example: "After both antecubital fossae were exhausted, the phlebotomist used a butterfly needle on the dorsal metacarpal vein of the hand." },

  // ── Equipment ────────────────────────────────────────────────
  { term: "Multisample Needle", type: "concept", category: "equipment", meaning: "A double-ended needle that screws into a tube holder; one end punctures the vein, the other end punctures successive evacuated tubes through a rubber sleeve that reseals between tubes.", example: "A 21-gauge multisample needle was attached to the Vacutainer holder for the routine venipuncture." },
  { term: "Butterfly (Winged Infusion Set)", type: "concept", category: "equipment", meaning: "A needle with attached plastic wings and tubing leading to a Luer adapter or holder; ideal for difficult veins, pediatric, and geriatric patients because of finer control and a smaller (21–25g) needle.", example: "The phlebotomist chose a 23-gauge butterfly for the elderly patient's small, fragile hand vein." },
  { term: "Syringe Method", type: "concept", category: "equipment", meaning: "Collection using a syringe and needle, drawing blood by manual plunger pull rather than tube vacuum; used for delicate veins where vacuum could collapse the vessel.", example: "A 10 mL syringe with a 23-gauge needle was used to slowly draw blood from a fragile pediatric vein." },
  { term: "Needle Gauge", type: "concept", category: "equipment", meaning: "The diameter of a needle's bore, indicated by a numerical gauge — smaller numbers mean larger bore. Standard venipuncture is 21g; butterflies range 21–25g; blood donation uses 16g.", example: "A 21-gauge needle was used for routine venipuncture, providing adequate flow without excessive hemolysis." },
  { term: "Tourniquet", type: "concept", category: "equipment", meaning: "An elastic band applied 3–4 inches above the puncture site to distend veins; must be released within 1 minute to prevent hemoconcentration and analyte alterations.", example: "After the tourniquet was applied for 30 seconds the median cubital vein became prominently visible and was selected." },
  { term: "Evacuated Tube System (Vacutainer)", type: "concept", category: "equipment", meaning: "A closed blood collection system consisting of a sterile, pre-evacuated tube with a calibrated vacuum that automatically draws a specific volume of blood when the rubber stopper is punctured.", example: "Each 4 mL EDTA tube has a precise vacuum to draw exactly 4 mL of blood for accurate anticoagulant-to-blood ratio." },
  { term: "Tube Holder (Adapter)", type: "concept", category: "equipment", meaning: "A clear plastic barrel that holds the evacuated tube and screws onto the multisample needle, providing a stable connection during collection; OSHA requires that holders be discarded with the needle.", example: "Per OSHA, the entire needle-and-holder unit was discarded into the sharps container after the draw — never reused." },
  { term: "Sharps Container", type: "concept", category: "equipment", meaning: "A puncture-resistant, leak-proof, color-coded (red/biohazard) container for disposing of contaminated needles and other sharp instruments immediately after use; never recapped or removed.", example: "The activated safety needle and attached holder were dropped together into the sharps container at the point of use." },
  { term: "Alcohol Prep Pad (70% Isopropyl)", type: "concept", category: "equipment", meaning: "A presoaked pad used to clean the venipuncture site; applied in a concentric circle from inside out and allowed to air dry for at least 30 seconds before puncture.", example: "After tourniquet application, the site was cleansed with a 70% isopropyl alcohol pad in concentric circles and allowed to air dry." },
  { term: "Chlorhexidine and Iodine", type: "concept", category: "equipment", meaning: "Stronger antiseptics used instead of alcohol when drawing blood cultures (chlorhexidine for adults, iodine traditionally) to ensure skin sterility and prevent contamination.", example: "For blood cultures the site was prepped with chlorhexidine and allowed to dry for 30 seconds before each bottle was inoculated." },

  // ── Tubes & Order of Draw ────────────────────────────────────
  { term: "Order of Draw (CLSI)", type: "concept", category: "tubes", meaning: "The CLSI-recommended sequence for filling evacuated tubes that minimizes carryover of additives between tubes: cultures → light blue → red/serum → green → lavender → gray.", example: "After filling the blood culture bottles first, the phlebotomist moved to the light blue citrate tube and continued the CLSI order of draw." },
  { term: "Sterile Blood Culture Bottles", type: "concept", category: "tubes", meaning: "Always drawn FIRST to prevent contamination from skin flora or other tubes; one aerobic and one anaerobic bottle are inoculated.", example: "Two sets of blood cultures (aerobic + anaerobic) were drawn FIRST, before any additive tube, to maximize sterility." },
  { term: "Light Blue Top (Sodium Citrate)", type: "concept", category: "tubes", meaning: "Contains 3.2% sodium citrate as an anticoagulant in a 9:1 blood-to-additive ratio; used for coagulation studies (PT/INR, PTT, fibrinogen). Must be filled completely or results are invalid.", example: "A short-draw light blue tube was rejected because the 9:1 blood-to-citrate ratio was not maintained, invalidating the PT/INR." },
  { term: "Red Top (No Additive)", type: "concept", category: "tubes", meaning: "Plain glass or plastic tube with no anticoagulant; blood clots normally and produces serum for chemistry and serology tests. Must clot for 30–60 minutes before centrifugation.", example: "The patient's red-top tube was set upright for 45 minutes to allow complete clotting before centrifugation for serum chemistry." },
  { term: "Serum Separator Tube (SST / Gold or Tiger Top)", type: "concept", category: "tubes", meaning: "Contains a clot activator and a thixotropic gel that, after centrifugation, forms a barrier between serum and cells; convenient for chemistry panels because serum can be transported in the same tube.", example: "The SST was inverted 5 times after collection and centrifuged at 1500 x g for 10 minutes, producing a clear gel barrier below the serum." },
  { term: "Green Top (Heparin)", type: "concept", category: "tubes", meaning: "Contains lithium, sodium, or ammonium heparin as an anticoagulant; provides plasma for chemistry tests that need rapid turnaround (no clotting time required). Lithium heparin is most common.", example: "The lithium-heparin green-top tube allowed immediate centrifugation and STAT chemistry results for the emergency patient." },
  { term: "Lavender (Purple) Top (EDTA)", type: "concept", category: "tubes", meaning: "Contains EDTA (K2 or K3) that chelates calcium and prevents clotting; the standard tube for hematology — CBCs, blood typing, and ESR. Must be inverted 8–10 times immediately to mix.", example: "After the lavender EDTA tube was filled it was gently inverted 8 times to thoroughly mix blood with anticoagulant for the CBC." },
  { term: "Gray Top (Sodium Fluoride / Potassium Oxalate)", type: "concept", category: "tubes", meaning: "Contains sodium fluoride (a glycolysis inhibitor) and potassium oxalate (anticoagulant); used for glucose, lactate, and ethanol testing where glycolysis would falsely lower glucose levels.", example: "A gray-top tube was drawn for glucose to inhibit glycolysis during transport and preserve accurate plasma glucose levels." },
  { term: "Royal Blue Top (Trace Elements)", type: "concept", category: "tubes", meaning: "Contains EDTA, heparin, or no additive (varies); the stopper is specially made of low-metal rubber for trace element testing (lead, zinc, copper) that would be contaminated by standard tubes.", example: "A royal blue tube was used to draw the lead level to avoid contamination from trace metals in standard rubber stoppers." },
  { term: "Yellow Top (ACD / SPS)", type: "concept", category: "tubes", meaning: "Two distinct types: ACD (acid-citrate-dextrose) for DNA, HLA typing, paternity testing; SPS (sodium polyanethol sulfonate) for blood cultures. Specific use depends on label.", example: "An ACD yellow-top tube was sent for HLA typing prior to bone marrow transplant matching." },
  { term: "Tube Inversion", type: "concept", category: "tubes", meaning: "Gentle inversion of an additive tube immediately after collection to mix blood with anticoagulant or activator; specific inversion counts apply per tube type (typically 3–10 times). Shaking causes hemolysis.", example: "The lavender tube received 8 gentle inversions, while the red top received 5; vigorous shaking would have caused hemolysis." },
  { term: "Underfilling and Overfilling", type: "concept", category: "tubes", meaning: "Tubes must be filled to the calibrated volume (indicated line) for the correct anticoagulant-to-blood ratio. Underfilled coag tubes have excess citrate causing falsely prolonged PT/PTT; overfilled tubes risk clotting.", example: "The underfilled light blue tube was redrawn because the citrate concentration would have falsely prolonged the PT result." },

  // ── Procedure ────────────────────────────────────────────────
  { term: "Patient Identification (Two Identifiers)", type: "concept", category: "procedure", meaning: "Verification of patient identity using two independent identifiers (typically full name and date of birth, with armband confirmation) before any blood draw; misidentification is the most serious phlebotomy error.", example: "The phlebotomist asked the patient to state their full name and date of birth, then verified them against the armband and requisition." },
  { term: "Requisition Verification", type: "concept", category: "procedure", meaning: "Review of the laboratory requisition to confirm correct patient, tests ordered, special handling (fasting, time-sensitive), and tube types required before starting the draw.", example: "The requisition specified a fasting glucose and a lithium level — the phlebotomist confirmed the patient had fasted 10 hours and selected gray and green tops." },
  { term: "Hand Hygiene and PPE", type: "concept", category: "procedure", meaning: "Hand washing or alcohol-based sanitizer before and after every patient, plus gloves for all draws (Standard Precautions); fluid-resistant gown and eye protection for splash risk.", example: "The phlebotomist sanitized hands, donned new gloves, performed the draw, then doffed gloves and sanitized again before touching the chart." },
  { term: "Site Selection", type: "concept", category: "procedure", meaning: "Choosing the best venipuncture site based on vein visibility and palpability; avoiding areas with mastectomy on same side, IV lines, hematomas, scarring, edema, fistulas, or burns.", example: "The phlebotomist drew from the opposite arm because the patient had a history of right-sided mastectomy with lymph node dissection." },
  { term: "Bevel-Up Needle Insertion", type: "concept", category: "procedure", meaning: "The needle must enter the skin with the bevel facing up at a 15–30° angle to the vein for smooth penetration and proper blood flow into tubes.", example: "Holding the needle bevel-up at 20°, the phlebotomist inserted in one smooth motion and felt the slight 'pop' indicating vein entry." },
  { term: "Tourniquet One-Minute Rule", type: "concept", category: "procedure", meaning: "The tourniquet must be released within 1 minute of application to prevent hemoconcentration, which falsely elevates protein, potassium, calcium, and many other analytes.", example: "Because the venipuncture attempt was difficult, the tourniquet was released after 1 minute and reapplied just before the second attempt." },
  { term: "Order of Draw vs Discard Tube", type: "concept", category: "procedure", meaning: "When a winged set (butterfly) is used to draw a coagulation tube first, a discard tube must be drawn first to fill the dead space air in the tubing, preventing under-filled citrate tubes.", example: "Because the first tube needed was light blue and a butterfly was used, a discard tube was filled first to clear the tubing dead space." },
  { term: "Labeling at Bedside", type: "concept", category: "procedure", meaning: "Each tube must be labeled with patient identifiers, date, time, and collector initials AT THE BEDSIDE immediately after collection — never before (would risk pre-labeled mix-ups) or in another room.", example: "Right after the last tube filled, the phlebotomist labeled all tubes at the bedside with name, DOB, time, and initials, then asked the patient to confirm the name." },
  { term: "Post-Puncture Care", type: "concept", category: "procedure", meaning: "After needle withdrawal: apply gauze with firm pressure, instruct the patient to keep the arm straight (not bent) for 3–5 minutes, then apply a bandage. Bending the arm increases hematoma risk.", example: "After releasing the tourniquet and withdrawing the needle, gauze was held with firm direct pressure for 3 minutes with the patient's arm straight." },
  { term: "Fasting Specimen", type: "concept", category: "procedure", meaning: "A blood draw performed after the patient has had nothing but water for 8–12 hours; required for accurate lipid panels and fasting glucose tests.", example: "The patient confirmed a 12-hour fast (water only) before the morning lipid panel draw." },

  // ── Complications & Errors ───────────────────────────────────
  { term: "Hematoma", type: "concept", category: "complications", meaning: "A swelling of blood that leaks from the vein into surrounding tissue, typically because the needle went through the back wall of the vein, the bevel was partially out of the vein, or pressure wasn't held long enough.", example: "Blood began to swell beneath the skin during the draw — the phlebotomist immediately released the tourniquet, withdrew the needle, and applied firm pressure for 5 minutes." },
  { term: "Hemolysis", type: "concept", category: "complications", meaning: "Rupture of red blood cells releasing hemoglobin into plasma; causes pink/red plasma serum, falsely elevates potassium, LDH, and AST. Common causes: needle too small, vigorous shaking, prolonged tourniquet, alcohol not dry.", example: "The plasma appeared pink — the specimen was rejected because hemolysis would falsely elevate the patient's potassium." },
  { term: "Vasovagal Syncope (Fainting)", type: "concept", category: "complications", meaning: "A reflex drop in blood pressure and heart rate causing fainting, triggered by anxiety, pain, or sight of blood; managed by laying the patient flat, raising legs, and applying cool compresses.", example: "The patient suddenly became pale and lightheaded — the phlebotomist quickly removed the needle, laid the patient flat, and elevated the legs." },
  { term: "Petechiae", type: "concept", category: "complications", meaning: "Small red pinpoint hemorrhages that appear distal to the tourniquet site, indicating a coagulation or platelet defect; not a draw error but an early warning of prolonged bleeding.", example: "Petechiae appeared below the tourniquet, prompting the phlebotomist to hold direct pressure for an extended 10 minutes after the draw." },
  { term: "Iatrogenic Anemia", type: "concept", category: "complications", meaning: "Anemia caused by repeated blood draws in hospitalized patients, especially in the ICU; minimized by using pediatric/small-volume tubes and consolidating draws to one collection per day when possible.", example: "The patient on day 7 in the ICU developed iatrogenic anemia from cumulative phlebotomy losses despite no active bleeding." },
  { term: "Nerve Injury", type: "concept", category: "complications", meaning: "Shooting pain, electric-shock sensation, numbness, or paresthesia during a draw indicates needle contact with a nerve; the needle must be withdrawn immediately to prevent permanent injury.", example: "When the patient reported electric pain down the forearm, the phlebotomist immediately removed the needle — most likely contact with the median nerve." },
  { term: "Accidental Arterial Puncture", type: "concept", category: "complications", meaning: "Inadvertent puncture of an artery, identified by bright red, rapidly pulsing blood that fills the tube quickly; requires immediate firm pressure for at least 5 minutes and physician notification.", example: "Bright red blood pulsed into the tube — the phlebotomist released the tourniquet, withdrew the needle, applied 5 minutes of pressure, and notified the physician." },
  { term: "Lymphostasis (Mastectomy Side)", type: "concept", category: "complications", meaning: "Risk of impaired lymph drainage on the side of prior mastectomy with lymph node dissection; venipuncture on the affected side may cause lymphedema or infection and is contraindicated.", example: "The patient had a right mastectomy 3 years ago — the phlebotomist drew from the left arm to avoid lymphostasis complications." },
  { term: "IV Arm Contraindication", type: "concept", category: "complications", meaning: "Blood should not be drawn from an arm with an active IV line because it dilutes the sample with infusing fluid; if unavoidable, the IV must be stopped for 2 minutes and the first 5 mL discarded.", example: "Both antecubital sites had IVs running — the IV was paused for 2 minutes, the first 5 mL of blood was discarded, and the sample was then collected." },
  { term: "Quantity Not Sufficient (QNS)", type: "concept", category: "complications", meaning: "A specimen rejected by the lab because the volume is too low to run the requested tests; underfilled tubes (especially light blue) frequently produce QNS results.", example: "The lab reported the coag tube as QNS — the light blue had been underfilled and the phlebotomist had to redraw." },

  // ── Safety & Standards ───────────────────────────────────────
  { term: "Standard Precautions", type: "concept", category: "safety", meaning: "OSHA/CDC infection-control practices applied to every patient — treat all blood and body fluids as potentially infectious. Includes hand hygiene, gloves, gowns/eye protection when needed, and safe sharps handling.", example: "The phlebotomist donned gloves for every draw and changed them between patients per Standard Precautions, regardless of patient infection status." },
  { term: "Bloodborne Pathogens Standard (OSHA 1910.1030)", type: "concept", category: "safety", meaning: "The OSHA regulation requiring employers to protect workers from bloodborne pathogens (HIV, HBV, HCV); mandates Exposure Control Plan, free HBV vaccination, PPE, sharps safety, and annual training.", example: "All new phlebotomists complete OSHA Bloodborne Pathogens training and are offered the HBV vaccine series at no cost as required by 1910.1030." },
  { term: "Engineered Sharps Injury Protection (Safety Needles)", type: "concept", category: "safety", meaning: "OSHA-mandated needles with built-in safety mechanisms (shielded or retracting tips) activated immediately after use to prevent needlestick injury — replaced traditional needles in 2001.", example: "Immediately after needle withdrawal, the phlebotomist pressed the safety shield forward until it clicked, locking the needle." },
  { term: "Needlestick Response", type: "concept", category: "safety", meaning: "After a needlestick: wash with soap and water immediately, do not squeeze the wound, report to supervisor, complete an exposure report, get post-exposure prophylaxis evaluation, and baseline labs.", example: "After an accidental needlestick the phlebotomist washed the site for 1 minute, reported the exposure, and started the post-exposure protocol within 1 hour." },
  { term: "Chain of Custody", type: "concept", category: "safety", meaning: "A documented, unbroken record of every person who handles a specimen, used for forensic or legal samples (drug testing, alcohol, paternity); breaks in chain invalidate the sample for legal use.", example: "For the court-ordered drug test the phlebotomist initialed the seal, documented every transfer, and never let the specimen out of sight." },
  { term: "Specimen Rejection Criteria", type: "concept", category: "safety", meaning: "Lab-defined reasons for rejecting samples: hemolysis, clots in anticoagulated tubes, mislabeling, QNS, wrong tube type, expired tube, or improper transport — all require a redraw.", example: "The clotted lavender CBC tube was rejected because EDTA was inadequate; the patient was redrawn with proper mixing this time." },
  { term: "Reference Range", type: "concept", category: "safety", meaning: "The interval (typically the central 95%) of values expected in a healthy reference population; results outside the range are flagged but interpretation depends on clinical context, age, sex, and timing.", example: "The patient's potassium of 5.8 mEq/L was flagged as high (reference 3.5–5.0) but was suspected to be due to hemolysis, prompting redraw." },
  { term: "Critical (Panic) Value", type: "concept", category: "safety", meaning: "A laboratory result so abnormal it represents an immediate threat to life and must be reported to the clinician within minutes by direct verbal communication; e.g., glucose < 40, potassium > 6.5.", example: "The lab tech immediately called the floor nurse with a critical potassium of 6.9 mEq/L and documented the time and recipient." },
];'''

m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
if not m: raise SystemExit('TERMS not found')
html = html[:m.start()] + TERMS_JS + html[m.end():]

CAT = """const categoryLabel = c => ({
  'anatomy':       'Venous Anatomy',
  'equipment':     'Equipment',
  'tubes':         'Tubes & Order of Draw',
  'procedure':     'Procedure',
  'complications': 'Complications',
  'safety':        'Safety & Standards',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)

html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'phlebotomy';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>',
                    '<title>HOSA Prep Hub — Phlebotomy</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>',
                    '<h1>Phle<em>botomy</em>.</h1>', 1)
html = html.replace(
    'A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
    'A study companion for venous anatomy, phlebotomy equipment, tubes and the CLSI order of draw, venipuncture procedure, complications and errors, and OSHA safety standards — built for HOSA competitors.',
    1
)
html = html.replace('//  DATA — HOSA Emergency Medical Science',
                    '//  DATA — HOSA Phlebotomy', 1)

with open(DST, 'w', encoding='utf-8') as f:
    f.write(html)

count = TERMS_JS.count('{ term:')
print(f'Wrote {DST} — {count} terms')
