#!/usr/bin/env python3
"""Generate forensic-science.html from dental-science.html template."""
import os, re

BASE = '/home/user/hosa-prep-hub'
SRC  = os.path.join(BASE, 'dental-science.html')
DST  = os.path.join(BASE, 'forensic-science.html')

with open(SRC, 'r', encoding='utf-8') as f:
    html = f.read()

TERMS_JS = '''const TERMS = [
  // ── Death Investigation ──────────────────────────────────────
  { term: "Manner vs Cause vs Mechanism of Death", type: "concept", category: "death-investigation", meaning: "Cause: disease/injury that started the lethal sequence (e.g., gunshot wound to head). Mechanism: physiological derangement that produced death (e.g., cerebral hemorrhage). Manner: category of death — Natural, Accident, Suicide, Homicide, or Undetermined (NASH+U).", example: "The death certificate listed cause: hypertensive cardiovascular disease; mechanism: cardiac arrhythmia; manner: natural — none of these were the same thing." },
  { term: "Livor Mortis (Lividity)", type: "concept", category: "death-investigation", meaning: "Purplish-red discoloration from blood pooling in dependent tissues after circulation stops; begins 1–2 hours post-mortem, becomes fixed (blanching stops) at 8–12 hours. Position of lividity can confirm or contradict where the body was found.", example: "Lividity was fixed on the posterior surface but the body was found face-down — the body had been moved at least 8–12 hours after death." },
  { term: "Rigor Mortis", type: "concept", category: "death-investigation", meaning: "Stiffening of muscles due to ATP depletion and actin-myosin crosslinking; begins 1–6 hours, fully established by 12 hours, dissipates by 36–48 hours as putrefaction progresses. Temperature, exertion, and environment alter timing.", example: "The body was fully rigid when found, placing time of death approximately 12–36 hours prior, consistent with the missing-person report." },
  { term: "Algor Mortis", type: "concept", category: "death-investigation", meaning: "Postmortem body cooling; approximately 1–1.5°F (0.5–0.8°C) per hour under average conditions until equilibrating with ambient temperature. Henssge nomogram accounts for body weight and environment for more accurate PMI estimation.", example: "The rectal temperature was 85°F in a 70°F room; applying the cooling rate formula estimated time of death 8–13 hours earlier." },
  { term: "Putrefaction", type: "concept", category: "death-investigation", meaning: "Decomposition of tissues by intrinsic bacteria and enzymes; produces bloating, green discoloration (starting in the abdomen at the cecum), skin slippage, marbling, and eventually skeletonization. Accelerated by heat, retarded by cold/embalming.", example: "The body showed green discoloration of the right lower quadrant and marbling along thigh vessels — mid-stage putrefaction consistent with weeks postmortem." },
  { term: "Forensic Entomology", type: "concept", category: "death-investigation", meaning: "Using insect succession patterns on remains to estimate minimum postmortem interval (PMI). Blow flies (Calliphoridae) are first colonizers; successive waves of insects follow. Larval development stages under known temperature data yield PMI.", example: "Third-instar blow fly larvae collected from the body were raised to adults; their known developmental time under local temperature data placed the minimum PMI at 9 days." },
  { term: "Forensic Anthropology", type: "concept", category: "death-investigation", meaning: "Analysis of skeletal remains to establish biological profile: sex (pelvis, skull), age (epiphyseal fusion, dental wear, pubic symphysis), ancestry (skull morphology), and stature (long-bone measurements). Also identifies trauma and disease.", example: "Skeletal analysis revealed a wide subpubic angle and heart-shaped greater sciatic notch — indicators of female sex — along with fused epiphyses placing age at 25–35 years." },
  { term: "Postmortem Interval (PMI) Estimation", type: "concept", category: "death-investigation", meaning: "Estimation of time elapsed since death using algor mortis, rigor, livor, decomposition stage, entomology, stomach contents, and vitreous humor chemistry (potassium rises predictably postmortem).", example: "Vitreous potassium of 14 mEq/L, combined with rigor resolution and early putrefaction, suggested a postmortem interval of 48–72 hours." },
  { term: "Autopsy (External and Internal)", type: "concept", category: "death-investigation", meaning: "Systematic examination to determine cause and manner of death. External: document injuries, scars, marks. Internal: Y-incision, remove/weigh organs, examine brain (Virchow or Rokitansky technique), collect toxicology specimens. Medicolegal autopsies do not require family consent.", example: "At autopsy the medical examiner documented a 3 cm entrance wound with marginal abrasion ring, performed Y-incision, and collected blood, urine, and vitreous for toxicology." },
  { term: "Chain of Custody (Forensics)", type: "concept", category: "death-investigation", meaning: "Documentation of every person who collected, received, or transferred evidence from scene to laboratory to court; any gap can render evidence inadmissible. Evidence is sealed, labeled, and signed at each transfer.", example: "The blood sample was placed in a sealed, labeled tube at autopsy, signed to the courier, and receipted by the laboratory — unbroken chain of custody preserved its admissibility." },

  // ── Wound Analysis ───────────────────────────────────────────
  { term: "Entrance vs Exit Gunshot Wounds", type: "concept", category: "wound-analysis", meaning: "Entrance: smaller, has abrasion collar (friction ring), may have soot/stippling at close range. Exit: typically larger, irregular stellate/lacerated margins, no abrasion collar. Contact wounds show star-shaped tears and soot in the wound track.", example: "The pathologist identified a small, circular wound with a symmetric abrasion collar as the entrance and an irregular, larger wound with no abrasion ring as the exit." },
  { term: "Range of Fire Estimation", type: "concept", category: "wound-analysis", meaning: "Contact: barrel pressed to skin — star-shaped wound, soot inside track, muzzle contusion. Close range (<1 ft): soot on skin. Intermediate (1–4 ft): stippling (gunpowder tattooing). Distant (>4 ft): abrasion collar only.", example: "Stippling (powder tattooing) 1 inch around the wound indicated an intermediate range of approximately 12–36 inches between the muzzle and the victim." },
  { term: "Sharp Force Injuries", type: "concept", category: "wound-analysis", meaning: "Incised wounds: longer than deep, smooth edges — from slashing. Stab wounds: deeper than long — from thrusting. Defense wounds on hands and arms indicate victim tried to protect themselves. Serrated blades leave saw-toothed wound margins.", example: "Multiple incised wounds on the palms and dorsal forearms were consistent with defense wounds; the deeper stab wound to the chest was the fatal injury." },
  { term: "Blunt Force Injuries", type: "concept", category: "wound-analysis", meaning: "Lacerations: irregular, stellate, with tissue bridging (unlike incised) — from impact force. Contusions (bruises): hemorrhage from blood vessel damage; pattern may mirror object shape. Abrasions: superficial scraping — preserve pattern of object.", example: "A crescent-shaped contusion with central laceration on the scalp mirrored the claw end of a hammer; tissue bridging in the laceration confirmed blunt rather than sharp force." },
  { term: "Manner of Strangulation", type: "concept", category: "wound-analysis", meaning: "Hanging: cervical fracture (judicial), ligature mark (upward angle), petechiae. Ligature strangulation: horizontal furrow, petechiae, petechial hemorrhages in conjunctivae and sclera. Manual (throttling): fingertip bruising, fingernail marks, hyoid fracture.", example: "Horizontal ligature furrow with conjunctival petechiae and a fractured hyoid were consistent with ligature strangulation rather than suicidal hanging." },
  { term: "Petechial Hemorrhages", type: "concept", category: "wound-analysis", meaning: "Pinpoint red hemorrhages in the conjunctivae, sclera, facial skin, or brain surface from rupture of small capillaries due to raised venous pressure; classic in asphyxial deaths (strangulation, smothering, hanging) and violent straining.", example: "Bilateral petechial hemorrhages in the conjunctivae combined with facial cyanosis strongly supported asphyxia as the mechanism of death." },
  { term: "Drowning (Freshwater vs Saltwater)", type: "concept", category: "wound-analysis", meaning: "Freshwater (hypotonic) dilutes blood — hemodilution, hemolysis, hyperkalemia, ventricular fibrillation. Saltwater (hypertonic) draws fluid into alveoli — hemoconcentration, rapid pulmonary edema. Both show overinflated lungs, foam, cutis anserina, and diatoms.", example: "Diatom species in the lungs and femoral bone marrow matched the lake's diatom profile, supporting drowning in that body of water." },
  { term: "Thermal Death Injuries", type: "concept", category: "wound-analysis", meaning: "Burns classified by degree (superficial, partial, full-thickness) and percent BSA (%TBSA by rule of nines). Pugilistic posture from heat-contracted muscles in fire deaths. Soot in airways confirms victim was alive during fire (CO poisoning).", example: "Soot in the trachea and carboxyhemoglobin of 68% confirmed the victim was breathing during the fire; the burns were postmortem injury superimposed on smoke inhalation death." },

  // ── Forensic Toxicology ──────────────────────────────────────
  { term: "Forensic Toxicology Specimens", type: "concept", category: "toxicology", meaning: "Preferred postmortem specimens: peripheral blood (femoral — less subject to redistribution), vitreous humor (protected, slow equilibration), urine (accumulates metabolites), liver (reservoir), gastric contents (last dose), bile, hair (chronic history), and nails.", example: "Femoral blood was collected for quantitative analysis to avoid central-blood postmortem redistribution artifact that inflates drug concentrations." },
  { term: "Postmortem Redistribution", type: "concept", category: "toxicology", meaning: "After death, drugs diffuse from drug-rich organs (liver, lung) into adjacent blood, artificially elevating heart-blood concentrations. Peripheral blood (femoral) is more reliable. High tissue-to-blood ratio drugs (amitriptyline, diltiazem) are most affected.", example: "The heart blood amitriptyline level of 12 mg/L was suspected of postmortem redistribution; the femoral blood level of 3.5 mg/L was more representative of antemortem concentration." },
  { term: "Carbon Monoxide Poisoning", type: "concept", category: "toxicology", meaning: "CO binds hemoglobin with 200× the affinity of O2, forming carboxyhemoglobin (COHb). Fatal COHb levels: >50–60% usually lethal. Skin and organs are cherry-red. Sources: fires, faulty heaters, vehicle exhaust. Diagnosed by CO-oximetry.", example: "The family of four found unresponsive in winter had COHb levels of 45–60%; a faulty furnace had been filling the home with carbon monoxide overnight." },
  { term: "Alcohol Metabolism and Postmortem Ethanol", type: "concept", category: "toxicology", meaning: "Ethanol metabolized at ~0.015–0.020 g/dL per hour by ADH. Postmortem ethanol production by putrefaction bacteria (neoformation) can create false-positive results; vitreous humor is less affected. Legal BAC limit: 0.08 g/dL in most states.", example: "The body was significantly decomposed; vitreous ethanol was used instead of blood to avoid neoformation artifact from bacterial putrefaction." },
  { term: "Drug Screening vs Confirmatory Testing", type: "concept", category: "toxicology", meaning: "Screening (immunoassay/EMIT): fast, sensitive, but prone to cross-reactivity (false positives). Confirmatory (GC-MS, LC-MS/MS): definitive, identifies specific compound and metabolites, required for legal proceedings.", example: "The urine immunoassay screened positive for opiates, but GC-MS confirmation identified only the metabolite of prescribed codeine — ruling out illicit heroin use." },
  { term: "Drugs of Abuse — Key Metabolites", type: "concept", category: "toxicology", meaning: "Cocaine → benzoylecgonine (urine marker, detectable 2–4 days). THC → THC-COOH (fat-soluble, chronic users weeks). Heroin → 6-MAM + morphine (6-MAM proves heroin, not morphine). Methamphetamine → amphetamine.", example: "Urine detection of 6-monoacetylmorphine (6-MAM) confirmed heroin use rather than morphine prescription — 6-MAM is unique to heroin metabolism." },
  { term: "Volatile Toxicants (Solvent Abuse)", type: "concept", category: "toxicology", meaning: "Inhalants (toluene, butane, nitrous oxide) detected in blood or scene air by headspace GC. Cause sudden sniffing death (cardiac sensitization to epinephrine). Autopsy may show chemical odor, pulmonary edema, perioral rash.", example: "The teenager found unresponsive with a plastic bag nearby showed blood toluene on headspace GC — sudden sniffing death from inhalant abuse." },

  // ── Trace Evidence ───────────────────────────────────────────
  { term: "Locard's Exchange Principle", type: "concept", category: "trace-evidence", meaning: "Every contact between two surfaces results in a mutual transfer of trace material; the perpetrator both leaves evidence on the victim/scene and takes evidence away. Basis for forensic trace evidence analysis.", example: "Fiber transfer from the suspect's sweater to the victim's clothing, and victim's hair on the suspect's jacket, demonstrated Locard's exchange principle." },
  { term: "Hair Analysis", type: "concept", category: "trace-evidence", meaning: "Microscopic comparison of hair cuticle, cortex, and medullary patterns — associative, not conclusive; cannot be used for positive identification. Nuclear DNA from hair root tags or mitochondrial DNA from shaft enables individualization.", example: "The brown hair found in the victim's hand had a similar microscopic profile to the suspect's hair; mtDNA sequencing was ordered for individualization." },
  { term: "Fiber Evidence", type: "concept", category: "trace-evidence", meaning: "Trace fibers identified by microscopy (shape, color, cross-section), microspectrophotometry, and IR spectroscopy. Manufactured (nylon, polyester) are more distinctive than natural (cotton). Fiber associations are class evidence.", example: "Blue nylon carpet fibers on the victim matched the carpet in the suspect's trunk microscopically and by IR spectroscopy — strong trace association." },
  { term: "Glass Fracture Analysis", type: "concept", category: "trace-evidence", meaning: "Radial fractures from an impact point; concentric rings follow. 3R-rule: Radial fractures have Ridges on the Reverse side of force. Refractive index of glass fragments, measured by phase-contrast microscopy, enables glass source comparison.", example: "The headlight glass found at the hit-and-run scene had a refractive index matching the suspect vehicle's headlamp within ±0.0001, linking them to the scene." },
  { term: "Fingerprint Classification (Ridge Detail)", type: "concept", category: "trace-evidence", meaning: "Three general patterns: loop (most common, ~60%), whorl (~35%), arch (~5%). Individualized by Level 2 minutiae (bifurcations, ridge endings) and Level 3 detail (pore positions). AFIS searches use minutiae comparisons.", example: "The latent print lifted from the knife showed a right-loop pattern; AFIS matched the minutiae to the suspect's left index finger." },
  { term: "Gunshot Residue (GSR)", type: "concept", category: "trace-evidence", meaning: "Primer combustion produces lead, barium, and antimony particles (characteristic triad) deposited on hands, face, and nearby surfaces; detected by SEM-EDX. Swabbed within 4–6 hours post-firing before loss by washing or activity.", example: "SEM-EDX analysis of the suspect's hand swab detected multiple unique GSR particles containing lead, barium, and antimony — consistent with discharging a firearm." },

  // ── Forensic DNA & Serology ──────────────────────────────────
  { term: "STR (Short Tandem Repeat) DNA Profiling", type: "concept", category: "dna-serology", meaning: "The CODIS standard uses 20 core STR loci; each locus has two alleles (one from each parent). The chance of a random match is less than 1 in a quintillion. Touch DNA, bloodstains, and hair roots are profiled by PCR amplification.", example: "DNA from the bloodstain on the suspect's shirt matched the victim's STR profile at all 20 CODIS loci — probability of random match 1 in 10²⁸." },
  { term: "CODIS (Combined DNA Index System)", type: "concept", category: "dna-serology", meaning: "The FBI's national DNA database with three tiers: Local (LDIS), State (SDIS), National (NDIS). Contains convicted offenders, arrestees, forensic profiles, and unidentified persons. Cold-case hits occur when a crime-scene profile matches the offender index.", example: "The 15-year-old unsolved rape kit was entered into CODIS and returned a cold hit to a convicted offender in the national offender index." },
  { term: "Presumptive vs Confirmatory Blood Tests", type: "concept", category: "dna-serology", meaning: "Presumptive: Luminol (chemiluminescence, detects trace blood even after cleaning), phenolphthalein (Kastle-Meyer), leucomalachite green — fast but non-specific (false positives with bleach, plant peroxidases). Confirmatory: Takayama crystal test or Hemastix.", example: "Luminol showed a strong positive reaction on the cleaned wall — suggestive of blood — but phenolphthalein confirmed and Hemastix was added before DNA extraction." },
  { term: "ABO Blood Typing in Forensics", type: "concept", category: "dna-serology", meaning: "ABO antigens on RBCs and corresponding antibodies in plasma; ~80% of the population are 'secretors' who also express blood type antigens in saliva, semen, and other body fluids — allowing blood typing of trace evidence before DNA.", example: "Before PCR DNA was available, the forensic serologist determined the semen was from a type A secretor, narrowing the suspect pool." },
  { term: "Sexual Assault Evidence Collection (SANE)", type: "concept", category: "dna-serology", meaning: "A Sexual Assault Nurse Examiner collects a SART kit within 72–120 hours including vaginal/cervical swabs, oral and rectal swabs, clothing, fingernail scrapings, pubic hair combings, and reference blood and saliva; all with strict chain of custody.", example: "The SANE completed the rape kit within 2 hours of the assault; DNA from the vaginal swab was entered into CODIS and matched the perpetrator 6 months later." },
  { term: "Mitochondrial DNA (mtDNA) Analysis", type: "concept", category: "dna-serology", meaning: "mtDNA is maternally inherited, present in high copy number — useful when nuclear DNA is degraded (old bones, hair shaft, teeth). Cannot individualize (shared by maternal relatives) but can exclude. Used for identification of unknown remains.", example: "The skeletal remains lacked sufficient nuclear DNA; mtDNA from the femur matched the victim's daughter (same maternal lineage), confirming identity." },
];'''

m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
if not m: raise SystemExit('TERMS not found')
html = html[:m.start()] + TERMS_JS + html[m.end():]

CAT = """const categoryLabel = c => ({
  'death-investigation': 'Death Investigation',
  'wound-analysis':      'Wound Analysis',
  'toxicology':          'Forensic Toxicology',
  'trace-evidence':      'Trace Evidence',
  'dna-serology':        'DNA & Serology',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)

html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'forensic-science';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>',
                    '<title>HOSA Prep Hub — Forensic Science</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>',
                    '<h1>Forensic<br><em>Science</em>.</h1>', 1)
html = html.replace(
    'A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
    'A study companion for death investigation, wound analysis, forensic toxicology, trace evidence, and forensic DNA and serology — built for HOSA competitors.',
    1
)
html = html.replace('//  DATA — HOSA Emergency Medical Science',
                    '//  DATA — HOSA Forensic Science', 1)

with open(DST, 'w', encoding='utf-8') as f:
    f.write(html)

count = TERMS_JS.count('{ term:')
print(f'Wrote {DST} — {count} terms')
