#!/usr/bin/env python3
"""Generate geriatrics.html from dental-science.html template."""
import os, re
BASE = '/home/user/hosa-prep-hub'
SRC, DST = os.path.join(BASE, 'dental-science.html'), os.path.join(BASE, 'geriatrics.html')
with open(SRC, 'r', encoding='utf-8') as f: html = f.read()
TERMS_JS = '''const TERMS = [
  // ── Physiology of Aging ──────────────────────────────────────
  { term: "Physiologic Changes of Aging", type: "concept", category: "aging-physiology", meaning: "Cardiovascular: ↓max HR, arterial stiffness, ↑BP. Pulmonary: ↓vital capacity. Renal: GFR declines 1 mL/min/year after 40. Cognitive: slower processing, preserved crystallized intelligence. Skin: thinning, ↓elasticity. Bone: declining density.", example: "The 80-year-old's slower drug clearance from age-related GFR decline required dose reduction of renally cleared medications." },
  { term: "Frailty Syndrome", type: "concept", category: "aging-physiology", meaning: "Clinical syndrome of decreased physiologic reserve and vulnerability to stressors. Fried criteria (≥3 of 5): unintentional weight loss, exhaustion, weak grip, slow gait, low activity. Predicts falls, disability, hospitalization, death.", example: "The 82-year-old's slow gait, weight loss, and exhaustion met Fried criteria for frailty — pre-op risk stratification flagged her for prehab." },
  { term: "Sarcopenia", type: "concept", category: "aging-physiology", meaning: "Age-related loss of muscle mass, strength, and function. Contributes to falls, disability, mortality. Treated with resistance exercise and adequate protein intake (1.2-1.5 g/kg/day in older adults).", example: "The patient's reduced grip strength and slow gait speed were addressed with resistance training and increased protein intake." },
  { term: "Polypharmacy", type: "concept", category: "aging-physiology", meaning: "Use of ≥5 medications; common in older adults. Risks: adverse drug events, falls, cognitive impairment, drug interactions. Periodic medication reconciliation and deprescribing reduce risk. Use Beers Criteria for potentially inappropriate medications.", example: "The 78-year-old on 12 medications had 2 fall events; deprescribing per Beers Criteria reduced her medication count to 7." },

  // ── Geriatric Syndromes ──────────────────────────────────────
  { term: "Falls Prevention", type: "concept", category: "syndromes", meaning: "Most common cause of injury in older adults. Risk factors: muscle weakness, gait/balance impairment, polypharmacy (especially psychotropics), home hazards, vision impairment. Multifactorial intervention: PT, home modifications, vit D, medication review.", example: "After a fall the 79-year-old had vision exam, vitamin D 800 IU started, home safety eval, and PT for strength and balance training." },
  { term: "Delirium", type: "concept", category: "syndromes", meaning: "Acute confusional state with fluctuating attention, disorganized thinking, altered consciousness. Hyperactive (agitation) vs hypoactive (lethargy — often missed). Causes: infection, drugs, dehydration, pain, hypoxia. CAM tool for diagnosis. Address underlying cause.", example: "The 85-year-old's acute confusion 2 days post-op with positive CAM was diagnosed as delirium from UTI and opioid pain medication." },
  { term: "Dementia (Alzheimer Disease)", type: "concept", category: "syndromes", meaning: "Most common dementia. Progressive memory loss, language deficit, executive dysfunction, behavioral changes. Amyloid plaques and neurofibrillary tangles. Treated with cholinesterase inhibitors (donepezil), memantine; new monoclonal antibodies for early disease.", example: "The patient's 2-year progressive memory loss with hippocampal atrophy on MRI was diagnosed as Alzheimer disease; donepezil was initiated." },
  { term: "Dementia Subtypes", type: "concept", category: "syndromes", meaning: "Alzheimer (most common). Vascular (stepwise decline, vascular risk factors). Lewy body (parkinsonism, visual hallucinations, fluctuating cognition, REM sleep behavior). Frontotemporal (early personality/language changes). Mixed types common.", example: "The patient's visual hallucinations, fluctuating cognition, and parkinsonism suggested Lewy body dementia — antipsychotics were avoided due to high sensitivity." },
  { term: "Urinary Incontinence", type: "concept", category: "syndromes", meaning: "Stress (cough/sneeze), urge (overactive bladder), overflow (BPH, neurogenic), functional (mobility/cognitive). Common in older women (stress) and men (BPH-related overflow). Treated with pelvic floor exercises, anticholinergics, mirabegron, surgery.", example: "The patient's stress incontinence with cough/laugh improved with pelvic floor exercises and was confirmed by positive cough stress test." },
  { term: "Pressure Injuries (Pressure Ulcers)", type: "concept", category: "syndromes", meaning: "Skin/soft tissue damage over bony prominences from prolonged pressure. Stages I-IV. Prevention: repositioning q2h, pressure redistribution surfaces, nutrition, skin assessment. Heels, sacrum most common.", example: "The bedridden patient's sacral stage II pressure injury was managed with hydrocolloid dressing, q2h repositioning, and air mattress." },
  { term: "Sensory Impairment", type: "concept", category: "syndromes", meaning: "Vision: cataracts, AMD, glaucoma, presbyopia affect majority of older adults. Hearing: presbycusis affects ~⅓ of those >65. Both contribute to falls, social isolation, depression, cognitive decline. Screen and treat with corrective devices.", example: "The patient's social withdrawal and cognitive decline were partially attributable to severe presbycusis; hearing aids dramatically improved engagement." },

  // ── Comprehensive Geriatric Assessment & End-of-Life ─────────
  { term: "Comprehensive Geriatric Assessment (CGA)", type: "concept", category: "assessment-eol", meaning: "Multidimensional, interdisciplinary evaluation: medical, functional (ADLs, IADLs), cognitive (MMSE, MoCA), psychological (GDS), social, environmental, nutritional. Guides care planning and improves outcomes.", example: "The CGA identified moderate cognitive impairment, IADL dependence, depression, and social isolation — coordinated multidisciplinary plan was developed." },
  { term: "ADLs and IADLs", type: "concept", category: "assessment-eol", meaning: "ADLs (Katz): bathing, dressing, toileting, transferring, continence, feeding. IADLs (Lawton): cooking, shopping, finances, medications, transportation, housework, telephone. ADL dependence predicts mortality; IADL loss precedes ADL loss.", example: "The patient could perform all ADLs independently but needed help with finances and medications — IADL dependence prompted home health services." },
  { term: "Cognitive Screening (MMSE, MoCA, Mini-Cog)", type: "concept", category: "assessment-eol", meaning: "MMSE (30 points; <24 cognitive impairment). MoCA (30 points; <26 mild cognitive impairment; more sensitive for early). Mini-Cog (rapid 3-min screen; 3-item recall + clock draw).", example: "The patient's MoCA of 22 raised concern for mild cognitive impairment, prompting further workup and cognitive monitoring." },
  { term: "Beers Criteria", type: "concept", category: "assessment-eol", meaning: "AGS list of potentially inappropriate medications in older adults. Examples: benzodiazepines (falls), anticholinergics (cognition), NSAIDs (GI/renal/CV), first-gen antihistamines (confusion). Guides safer prescribing.", example: "Per Beers Criteria, the patient's diphenhydramine was stopped due to anticholinergic burden and replaced with non-pharmacologic sleep strategies." },
  { term: "Advance Care Planning", type: "concept", category: "assessment-eol", meaning: "Conversations about goals, values, preferences for future care. Documents: advance directive, living will, durable POA for healthcare, POLST (Physician Orders for Life-Sustaining Treatment), DNR.", example: "The patient completed POLST specifying no CPR, no mechanical ventilation, comfort-focused care — preferences honored across settings." },
  { term: "Palliative Care vs Hospice", type: "concept", category: "assessment-eol", meaning: "Palliative: symptom-focused care alongside disease-directed treatment at any stage. Hospice: comfort-focused care when prognosis <6 months and curative treatment stopped. Both improve quality of life and reduce caregiver burden.", example: "The patient with advanced dementia and recurrent infections transitioned to hospice — focus shifted to comfort, family support, and dignity." },
  { term: "Caregiver Support", type: "concept", category: "assessment-eol", meaning: "Family caregivers experience high rates of stress, depression, financial strain, health problems. Resources: respite care, support groups, Area Agencies on Aging, adult day programs. Assess caregiver burden routinely.", example: "The patient's daughter caring for her mother with dementia was referred to a respite program and support group, reducing caregiver burden and depression." },
];'''
m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
html = html[:m.start()] + TERMS_JS + html[m.end():]
CAT = """const categoryLabel = c => ({
  'aging-physiology': 'Physiology of Aging',
  'syndromes':        'Geriatric Syndromes',
  'assessment-eol':   'Assessment & End-of-Life',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'geriatrics';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>', '<title>HOSA Prep Hub — Geriatrics</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>', '<h1>Geri<em>atrics</em>.</h1>', 1)
html = html.replace('A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
                    'A study companion for the physiology of aging, geriatric syndromes including falls and delirium and dementia, and comprehensive assessment and end-of-life care — built for HOSA competitors.', 1)
html = html.replace('//  DATA — HOSA Emergency Medical Science', '//  DATA — HOSA Geriatrics', 1)
with open(DST, 'w', encoding='utf-8') as f: f.write(html)
print(f'Wrote {DST} — {TERMS_JS.count("{ term:")} terms')
