#!/usr/bin/env python3
"""Generate gastroenterology.html from dental-science.html template."""
import os, re
BASE = '/home/user/hosa-prep-hub'
SRC, DST = os.path.join(BASE, 'dental-science.html'), os.path.join(BASE, 'gastroenterology.html')
with open(SRC, 'r', encoding='utf-8') as f: html = f.read()
TERMS_JS = '''const TERMS = [
  // ── GI Anatomy & Physiology ──────────────────────────────────
  { term: "GI Tract Overview", type: "concept", category: "anatomy", meaning: "Mouth → pharynx → esophagus → stomach → small intestine (duodenum, jejunum, ileum) → large intestine (cecum, colon, rectum) → anus. Accessory organs: liver, gallbladder, pancreas, salivary glands. Total length ~30 ft.", example: "The patient's colonoscopy advanced from rectum through sigmoid, descending, transverse, ascending colon to cecum — visualizing the entire large intestine." },
  { term: "Stomach Functions", type: "concept", category: "anatomy", meaning: "Stores food, secretes gastric juice (HCl from parietal cells, pepsinogen from chief cells, intrinsic factor for B12). Churns mixture into chyme. Empties into duodenum through pyloric sphincter. pH ~2 kills most pathogens.", example: "Parietal cell destruction in pernicious anemia eliminated intrinsic factor production, causing B12 malabsorption and macrocytic anemia." },
  { term: "Small Intestine", type: "concept", category: "anatomy", meaning: "~20 ft long; primary site of digestion and absorption via villi and microvilli (brush border). Duodenum: receives bile and pancreatic juice. Jejunum: most absorption. Ileum: B12 and bile salt absorption.", example: "Crohn's disease of the terminal ileum impaired B12 absorption — the patient developed macrocytic anemia requiring monthly B12 injections." },
  { term: "Large Intestine", type: "concept", category: "anatomy", meaning: "~5 ft long; absorbs water and electrolytes, stores feces, houses gut microbiota (synthesize vitamin K). Major segments: cecum (with appendix), ascending, transverse, descending, sigmoid colon, rectum.", example: "Antibiotic disruption of normal colonic flora allowed C. difficile overgrowth, causing pseudomembranous colitis." },
  { term: "Liver Functions", type: "concept", category: "anatomy", meaning: "Metabolism (carb, fat, protein), detoxification (CYP450 drug metabolism, ammonia → urea), bile production, plasma protein synthesis (albumin, clotting factors), bilirubin processing, storage (glycogen, vitamins).", example: "The cirrhotic patient's low albumin, prolonged PT, and hyperammonemia reflected hepatic synthetic failure and impaired detoxification." },
  { term: "Pancreas (Exocrine vs Endocrine)", type: "concept", category: "anatomy", meaning: "Exocrine: acini secrete digestive enzymes (amylase, lipase, trypsin, chymotrypsin) into duodenum via pancreatic duct. Endocrine: islets of Langerhans secrete insulin (β-cells), glucagon (α-cells), somatostatin (δ-cells).", example: "Acute pancreatitis released lipase into the bloodstream — elevated serum lipase 1200 U/L was diagnostic." },
  { term: "Gallbladder and Biliary System", type: "concept", category: "anatomy", meaning: "Gallbladder concentrates and stores bile (from liver), released via cystic duct → common bile duct → duodenum (sphincter of Oddi). CCK from duodenum signals gallbladder contraction when fats arrive.", example: "Fatty meals triggered the patient's biliary colic — gallstones obstructed the cystic duct as the gallbladder contracted." },

  // ── Upper GI Disorders ───────────────────────────────────────
  { term: "GERD (Gastroesophageal Reflux Disease)", type: "concept", category: "upper-gi", meaning: "Reflux of gastric contents into esophagus from incompetent LES → heartburn, regurgitation, dysphagia. Risk factors: obesity, hiatal hernia, pregnancy. Complications: esophagitis, Barrett esophagus, adenocarcinoma. Treated with PPIs.", example: "The patient's burning retrosternal pain after meals and at night improved dramatically with omeprazole — classic GERD response to PPI." },
  { term: "Peptic Ulcer Disease", type: "concept", category: "upper-gi", meaning: "Mucosal break in stomach (gastric ulcer — pain WITH eating) or duodenum (duodenal — pain RELIEVED by eating, 2–3 hours postprandial). Caused by H. pylori (~90%) or NSAIDs. Treated with PPI + H. pylori eradication (triple therapy).", example: "The patient's duodenal ulcer with positive urea breath test was treated with PPI plus amoxicillin and clarithromycin — H. pylori eradication." },
  { term: "H. pylori Infection", type: "concept", category: "upper-gi", meaning: "Gram-negative spiral urease-producing bacterium colonizing gastric mucosa. Causes most peptic ulcers and gastric MALT lymphoma. Diagnosed by urea breath test, stool antigen, biopsy. Treated with triple therapy (PPI + 2 antibiotics).", example: "The patient's H. pylori-positive ulcer was eradicated with PPI, amoxicillin, and clarithromycin for 14 days; follow-up urea breath test confirmed cure." },
  { term: "Esophageal Varices", type: "concept", category: "upper-gi", meaning: "Dilated submucosal veins at the GE junction from portal hypertension (cirrhosis); risk of massive bleeding — medical emergency. Prophylaxis: nonselective beta-blocker. Acute bleed: octreotide, band ligation, TIPS for refractory.", example: "The cirrhotic patient's hematemesis was caused by ruptured esophageal varices; band ligation during emergent EGD controlled the bleeding." },
  { term: "Gastritis", type: "concept", category: "upper-gi", meaning: "Inflammation of gastric mucosa; acute (NSAIDs, alcohol, stress) or chronic (H. pylori, autoimmune — pernicious anemia). Symptoms: epigastric pain, nausea. Diagnosed by endoscopy with biopsy.", example: "Chronic alcohol use caused the patient's erythematous gastric mucosa on EGD — chronic gastritis; PPI was started and abstinence advised." },

  // ── Lower GI Disorders ───────────────────────────────────────
  { term: "Crohn Disease", type: "concept", category: "lower-gi", meaning: "Transmural inflammation anywhere mouth-to-anus, with skip lesions; terminal ileum most common. Cobblestone mucosa, granulomas, fistulas, strictures. Diarrhea, abdominal pain, weight loss, perianal disease. Treated with mesalamine, steroids, biologics.", example: "The patient's terminal ileitis on colonoscopy with skip lesions and granulomas confirmed Crohn disease; infliximab achieved remission." },
  { term: "Ulcerative Colitis", type: "concept", category: "lower-gi", meaning: "Continuous mucosal inflammation starting at rectum, extending proximally; limited to colon. Bloody diarrhea, tenesmus, urgency. Toxic megacolon is severe complication. Treated with mesalamine, steroids, biologics; colectomy is curative.", example: "The patient's continuous rectosigmoid ulceration with crypt abscesses on biopsy confirmed ulcerative colitis; mesalamine maintained remission." },
  { term: "Irritable Bowel Syndrome (IBS)", type: "concept", category: "lower-gi", meaning: "Functional GI disorder with abdominal pain related to defecation, altered bowel habits (IBS-D, IBS-C, IBS-M). Rome IV criteria; no structural cause. Treated with diet (low FODMAP), fiber, antispasmodics, SSRIs.", example: "The patient's chronic abdominal pain relieved by defecation with alternating diarrhea and constipation met Rome IV criteria for IBS." },
  { term: "Diverticular Disease", type: "concept", category: "lower-gi", meaning: "Diverticulosis: outpouchings of colon (usually sigmoid), often asymptomatic. Diverticulitis: inflammation/infection of diverticula — LLQ pain, fever, leukocytosis. Treated with antibiotics; surgery for complications (abscess, perforation).", example: "The patient's LLQ pain, fever, and CT showing sigmoid diverticulitis with peri-colonic stranding were managed with ciprofloxacin + metronidazole." },
  { term: "Appendicitis", type: "concept", category: "lower-gi", meaning: "Inflammation of vermiform appendix from luminal obstruction (fecalith, lymphoid hyperplasia). Periumbilical pain → RLQ (McBurney point), fever, anorexia, leukocytosis. Surgical emergency — appendectomy.", example: "The patient's pain migration from umbilicus to RLQ with rebound tenderness at McBurney point led to laparoscopic appendectomy; pathology confirmed acute appendicitis." },
  { term: "Colorectal Cancer", type: "concept", category: "lower-gi", meaning: "Adenocarcinoma from adenoma-carcinoma sequence (APC pathway). Screening colonoscopy every 10 yrs starting age 45. Symptoms: change in bowel habits, hematochezia (left-sided), iron-deficiency anemia (right-sided), obstruction.", example: "The patient's iron-deficiency anemia and positive FOBT led to colonoscopy showing a cecal mass — right-sided colon cancer." },
  { term: "Hemorrhoids", type: "concept", category: "lower-gi", meaning: "Dilated rectal/anal veins. Internal: above dentate line, painless bleeding, prolapse. External: below dentate line, painful (rich somatic innervation), can thrombose. Treated with fiber, sitz baths, banding, hemorrhoidectomy.", example: "The patient's bright red blood per rectum without pain and prolapse on straining indicated grade III internal hemorrhoids; rubber band ligation was performed." },

  // ── Hepatobiliary & Pancreas ─────────────────────────────────
  { term: "Hepatitis (Viral)", type: "concept", category: "liver-pancreas", meaning: "HAV (fecal-oral, acute only). HBV (blood/sex, acute + chronic, vaccine). HCV (blood, mostly chronic, curable with DAAs). HDV (requires HBV). HEV (fecal-oral, severe in pregnancy). Diagnosed by serology.", example: "The patient's positive HCV antibody and viral load were treated with 12 weeks of sofosbuvir/velpatasvir — cured with direct-acting antivirals." },
  { term: "Cirrhosis", type: "concept", category: "liver-pancreas", meaning: "Irreversible hepatic fibrosis with regenerative nodules; causes: alcohol, HBV/HCV, NAFLD, autoimmune, hemochromatosis. Manifestations: portal HTN (varices, ascites), synthetic failure (low albumin, coagulopathy), encephalopathy.", example: "The patient's alcoholic cirrhosis presented with ascites, jaundice, esophageal varices, and hepatic encephalopathy — decompensated end-stage liver disease." },
  { term: "Hepatic Encephalopathy", type: "concept", category: "liver-pancreas", meaning: "Neuropsychiatric manifestation of liver failure from ammonia and other toxins reaching the brain; presents as confusion, asterixis, altered consciousness → coma. Treated with lactulose (traps ammonia in colon) and rifaximin.", example: "The cirrhotic patient's confusion and asterixis with elevated ammonia were treated with lactulose; mental status normalized within 24 hours." },
  { term: "Cholelithiasis and Cholecystitis", type: "concept", category: "liver-pancreas", meaning: "Cholelithiasis: gallstones (often cholesterol). Cholecystitis: inflammation when stone obstructs cystic duct — RUQ pain, Murphy sign, fever, leukocytosis. Diagnosed by ultrasound. Treated with antibiotics and cholecystectomy.", example: "The patient's RUQ pain, positive Murphy sign, and ultrasound showing gallstones with wall thickening confirmed acute cholecystitis; laparoscopic cholecystectomy was performed." },
  { term: "Acute Pancreatitis", type: "concept", category: "liver-pancreas", meaning: "Inflammation from pancreatic enzyme autodigestion; main causes: gallstones, alcohol ('I GET SMASHED' mnemonic). Severe epigastric pain radiating to back, lipase >3× normal. Ranson criteria predict severity. Treated supportively (NPO, fluids, pain).", example: "The patient's epigastric pain radiating to the back with lipase 1800 U/L confirmed acute pancreatitis from gallstones; he was made NPO and aggressively fluid resuscitated." },
  { term: "Inflammatory Markers in IBD", type: "concept", category: "liver-pancreas", meaning: "Fecal calprotectin (specific for intestinal inflammation, differentiates IBD from IBS). C-reactive protein (CRP), ESR (systemic inflammation). Used for disease activity and treatment monitoring.", example: "The patient's elevated fecal calprotectin of 850 µg/g indicated active intestinal inflammation — colonoscopy confirmed Crohn flare." },
  { term: "Bilirubin Metabolism and Jaundice", type: "concept", category: "liver-pancreas", meaning: "Heme → unconjugated (indirect) bilirubin → conjugated by liver → excreted in bile. Pre-hepatic jaundice (hemolysis): high indirect. Hepatic: both. Post-hepatic (obstruction): high direct + pale stools + dark urine.", example: "The patient's painless jaundice with elevated direct bilirubin, dark urine, and pale stools suggested obstructive jaundice — CT confirmed pancreatic head mass." },
];'''
m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
html = html[:m.start()] + TERMS_JS + html[m.end():]
CAT = """const categoryLabel = c => ({
  'anatomy':        'GI Anatomy & Physiology',
  'upper-gi':       'Upper GI Disorders',
  'lower-gi':       'Lower GI Disorders',
  'liver-pancreas': 'Hepatobiliary & Pancreas',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'gastroenterology';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>', '<title>HOSA Prep Hub — Gastroenterology</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>', '<h1>Gastro<em>enterology</em>.</h1>', 1)
html = html.replace('A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
                    'A study companion for GI anatomy and physiology, upper GI disorders, lower GI disorders, and hepatobiliary and pancreatic disease — built for HOSA competitors.', 1)
html = html.replace('//  DATA — HOSA Emergency Medical Science', '//  DATA — HOSA Gastroenterology', 1)
with open(DST, 'w', encoding='utf-8') as f: f.write(html)
print(f'Wrote {DST} — {TERMS_JS.count("{ term:")} terms')
