#!/usr/bin/env python3
"""Generate healthcare-systems.html from dental-science.html template."""
import os, re
BASE = '/home/user/hosa-prep-hub'
SRC, DST = os.path.join(BASE, 'dental-science.html'), os.path.join(BASE, 'healthcare-systems.html')
with open(SRC, 'r', encoding='utf-8') as f: html = f.read()
TERMS_JS = '''const TERMS = [
  // ── US Healthcare Structure ──────────────────────────────────
  { term: "US Healthcare Spending", type: "concept", category: "structure", meaning: "US spends ~18% of GDP on healthcare (~$4.5 trillion, ~$13,500/person) — highest in the world. Outcomes (life expectancy, infant mortality) lag peer nations. Major drivers: administrative costs, drug prices, technology, specialist care.", example: "The US spends nearly twice as much per capita as comparable wealthy nations but has lower life expectancy — a key motivation for healthcare reform." },
  { term: "Levels of Care", type: "concept", category: "structure", meaning: "Primary care: first-contact, ongoing comprehensive (family medicine, pediatrics, internal medicine). Secondary: specialists (cardiology, dermatology). Tertiary: complex hospital-based (cardiac surgery, cancer). Quaternary: highly specialized (transplant, experimental).", example: "The patient's diabetes was managed by primary care, with cardiology consultation (secondary) and eventual coronary artery bypass surgery (tertiary)." },
  { term: "Healthcare Provider Types", type: "concept", category: "structure", meaning: "Physicians (MD, DO), Advanced Practice Providers (NP, PA, CRNA, CNM), Nurses (RN, LPN), Allied Health (RT, PT, OT, SLP, RD, MA), Pharmacists, Mental Health (psychologist, social worker, counselor). Each with distinct education and scope.", example: "The patient's care team included a primary care MD, NP for routine visits, RN for diabetes education, RD for nutrition, and pharmacist for medication management." },
  { term: "Hospital Types", type: "concept", category: "structure", meaning: "Acute care (short-term medical/surgical). Critical access (rural, ≤25 beds). Teaching/academic (residents, complex care). Specialty (cancer, children, psychiatric, rehabilitation). For-profit vs nonprofit. Public (VA, county) vs private.", example: "The patient was transferred from the local community hospital to the academic medical center for advanced cardiac surgery." },

  // ── Insurance & Payment ──────────────────────────────────────
  { term: "Medicare", type: "concept", category: "insurance", meaning: "Federal insurance for ages ≥65, ESRD, and some disabilities. Four parts: A (hospital), B (outpatient), C (Medicare Advantage — private), D (drugs). Funded by payroll taxes and premiums. Covers ~67 million Americans.", example: "The 67-year-old's Medicare Part A covered her hospital admission; Part B covered the cardiologist visits and Part D her medications." },
  { term: "Medicaid", type: "concept", category: "insurance", meaning: "Joint federal-state insurance for low-income individuals. State-administered with federal matching. Eligibility and benefits vary by state. ACA expansion extended to adults <138% FPL in expansion states. Covers ~84 million Americans.", example: "The low-income family enrolled in Medicaid after the state's ACA expansion — gaining comprehensive coverage including preventive care." },
  { term: "Private Insurance", type: "concept", category: "insurance", meaning: "Employer-sponsored (most common, ~50% of Americans), individual marketplace plans, COBRA continuation. Plan types: HMO (in-network only, lower cost), PPO (out-of-network coverage, higher cost), EPO, POS, HDHP with HSA.", example: "The employer-sponsored PPO allowed the patient to see any specialist without referral but at higher cost than the HMO option." },
  { term: "ACA (Affordable Care Act, 2010)", type: "concept", category: "insurance", meaning: "Expanded coverage via Medicaid expansion (in adopting states), health insurance marketplaces, subsidies, pre-existing condition protection, essential health benefits, no lifetime limits, dependents covered to age 26, preventive services without cost-sharing.", example: "The patient with diabetes obtained marketplace coverage with subsidies under the ACA — no longer denied for pre-existing condition." },
  { term: "Uninsured and Underinsured", type: "concept", category: "insurance", meaning: "~27 million Americans uninsured (~8%); higher rates in non-expansion states. Underinsured: have coverage but high cost-sharing causing care delays. Disparities by race, income, immigration status. Worse health outcomes, mortality, financial hardship.", example: "The uninsured patient delayed care for chest pain due to cost concerns — presenting in cardiogenic shock from preventable MI." },
  { term: "Out-of-Pocket Costs", type: "concept", category: "insurance", meaning: "Premium (monthly fee), deductible (paid before insurance kicks in), copayment (fixed amount per service), coinsurance (% of cost after deductible), out-of-pocket maximum (annual cap). Drives access barriers, especially for chronic care.", example: "The patient's $5000 deductible and 20% coinsurance for the new oncology drug caused her to delay treatment despite insurance coverage." },
  { term: "Value-Based Care", type: "concept", category: "insurance", meaning: "Payment models tying reimbursement to outcomes and quality rather than volume (fee-for-service). Examples: ACOs, bundled payments, capitation, pay-for-performance. Aims to improve quality and reduce costs.", example: "The ACO's value-based contract rewarded the practice for keeping diabetics' A1c controlled and reducing avoidable hospitalizations." },

  // ── Quality, Policy & Public Health ──────────────────────────
  { term: "Quality Measures", type: "concept", category: "quality-policy", meaning: "Process measures (was the right care given — e.g., aspirin in MI). Outcome measures (results — mortality, readmission). Patient experience (satisfaction surveys). Reported via HEDIS, CMS Star Ratings, Hospital Compare. Drive value-based payment.", example: "The hospital's 30-day readmission rate after heart failure was a CMS outcome measure linked to Medicare reimbursement penalties." },
  { term: "Patient Safety and Joint Commission", type: "concept", category: "quality-policy", meaning: "The Joint Commission accredits hospitals; sets National Patient Safety Goals annually (identify patients correctly, improve communication, prevent infections, prevent surgical errors, reduce falls). Required for Medicare/Medicaid participation.", example: "The hospital implemented two-identifier verification, time-outs before procedures, and barcode medication administration per Joint Commission patient safety goals." },
  { term: "Healthcare Disparities", type: "concept", category: "quality-policy", meaning: "Differences in health/healthcare access and outcomes based on race, ethnicity, socioeconomic status, gender, geography. Black maternal mortality 3× white; rural areas lower access; LGBTQ+ patients face discrimination. Address via cultural competence, social determinants, policy.", example: "The healthcare system's targeted outreach in underserved neighborhoods reduced disparities in colorectal cancer screening between racial groups." },
  { term: "Social Determinants of Health (SDOH)", type: "concept", category: "quality-policy", meaning: "Non-medical factors shaping health: economic stability, education, neighborhood, food security, social context, access to care. Account for 80%+ of health outcomes. Healthcare increasingly screens for SDOH and connects patients to community resources.", example: "The patient's poorly controlled diabetes was traced to food insecurity; SNAP enrollment and food bank referral improved both nutrition and glycemic control." },
  { term: "Public Health vs Medicine", type: "concept", category: "quality-policy", meaning: "Medicine: individual patient diagnosis and treatment. Public health: population-level prevention, surveillance, policy, environment. CDC, state and local health departments. Examples: vaccination programs, smoking cessation, infectious disease tracking, food safety.", example: "The COVID-19 pandemic highlighted public health functions: surveillance, testing, contact tracing, vaccination campaigns — distinct from individual care." },
  { term: "Population Health Management", type: "concept", category: "quality-policy", meaning: "Proactive care of defined patient populations using risk stratification, gap analysis, targeted interventions. Examples: identifying diabetics with elevated A1c for outreach, offering colorectal cancer screening to all eligible patients. Aligned with value-based care.", example: "The ACO's population health team contacted all unscreened diabetics — increasing eye exam completion from 45% to 78% in one year." },
  { term: "Health Literacy", type: "concept", category: "quality-policy", meaning: "Capacity to obtain, understand, and use health information. ~36% of US adults have basic or below-basic health literacy. Affects medication adherence, chronic disease management, navigating system. Address with plain language, teach-back, visual aids, multilingual resources.", example: "Using teach-back technique, the nurse confirmed the patient understood his diabetes self-management plan — bridging health literacy gaps." },
  { term: "Bioethics and Informed Consent", type: "concept", category: "quality-policy", meaning: "Four principles: autonomy (patient self-determination), beneficence (do good), nonmaleficence (do no harm), justice (fairness). Informed consent: capacity, voluntariness, disclosure (risks, benefits, alternatives), understanding. Foundational to ethical practice.", example: "Before the surgery the surgeon obtained informed consent — discussing the procedure, risks, benefits, alternatives, and consequences of refusal." },
  { term: "End-of-Life Decisions", type: "concept", category: "quality-policy", meaning: "Advance directives, living will, durable POA for healthcare, POLST, DNR, hospice, palliative care. Reflect patient values; family/surrogate decisions when capacity lost. Increasingly addressed earlier in serious illness through advance care planning.", example: "The patient completed POLST specifying no CPR and comfort-focused care — preferences followed across hospital and home settings." },
];'''
m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
html = html[:m.start()] + TERMS_JS + html[m.end():]
CAT = """const categoryLabel = c => ({
  'structure':      'US Healthcare Structure',
  'insurance':      'Insurance & Payment',
  'quality-policy': 'Quality, Policy & Public Health',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'healthcare-systems';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>', '<title>HOSA Prep Hub — Healthcare Systems &amp; Policy</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>', '<h1>Healthcare<br><em>Systems</em>.</h1>', 1)
html = html.replace('A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
                    'A study companion for US healthcare structure, insurance and payment systems, and healthcare quality and policy and public health — built for HOSA competitors.', 1)
html = html.replace('//  DATA — HOSA Emergency Medical Science', '//  DATA — HOSA Healthcare Systems', 1)
with open(DST, 'w', encoding='utf-8') as f: f.write(html)
print(f'Wrote {DST} — {TERMS_JS.count("{ term:")} terms')
