#!/usr/bin/env python3
"""Generate respiratory-therapy.html from dental-science.html template."""
import os, re

BASE = '/home/user/hosa-prep-hub'
SRC  = os.path.join(BASE, 'dental-science.html')
DST  = os.path.join(BASE, 'respiratory-therapy.html')

with open(SRC, 'r', encoding='utf-8') as f:
    html = f.read()

TERMS_JS = '''const TERMS = [
  // ── Pulmonary Anatomy & Physiology ───────────────────────────
  { term: "Conducting vs Respiratory Zones", type: "concept", category: "anatomy-physiology", meaning: "Conducting zone (anatomic dead space, ~150 mL): nose → larynx → trachea → bronchi → bronchioles → terminal bronchioles; warms, humidifies, filters air, no gas exchange. Respiratory zone: respiratory bronchioles → alveolar ducts → alveoli; gas exchange occurs here.", example: "The patient's anatomic dead space of 150 mL was bypassed by a tracheostomy, improving alveolar ventilation efficiency." },
  { term: "Alveolar-Capillary Membrane", type: "concept", category: "anatomy-physiology", meaning: "The thin barrier (0.2–0.5 µm) across which O2 and CO2 diffuse, composed of alveolar Type I epithelium, fused basement membranes, and capillary endothelium. Pulmonary edema, fibrosis, and ARDS thicken it, impairing gas exchange.", example: "ARDS thickened the alveolar-capillary membrane with edema and inflammation, causing severe hypoxemia despite high FiO2." },
  { term: "Surfactant", type: "concept", category: "anatomy-physiology", meaning: "A phospholipid (mainly dipalmitoylphosphatidylcholine) produced by Type II pneumocytes that lowers alveolar surface tension, preventing collapse on expiration. Deficiency causes neonatal RDS and contributes to atelectasis.", example: "The 28-week premature neonate's surfactant deficiency caused respiratory distress; intratracheal surfactant replacement rapidly improved oxygenation." },
  { term: "Tidal Volume and Minute Ventilation", type: "concept", category: "anatomy-physiology", meaning: "Tidal volume (VT): air moved per breath (~500 mL normal). Minute ventilation (VE) = VT × RR. Alveolar ventilation (VA) = (VT − dead space) × RR; only VA produces gas exchange.", example: "With VT 400 mL and RR 20: VE = 8 L/min, but VA only 5 L/min after subtracting 150 mL dead space per breath." },
  { term: "Lung Volumes and Capacities", type: "concept", category: "anatomy-physiology", meaning: "Tidal (VT), Inspiratory Reserve (IRV), Expiratory Reserve (ERV), Residual (RV). Capacities: Inspiratory (IRV+VT), Functional Residual (ERV+RV — air remaining after normal expiration), Vital (IRV+VT+ERV), Total Lung Capacity (all four).", example: "The COPD patient's increased RV and FRC (air trapping) but reduced VC reflected obstructive lung disease physiology." },
  { term: "FEV1/FVC Ratio", type: "concept", category: "anatomy-physiology", meaning: "Spirometric ratio of Forced Expiratory Volume in 1 second to Forced Vital Capacity; normal >70%. Obstructive disease (asthma, COPD): <70%. Restrictive disease: normal or elevated ratio with reduced lung volumes.", example: "The patient's FEV1/FVC of 58% confirmed obstruction; the low FEV1 of 45% predicted classified COPD as severe (GOLD Stage 3)." },
  { term: "Ventilation/Perfusion (V/Q) Matching", type: "concept", category: "anatomy-physiology", meaning: "Normal V/Q ≈ 0.8; mismatch causes hypoxemia. V/Q > 1 (dead space, e.g., PE — ventilation without perfusion). V/Q < 1 (shunt, e.g., pneumonia, atelectasis — perfusion without ventilation; doesn't correct with O2).", example: "The patient's persistent hypoxemia despite 100% FiO2 indicated true shunt physiology — likely from severe pneumonia consolidation." },
  { term: "Oxyhemoglobin Dissociation Curve", type: "concept", category: "anatomy-physiology", meaning: "Sigmoid curve relating PaO2 to SaO2; SaO2 of 50% at PaO2 27 mmHg (P50). Right shift (lower affinity): ↑CO2, ↓pH, ↑temp, ↑2,3-DPG — favors tissue O2 release. Left shift: opposite — impairs delivery.", example: "Acidosis from sepsis shifted the curve right, enhancing O2 unloading to hypoxic tissues despite low PaO2." },

  // ── Pulmonary Pathology ──────────────────────────────────────
  { term: "Asthma", type: "concept", category: "pathology", meaning: "Reversible airway hyperresponsiveness, inflammation, and bronchoconstriction; triggered by allergens, exercise, cold air, viral URIs. Symptoms: wheezing, dyspnea, cough, chest tightness. PFTs: FEV1/FVC < 70% reversible with bronchodilator (≥12% improvement).", example: "The patient's wheezing resolved and FEV1 improved by 18% after albuterol — diagnostic of asthma per reversibility criteria." },
  { term: "COPD (Emphysema vs Chronic Bronchitis)", type: "concept", category: "pathology", meaning: "Emphysema: destruction of alveolar walls → 'pink puffer' (thin, hyperventilating, less hypoxic). Chronic bronchitis: productive cough ≥3 mo for 2 yr → 'blue bloater' (cyanotic, hypoxic). Both: progressive, irreversible airflow obstruction.", example: "The chronic smoker's barrel chest, prolonged expiration, and FEV1/FVC of 55% confirmed COPD; his thin habitus suggested emphysematous predominance." },
  { term: "Pneumonia", type: "concept", category: "pathology", meaning: "Lower respiratory infection with alveolar consolidation. Community-acquired: S. pneumoniae most common; M. pneumoniae and Legionella also frequent. Healthcare-associated: more resistant organisms (Pseudomonas, MRSA). Diagnosed by clinical signs + CXR infiltrate.", example: "The patient's right lower lobe consolidation on CXR, fever, productive cough, and rusty sputum suggested S. pneumoniae community-acquired pneumonia." },
  { term: "Acute Respiratory Distress Syndrome (ARDS)", type: "concept", category: "pathology", meaning: "Acute non-cardiogenic pulmonary edema from increased alveolar-capillary permeability; bilateral infiltrates, PaO2/FiO2 ≤ 300, no cardiogenic cause. Treated with low-tidal-volume ventilation (6 mL/kg PBW), prone positioning, PEEP.", example: "The septic patient's bilateral infiltrates and PaO2/FiO2 of 95 mmHg on 60% FiO2 confirmed severe ARDS; low-tidal-volume ventilation was initiated." },
  { term: "Pulmonary Embolism (PE)", type: "concept", category: "pathology", meaning: "Obstruction of pulmonary arteries usually by DVT-origin thrombus; causes sudden dyspnea, pleuritic pain, hypoxemia. Diagnosed by CT pulmonary angiography. Treated with anticoagulation; thrombolytics for massive PE with hemodynamic instability.", example: "The post-op patient's sudden dyspnea, tachycardia, and SpO2 drop prompted CTPA, which showed bilateral segmental PE; heparin was started." },
  { term: "Pneumothorax", type: "concept", category: "pathology", meaning: "Air in the pleural space causing lung collapse. Spontaneous (tall thin males), traumatic, iatrogenic (after central line, biopsy). Tension pneumothorax (mediastinal shift, hemodynamic collapse) is a life-threatening emergency requiring immediate needle decompression.", example: "After tall lean patient sudden chest pain and dyspnea: tracheal deviation to right, absent left breath sounds — tension pneumothorax decompressed with 14g needle at 2nd ICS midclavicular." },
  { term: "Cystic Fibrosis (Pulmonary)", type: "concept", category: "pathology", meaning: "Autosomal recessive CFTR defect → thick mucus, impaired ciliary clearance, chronic bacterial colonization (Pseudomonas aeruginosa, Staph aureus), bronchiectasis, progressive obstruction. Airway clearance and CFTR modulators (ivacaftor/elexacaftor) are central to management.", example: "The 19-year-old CF patient's chronic Pseudomonas colonization and frequent exacerbations were managed with daily airway clearance therapy and elexacaftor-tezacaftor-ivacaftor." },

  // ── Patient Assessment & Diagnostics ─────────────────────────
  { term: "Arterial Blood Gas (ABG)", type: "concept", category: "assessment", meaning: "Measures pH (7.35–7.45), PaCO2 (35–45 mmHg), PaO2 (80–100), HCO3 (22–26), SaO2 (>95%). Diagnoses acid-base disorders and respiratory failure (Type I: PaO2 <60; Type II: PaCO2 >50).", example: "ABG: pH 7.21, PaCO2 65, PaO2 55, HCO3 26 — acute respiratory acidosis with hypoxemic-hypercapnic (Type II) respiratory failure." },
  { term: "Pulse Oximetry (SpO2)", type: "concept", category: "assessment", meaning: "Non-invasive measure of arterial O2 saturation via red/infrared light absorption; normal ≥95%. Unreliable in poor perfusion, methemoglobinemia, CO poisoning (falsely normal), severe anemia, dark nail polish, motion.", example: "The CO-poisoning patient's SpO2 of 98% was falsely reassuring; carboxyhemoglobin co-oximetry revealed 35% COHb." },
  { term: "Capnography (End-Tidal CO2)", type: "concept", category: "assessment", meaning: "Continuous measurement of exhaled CO2; ETCO2 normally 35–45 mmHg. Confirms ET tube placement, monitors ventilation in sedation/ICU, detects PE (low ETCO2 from increased dead space) and cardiac arrest (sudden drop with loss of perfusion).", example: "After intubation, a sustained ETCO2 of 36 mmHg confirmed tracheal placement; sudden drop to 5 mmHg during transport signaled cardiac arrest." },
  { term: "Chest Auscultation", type: "concept", category: "assessment", meaning: "Listening to breath sounds: vesicular (normal), bronchial (consolidation), wheezing (asthma, COPD), crackles/rales (pulmonary edema, pneumonia, fibrosis), rhonchi (secretions), pleural friction rub (pleuritis), stridor (upper airway obstruction).", example: "Fine inspiratory crackles at the lung bases were consistent with the diagnosis of pulmonary edema in the heart failure patient." },
  { term: "Peak Expiratory Flow Rate (PEFR)", type: "concept", category: "assessment", meaning: "Maximum airflow rate during forced expiration, measured by peak flow meter; used to monitor asthma. Green zone ≥80% personal best, yellow 50–79%, red <50% (severe — emergency).", example: "The asthma patient's PEFR of 180 (40% personal best) placed her in the red zone, indicating severe exacerbation requiring ED evaluation." },
  { term: "Chest X-Ray Findings", type: "concept", category: "assessment", meaning: "Pneumonia: lobar or patchy consolidation, air bronchograms. CHF: cardiomegaly, cephalization, Kerley B lines, pleural effusion. Pneumothorax: visceral pleural line, no markings beyond. ARDS: bilateral diffuse infiltrates.", example: "The bilateral diffuse 'whiteout' on the patient's CXR was consistent with ARDS; cardiac silhouette was normal, ruling out cardiogenic edema." },

  // ── Oxygen Therapy & Airway Management ───────────────────────
  { term: "Oxygen Delivery Devices", type: "concept", category: "therapy", meaning: "Nasal cannula: 1–6 L/min (24–44% FiO2). Simple mask: 5–10 L/min (35–55%). Venturi: precise FiO2 24–50%. Non-rebreather: 10–15 L/min (~80–95%). High-flow nasal cannula (HFNC): up to 60 L/min, heated/humidified, PEEP effect.", example: "The hypoxemic COPD patient required Venturi mask at 28% FiO2 to maintain SpO2 88–92% without suppressing hypoxic drive." },
  { term: "Bronchodilators (SABA, LABA, SAMA, LAMA)", type: "concept", category: "therapy", meaning: "Short-acting β2 agonists (albuterol — rescue). Long-acting β2 agonists (salmeterol, formoterol — maintenance). Short-acting muscarinic antagonist (ipratropium). Long-acting muscarinic antagonist (tiotropium). LABA + ICS, LABA+LAMA combos for asthma/COPD.", example: "The asthmatic was on inhaled corticosteroid plus salmeterol daily for maintenance and albuterol as rescue during exacerbations." },
  { term: "Inhaled Corticosteroids (ICS)", type: "concept", category: "therapy", meaning: "Anti-inflammatory inhaled steroids (fluticasone, budesonide) are first-line controllers for persistent asthma; reduce airway inflammation and hyperresponsiveness. Side effects: oral candidiasis (prevent by rinsing mouth), dysphonia.", example: "Daily inhaled fluticasone reduced the asthmatic's exacerbations by 60%; rinsing the mouth after each dose prevented thrush." },
  { term: "Non-Invasive Ventilation (BiPAP/CPAP)", type: "concept", category: "therapy", meaning: "BiPAP: separate inspiratory and expiratory pressures, supports both ventilation and oxygenation; used for COPD exacerbation and CHF. CPAP: constant pressure for oxygenation and OSA. Avoid in altered mental status, vomiting, hemodynamic instability.", example: "The COPD exacerbation patient was placed on BiPAP 12/5 — PaCO2 fell from 78 to 55 within 4 hours, avoiding intubation." },
  { term: "Mechanical Ventilation Modes", type: "concept", category: "therapy", meaning: "Assist-Control (AC): set RR + VT, ventilator delivers full breath whenever triggered. SIMV: synchronized mandatory breaths with spontaneous breaths in between. Pressure Support (PSV): augments patient-initiated breaths; used for weaning.", example: "The patient was weaned from AC to PSV 10/PEEP 5, demonstrating adequate spontaneous breathing before extubation." },
  { term: "PEEP and Recruitment", type: "concept", category: "therapy", meaning: "Positive End-Expiratory Pressure prevents alveolar collapse at end-expiration, recruiting atelectatic lung and improving oxygenation; standard 5 cm H2O, higher in ARDS. Excessive PEEP causes barotrauma and reduced venous return.", example: "Increasing PEEP from 8 to 14 in the ARDS patient improved PaO2/FiO2 from 95 to 165 by recruiting collapsed alveoli." },
  { term: "Endotracheal Intubation", type: "concept", category: "therapy", meaning: "Placement of an ET tube through the vocal cords for mechanical ventilation; confirmed by ETCO2 waveform, bilateral breath sounds, and CXR (tip 2–4 cm above carina). RSI with sedation + paralytic is standard for emergent intubation.", example: "RSI with etomidate and succinylcholine allowed atraumatic intubation; placement was confirmed by sustained ETCO2 capnography and bilateral chest rise." },
  { term: "Airway Clearance Techniques", type: "concept", category: "therapy", meaning: "Methods to mobilize secretions in CF, bronchiectasis, neuromuscular disease: postural drainage + percussion, active cycle of breathing, autogenic drainage, oscillating PEP (Acapella, Flutter), high-frequency chest wall oscillation (vest).", example: "The CF patient performed 30 minutes of vest therapy twice daily plus nebulized dornase alfa to maintain airway clearance." },
  { term: "Suctioning (Open vs Closed)", type: "concept", category: "therapy", meaning: "Removal of secretions from airway. Open: disconnect ventilator, insert catheter — risks contamination and desaturation. Closed (in-line): suction without disconnection — preferred for high PEEP or infectious patients. Limit to 10 seconds; pre-oxygenate.", example: "Closed in-line suctioning was used in the COVID-19 patient on PEEP 14 to avoid derecruitment and aerosol generation during disconnection." },
];'''

m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
if not m: raise SystemExit('TERMS not found')
html = html[:m.start()] + TERMS_JS + html[m.end():]

CAT = """const categoryLabel = c => ({
  'anatomy-physiology': 'Anatomy & Physiology',
  'pathology':          'Pulmonary Pathology',
  'assessment':         'Assessment & Diagnostics',
  'therapy':            'Oxygen & Airway Therapy',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)

html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'respiratory-therapy';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>',
                    '<title>HOSA Prep Hub — Respiratory Therapy</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>',
                    '<h1>Respiratory<br><em>Therapy</em>.</h1>', 1)
html = html.replace(
    'A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
    'A study companion for pulmonary anatomy and physiology, lung pathology, respiratory assessment, and oxygen and airway therapy — built for HOSA competitors.',
    1
)
html = html.replace('//  DATA — HOSA Emergency Medical Science',
                    '//  DATA — HOSA Respiratory Therapy', 1)

with open(DST, 'w', encoding='utf-8') as f:
    f.write(html)

count = TERMS_JS.count('{ term:')
print(f'Wrote {DST} — {count} terms')
