#!/usr/bin/env python3
"""Generate pediatrics.html from dental-science.html template."""
import os, re
BASE = '/home/user/hosa-prep-hub'
SRC, DST = os.path.join(BASE, 'dental-science.html'), os.path.join(BASE, 'pediatrics.html')
with open(SRC, 'r', encoding='utf-8') as f: html = f.read()
TERMS_JS = '''const TERMS = [
  // ── Growth, Development & Well Child ─────────────────────────
  { term: "Growth Charts", type: "concept", category: "growth-development", meaning: "WHO charts for 0-2 years; CDC for 2-20. Plot weight, length/height, head circumference (under 2), BMI (over 2). Crossing two percentiles down is concerning for failure to thrive.", example: "The 9-month-old's weight dropped from 25th to 5th percentile in 3 months — failure to thrive prompted nutritional and medical workup." },
  { term: "Developmental Milestones", type: "concept", category: "growth-development", meaning: "2 mo: social smile, head up. 4 mo: rolls. 6 mo: sits unsupported, transfers objects. 9 mo: pulls to stand, pincer grasp. 12 mo: walks, says 1-3 words. 18 mo: runs, 10-25 words. 2 yr: 2-word phrases.", example: "The 18-month-old who could walk and use 15 words was developing appropriately for language and gross motor milestones." },
  { term: "APGAR Score", type: "concept", category: "growth-development", meaning: "Newborn assessment at 1 and 5 min: Appearance (color), Pulse, Grimace (reflex), Activity (tone), Respirations. Each scored 0-2, max 10. <7 at 5 min suggests neonatal depression.", example: "The newborn's APGAR was 8 at 1 min (1 off for color), 9 at 5 min — reassuring transition to extrauterine life." },
  { term: "Newborn Screening", type: "concept", category: "growth-development", meaning: "Universal heel-stick blood spot 24-48 hr after birth screening for treatable disorders: PKU, congenital hypothyroidism, CF, SCD, MCAD, galactosemia, MSUD, plus state-specific. Early intervention prevents ID and death.", example: "The newborn screen flagged elevated TSH; confirmatory testing diagnosed congenital hypothyroidism and levothyroxine began by week 2." },
  { term: "Pediatric Vital Signs (Normal Ranges)", type: "concept", category: "growth-development", meaning: "Newborn: HR 100-180, RR 30-60, SBP 60-90. Infant: HR 100-160, RR 30-50. Toddler: HR 90-140, RR 24-40. School age: HR 75-115, RR 18-30. Adolescent approach adult ranges. Vary by age!", example: "The 6-month-old's HR of 140 and RR of 30 fell within normal infant ranges — no intervention indicated." },
  { term: "Well-Child Visit Schedule", type: "concept", category: "growth-development", meaning: "AAP: visits at 3-5 days, 1 mo, 2, 4, 6, 9, 12, 15, 18, 24, 30 mo, then annually. Each includes growth, development, exam, anticipatory guidance, screening, vaccines.", example: "The 12-month visit included MMR/varicella vaccines, hemoglobin and lead screening, and anticipatory guidance about cup transition." },

  // ── Pediatric Vaccines & Infections ──────────────────────────
  { term: "Childhood Vaccine Schedule", type: "concept", category: "vaccines-infections", meaning: "HBV: birth. 2,4,6 mo: DTaP, IPV, Hib, PCV13, rotavirus. 12-15 mo: MMR, varicella, Hib, PCV13. 4-6 yr: DTaP, IPV, MMR, varicella boosters. 11-12 yr: Tdap, HPV, MenACWY. Annual flu starting 6 mo.", example: "At the 2-month visit the infant received DTaP, IPV, Hib, PCV13, and rotavirus per CDC schedule." },
  { term: "Otitis Media", type: "concept", category: "vaccines-infections", meaning: "Most common pediatric infection. S. pneumoniae, H. influenzae, M. catarrhalis. Bulging erythematous TM, ear pain, fever. First-line: amoxicillin 80-90 mg/kg/day; watchful waiting for mild cases >6 mo.", example: "The 2-year-old's right ear pain with bulging erythematous TM was treated with high-dose amoxicillin for 10 days." },
  { term: "Croup (Laryngotracheobronchitis)", type: "concept", category: "vaccines-infections", meaning: "Parainfluenza virus; barking cough, stridor, hoarseness, fever, ages 6 mo - 6 yr. Steeple sign on neck X-ray. Treated with humidified air, dexamethasone, racemic epinephrine for severe stridor.", example: "The 18-month-old's barking cough and inspiratory stridor responded to single dose oral dexamethasone in the ED." },
  { term: "Bronchiolitis (RSV)", type: "concept", category: "vaccines-infections", meaning: "Lower respiratory infection of infants <2 yr; RSV most common. Cough, wheezing, retractions, tachypnea. Supportive treatment: hydration, suctioning, oxygen. Palivizumab prophylaxis for high-risk infants.", example: "The 4-month-old's RSV bronchiolitis with hypoxia required admission for nasal suctioning, IV fluids, and supplemental oxygen." },
  { term: "Streptococcal Pharyngitis", type: "concept", category: "vaccines-infections", meaning: "Group A strep; sore throat, fever, tonsillar exudate, anterior cervical lymphadenopathy, no cough. Confirmed by rapid strep or culture. Treated with penicillin or amoxicillin to prevent rheumatic fever.", example: "The 7-year-old's sore throat with exudate, no cough, and positive rapid strep was treated with 10 days of amoxicillin." },
  { term: "Pediatric Sepsis", type: "concept", category: "vaccines-infections", meaning: "Suspected if febrile child with abnormal HR/RR, mental status, or perfusion. Early signs subtle: poor feeding, lethargy, hypotension is LATE. Treat with fluids 20 mL/kg boluses + broad-spectrum antibiotics within 1 hour.", example: "The 2-month-old's fever and lethargy prompted septic workup; empiric ampicillin + gentamicin (covering GBS, E. coli, Listeria) was started immediately." },

  // ── Common Pediatric Conditions ──────────────────────────────
  { term: "Asthma (Pediatric)", type: "concept", category: "common-conditions", meaning: "Most common chronic childhood disease. Episodic wheezing, cough (often night), dyspnea, triggered by viral URI, exercise, allergens. Treated with SABA rescue + ICS controller; severity-based stepwise approach.", example: "The 8-year-old's nocturnal cough and exercise-induced wheezing improved with daily low-dose inhaled fluticasone." },
  { term: "Food Allergies and Anaphylaxis", type: "concept", category: "common-conditions", meaning: "Top 9: milk, egg, peanut, tree nuts, soy, wheat, fish, shellfish, sesame. IgE-mediated reactions: urticaria, angioedema, vomiting, anaphylaxis (multi-system). Treat anaphylaxis: IM epinephrine 0.01 mg/kg (max 0.3 mg).", example: "Minutes after peanut exposure the child developed hives, wheezing, and hypotension — anaphylaxis treated with IM epinephrine 0.15 mg auto-injector." },
  { term: "Iron Deficiency Anemia in Children", type: "concept", category: "common-conditions", meaning: "Common 9-24 months; risk factors include cow's milk before 12 mo, exclusive breastfeeding >6 mo without iron supplementation. Screened with hemoglobin at 12 mo. Treated with oral ferrous sulfate 3-6 mg/kg/day.", example: "The 15-month-old who drank 32 oz of whole milk daily had Hgb 9.2 — IDA from excess milk consumption; iron supplementation and milk restriction started." },
  { term: "Constipation (Functional)", type: "concept", category: "common-conditions", meaning: "Hard infrequent stools, withholding behavior, fecal impaction with overflow soiling. Treated with disimpaction (polyethylene glycol), maintenance laxatives, increased fiber/fluid, toilet sitting routine.", example: "The 4-year-old's encopresis from fecal impaction was treated with polyethylene glycol disimpaction and maintenance dose plus toileting routine." },
  { term: "ADHD", type: "concept", category: "common-conditions", meaning: "Inattention and/or hyperactivity-impulsivity persisting ≥6 months, beginning before age 12, present in ≥2 settings (school, home). Treated with behavioral therapy, school accommodations, stimulants (methylphenidate, amphetamines).", example: "The 8-year-old's inattention in school and at home with onset at age 6 met DSM-5 criteria for ADHD combined type; methylphenidate XR was initiated." },
  { term: "Autism Spectrum Disorder", type: "concept", category: "common-conditions", meaning: "Persistent deficits in social communication + restricted/repetitive behaviors, present in early development. Screening with M-CHAT at 18 and 24 months. Early intervention (ABA, speech, OT) improves outcomes.", example: "The 18-month-old's positive M-CHAT screen led to formal evaluation diagnosing autism; early intervention services were initiated." },
  { term: "Diabetes Type 1 (Pediatric)", type: "concept", category: "common-conditions", meaning: "Autoimmune β-cell destruction; typically childhood onset with polyuria, polydipsia, polyphagia, weight loss, often DKA at diagnosis. Lifelong insulin therapy with intensive management (pump, CGM).", example: "The 9-year-old's weight loss and polydipsia with glucose 480 and ketones confirmed new-onset T1DM presenting in DKA." },
  { term: "Child Abuse Recognition", type: "concept", category: "common-conditions", meaning: "Red flags: injury inconsistent with history, multiple injuries different ages, posterior rib fractures (squeezing), spiral long-bone fractures in pre-ambulatory child, retinal hemorrhages (shaken baby), unexplained bruises in non-mobile infant. Mandatory reporting.", example: "The 4-month-old's retinal hemorrhages, subdural hematoma, and posterior rib fractures prompted CPS report for suspected abusive head trauma." },
];'''
m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
html = html[:m.start()] + TERMS_JS + html[m.end():]
CAT = """const categoryLabel = c => ({
  'growth-development':  'Growth, Development & Well Child',
  'vaccines-infections': 'Vaccines & Pediatric Infections',
  'common-conditions':   'Common Pediatric Conditions',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'pediatrics';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>', '<title>HOSA Prep Hub — Pediatrics</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>', '<h1>Pedi<em>atrics</em>.</h1>', 1)
html = html.replace('A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
                    'A study companion for growth and development, vaccines and pediatric infections, and the most common conditions of childhood — built for HOSA competitors.', 1)
html = html.replace('//  DATA — HOSA Emergency Medical Science', '//  DATA — HOSA Pediatrics', 1)
with open(DST, 'w', encoding='utf-8') as f: f.write(html)
print(f'Wrote {DST} — {TERMS_JS.count("{ term:")} terms')
