#!/usr/bin/env python3
"""Generate speech-language-pathology.html from dental-science.html template."""
import os, re
BASE = '/home/user/hosa-prep-hub'
SRC, DST = os.path.join(BASE, 'dental-science.html'), os.path.join(BASE, 'speech-language-pathology.html')
with open(SRC, 'r', encoding='utf-8') as f: html = f.read()
TERMS_JS = '''const TERMS = [
  // ── Communication Foundations ────────────────────────────────
  { term: "Scope of SLP Practice", type: "concept", category: "foundations", meaning: "Speech-language pathologists assess and treat: speech sound disorders, language disorders, fluency, voice, cognitive-communication, social communication, swallowing (dysphagia), AAC. Settings: schools, hospitals, rehab, private practice, SNF.", example: "The SLP evaluated the stroke patient's aphasia, dysarthria, and dysphagia — all within scope of practice." },
  { term: "Speech vs Language vs Communication", type: "concept", category: "foundations", meaning: "Speech: motor production of sounds (articulation, fluency, voice). Language: rule-governed symbolic system (phonology, morphology, syntax, semantics, pragmatics). Communication: broader exchange of information including nonverbal, gesture, AAC.", example: "The child with autism had intact speech production but impaired pragmatic language and social communication." },
  { term: "Language Development Milestones", type: "concept", category: "foundations", meaning: "12 mo: first words, follows simple commands. 18 mo: 10-25 words. 2 yr: 2-word phrases, 200+ words. 3 yr: 3-word sentences, intelligible to strangers ~75%. 4 yr: complex sentences, intelligible 100%. 5 yr: complete grammar, narratives.", example: "The 3-year-old speaking in 2-word phrases with 50% intelligibility was referred for SLP evaluation — below milestones." },
  { term: "Phonemes and Articulation", type: "concept", category: "foundations", meaning: "Phoneme: smallest unit of sound that differentiates meaning. Articulation: production of speech sounds via place, manner, voicing. Children acquire sounds in predictable order (early: /p/, /b/, /m/; late: /r/, /s/, /th/).", example: "The 6-year-old's substitution of /w/ for /r/ ('wabbit') was age-appropriate; persisting past age 7 would warrant intervention." },

  // ── Speech & Language Disorders ──────────────────────────────
  { term: "Articulation Disorder", type: "concept", category: "disorders", meaning: "Difficulty producing speech sounds correctly. Types of errors: substitution, omission, distortion, addition. Treated with targeted articulation therapy practicing correct sound production in isolation → syllables → words → phrases → conversation.", example: "The 7-year-old's persistent /th/ for /s/ substitution affected school participation; targeted articulation therapy improved production within 6 months." },
  { term: "Phonological Disorder", type: "concept", category: "disorders", meaning: "Pattern-based sound errors (e.g., fronting — substituting front sounds for back: 'tat' for 'cat'; final consonant deletion: 'ca' for 'cat'). Differs from articulation by affecting sound classes. Treated by addressing patterns, not individual sounds.", example: "The preschooler's pattern of final consonant deletion across many sounds was a phonological process disorder; therapy targeted the pattern rather than individual sounds." },
  { term: "Childhood Apraxia of Speech (CAS)", type: "concept", category: "disorders", meaning: "Motor speech disorder — impaired planning/sequencing of speech movements. Inconsistent errors, difficulty with longer/more complex utterances, prosodic errors. Distinct from articulation disorders. Requires intensive motor-based therapy.", example: "The child's inconsistent speech errors that worsened with longer utterances were diagnostic of CAS; intensive motor-based therapy was prescribed." },
  { term: "Stuttering (Fluency Disorder)", type: "concept", category: "disorders", meaning: "Disruptions in speech flow: repetitions, prolongations, blocks. Often begins age 2-5. Most preschoolers recover; persisting beyond 4 years or with family history may need intervention. Lidcombe Program effective in young children.", example: "The 4-year-old with persistent stuttering beyond 12 months received the Lidcombe Program — parent-administered operant treatment in everyday speech contexts." },
  { term: "Aphasia (Post-Stroke)", type: "concept", category: "disorders", meaning: "Acquired language disorder from brain injury, most commonly left MCA stroke. Broca (expressive): non-fluent, effortful, agrammatic. Wernicke (receptive): fluent but nonsensical, impaired comprehension. Global: severe in both. Treated with intensive language therapy.", example: "The patient's effortful 'telegraphic' speech with preserved comprehension after left frontal stroke was Broca aphasia; targeted language therapy improved expression." },
  { term: "Voice Disorders (Dysphonia)", type: "concept", category: "disorders", meaning: "Abnormal vocal quality (hoarseness, breathiness, harshness, strain). Causes: vocal nodules (overuse), polyps (acute trauma, smoking), paralysis (recurrent laryngeal nerve), GERD, malignancy. Treated with voice therapy, surgery, behavioral changes.", example: "The teacher's chronic vocal nodules from voice overuse responded to voice therapy emphasizing reduced loudness and forward tone placement." },
  { term: "Cognitive-Communication Disorders", type: "concept", category: "disorders", meaning: "Communication problems from cognitive deficits (attention, memory, executive function, problem-solving) — common after TBI, stroke, dementia. Treated by SLPs with strategy training, environmental modification, communication partner training.", example: "The TBI patient's word-finding difficulty and tangential speech were addressed with compensatory strategies and external memory aids by the SLP." },

  // ── Dysphagia ────────────────────────────────────────────────
  { term: "Swallowing Phases", type: "concept", category: "dysphagia", meaning: "Oral preparatory (bolus formation by mastication). Oral (tongue propels bolus posteriorly). Pharyngeal (swallow reflex — soft palate elevation, airway protection, UES opening). Esophageal (peristalsis to stomach).", example: "The patient's pharyngeal-phase dysphagia from poor laryngeal elevation increased aspiration risk during swallow." },
  { term: "Aspiration vs Penetration", type: "concept", category: "dysphagia", meaning: "Penetration: material enters laryngeal vestibule but stays above true vocal cords. Aspiration: material enters airway below vocal cords. Silent aspiration: no overt cough — common and dangerous. Both increase pneumonia risk.", example: "The MBS revealed silent aspiration of thin liquids — no cough response — necessitating diet modification to thickened liquids." },
  { term: "Modified Barium Swallow (MBS)", type: "concept", category: "dysphagia", meaning: "Videofluoroscopic study with various barium consistencies and volumes; visualizes all swallow phases. Identifies aspiration, penetration, residue, mechanism of dysfunction. Guides diet recommendations and therapy targets.", example: "The MBS identified delayed swallow trigger and laryngeal penetration with thin liquids; nectar-thick liquids and chin tuck were recommended." },
  { term: "FEES (Fiberoptic Endoscopic Evaluation of Swallowing)", type: "concept", category: "dysphagia", meaning: "SLP-performed bedside endoscopy through nose viewing pharynx during swallowing. Advantages: no radiation, easily repeated, real food assessed. Limitations: can't view oral phase or moment of swallow ('whiteout').", example: "The bedridden patient unable to tolerate MBS underwent FEES — revealing pooling and silent aspiration of liquid consistencies." },
  { term: "Dysphagia Treatment Strategies", type: "concept", category: "dysphagia", meaning: "Postural: chin tuck, head turn. Maneuvers: effortful swallow, Mendelsohn, supraglottic. Diet modification: liquid thickening (IDDSI levels), texture changes. Exercises: tongue/lingual strengthening, Shaker. Compensation vs rehabilitation strategies.", example: "The stroke patient's dysphagia plan included chin tuck for thin liquids, effortful swallow for solids, and Mendelsohn maneuver — coordinated by SLP." },

  // ── Augmentative & Pediatric Issues ──────────────────────────
  { term: "Augmentative and Alternative Communication (AAC)", type: "concept", category: "aac-pediatric", meaning: "Methods supplementing or replacing speech: low-tech (picture boards, sign language) to high-tech (speech-generating devices, eye-gaze systems). Used for ALS, severe CP, autism, post-stroke severe aphasia. Multimodal often best.", example: "The patient with progressive ALS used an eye-gaze speech-generating device to communicate as bulbar speech declined." },
  { term: "Autism Spectrum Communication", type: "concept", category: "aac-pediatric", meaning: "Variable presentation from non-verbal to verbose with pragmatic deficits. Common: literal language, echolalia, restricted interests, difficulty with conversational turn-taking, theory of mind challenges. SLP role: language, pragmatics, AAC.", example: "The 5-year-old with autism used PECS (Picture Exchange Communication System) to request items and gradually developed verbal language with SLP support." },
  { term: "Hearing Loss and Communication", type: "concept", category: "aac-pediatric", meaning: "Even mild hearing loss affects language development in children. Universal newborn hearing screening allows early identification. SLP collaborates with audiology for hearing aids/cochlear implants; aural rehabilitation, language therapy. ASL for deaf community.", example: "The infant diagnosed with bilateral sensorineural hearing loss at 1 month received hearing aids at 3 months and early language intervention." },
  { term: "Cleft Lip and Palate", type: "concept", category: "aac-pediatric", meaning: "Congenital orofacial cleft affecting feeding, speech (hypernasality, articulation errors), middle ear (chronic otitis media). Multidisciplinary team: surgery (lip repair 3-6 mo, palate 9-18 mo), SLP, audiology, ENT, orthodontics, dentistry.", example: "The infant with cleft palate received early SLP feeding support; speech development was monitored after palatal repair at 12 months." },
  { term: "School-Age Language Disorder", type: "concept", category: "aac-pediatric", meaning: "Difficulty understanding or using spoken/written language affecting academic achievement. May be receptive, expressive, or mixed. Features: limited vocabulary, syntactic errors, narrative weakness, reading comprehension issues. SLP collaborates in IEP development.", example: "The 8-year-old's poor reading comprehension and narrative skills despite normal articulation indicated language disorder; intervention focused on vocabulary and discourse." },
];'''
m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
html = html[:m.start()] + TERMS_JS + html[m.end():]
CAT = """const categoryLabel = c => ({
  'foundations':  'Communication Foundations',
  'disorders':    'Speech & Language Disorders',
  'dysphagia':    'Dysphagia',
  'aac-pediatric':'AAC & Pediatric Issues',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'speech-language-pathology';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>', '<title>HOSA Prep Hub — Speech-Language Pathology</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>', '<h1>Speech-Language<br><em>Pathology</em>.</h1>', 1)
html = html.replace('A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
                    'A study companion for SLP scope and communication foundations, speech and language disorders, dysphagia evaluation and treatment, and AAC and pediatric communication issues — built for HOSA competitors.', 1)
html = html.replace('//  DATA — HOSA Emergency Medical Science', '//  DATA — HOSA Speech-Language Pathology', 1)
with open(DST, 'w', encoding='utf-8') as f: f.write(html)
print(f'Wrote {DST} — {TERMS_JS.count("{ term:")} terms')
