#!/usr/bin/env python3
"""Generate immunology.html from dental-science.html template."""
import os, re
BASE = '/home/user/hosa-prep-hub'
SRC, DST = os.path.join(BASE, 'dental-science.html'), os.path.join(BASE, 'immunology.html')
with open(SRC, 'r', encoding='utf-8') as f: html = f.read()
TERMS_JS = '''const TERMS = [
  // ── Innate Immunity ──────────────────────────────────────────
  { term: "Innate vs Adaptive Immunity", type: "concept", category: "innate", meaning: "Innate: rapid (minutes-hours), nonspecific, no memory — skin, mucosa, phagocytes (neutrophils, macrophages), NK cells, complement. Adaptive: slower (days), specific (T/B cells), establishes memory.", example: "The patient's neutrophil response to bacterial pneumonia within hours represented innate immunity, while antibody production weeks later represented adaptive immunity." },
  { term: "Physical and Chemical Barriers", type: "concept", category: "innate", meaning: "First line of defense: intact skin and mucous membranes, mucus and cilia (respiratory), gastric acid, urine flow, normal flora, lysozyme in tears/saliva, defensins in skin/gut.", example: "The patient's severe burn breached the skin barrier, dramatically increasing infection risk despite intact immune function." },
  { term: "Phagocytes (Neutrophils, Macrophages)", type: "concept", category: "innate", meaning: "Neutrophils: first responders to bacterial infection (~60% of WBCs); short-lived, form pus. Macrophages: tissue-resident phagocytes (alveolar macrophages, Kupffer cells, microglia); also antigen presentation.", example: "Bacterial pneumonia recruited neutrophils to the alveoli; subsequent alveolar macrophage activity cleared debris during resolution." },
  { term: "Natural Killer (NK) Cells", type: "concept", category: "innate", meaning: "Lymphoid cells of innate immunity that kill virally infected and tumor cells lacking MHC class I ('missing self'); do not require prior exposure. Release perforin and granzymes.", example: "NK cells eliminated the virally infected hepatocytes that had downregulated MHC class I — a tumor immune evasion strategy that NK cells circumvent." },
  { term: "Complement System", type: "concept", category: "innate", meaning: "Cascade of plasma proteins (C1–C9) activated by classical (antibody-antigen), lectin, or alternative pathways. Functions: opsonization (C3b), inflammation (C3a/C5a), membrane attack complex (C5b-9) lyses pathogens.", example: "The patient's gram-negative bacterial infection was opsonized by C3b for phagocyte clearance and lysed by C5b-9 membrane attack complex." },
  { term: "Inflammation (Cardinal Signs)", type: "concept", category: "innate", meaning: "Five signs: redness (rubor — vasodilation), heat (calor), swelling (tumor — increased permeability), pain (dolor — bradykinin, prostaglandins), loss of function (functio laesa). Mediated by histamine, prostaglandins, cytokines.", example: "The patient's cellulitis exhibited all five cardinal signs — red, warm, swollen, painful, with limited limb use." },
  { term: "Cytokines and Interferons", type: "concept", category: "innate", meaning: "Cytokines: small signaling proteins (interleukins, TNF, interferons) regulating immunity. Interferons (IFN-α, β, γ) are antiviral — induce neighboring cell defenses. Cytokine storm (sepsis, COVID-19) is dysregulated overproduction.", example: "Severe COVID-19 triggered a cytokine storm with massive IL-6 release — tocilizumab (IL-6 receptor antibody) was given to dampen the response." },

  // ── Adaptive Immunity ────────────────────────────────────────
  { term: "B Cells and Antibodies", type: "concept", category: "adaptive", meaning: "B lymphocytes mature in bone marrow; when activated, differentiate into plasma cells producing antigen-specific antibodies (immunoglobulins). Establish humoral immunity and memory.", example: "The vaccinated patient's memory B cells generated rapid IgG production on re-exposure to the influenza virus — humoral immune memory." },
  { term: "Immunoglobulin Classes (IgG, IgA, IgM, IgE, IgD)", type: "concept", category: "adaptive", meaning: "IgG: most abundant, secondary response, crosses placenta. IgM: first produced (acute infection marker), pentamer. IgA: mucosal/breast milk. IgE: allergic reactions, parasites. IgD: B-cell receptor.", example: "Elevated hepatitis A IgM indicated acute infection; IgG indicated past exposure or vaccination — classic acute/chronic differentiation." },
  { term: "T Cells (CD4 vs CD8)", type: "concept", category: "adaptive", meaning: "T lymphocytes mature in thymus. CD4+ (helper): coordinate immune response, secrete cytokines. CD8+ (cytotoxic): kill virally infected and tumor cells. CD4 recognize MHC II; CD8 recognize MHC I.", example: "HIV preferentially infects CD4+ T cells, depleting them and crippling adaptive immunity — AIDS defined by CD4 <200." },
  { term: "MHC / HLA", type: "concept", category: "adaptive", meaning: "Major histocompatibility complex (in humans: HLA — human leukocyte antigens). Class I: on all nucleated cells, presents intracellular peptides to CD8. Class II: on APCs, presents extracellular peptides to CD4. Determines transplant compatibility.", example: "Transplant matching by HLA-A, B, DR loci minimized rejection risk; mismatched HLA triggers strong cellular immune response." },
  { term: "Antigen Presenting Cells (APCs)", type: "concept", category: "adaptive", meaning: "Dendritic cells (most potent), macrophages, B cells. Process antigens and present peptide fragments on MHC II to CD4 T cells, initiating adaptive immunity.", example: "Dendritic cells in the skin captured the vaccine antigen, migrated to draining lymph nodes, and primed naive T cells — initiating adaptive response." },
  { term: "Active vs Passive Immunity", type: "concept", category: "adaptive", meaning: "Active: own immune system produces antibodies — natural (infection) or artificial (vaccine); long-lasting, with memory. Passive: pre-formed antibodies transferred — natural (maternal IgG, breast milk IgA) or artificial (IVIG, monoclonal); short-lived, no memory.", example: "After the patient's needlestick, passive immunity from HBIG provided immediate protection while active immunity from HBV vaccine took weeks to develop." },
  { term: "Immunologic Memory", type: "concept", category: "adaptive", meaning: "Memory B and T cells persist after primary infection or vaccination; on re-exposure, they generate faster, stronger secondary response (peaks 5–7 days vs 1–2 weeks). Basis of vaccination.", example: "The boostered patient's anamnestic response produced high-titer antibodies within 5 days of measles exposure — memory B-cell activation." },

  // ── Hypersensitivity & Disease ───────────────────────────────
  { term: "Type I Hypersensitivity (Anaphylaxis/Allergy)", type: "concept", category: "disease", meaning: "IgE-mediated, immediate (minutes); mast cell degranulation releases histamine, leukotrienes. Examples: anaphylaxis, allergic asthma, hay fever, food allergies. Treated with epinephrine (anaphylaxis), antihistamines.", example: "Minutes after the peanut bite, the child developed urticaria, wheezing, and hypotension — Type I anaphylaxis; IM epinephrine was administered immediately." },
  { term: "Type II Hypersensitivity (Antibody-Mediated)", type: "concept", category: "disease", meaning: "IgG/IgM bind cell surface antigens → cell destruction. Examples: hemolytic transfusion reaction, hemolytic disease of newborn (Rh), Goodpasture syndrome, autoimmune hemolytic anemia, myasthenia gravis (AChR antibodies).", example: "The Rh-negative mother's anti-Rh IgG crossed the placenta and destroyed the Rh-positive fetus's RBCs — Type II hemolytic disease of newborn." },
  { term: "Type III Hypersensitivity (Immune Complex)", type: "concept", category: "disease", meaning: "Antigen-antibody complexes deposit in tissues → complement activation, neutrophil influx, damage. Examples: serum sickness, SLE (joints, kidneys), post-streptococcal glomerulonephritis, rheumatoid arthritis.", example: "The SLE patient's nephritis was caused by immune complex deposition in glomeruli — Type III hypersensitivity confirmed by biopsy showing 'full-house' staining." },
  { term: "Type IV Hypersensitivity (Delayed/Cell-Mediated)", type: "concept", category: "disease", meaning: "T-cell mediated, develops 24–72 hours; no antibody involvement. Examples: TB skin test (PPD), contact dermatitis (poison ivy, nickel), graft rejection, T1DM, MS, contact hypersensitivity to latex.", example: "The PPD test induration of 12 mm at 48 hours represented delayed-type hypersensitivity — Type IV cellular memory of prior M. tuberculosis exposure." },
  { term: "Autoimmunity", type: "concept", category: "disease", meaning: "Loss of tolerance → immune attack on self. Examples: rheumatoid arthritis, lupus, T1DM, Hashimoto, MS, Crohn's, Graves disease. Associated with HLA risk alleles, environmental triggers, female predominance.", example: "The young woman's malar rash, photosensitivity, arthritis, and positive ANA and anti-dsDNA confirmed systemic lupus erythematosus." },
  { term: "Immunodeficiency", type: "concept", category: "disease", meaning: "Primary (genetic): SCID (severe combined — no T or B cells), CVID, X-linked agammaglobulinemia (Bruton — no B cells), DiGeorge (no thymus → no T cells). Secondary: HIV, chemotherapy, malnutrition, splenectomy.", example: "The SCID infant's recurrent severe infections required bone marrow transplant; the 'bubble baby' phenotype reflected total adaptive immune absence." },
  { term: "HIV/AIDS Immunology", type: "concept", category: "disease", meaning: "HIV infects CD4+ T cells via CD4 + CCR5/CXCR4 → progressive CD4 depletion. AIDS defined by CD4 <200 or AIDS-defining illness. Opportunistic infections (PCP, toxoplasma, CMV). ART prevents progression.", example: "The HIV patient's CD4 of 145 met AIDS criteria; PCP prophylaxis with TMP-SMX was added alongside ART." },

  // ── Vaccines & Transplant ────────────────────────────────────
  { term: "Vaccine Types", type: "concept", category: "vaccines", meaning: "Live attenuated (MMR, varicella, rotavirus, yellow fever — strong immunity, avoid in immunocompromised/pregnancy). Inactivated (flu, polio IPV, HAV). Subunit/conjugate (HBV, HPV, pneumococcal). mRNA (COVID-19). Toxoid (tetanus, diphtheria).", example: "The pregnant patient could receive the inactivated flu vaccine but not the live attenuated nasal flu vaccine or MMR." },
  { term: "Herd Immunity", type: "concept", category: "vaccines", meaning: "When sufficient vaccination/immunity in a population indirectly protects susceptible individuals by interrupting transmission. Threshold varies by R0: measles ~95%, polio ~80%, COVID-19 ~60–70%.", example: "Declining MMR uptake below the 95% herd immunity threshold led to measles outbreaks in unvaccinated clusters." },
  { term: "Vaccine Schedule (Pediatric)", type: "concept", category: "vaccines", meaning: "Standard US schedule: HBV at birth, then DTaP/HiB/IPV/PCV/rotavirus at 2, 4, 6 months; MMR/varicella at 12–15 months. Adolescent: Tdap, meningococcal, HPV. Annual flu starting 6 months.", example: "The 6-month infant received DTaP, HiB, IPV, PCV, and rotavirus per the CDC pediatric vaccine schedule." },
  { term: "Transplant Rejection", type: "concept", category: "vaccines", meaning: "Hyperacute (minutes — preformed antibodies, ABO mismatch). Acute (days-weeks — T-cell mediated). Chronic (months-years — fibrosis, vasculopathy). Prevented by HLA matching + immunosuppression (calcineurin inhibitors, mycophenolate, steroids).", example: "The renal transplant patient's acute rejection at 2 weeks responded to high-dose corticosteroids; tacrolimus and mycophenolate were continued for maintenance immunosuppression." },
  { term: "Graft-Versus-Host Disease (GVHD)", type: "concept", category: "vaccines", meaning: "Donor T cells attack recipient tissues after allogeneic stem cell transplant; affects skin (rash), gut (diarrhea), liver. Acute (<100 days) vs chronic (>100 days). Treated with corticosteroids; prophylaxis with calcineurin inhibitor + methotrexate.", example: "Two weeks after allogeneic BMT, the patient developed a rash, diarrhea, and elevated bilirubin — acute GVHD; high-dose prednisone was started." },
  { term: "Allergy Testing", type: "concept", category: "vaccines", meaning: "Skin prick (introduce allergen, look for wheal — Type I IgE), intradermal (more sensitive), patch testing (Type IV contact). Serum specific IgE (RAST) when skin testing contraindicated. Always emergency-ready for anaphylaxis.", example: "The patient's positive skin prick to dust mites (wheal 8 mm vs negative control 2 mm) confirmed Type I dust mite allergy." },
];'''
m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
html = html[:m.start()] + TERMS_JS + html[m.end():]
CAT = """const categoryLabel = c => ({
  'innate':   'Innate Immunity',
  'adaptive': 'Adaptive Immunity',
  'disease':  'Hypersensitivity & Disease',
  'vaccines': 'Vaccines & Transplant',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'immunology';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>', '<title>HOSA Prep Hub — Immunology</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>', '<h1>Immuno<em>logy</em>.</h1>', 1)
html = html.replace('A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
                    'A study companion for innate and adaptive immunity, hypersensitivity reactions and immune disease, and vaccines and transplant immunology — built for HOSA competitors.', 1)
html = html.replace('//  DATA — HOSA Emergency Medical Science', '//  DATA — HOSA Immunology', 1)
with open(DST, 'w', encoding='utf-8') as f: f.write(html)
print(f'Wrote {DST} — {TERMS_JS.count("{ term:")} terms')
