#!/usr/bin/env python3
"""Generate otolaryngology.html from dental-science.html template."""
import os, re
BASE = '/home/user/hosa-prep-hub'
SRC, DST = os.path.join(BASE, 'dental-science.html'), os.path.join(BASE, 'otolaryngology.html')
with open(SRC, 'r', encoding='utf-8') as f: html = f.read()
TERMS_JS = '''const TERMS = [
  // ── Ear Disorders ────────────────────────────────────────────
  { term: "External Ear Anatomy", type: "concept", category: "ear", meaning: "Auricle (pinna), external auditory canal, tympanic membrane. Cerumen produced by ceruminous glands. Innervation: CN V, VII, IX, X (referred pain from these areas).", example: "The patient's ear pain on swallowing was referred otalgia from CN IX — investigation revealed tonsillitis as the source." },
  { term: "Middle Ear and Eustachian Tube", type: "concept", category: "ear", meaning: "Air-filled cavity with three ossicles (malleus, incus, stapes) transmitting sound to oval window. Eustachian tube connects to nasopharynx, equalizes pressure. Dysfunction causes barotrauma, effusion, otitis media.", example: "The child's eustachian tube dysfunction from URI led to middle ear effusion and recurrent otitis media." },
  { term: "Otitis Externa (Swimmer's Ear)", type: "concept", category: "ear", meaning: "External canal infection, often Pseudomonas or S. aureus; presents with pain, pruritus, discharge, tragal tenderness. Treated with topical antibiotics (ciprofloxacin/dexamethasone drops); keep ear dry.", example: "The swimmer's ear pain, tragal tenderness, and discharge were treated with ciprofloxacin/dexamethasone otic drops for 7 days." },
  { term: "Acute Otitis Media (AOM)", type: "concept", category: "ear", meaning: "Middle ear infection with bulging erythematous TM, fever, ear pain. S. pneumoniae, H. influenzae, M. catarrhalis most common. First-line: high-dose amoxicillin 80-90 mg/kg/day for 10 days; watchful waiting acceptable for mild cases >6 mo.", example: "The 18-month-old's bulging erythematous TM with fever was treated with amoxicillin 90 mg/kg/day for 10 days." },
  { term: "Otitis Media with Effusion (OME)", type: "concept", category: "ear", meaning: "Middle ear fluid without acute infection; often follows AOM. Conductive hearing loss, fullness. Most resolve spontaneously in 3 months. Tympanostomy tubes considered for persistent bilateral effusion >3 months with hearing loss or recurrent AOM.", example: "The child's persistent bilateral middle ear effusion >3 months with hearing loss prompted tympanostomy tube placement." },
  { term: "Hearing Loss (Conductive vs Sensorineural)", type: "concept", category: "ear", meaning: "Conductive: external/middle ear (cerumen, OME, otosclerosis). Sensorineural: cochlea/CN VIII (presbycusis, noise, ototoxicity). Weber/Rinne tests distinguish. Audiogram quantifies. Treated with hearing aids, cochlear implants, surgery.", example: "The patient's audiogram showed bilateral high-frequency sensorineural hearing loss consistent with presbycusis; hearing aids were prescribed." },
  { term: "Vertigo (Peripheral vs Central)", type: "concept", category: "ear", meaning: "Peripheral (inner ear): BPPV, Ménière, vestibular neuritis — horizontal nystagmus, more severe, hearing affected. Central (brainstem/cerebellum): vertical nystagmus, persistent, focal neuro signs — stroke/MS workup needed.", example: "The patient's brief positional vertigo with horizontal nystagmus on Dix-Hallpike confirmed BPPV; Epley maneuver provided immediate relief." },

  // ── Nose & Sinus Disorders ───────────────────────────────────
  { term: "Allergic Rhinitis", type: "concept", category: "nose-sinus", meaning: "IgE-mediated nasal mucosa inflammation; sneezing, rhinorrhea, nasal pruritus, congestion. Often with allergic conjunctivitis. Treated with intranasal corticosteroids (first-line), antihistamines, leukotriene antagonists, immunotherapy.", example: "The patient's seasonal sneezing, rhinorrhea, and itchy watery eyes with positive grass-pollen skin testing confirmed allergic rhinitis; fluticasone nasal spray was started." },
  { term: "Acute Sinusitis", type: "concept", category: "nose-sinus", meaning: "Inflammation of paranasal sinuses; usually viral (resolves within 10 days) vs bacterial (worsening after 5-7 days, persistent >10 days). S. pneumoniae and H. influenzae most common bacterial. Treated symptomatically; amoxicillin-clavulanate if bacterial.", example: "The patient's facial pain and purulent rhinorrhea worsening at day 10 was treated with amoxicillin-clavulanate for presumed bacterial sinusitis." },
  { term: "Epistaxis (Nosebleed)", type: "concept", category: "nose-sinus", meaning: "Anterior (90%, Kiesselbach plexus): usually controlled with pressure and topical decongestant. Posterior: severe, posterior packing or surgical intervention. Causes: trauma, dry air, anticoagulants, HTN, NSAIDs, rarely tumor.", example: "The patient's anterior epistaxis from nose-picking was controlled with 15 minutes of pressure and oxymetazoline; lubricating gel and humidification prevented recurrence." },
  { term: "Nasal Polyps", type: "concept", category: "nose-sinus", meaning: "Benign edematous outgrowths of nasal/sinus mucosa, often bilateral; associated with chronic rhinosinusitis, asthma, aspirin sensitivity (Samter triad). Treated with intranasal/oral steroids, surgery for refractory cases.", example: "The patient's chronic nasal congestion with bilateral polyps and aspirin sensitivity (Samter triad) was managed with intranasal mometasone and montelukast." },

  // ── Throat & Voice Disorders ─────────────────────────────────
  { term: "Streptococcal Pharyngitis", type: "concept", category: "throat-voice", meaning: "Group A strep tonsillopharyngitis. Centor criteria (fever, tonsillar exudate, anterior cervical adenopathy, no cough) predict likelihood. Confirmed by rapid antigen test or culture. Treated with penicillin or amoxicillin 10 days to prevent rheumatic fever.", example: "The patient's 4/4 Centor criteria and positive rapid strep were treated with amoxicillin 500 mg BID for 10 days." },
  { term: "Tonsillitis and Tonsillectomy", type: "concept", category: "throat-voice", meaning: "Recurrent throat infections (≥7 episodes/year, ≥5/year × 2 years, ≥3/year × 3 years — Paradise criteria) may indicate tonsillectomy. Also for sleep-disordered breathing, peritonsillar abscess.", example: "The child meeting Paradise criteria with 7 documented strep infections in 1 year was referred for tonsillectomy." },
  { term: "Peritonsillar Abscess", type: "concept", category: "throat-voice", meaning: "Complication of tonsillitis with collection of pus in peritonsillar space; muffled 'hot potato' voice, trismus, uvular deviation, drooling. Treated with drainage (needle aspiration or I&D) + antibiotics.", example: "The patient's hot potato voice, trismus, and uvular deviation prompted needle aspiration yielding purulent fluid — peritonsillar abscess." },
  { term: "Laryngitis", type: "concept", category: "throat-voice", meaning: "Inflammation of larynx causing hoarseness; usually viral. Most resolve within 1-2 weeks with voice rest, hydration, humidification. Persistent hoarseness >2 weeks requires evaluation for vocal cord lesion, GERD, malignancy.", example: "The teacher's hoarseness after teaching multiple classes resolved with 2 weeks of voice rest, hydration, and avoidance of throat clearing." },
  { term: "Vocal Cord Nodules and Polyps", type: "concept", category: "throat-voice", meaning: "Nodules: bilateral, from chronic voice overuse (singers, teachers, children). Polyps: usually unilateral, from acute voice trauma or smoking. Treated with voice therapy; surgery for persistent symptoms.", example: "The singer's bilateral vocal cord nodules were treated with voice therapy and abstinence from singing for 6 weeks." },
  { term: "Head and Neck Cancer", type: "concept", category: "throat-voice", meaning: "Squamous cell carcinoma most common; risk factors smoking, alcohol, HPV (oropharyngeal). Symptoms: persistent hoarseness, neck mass, oral lesion, dysphagia. Treated with surgery, radiation, chemotherapy, targeted therapy (cetuximab).", example: "The patient's persistent hoarseness >6 weeks and smoking history prompted laryngoscopy revealing T2 laryngeal squamous cell carcinoma." },
  { term: "Obstructive Sleep Apnea (OSA)", type: "concept", category: "throat-voice", meaning: "Recurrent upper airway collapse during sleep → hypoxemia, fragmented sleep, daytime fatigue. Risk factors: obesity, neck circumference, anatomy. Diagnosed by polysomnography (AHI ≥5). Treated with CPAP, weight loss, oral appliance, surgery (UPPP).", example: "The patient's loud snoring, witnessed apneas, and AHI of 35 on polysomnography confirmed severe OSA; CPAP improved daytime alertness within weeks." },
];'''
m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
html = html[:m.start()] + TERMS_JS + html[m.end():]
CAT = """const categoryLabel = c => ({
  'ear':          'Ear Disorders',
  'nose-sinus':   'Nose & Sinus Disorders',
  'throat-voice': 'Throat & Voice Disorders',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'otolaryngology';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>', '<title>HOSA Prep Hub — Otolaryngology (ENT)</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>', '<h1>Otolaryng<em>ology</em>.</h1>', 1)
html = html.replace('A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
                    'A study companion for ear disorders from otitis to vertigo, nose and sinus conditions including allergic rhinitis and sinusitis, and throat and voice disorders including pharyngitis and OSA — built for HOSA competitors.', 1)
html = html.replace('//  DATA — HOSA Emergency Medical Science', '//  DATA — HOSA Otolaryngology', 1)
with open(DST, 'w', encoding='utf-8') as f: f.write(html)
print(f'Wrote {DST} — {TERMS_JS.count("{ term:")} terms')
