#!/usr/bin/env python3
"""Generate endocrinology.html from dental-science.html template."""
import os, re
BASE = '/home/user/hosa-prep-hub'
SRC, DST = os.path.join(BASE, 'dental-science.html'), os.path.join(BASE, 'endocrinology.html')
with open(SRC, 'r', encoding='utf-8') as f: html = f.read()
TERMS_JS = '''const TERMS = [
  // ── Pituitary & Hypothalamus ─────────────────────────────────
  { term: "Hypothalamic-Pituitary Axis", type: "concept", category: "pituitary", meaning: "Hypothalamus produces releasing/inhibiting hormones controlling anterior pituitary, which secretes TSH, ACTH, FSH, LH, GH, prolactin. Posterior pituitary stores hypothalamic-made ADH and oxytocin.", example: "Loss of pulsatile GnRH from hypothalamic damage suppressed pituitary LH/FSH, causing secondary hypogonadism in the patient." },
  { term: "Growth Hormone (GH) Disorders", type: "concept", category: "pituitary", meaning: "GH excess: gigantism (before epiphyseal closure), acromegaly (after — enlarged hands, feet, jaw, organomegaly). GH deficiency: short stature in children. Diagnosis: IGF-1, oral glucose tolerance test (no suppression in acromegaly).", example: "The 45-year-old's enlarged hands, jaw, and elevated IGF-1 with non-suppressible GH on OGTT confirmed acromegaly from a pituitary adenoma." },
  { term: "Diabetes Insipidus (DI)", type: "concept", category: "pituitary", meaning: "ADH deficiency (central DI) or renal resistance (nephrogenic DI) → polyuria with dilute urine, intense thirst. Differentiated from DM by normal glucose. Water deprivation test + desmopressin distinguishes central from nephrogenic.", example: "The post-pituitary-surgery patient's 8 L/day urine output and serum sodium of 152 responded to desmopressin — central diabetes insipidus." },
  { term: "SIADH (Syndrome of Inappropriate ADH)", type: "concept", category: "pituitary", meaning: "Excess ADH secretion → water retention → euvolemic hyponatremia, concentrated urine, low serum osmolality. Causes: small cell lung cancer, head injury, SSRIs, infection. Treated with fluid restriction.", example: "The patient's serum sodium of 122 with concentrated urine and small cell lung cancer was diagnostic of paraneoplastic SIADH." },

  // ── Thyroid Disorders ────────────────────────────────────────
  { term: "Hyperthyroidism (Graves Disease)", type: "concept", category: "thyroid", meaning: "Autoimmune TSH receptor antibodies stimulate thyroid → ↑T4/T3, ↓TSH. Symptoms: weight loss despite increased appetite, heat intolerance, tachycardia, tremor, exophthalmos. Treated with methimazole, radioactive iodine, or surgery.", example: "The patient's weight loss, palpitations, heat intolerance, and exophthalmos with low TSH and high T4 confirmed Graves disease." },
  { term: "Hypothyroidism (Hashimoto)", type: "concept", category: "thyroid", meaning: "Autoimmune (anti-TPO antibodies) destroys thyroid → ↓T4, ↑TSH. Symptoms: fatigue, weight gain, cold intolerance, bradycardia, constipation, dry skin, depression. Treated with levothyroxine.", example: "The patient's fatigue, constipation, and weight gain with TSH of 28 and low T4 and positive anti-TPO confirmed Hashimoto thyroiditis; levothyroxine was started." },
  { term: "Thyroid Storm", type: "concept", category: "thyroid", meaning: "Life-threatening hyperthyroidism precipitated by infection, surgery, or trauma; presents with hyperthermia (>104°F), tachycardia, agitation, vomiting, cardiovascular collapse. Treated with beta-blocker, PTU, iodine, glucocorticoids.", example: "The undiagnosed Graves patient developed thyroid storm post-surgery with HR 180 and temp 105.2°F; ICU admission with propranolol, PTU, and hydrocortisone was initiated." },
  { term: "Myxedema Coma", type: "concept", category: "thyroid", meaning: "Severe untreated hypothyroidism causing altered mental status, hypothermia, hypoventilation, bradycardia, hyponatremia. High mortality. Treated with IV levothyroxine, hydrocortisone, supportive care.", example: "The elderly woman found unresponsive with temp 89°F, HR 42, and TSH >100 was diagnosed with myxedema coma and admitted for IV levothyroxine." },
  { term: "Thyroid Nodules and Cancer", type: "concept", category: "thyroid", meaning: "Most thyroid nodules are benign; FNA biopsy guided by ultrasound stratifies risk. Papillary thyroid cancer is most common (~80%); excellent prognosis with thyroidectomy + radioactive iodine. Medullary cancer associated with MEN2.", example: "The 3 cm hypoechoic nodule with microcalcifications on ultrasound was biopsied — papillary thyroid carcinoma; total thyroidectomy was performed." },

  // ── Diabetes Mellitus ────────────────────────────────────────
  { term: "Type 1 vs Type 2 Diabetes", type: "concept", category: "diabetes", meaning: "T1DM: autoimmune β-cell destruction → absolute insulin deficiency; usually childhood onset, requires insulin. T2DM: insulin resistance + relative deficiency; adult onset, obesity, lifestyle and oral agents first-line.", example: "The 12-year-old's polyuria, weight loss, and DKA with positive anti-GAD antibodies confirmed T1DM; insulin was started." },
  { term: "Diagnostic Criteria for Diabetes", type: "concept", category: "diabetes", meaning: "Any of: HbA1c ≥6.5%; fasting glucose ≥126 mg/dL; 2-hr glucose ≥200 on OGTT; random glucose ≥200 with symptoms. Prediabetes: HbA1c 5.7–6.4%, fasting 100–125, OGTT 140–199.", example: "The patient's HbA1c of 7.2% and fasting glucose of 142 met diabetes criteria on two occasions; metformin was started." },
  { term: "HbA1c (Glycated Hemoglobin)", type: "concept", category: "diabetes", meaning: "Reflects average glucose over preceding 2–3 months (RBC lifespan). Target <7% for most adults; <6.5% for select, <8% for elderly/frail. Estimated average glucose (eAG) = 28.7 × A1c − 46.7.", example: "The patient's A1c of 8.4% (eAG 196) prompted intensification of therapy with addition of a GLP-1 agonist." },
  { term: "Diabetic Ketoacidosis (DKA)", type: "concept", category: "diabetes", meaning: "Hyperglycemia + ketosis + anion gap metabolic acidosis from absolute insulin deficiency; presents with Kussmaul respirations, fruity breath, dehydration, abdominal pain. Treated with IV insulin, fluids, K+ replacement.", example: "The T1DM patient's glucose 480, pH 7.18, bicarbonate 12, and large ketones confirmed DKA; IV insulin infusion and saline resuscitation were started." },
  { term: "Hyperosmolar Hyperglycemic State (HHS)", type: "concept", category: "diabetes", meaning: "Severe hyperglycemia (>600 mg/dL), profound dehydration, hyperosmolality (>320 mOsm/kg), altered mental status, minimal ketosis (T2DM has enough insulin to suppress ketogenesis). Higher mortality than DKA.", example: "The elderly T2DM patient with glucose 980, serum osm 340, and obtundation but minimal ketones was diagnosed with HHS; aggressive fluids and insulin were initiated." },
  { term: "Diabetic Complications (Macrovascular & Microvascular)", type: "concept", category: "diabetes", meaning: "Macrovascular: CAD, stroke, PAD. Microvascular: retinopathy (leading cause of new adult blindness), nephropathy (leading cause of ESRD), neuropathy (peripheral and autonomic). Tight glucose control reduces microvascular risk.", example: "The longstanding diabetic developed proliferative retinopathy, diabetic kidney disease, and foot ulcer from peripheral neuropathy — classic microvascular complications." },
  { term: "Insulin Types", type: "concept", category: "diabetes", meaning: "Rapid (lispro, aspart — onset 15 min, peak 1 h). Short (regular). Intermediate (NPH). Long-acting (glargine, detemir — flat 24 h profile). Basal + bolus regimens mimic physiologic secretion.", example: "The T1DM patient was on glargine 22 units nightly (basal) and lispro 6–10 units before each meal (bolus) — basal-bolus regimen." },
  { term: "Oral Diabetes Medications", type: "concept", category: "diabetes", meaning: "Metformin (1st line, biguanide). SGLT2 inhibitors (-flozin): glucose excretion, CV/renal benefit. GLP-1 agonists (-tide): weight loss, CV benefit. DPP-4 inhibitors (-gliptin). Sulfonylureas: stimulate insulin (hypoglycemia risk).", example: "The T2DM patient was started on metformin; SGLT2 inhibitor empagliflozin was added for the patient's heart failure and cardioprotective benefit." },

  // ── Adrenal & Other Endocrine ────────────────────────────────
  { term: "Cushing Syndrome", type: "concept", category: "adrenal-other", meaning: "Excess cortisol; causes weight gain (truncal, buffalo hump, moon face), purple striae, easy bruising, hypertension, hyperglycemia, osteoporosis. Most common cause: iatrogenic (steroid use). Cushing disease = pituitary ACTH adenoma.", example: "The patient on chronic prednisone for RA developed truncal obesity, moon face, and purple abdominal striae — iatrogenic Cushing syndrome." },
  { term: "Addison Disease", type: "concept", category: "adrenal-other", meaning: "Primary adrenal insufficiency — usually autoimmune destruction. Cortisol AND aldosterone deficient: fatigue, weight loss, hyperpigmentation, hypotension, hyponatremia, hyperkalemia. Treated with hydrocortisone + fludrocortisone.", example: "The patient's fatigue, hyperpigmentation, low cortisol with high ACTH confirmed Addison disease; replacement steroids were initiated." },
  { term: "Adrenal Crisis", type: "concept", category: "adrenal-other", meaning: "Acute life-threatening adrenal insufficiency from stress (infection, trauma, surgery) in steroid-deficient patient. Presents with hypotension, shock, hypoglycemia, hyponatremia. Treated emergently with IV hydrocortisone and saline.", example: "The Addison patient who stopped steroids developed hypotension and hyponatremia during pneumonia — adrenal crisis treated with IV hydrocortisone 100 mg." },
  { term: "Pheochromocytoma", type: "concept", category: "adrenal-other", meaning: "Catecholamine-secreting tumor of adrenal medulla; episodic headaches, palpitations, diaphoresis (classic triad), severe hypertension. Diagnosed by plasma/urine metanephrines. Surgical resection after alpha-blockade (phenoxybenzamine).", example: "Episodic headaches, palpitations, and BP 220/130 with elevated plasma metanephrines confirmed pheochromocytoma; alpha-blockade preceded surgical resection." },
  { term: "Hyperparathyroidism", type: "concept", category: "adrenal-other", meaning: "Primary: parathyroid adenoma → ↑PTH → ↑Ca, ↓PO4. 'Stones (kidney), bones (lytic lesions), groans (abdominal pain), thrones (constipation), psychiatric overtones'. Treated by parathyroidectomy if symptomatic.", example: "The patient's hypercalcemia of 12.1, kidney stones, and elevated PTH confirmed primary hyperparathyroidism from a parathyroid adenoma." },
  { term: "Hypoparathyroidism", type: "concept", category: "adrenal-other", meaning: "PTH deficiency (often post-thyroidectomy) → hypocalcemia: tetany, perioral numbness, carpopedal spasm (Trousseau sign), facial twitch (Chvostek sign), seizures. Treated with calcium and calcitriol.", example: "Post-total-thyroidectomy the patient developed perioral tingling and positive Chvostek sign with serum Ca 7.4 — acute hypoparathyroidism; IV calcium was given." },
  { term: "PCOS (Polycystic Ovary Syndrome)", type: "concept", category: "adrenal-other", meaning: "Hyperandrogenism + ovulatory dysfunction + polycystic ovaries (Rotterdam criteria, 2 of 3); insulin resistance common. Presents with hirsutism, acne, irregular menses, infertility, obesity. Treated with OCPs, metformin, lifestyle.", example: "The young woman's irregular menses, hirsutism, and polycystic ovaries on ultrasound met Rotterdam criteria for PCOS." },
];'''
m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
html = html[:m.start()] + TERMS_JS + html[m.end():]
CAT = """const categoryLabel = c => ({
  'pituitary':     'Pituitary & Hypothalamus',
  'thyroid':       'Thyroid Disorders',
  'diabetes':      'Diabetes Mellitus',
  'adrenal-other': 'Adrenal & Other Endocrine',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'endocrinology';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>', '<title>HOSA Prep Hub — Endocrinology</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>', '<h1>Endo<em>crinology</em>.</h1>', 1)
html = html.replace('A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
                    'A study companion for pituitary disorders, thyroid disease, diabetes mellitus, and adrenal and other endocrine conditions — built for HOSA competitors.', 1)
html = html.replace('//  DATA — HOSA Emergency Medical Science', '//  DATA — HOSA Endocrinology', 1)
with open(DST, 'w', encoding='utf-8') as f: f.write(html)
print(f'Wrote {DST} — {TERMS_JS.count("{ term:")} terms')
