#!/usr/bin/env python3
"""Generate oncology.html from dental-science.html template."""
import os, re
BASE = '/home/user/hosa-prep-hub'
SRC, DST = os.path.join(BASE, 'dental-science.html'), os.path.join(BASE, 'oncology.html')
with open(SRC, 'r', encoding='utf-8') as f: html = f.read()
TERMS_JS = '''const TERMS = [
  // ── Cancer Biology ───────────────────────────────────────────
  { term: "Hallmarks of Cancer", type: "concept", category: "biology", meaning: "Hanahan/Weinberg's six core capabilities of cancer cells: sustained proliferative signaling, evading growth suppressors, resisting cell death, enabling replicative immortality, inducing angiogenesis, activating invasion and metastasis. Plus emerging: reprogramming metabolism, immune evasion.", example: "The tumor's overexpression of VEGF (angiogenesis) and resistance to apoptosis (anti-cell death) exemplified two classic hallmarks of cancer." },
  { term: "Oncogenes vs Tumor Suppressors", type: "concept", category: "biology", meaning: "Oncogenes: mutated/overactive genes driving proliferation (RAS, MYC, HER2). Tumor suppressors: protective genes whose loss permits cancer (TP53, RB1, BRCA1/2, APC). Oncogenes 'step on gas'; tumor suppressors 'brakes that fail'.", example: "HER2 amplification (oncogene) drives some breast cancers and is targeted by trastuzumab — antibody therapy against HER2." },
  { term: "Carcinogens", type: "concept", category: "biology", meaning: "Agents causing cancer: chemical (tobacco smoke, asbestos, alcohol), physical (UV, ionizing radiation), biological (HPV → cervical; HBV/HCV → liver; H. pylori → gastric; EBV → lymphoma). Many require chronic exposure.", example: "The patient's lung adenocarcinoma was linked to her 40 pack-year smoking history — tobacco is the leading chemical carcinogen." },
  { term: "Metastasis", type: "concept", category: "biology", meaning: "Spread of cancer cells from primary site to distant organs via lymphatic (most carcinomas), hematogenous (sarcomas, lung→brain), or transcoelomic (ovarian→peritoneum). Common sites: lung, liver, bone, brain.", example: "The patient's lung cancer metastasized hematogenously to brain and adrenal glands — distant spread that defined Stage IV disease." },
  { term: "Carcinoma vs Sarcoma vs Lymphoma vs Leukemia", type: "concept", category: "biology", meaning: "Carcinoma: epithelial origin (90% of cancers — breast, lung, colon, prostate). Sarcoma: mesenchymal (bone, muscle, fat). Lymphoma: lymphoid tissue. Leukemia: bone marrow/blood. Names reflect tissue of origin.", example: "The pathology report distinguished invasive ductal carcinoma (epithelial breast) from osteosarcoma (mesenchymal bone) — two fundamentally different cancer types." },
  { term: "Benign vs Malignant", type: "concept", category: "biology", meaning: "Benign: well-differentiated, slow-growing, encapsulated, no invasion or metastasis (lipoma, fibroadenoma). Malignant: poorly differentiated, rapid growth, invasive, metastasizes (carcinoma, sarcoma). Behavior — not appearance — defines malignancy.", example: "The breast biopsy showed a well-circumscribed fibroadenoma — benign — versus the patient's other breast lesion of invasive ductal carcinoma." },

  // ── Common Cancers ───────────────────────────────────────────
  { term: "Lung Cancer", type: "concept", category: "common-cancers", meaning: "Leading cancer death cause. Small cell (15%, aggressive, paraneoplastic SIADH, ectopic ACTH, treated with chemo/RT) vs Non-small cell (85% — adenocarcinoma most common, squamous, large cell — surgery if early stage).", example: "Bronchoscopy revealed an EGFR-mutated adenocarcinoma; the patient was treated with osimertinib targeted therapy." },
  { term: "Breast Cancer", type: "concept", category: "common-cancers", meaning: "Most common female cancer. Receptor subtypes: ER/PR-positive (responsive to hormonal therapy — tamoxifen, AI); HER2-positive (trastuzumab); triple-negative (chemotherapy mainstay). Screening with mammography starting age 40–50.", example: "The patient's ER-positive, HER2-negative invasive ductal carcinoma was treated with lumpectomy, radiation, and 5 years of tamoxifen." },
  { term: "Colorectal Cancer", type: "concept", category: "common-cancers", meaning: "Adenocarcinoma from APC pathway mutations; develops via adenoma-carcinoma sequence over years. Screening: colonoscopy every 10 years starting age 45 (or earlier with risk). Treatment: surgery, FOLFOX chemotherapy, biologics (cetuximab, bevacizumab).", example: "The screening colonoscopy at age 45 detected a 2 cm villous adenoma — precursor lesion removed before malignant transformation could occur." },
  { term: "Prostate Cancer", type: "concept", category: "common-cancers", meaning: "Most common cancer in men; usually adenocarcinoma of peripheral zone. PSA screening controversial. Gleason score grades aggressiveness. Treatment: active surveillance (low-risk), prostatectomy, radiation, androgen deprivation.", example: "The patient's elevated PSA (8.4) led to biopsy showing Gleason 7 adenocarcinoma; robotic prostatectomy was performed." },
  { term: "Melanoma", type: "concept", category: "common-cancers", meaning: "Aggressive skin cancer from melanocytes. ABCDE: Asymmetry, Border irregularity, Color variegation, Diameter >6mm, Evolution. Breslow depth determines staging. Immunotherapy (pembrolizumab) and BRAF-targeted therapy revolutionized advanced disease.", example: "The 8 mm asymmetric pigmented lesion with irregular borders met ABCDE criteria; excisional biopsy confirmed melanoma with Breslow depth 1.2 mm." },
  { term: "Leukemia (AML, ALL, CML, CLL)", type: "concept", category: "common-cancers", meaning: "AML: acute myeloid, adults. ALL: acute lymphoblastic, children (highly curable). CML: chronic myeloid, Philadelphia chromosome (BCR-ABL) → imatinib. CLL: chronic lymphocytic, older adults, often indolent.", example: "The child's pancytopenia, blasts on smear, and TdT-positive immunophenotyping confirmed ALL; >85% cure rate with multi-agent chemotherapy." },
  { term: "Lymphoma (Hodgkin vs Non-Hodgkin)", type: "concept", category: "common-cancers", meaning: "Hodgkin: bimodal age, Reed-Sternberg cells, contiguous spread, highly curable. Non-Hodgkin: heterogeneous (DLBCL most common aggressive, follicular indolent); diffuse spread. Both treated with combination chemotherapy ± immunotherapy.", example: "The young man's cervical lymphadenopathy with Reed-Sternberg cells confirmed Hodgkin lymphoma; ABVD chemotherapy achieved complete remission." },
  { term: "Pancreatic Cancer", type: "concept", category: "common-cancers", meaning: "Highly lethal; presents late with painless jaundice, weight loss, abdominal pain. KRAS mutation in 90%. Whipple resection only curative option for resectable disease. Median survival in metastatic disease <1 year.", example: "The patient's painless jaundice and weight loss prompted CT showing pancreatic head mass with double-duct sign — pancreatic adenocarcinoma." },

  // ── Diagnosis & Staging ──────────────────────────────────────
  { term: "TNM Staging", type: "concept", category: "diagnosis-staging", meaning: "Universal cancer staging: T (Tumor size/invasion), N (Nodal involvement), M (Metastasis). Combined into Stage I (localized) to IV (distant metastases). Guides treatment and prognosis.", example: "The colon cancer was staged T3N1M0 — Stage IIIB — with regional nodal involvement but no distant metastases, prompting surgery plus adjuvant chemotherapy." },
  { term: "Biopsy Types", type: "concept", category: "diagnosis-staging", meaning: "Fine needle aspiration (cytology, fastest), core needle (preserves architecture), incisional (partial tumor sample), excisional (removes entire lesion). Required for definitive cancer diagnosis.", example: "The breast mass was sampled by core needle biopsy under ultrasound guidance, preserving tissue architecture for invasive vs in situ classification." },
  { term: "Tumor Markers", type: "concept", category: "diagnosis-staging", meaning: "Substances elevated in cancer used for monitoring (rarely screening): CEA (colorectal), AFP (hepatocellular, germ cell), PSA (prostate), CA-125 (ovarian), CA 19-9 (pancreatic), βhCG (germ cell, trophoblastic), LDH (lymphoma).", example: "The post-treatment CEA tracking allowed early detection of colorectal cancer recurrence — rising from 2 to 18 prompted restaging imaging." },
  { term: "Imaging in Cancer", type: "concept", category: "diagnosis-staging", meaning: "CT: anatomic detail. MRI: soft tissue/brain/spine. PET-CT: metabolic activity (FDG uptake by hypermetabolic tumors). Bone scan: skeletal metastases. Each modality used for staging and surveillance.", example: "The patient's PET-CT showed FDG-avid mediastinal lymph nodes and a liver lesion — staging upgraded from IIIA to IV." },
  { term: "Performance Status (ECOG/KPS)", type: "concept", category: "diagnosis-staging", meaning: "Standardized assessment of patient functional capacity. ECOG 0 (fully active) – 4 (bedridden). Karnofsky 100 (normal) – 0 (dead). Determines treatment tolerance; poor PS contraindicates aggressive therapy.", example: "The patient's ECOG performance status of 3 (in bed >50% of day) precluded aggressive chemotherapy; best supportive care was chosen." },

  // ── Cancer Treatment ─────────────────────────────────────────
  { term: "Chemotherapy Classes", type: "concept", category: "treatment", meaning: "Alkylating (cyclophosphamide — DNA crosslinks). Antimetabolites (5-FU, methotrexate — DNA synthesis). Anthracyclines (doxorubicin — topoisomerase II, cardiotoxic). Taxanes (paclitaxel — microtubule stabilizers). Platinums (cisplatin — nephrotoxic, ototoxic).", example: "The breast cancer regimen 'AC-T' combined doxorubicin/cyclophosphamide followed by paclitaxel — alkylator + anthracycline → taxane." },
  { term: "Radiation Therapy", type: "concept", category: "treatment", meaning: "Ionizing radiation damages DNA of dividing cells. External beam (most common), brachytherapy (radioactive sources inside body), stereotactic (focused high dose). Used curative, adjuvant, palliative. Acute side effects: skin reaction, fatigue, organ-specific.", example: "After lumpectomy the patient received 5 weeks of external beam radiation to the breast — adjuvant therapy reducing local recurrence risk by ~50%." },
  { term: "Immunotherapy (Checkpoint Inhibitors)", type: "concept", category: "treatment", meaning: "PD-1 inhibitors (pembrolizumab, nivolumab), PD-L1 inhibitors (atezolizumab), CTLA-4 (ipilimumab) release immune brakes on T cells. Revolutionary in melanoma, NSCLC, renal, bladder. Side effects: autoimmune-like (colitis, hepatitis, pneumonitis).", example: "The metastatic melanoma patient received pembrolizumab with complete response — checkpoint inhibition unleashed T-cell attack on tumor." },
  { term: "Targeted Therapy", type: "concept", category: "treatment", meaning: "Drugs targeting specific molecular alterations: trastuzumab (HER2), imatinib (BCR-ABL), erlotinib/osimertinib (EGFR), vemurafenib (BRAF), olaparib (BRCA/PARP). Requires biomarker testing to identify candidates.", example: "Testing revealed the patient's NSCLC harbored an EGFR exon 19 deletion — osimertinib was started with dramatic response." },
  { term: "Bone Marrow Transplant", type: "concept", category: "treatment", meaning: "Autologous (patient's own cells, after high-dose chemo) or allogeneic (donor cells, also provides graft-vs-leukemia effect). Used for leukemias, lymphomas, multiple myeloma. Complications: GVHD, infection, relapse.", example: "The AML patient underwent allogeneic stem cell transplant from her matched sibling, providing both rescue from chemotherapy and graft-versus-leukemia immunity." },
  { term: "Neutropenic Fever", type: "concept", category: "treatment", meaning: "ANC <500 plus fever ≥38.3°C — oncologic emergency in chemotherapy patients due to high infection mortality risk. Requires immediate broad-spectrum IV antibiotics (cefepime, piperacillin-tazobactam) within 1 hour.", example: "The post-chemotherapy patient's ANC of 200 and fever 38.8°C prompted immediate blood cultures and IV cefepime — neutropenic fever protocol." },
  { term: "Palliative and Hospice Care", type: "concept", category: "treatment", meaning: "Palliative: symptom-focused care alongside disease-directed treatment, at any stage. Hospice: comfort-focused care when prognosis <6 months and curative treatment stopped. Both improve quality of life and reduce symptom burden.", example: "After progression on third-line therapy, the patient transitioned from oncology to hospice care, focusing on comfort, family, and dignity in her remaining months." },
];'''
m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
html = html[:m.start()] + TERMS_JS + html[m.end():]
CAT = """const categoryLabel = c => ({
  'biology':           'Cancer Biology',
  'common-cancers':    'Common Cancers',
  'diagnosis-staging': 'Diagnosis & Staging',
  'treatment':         'Cancer Treatment',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'oncology';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>', '<title>HOSA Prep Hub — Oncology</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>', '<h1>Onco<em>logy</em>.</h1>', 1)
html = html.replace('A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
                    'A study companion for cancer biology, common cancers, diagnosis and staging, and modern cancer treatment — built for HOSA competitors.', 1)
html = html.replace('//  DATA — HOSA Emergency Medical Science', '//  DATA — HOSA Oncology', 1)
with open(DST, 'w', encoding='utf-8') as f: f.write(html)
print(f'Wrote {DST} — {TERMS_JS.count("{ term:")} terms')
