#!/usr/bin/env python3
"""Generate audiology.html from dental-science.html template."""
import os, re
BASE = '/home/user/hosa-prep-hub'
SRC, DST = os.path.join(BASE, 'dental-science.html'), os.path.join(BASE, 'audiology.html')
with open(SRC, 'r', encoding='utf-8') as f: html = f.read()
TERMS_JS = '''const TERMS = [
  // ── Auditory Anatomy & Physiology ────────────────────────────
  { term: "Outer Ear", type: "concept", category: "anatomy", meaning: "Auricle (pinna) collects sound; external auditory canal (~2.5 cm) directs sound to tympanic membrane. Cerumen-producing glands provide protection. Canal naturally amplifies frequencies around 3000 Hz (speech frequencies).", example: "Cerumen impaction in the patient's external canal caused a 30 dB conductive hearing loss that resolved with removal." },
  { term: "Middle Ear", type: "concept", category: "anatomy", meaning: "Air-filled cavity with three ossicles: malleus (attached to TM), incus, stapes (attached to oval window of inner ear). Acts as impedance-matching transformer, amplifying sound ~30 dB for transmission from air to fluid-filled cochlea.", example: "The patient's otosclerosis caused stapes fixation, preventing ossicular movement and causing progressive conductive hearing loss." },
  { term: "Cochlea and Hair Cells", type: "concept", category: "anatomy", meaning: "Snail-shaped fluid-filled inner ear containing organ of Corti with inner and outer hair cells. Tonotopic organization: high frequencies at base, low frequencies at apex. Outer hair cells amplify; inner hair cells transduce signal to CN VIII.", example: "Noise-induced hair cell damage at the cochlear base produces the characteristic high-frequency hearing loss seen on audiograms." },
  { term: "Auditory Pathway", type: "concept", category: "anatomy", meaning: "Cochlea → CN VIII (vestibulocochlear) → cochlear nucleus → superior olivary complex → lateral lemniscus → inferior colliculus → medial geniculate body (thalamus) → primary auditory cortex (Heschl gyrus, temporal lobe).", example: "Acoustic neuroma compressed CN VIII, causing progressive unilateral sensorineural hearing loss and tinnitus." },
  { term: "Vestibular System", type: "concept", category: "anatomy", meaning: "Inner ear balance organs: three semicircular canals (angular acceleration), utricle and saccule (linear acceleration and gravity). Signals via vestibular nerve to brainstem. Dysfunction causes vertigo, imbalance, nystagmus.", example: "Calcium debris in the posterior semicircular canal caused BPPV; Epley maneuver repositioned the otoconia." },

  // ── Hearing Loss Types ───────────────────────────────────────
  { term: "Conductive Hearing Loss", type: "concept", category: "hearing-loss", meaning: "Sound transmission impaired in outer/middle ear: cerumen, otitis media, perforation, otosclerosis, ossicular discontinuity. Air-bone gap on audiogram. Often correctable. Weber lateralizes to affected ear; Rinne: bone > air.", example: "The patient's otosclerosis caused 40 dB conductive loss with air-bone gap; stapedectomy restored normal hearing." },
  { term: "Sensorineural Hearing Loss (SNHL)", type: "concept", category: "hearing-loss", meaning: "Cochlear or CN VIII dysfunction: presbycusis (age-related), noise-induced, ototoxicity (aminoglycosides, cisplatin), sudden SNHL, Meniere, acoustic neuroma. No air-bone gap. Weber lateralizes to BETTER ear; Rinne: air > bone (normal pattern).", example: "The patient's bilateral symmetric high-frequency SNHL from noise exposure was managed with hearing aids and hearing protection." },
  { term: "Mixed Hearing Loss", type: "concept", category: "hearing-loss", meaning: "Combined conductive and sensorineural components. Air-bone gap with reduced bone conduction (both elevated). Common in chronic ear disease (cholesteatoma) and otosclerosis with cochlear involvement.", example: "The patient with longstanding chronic otitis media and presbycusis had mixed hearing loss — surgical and amplification options were both considered." },
  { term: "Presbycusis", type: "concept", category: "hearing-loss", meaning: "Age-related sensorineural hearing loss affecting ~⅓ of those >65. Symmetric, bilateral, high-frequency. Difficulty hearing in noise (cocktail party problem). Treated with hearing aids; cochlear implants for severe cases.", example: "The 75-year-old's progressive difficulty understanding speech in restaurants reflected presbycusis; bilateral hearing aids dramatically improved communication." },
  { term: "Noise-Induced Hearing Loss (NIHL)", type: "concept", category: "hearing-loss", meaning: "Cochlear hair cell damage from chronic noise exposure (>85 dB) or acute acoustic trauma. Characteristic 'noise notch' at 4000 Hz on audiogram. Preventable with hearing protection; OSHA mandates protection at 85 dB.", example: "The construction worker's audiogram showed classic 4000 Hz noise notch; hearing protection education was reinforced and annual screening initiated." },
  { term: "Sudden Sensorineural Hearing Loss", type: "concept", category: "hearing-loss", meaning: "Unilateral SNHL of ≥30 dB across 3 contiguous frequencies developing within 72 hours. Urgent ENT referral. Most idiopathic; some viral, vascular, autoimmune. Oral corticosteroids within 2 weeks improve outcomes.", example: "The patient's overnight unilateral hearing loss was diagnosed as sudden SNHL within 24 hours; high-dose prednisone improved hearing." },

  // ── Assessment ───────────────────────────────────────────────
  { term: "Pure Tone Audiometry", type: "concept", category: "assessment", meaning: "Standard hearing test measuring thresholds at frequencies 250-8000 Hz for each ear; air conduction (headphones) and bone conduction (bone oscillator). Results plotted on audiogram. Normal: ≤25 dB HL; mild loss 26-40; moderate 41-55; severe 71-90; profound >90.", example: "The patient's audiogram showed normal hearing 250-2000 Hz, then sloping to 65 dB at 4000-8000 Hz — typical presbycusis pattern." },
  { term: "Tympanometry", type: "concept", category: "assessment", meaning: "Measures middle ear function and TM mobility by varying air pressure in ear canal. Type A: normal. Type B: flat — fluid, perforation. Type C: negative pressure — eustachian tube dysfunction. Quick objective test useful in children.", example: "The child's flat (type B) tympanogram with absent stapedial reflex confirmed middle ear effusion." },
  { term: "Otoacoustic Emissions (OAEs)", type: "concept", category: "assessment", meaning: "Sounds generated by outer hair cells measurable in ear canal. Present with normal cochlear function; absent with hair cell damage. Used in newborn hearing screening and to distinguish cochlear vs retrocochlear pathology.", example: "The newborn's failed OAE screen prompted further testing — eventual diagnosis of bilateral sensorineural hearing loss." },
  { term: "Auditory Brainstem Response (ABR)", type: "concept", category: "assessment", meaning: "Electrophysiologic test of auditory pathway from CN VIII to brainstem. Used in infants who can't perform behavioral audiometry, to estimate hearing thresholds, and to identify retrocochlear pathology (acoustic neuroma).", example: "The newborn's elevated ABR thresholds confirmed bilateral severe hearing loss; cochlear implant candidacy was discussed." },
  { term: "Speech Audiometry", type: "concept", category: "assessment", meaning: "Speech Reception Threshold (SRT): lowest level at which patient correctly repeats 50% of spondee words. Word Recognition Score (WRS): % correct of phonetically balanced words at suprathreshold level. WRS helps predict hearing aid benefit.", example: "The patient's WRS of 65% on the worse ear despite amplification suggested limited benefit from a hearing aid; cochlear implant evaluation was pursued." },
  { term: "Newborn Hearing Screening", type: "concept", category: "assessment", meaning: "Universal screening within first month using OAE and/or AABR. 1-3-6 principle: screen by 1 mo, diagnose by 3 mo, intervention by 6 mo. Early identification dramatically improves language outcomes.", example: "The newborn's failed screen led to confirmatory ABR at 6 weeks identifying severe bilateral hearing loss; hearing aids and early intervention began at 3 months." },

  // ── Treatment ────────────────────────────────────────────────
  { term: "Hearing Aids", type: "concept", category: "treatment", meaning: "Amplification devices with microphone, amplifier, receiver. Styles: behind-the-ear (BTE), in-the-ear (ITE), in-the-canal (ITC), completely-in-canal (CIC), receiver-in-canal (RIC). Digital signal processing customizes amplification by frequency.", example: "The patient's bilateral mild-moderate sensorineural hearing loss was fitted with BTE hearing aids — programmable to her specific audiogram." },
  { term: "Cochlear Implants", type: "concept", category: "treatment", meaning: "Surgically implanted device bypassing damaged hair cells, directly stimulating auditory nerve. Indicated for severe-profound SNHL with limited hearing aid benefit. External processor + internal receiver-electrode array. Requires intensive auditory rehabilitation.", example: "The patient with profound bilateral SNHL and limited hearing aid benefit received a cochlear implant; with rehabilitation she achieved excellent speech understanding." },
  { term: "Assistive Listening Devices (ALDs)", type: "concept", category: "treatment", meaning: "Beyond hearing aids: FM systems (transmitter to receiver), induction loops, infrared systems, captioned phones, alerting devices. Improve signal-to-noise ratio especially in classrooms, theaters, and large gatherings.", example: "The student with mild hearing loss received an FM system in the classroom — teacher's microphone transmitted directly to her hearing aids." },
  { term: "Tinnitus Management", type: "concept", category: "treatment", meaning: "Perception of sound without external source; often associated with hearing loss. Management: address underlying cause, hearing aids (most effective), sound masking, tinnitus retraining therapy, CBT for distress. No FDA-approved drug.", example: "The patient's chronic bilateral tinnitus with hearing loss improved significantly with bilateral hearing aids — providing amplification and partial masking." },
  { term: "Vestibular Rehabilitation", type: "concept", category: "treatment", meaning: "Exercise-based therapy for chronic vertigo, imbalance, dizziness. Includes gaze stabilization, balance training, habituation exercises. Specific maneuvers (Epley, Semont) for BPPV. Highly effective for many vestibular disorders.", example: "The patient with chronic vestibular hypofunction after vestibular neuritis improved significantly with 6 weeks of vestibular physical therapy." },
];'''
m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
html = html[:m.start()] + TERMS_JS + html[m.end():]
CAT = """const categoryLabel = c => ({
  'anatomy':       'Auditory Anatomy & Physiology',
  'hearing-loss':  'Hearing Loss Types',
  'assessment':    'Audiologic Assessment',
  'treatment':     'Treatment & Rehabilitation',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'audiology';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>', '<title>HOSA Prep Hub — Audiology</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>', '<h1>Audio<em>logy</em>.</h1>', 1)
html = html.replace('A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
                    'A study companion for auditory anatomy and physiology, types of hearing loss, audiologic assessment, and hearing rehabilitation including hearing aids and cochlear implants — built for HOSA competitors.', 1)
html = html.replace('//  DATA — HOSA Emergency Medical Science', '//  DATA — HOSA Audiology', 1)
with open(DST, 'w', encoding='utf-8') as f: f.write(html)
print(f'Wrote {DST} — {TERMS_JS.count("{ term:")} terms')
