#!/usr/bin/env python3
"""Generate physical-medicine-rehabilitation.html from dental-science.html template."""
import os, re
BASE = '/home/user/hosa-prep-hub'
SRC, DST = os.path.join(BASE, 'dental-science.html'), os.path.join(BASE, 'physical-medicine-rehabilitation.html')
with open(SRC, 'r', encoding='utf-8') as f: html = f.read()
TERMS_JS = '''const TERMS = [
  // ── Rehabilitation Foundations ───────────────────────────────
  { term: "Scope of PM&R", type: "concept", category: "foundations", meaning: "Physical medicine and rehabilitation (physiatry) focuses on restoring function and quality of life after injury, illness, or disabling conditions. Treats musculoskeletal injuries, spinal cord injury, stroke, TBI, amputation, chronic pain, and neuromuscular disease. Coordinates multidisciplinary rehab teams.", example: "The physiatrist coordinated the stroke patient's rehab team — PT for gait, OT for ADLs, SLP for aphasia, and neuropsychology for cognition." },
  { term: "Rehabilitation Team & Settings", type: "concept", category: "foundations", meaning: "Team: physiatrist, PT (mobility), OT (ADLs, fine motor), SLP (speech/swallow), rehab nurse, case manager, social worker, psychologist, prosthetist/orthotist. Settings: acute inpatient rehab (3h therapy/day), subacute/SNF, outpatient, home health. Level determined by function and goals.", example: "The patient post-TKA met criteria for acute inpatient rehab with 3 hours of PT/OT daily; discharged home with outpatient PT after 5 days." },
  { term: "Functional Independence Measure (FIM)", type: "concept", category: "foundations", meaning: "18-item scale rating 7 levels of independence (1=total assist, 7=complete independence) across self-care, sphincter control, transfers, locomotion, communication, social cognition. Total 18–126. Used to measure rehab progress and predict discharge needs.", example: "The patient's FIM improved from 42 at admission to 98 at discharge from inpatient stroke rehab — reflecting gains in dressing, transfers, and ambulation." },

  // ── Stroke & Neurological Rehabilitation ─────────────────────
  { term: "Stroke Rehabilitation", type: "concept", category: "neuro-rehab", meaning: "Begins as early as 24–48h post-stroke when medically stable. Key deficits: hemiplegia/hemiparesis, aphasia, dysphagia, neglect, spasticity, hemianopia. PT: gait, transfers. OT: ADLs, hand function. SLP: communication, swallowing. Goal: maximize neurological recovery via neuroplasticity.", example: "The stroke patient with left hemiplegia and Broca aphasia began early mobilization at day 2; 3 weeks of inpatient rehab improved her FIM from 38 to 89." },
  { term: "Spasticity Management", type: "concept", category: "neuro-rehab", meaning: "Velocity-dependent resistance from upper motor neuron injury (stroke, SCI, TBI, MS, CP). Interferes with function, hygiene, positioning. Treatment: stretching, splinting, physical therapy; oral medications (baclofen, tizanidine, dantrolene, diazepam); intramuscular botulinum toxin; intrathecal baclofen pump for severe.", example: "The stroke patient's severe ankle spasticity preventing ambulation was treated with botulinum toxin injections to the gastrocnemius — improving gait pattern within 2 weeks." },
  { term: "Traumatic Brain Injury (TBI) Rehabilitation", type: "concept", category: "neuro-rehab", meaning: "Rancho Los Amigos scale tracks cognitive recovery (I=no response to X=purposeful, appropriate). Deficits: cognitive, behavioral, motor. Cognitive-behavioral rehab: memory compensatory strategies, behavioral modification. Community reintegration. Agitation management: amantadine (promotes recovery).", example: "The moderate TBI patient at Rancho Level V (confused, inappropriate) benefited from structured environment, low-stimulation therapy, and amantadine; advanced to Level VII in 3 weeks." },

  // ── Spinal Cord Injury ───────────────────────────────────────
  { term: "Spinal Cord Injury (SCI) Classification", type: "concept", category: "sci", meaning: "ASIA (American Spinal Injury Association) Impairment Scale: A=complete (no motor/sensory below lesion), B=sensory only preserved, C=motor preserved <grade 3, D=motor preserved ≥grade 3, E=normal. Level determined by lowest intact motor and sensory segment.", example: "The patient's C5 ASIA A injury meant he was complete at C5 — preserved elbow flexion but no wrist extension — classified as tetraplegia, ASIA A." },
  { term: "SCI Complications", type: "concept", category: "sci", meaning: "Neurogenic bladder: intermittent catheterization prevents UTI, stone, renal failure. Pressure injuries: repositioning, specialized mattresses. DVT: anticoagulation prophylaxis. Autonomic dysreflexia (injury ≥T6): massive sympathetic surge from noxious stimuli below lesion — HTN crisis, bradycardia, diaphoresis; remove stimulus, sit up, antihypertensives.", example: "The T4 SCI patient's sudden BP of 200/110 with headache and diaphoresis was autonomic dysreflexia from a kinked catheter — removing the kink resolved the crisis." },

  // ── Musculoskeletal & Amputee Care ───────────────────────────
  { term: "Gait Analysis & Assistive Devices", type: "concept", category: "msk-amputee", meaning: "Normal gait cycle: stance phase (60%) and swing phase (40%). Gait deviations: Trendelenburg (hip abductor weakness), steppage gait (foot drop), antalgic gait (pain). Assistive devices: cane (opposite weak leg), walker (bilateral), crutches. Wheelchair prescription by functional level.", example: "The patient's ipsilateral trunk shift and pelvic drop during gait were Trendelenburg signs from hip abductor weakness — a cane in the contralateral hand reduced deviation." },
  { term: "Amputation Levels & Prosthetics", type: "concept", category: "msk-amputee", meaning: "Lower extremity: transtibial (below knee, better ambulation), transfemoral (above knee, more energy cost), hip disarticulation. Upper extremity: transradial, transhumeral. Prosthetic rehabilitation: residual limb shaping, prosthetic fitting, gait training. Energy expenditure increases with more proximal amputation.", example: "The transtibial amputee required 25% more energy to ambulate than a normal limb — a modular prosthesis with energy-return foot improved gait efficiency." },
  { term: "Orthoses and Splinting", type: "concept", category: "msk-amputee", meaning: "Orthosis: external device to support, correct, or prevent deformity. Lower extremity: AFO (ankle-foot orthosis) for foot drop, KAFO for knee instability. Upper extremity: resting hand splint (MCP/wrist in functional position), dynamic splints. Cervical collars: soft (mild), hard (Philadelphia), halo (unstable fracture).", example: "The stroke patient's foot drop during swing phase was corrected with an AFO — maintaining neutral dorsiflexion and preventing toe-catch." },
  { term: "Electrodiagnostics (EMG/NCS)", type: "concept", category: "msk-amputee", meaning: "Nerve conduction studies (NCS): measures nerve conduction velocity and amplitude — identifies neuropathy, demyelination vs axon loss. Electromyography (EMG): evaluates muscle electrical activity at rest (fibrillations, positive waves = denervation) and with contraction — differentiates radiculopathy from neuropathy from myopathy.", example: "The patient's foot drop NCS showed slowed peroneal velocity with preserved amplitude — demyelinating peroneal neuropathy at the fibular head from prolonged crossing of legs." },
];'''
m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
html = html[:m.start()] + TERMS_JS + html[m.end():]
CAT = """const categoryLabel = c => ({
  'foundations': 'Rehabilitation Foundations',
  'neuro-rehab': 'Stroke & Neurological Rehabilitation',
  'sci':         'Spinal Cord Injury',
  'msk-amputee': 'Musculoskeletal & Amputee Care',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'physical-medicine-rehabilitation';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>', '<title>HOSA Prep Hub — Physical Medicine & Rehabilitation</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>', '<h1>Physical Medicine &amp;<br><em>Rehabilitation</em>.</h1>', 1)
html = html.replace('A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
                    'A study companion for rehabilitation foundations and the rehab team, stroke and neurological rehabilitation, spinal cord injury and its complications, and musculoskeletal medicine and amputee care — built for HOSA competitors.', 1)
html = html.replace('//  DATA — HOSA Emergency Medical Science', '//  DATA — HOSA Physical Medicine & Rehabilitation', 1)
with open(DST, 'w', encoding='utf-8') as f: f.write(html)
print(f'Wrote {DST} — {TERMS_JS.count("{ term:")} terms')
