#!/usr/bin/env python3
"""Generate nephrology.html from dental-science.html template."""
import os, re
BASE = '/home/user/hosa-prep-hub'
SRC, DST = os.path.join(BASE, 'dental-science.html'), os.path.join(BASE, 'nephrology.html')
with open(SRC, 'r', encoding='utf-8') as f: html = f.read()
TERMS_JS = '''const TERMS = [
  // ── Kidney Anatomy & Physiology ──────────────────────────────
  { term: "Nephron Structure", type: "concept", category: "anatomy", meaning: "Functional unit of the kidney (~1 million per kidney). Glomerulus + Bowman capsule → proximal tubule → loop of Henle → distal tubule → collecting duct. Filters ~180 L of plasma daily; reabsorbs 99%.", example: "The patient's GFR of 25 mL/min reflected loss of functional nephrons after years of uncontrolled diabetes." },
  { term: "Glomerular Filtration Rate (GFR)", type: "concept", category: "anatomy", meaning: "Volume of plasma filtered by glomeruli per minute (~125 mL/min normal). Estimated by creatinine-based equations (CKD-EPI). CKD stages: G1 (≥90), G2 (60-89), G3a (45-59), G3b (30-44), G4 (15-29), G5/ESRD (<15).", example: "eGFR of 38 mL/min placed the patient in CKD stage G3b; nephrology referral and renal-dose adjustments were initiated." },
  { term: "RAAS (Renin-Angiotensin-Aldosterone System)", type: "concept", category: "anatomy", meaning: "Renin (from JG cells) → angiotensin I → ACE → angiotensin II → vasoconstriction + aldosterone release → Na retention. Inhibited by ACEi (-pril), ARBs (-sartan), MRAs (spironolactone).", example: "Lisinopril blocked ACE, reducing angiotensin II and providing renoprotection in the patient's diabetic nephropathy." },
  { term: "Tubular Reabsorption Sites", type: "concept", category: "anatomy", meaning: "PCT: 65% Na, glucose, amino acids, bicarbonate (target of SGLT2 inhibitors). Loop of Henle: 25% Na via NKCC2 (loop diuretics). DCT: NaCl cotransporter (thiazides). Collecting duct: aldosterone-Na, ADH-water.", example: "Furosemide blocked NKCC2 in the loop of Henle, producing potent diuresis in the patient's CHF exacerbation." },

  // ── Fluid, Electrolyte & Acid-Base ───────────────────────────
  { term: "Hyponatremia", type: "concept", category: "fluid-electrolyte", meaning: "Serum Na <135. Classified by volume status: hypovolemic (diuretics, vomiting), euvolemic (SIADH, hypothyroid), hypervolemic (HF, cirrhosis, nephrosis). Correct slowly (<8-10 mEq/24h) to avoid osmotic demyelination.", example: "The SCLC patient's Na of 118 with concentrated urine confirmed SIADH; fluid restriction and tolvaptan corrected it slowly." },
  { term: "Hyperkalemia", type: "concept", category: "fluid-electrolyte", meaning: "Serum K >5.0; emergency if >6.5 with EKG changes (peaked T waves → wide QRS → sine wave). Causes: AKI, CKD, ACEi/ARB, K-sparing diuretics, rhabdomyolysis. Treat: calcium (stabilize myocardium), insulin/D50, albuterol, kayexalate, dialysis.", example: "The CKD patient's K of 7.2 with peaked T waves prompted emergent IV calcium gluconate, insulin/dextrose, and emergent hemodialysis." },
  { term: "Hypocalcemia and Hypercalcemia", type: "concept", category: "fluid-electrolyte", meaning: "Hypocalcemia (Ca <8.5): tetany, Chvostek/Trousseau signs, prolonged QT. Causes: hypoparathyroidism, vit D deficiency, CKD. Hypercalcemia (>10.5): 'stones, bones, groans, thrones, psych overtones'. Most common cause: malignancy, hyperparathyroidism.", example: "The multiple myeloma patient's Ca of 14.5 prompted IV fluids, calcitonin, and zoledronic acid for severe hypercalcemia of malignancy." },
  { term: "Metabolic Acidosis (Anion Gap)", type: "concept", category: "fluid-electrolyte", meaning: "AG = Na - (Cl + HCO3); normal 8-12. High AG: 'MUDPILES' — Methanol, Uremia, DKA, Propylene glycol, Iron/INH, Lactic acidosis, Ethylene glycol, Salicylates. Normal AG: GI loss, RTA.", example: "The patient's pH 7.18, HCO3 12, anion gap 28, lactate 8 confirmed lactic acidosis from septic shock." },
  { term: "Acid-Base Disorders (Compensation)", type: "concept", category: "fluid-electrolyte", meaning: "Metabolic acidosis: ↓HCO3, respiratory compensation ↓PaCO2 (Winter formula: PaCO2 = 1.5×HCO3 + 8 ± 2). Metabolic alkalosis: ↑HCO3. Respiratory acidosis: ↑PaCO2. Respiratory alkalosis: ↓PaCO2. Mixed disorders common.", example: "The DKA patient's pH 7.10, HCO3 8 had appropriate respiratory compensation: predicted PaCO2 = 1.5(8)+8 = 20; measured 22 — pure metabolic acidosis." },

  // ── Acute & Chronic Kidney Disease ───────────────────────────
  { term: "Acute Kidney Injury (AKI)", type: "concept", category: "akd-ckd", meaning: "Sudden ↓ kidney function: KDIGO criteria — Cr rise ≥0.3 mg/dL in 48h, ≥1.5× baseline in 7 days, or urine output <0.5 mL/kg/h for 6h. Three categories: prerenal, intrinsic, postrenal.", example: "The hospitalized patient's Cr rose from 1.0 to 2.4 over 3 days after IV contrast — contrast-induced AKI met KDIGO criteria." },
  { term: "Prerenal vs Intrinsic vs Postrenal AKI", type: "concept", category: "akd-ckd", meaning: "Prerenal: hypoperfusion (dehydration, shock, HF); FENa <1%, BUN/Cr >20. Intrinsic: parenchymal damage (ATN, glomerulonephritis, AIN); FENa >2%. Postrenal: obstruction (stones, BPH, mass); hydronephrosis on imaging.", example: "The septic patient's FENa <1% and BUN/Cr ratio 35 indicated prerenal AKI; IV fluid resuscitation restored kidney function within 48 hours." },
  { term: "Chronic Kidney Disease (CKD)", type: "concept", category: "akd-ckd", meaning: "GFR <60 for ≥3 months or kidney damage markers. Causes: diabetes (#1), hypertension (#2), glomerulonephritis. Complications: anemia, mineral bone disease, hyperkalemia, acidosis, CV disease. Treatment: ACEi/ARB, SGLT2i, BP control.", example: "The diabetic patient's eGFR 32, proteinuria 1.2 g/day, and 5-year decline confirmed CKD G3b A3; SGLT2 inhibitor was added for renoprotection." },
  { term: "Glomerulonephritis", type: "concept", category: "akd-ckd", meaning: "Inflammation of glomeruli with hematuria, RBC casts, proteinuria, hypertension. Nephritic syndrome. Examples: post-strep GN, IgA nephropathy (Berger), lupus nephritis, ANCA-associated vasculitis, anti-GBM (Goodpasture).", example: "The patient's hematuria with RBC casts 2 weeks after strep pharyngitis confirmed post-streptococcal glomerulonephritis." },
  { term: "Nephrotic Syndrome", type: "concept", category: "akd-ckd", meaning: "Proteinuria >3.5 g/day, hypoalbuminemia, edema, hyperlipidemia. Adults: membranous nephropathy, FSGS, diabetic. Children: minimal change disease. Treated with steroids; ACEi/ARB to reduce proteinuria.", example: "The patient's 8 g/day proteinuria, albumin 1.8, and severe edema confirmed nephrotic syndrome; renal biopsy showed FSGS." },

  // ── Stones, Dialysis & Transplant ────────────────────────────
  { term: "Nephrolithiasis (Kidney Stones)", type: "concept", category: "stones-dialysis", meaning: "Calcium oxalate most common (75%). Severe flank pain radiating to groin, hematuria. CT non-contrast for diagnosis. Treatment: fluids, NSAIDs/opioids for pain, alpha-blocker (tamsulosin) for stones <10 mm; lithotripsy or ureteroscopy for larger.", example: "The patient's severe flank-to-groin pain with hematuria and 6 mm proximal ureteral stone on CT was managed with tamsulosin and pain control for spontaneous passage." },
  { term: "Hemodialysis", type: "concept", category: "stones-dialysis", meaning: "Blood diffuses across semipermeable membrane against dialysate; typically 4 hours, 3× weekly. Requires vascular access (AV fistula preferred, AV graft, or central catheter). Removes water, solutes, electrolytes, toxins.", example: "After CKD stage 5 progression, the patient received an AV fistula and started outpatient hemodialysis 3 times weekly." },
  { term: "Peritoneal Dialysis", type: "concept", category: "stones-dialysis", meaning: "Dialysate instilled into peritoneal cavity via permanent catheter; uses peritoneum as membrane. CAPD (manual exchanges 4×/day) or APD (automated overnight). Home-based, less hemodynamic stress, peritonitis risk.", example: "The patient chose peritoneal dialysis for at-home flexibility; cloudy dialysate and abdominal pain on day 60 indicated PD peritonitis." },
  { term: "Renal Transplantation", type: "concept", category: "stones-dialysis", meaning: "Best long-term outcome for ESRD. Sources: living donor (better outcomes, faster), deceased donor. Requires lifelong immunosuppression (calcineurin inhibitor + antimetabolite + steroids). Rejection types: hyperacute, acute, chronic.", example: "The patient received a living-related donor kidney from her sister; tacrolimus, mycophenolate, and prednisone prevented rejection." },
  { term: "Uremia and Indications for Dialysis", type: "concept", category: "stones-dialysis", meaning: "Mnemonic 'AEIOU': Acidosis (refractory), Electrolyte (hyperK refractory), Ingestion (toxins — lithium, methanol), Overload (refractory fluid), Uremia (encephalopathy, pericarditis, bleeding). Indicates urgent dialysis.", example: "The CKD patient's uremic encephalopathy and pericardial friction rub were indications for urgent initiation of hemodialysis." },
];'''
m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
html = html[:m.start()] + TERMS_JS + html[m.end():]
CAT = """const categoryLabel = c => ({
  'anatomy':           'Kidney Anatomy & Physiology',
  'fluid-electrolyte': 'Fluid, Electrolyte & Acid-Base',
  'akd-ckd':           'Acute & Chronic Kidney Disease',
  'stones-dialysis':   'Stones, Dialysis & Transplant',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'nephrology';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>', '<title>HOSA Prep Hub — Nephrology</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>', '<h1>Nephro<em>logy</em>.</h1>', 1)
html = html.replace('A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
                    'A study companion for kidney anatomy and physiology, fluid and electrolyte and acid-base disorders, acute and chronic kidney disease, and dialysis and renal transplant — built for HOSA competitors.', 1)
html = html.replace('//  DATA — HOSA Emergency Medical Science', '//  DATA — HOSA Nephrology', 1)
with open(DST, 'w', encoding='utf-8') as f: f.write(html)
print(f'Wrote {DST} — {TERMS_JS.count("{ term:")} terms')
