#!/usr/bin/env python3
"""Generate surgical-technology.html from dental-science.html template."""
import os, re
BASE = '/home/user/hosa-prep-hub'
SRC, DST = os.path.join(BASE, 'dental-science.html'), os.path.join(BASE, 'surgical-technology.html')
with open(SRC, 'r', encoding='utf-8') as f: html = f.read()
TERMS_JS = '''const TERMS = [
  // ── OR Roles & Environment ───────────────────────────────────
  { term: "Surgical Team Roles", type: "concept", category: "or-roles", meaning: "Surgeon (performs procedure), first assistant (helps surgeon), surgical tech/scrub (passes instruments, maintains sterile field), circulator RN (manages non-sterile environment, charts, counts), anesthesiologist/CRNA (anesthesia management).", example: "The scrub tech anticipated the surgeon's next instrument while the circulator documented and prepared additional supplies — coordinated team workflow." },
  { term: "Sterile vs Non-Sterile Personnel", type: "concept", category: "or-roles", meaning: "Sterile: scrubbed and gowned; remain at field, may only touch sterile items. Non-sterile (circulator, anesthesia): control environment, retrieve supplies, document. Sterile personnel pass each other back-to-back or front-to-front.", example: "When the circulator delivered additional sutures, she opened them onto the sterile field without contact while the scrub tech accepted them." },
  { term: "OR Suite Design", type: "concept", category: "or-roles", meaning: "Positive air pressure relative to corridors; HEPA-filtered laminar airflow; temperature 68–73°F; humidity 30–60%. Restricted (full OR attire), semi-restricted (hat/mask), unrestricted (street clothes) zones.", example: "The positive air pressure and HEPA filtration in the OR suite minimized airborne particles, reducing surgical site infection risk." },
  { term: "Surgical Attire", type: "concept", category: "or-roles", meaning: "Scrubs, head covering (covering all hair), mask covering nose and mouth, shoe covers, eye protection. Sterile personnel add cap, gown, gloves. Never wear OR attire outside the restricted area without a coverup.", example: "Before entering the semi-restricted corridor, the new staff member donned a bouffant hat and surgical mask per OR attire policy." },

  // ── Asepsis & Sterilization ──────────────────────────────────
  { term: "Surgical Scrub", type: "concept", category: "asepsis", meaning: "Antiseptic hand and forearm wash (chlorhexidine or povidone-iodine) to remove transient bacteria and reduce resident flora before donning sterile gown and gloves; traditional 5-min scrub or 3-min brushless scrub with alcohol-based agents.", example: "Before the first case the scrub tech performed a 3-minute brushless chlorhexidine scrub, then gowned and gloved using closed technique." },
  { term: "Sterile Field Setup", type: "concept", category: "asepsis", meaning: "Established with sterile drapes on the patient and Mayo stand/back table. Edges (1 inch) and below the table top are NOT sterile. Once established, only sterile items may touch it; contamination = redraping.", example: "When the surgeon's sleeve fell below the table edge, the scrub tech recognized contamination and changed gloves and gown immediately." },
  { term: "Sterile Principles", type: "concept", category: "asepsis", meaning: "Only sterile to sterile contact. Items below waist, behind back, or out of vision are unsterile. Sterile packages opened with edges away from sterile field. Never reach over sterile field. Wet drape = contaminated.", example: "The scrub tech turned to retrieve an instrument from the back table, keeping her sterile front visible to maintain sterile principles." },
  { term: "Autoclave Sterilization (Steam)", type: "concept", category: "asepsis", meaning: "Most common sterilization: saturated steam under pressure at 121°C, 15 psi, 15–30 minutes (or 132°C for 4 min flash). Kills all microorganisms including spores. Biological indicator (Geobacillus stearothermophilus) validates effectiveness.", example: "After the autoclave cycle, the biological indicator showed no growth — confirming sterilization had been achieved." },
  { term: "Ethylene Oxide (EtO) Sterilization", type: "concept", category: "asepsis", meaning: "Gas sterilization for heat-sensitive items (endoscopes, plastics). Long cycle times, requires aeration (toxic gas residue), space-intensive. Largely replaced by hydrogen peroxide gas plasma (Sterrad).", example: "The fiberoptic endoscope was processed by EtO sterilization — its heat-sensitive components could not tolerate autoclave temperatures." },
  { term: "High-Level Disinfection", type: "concept", category: "asepsis", meaning: "For semi-critical items (endoscopes contacting mucous membranes) — glutaraldehyde or ortho-phthalaldehyde. Kills all microbes except high numbers of spores. Distinct from sterilization (which kills all spores).", example: "After each colonoscopy, the scope underwent high-level disinfection with glutaraldehyde — appropriate for semi-critical mucous membrane contact." },

  // ── Instruments & Supplies ───────────────────────────────────
  { term: "Instrument Categories", type: "concept", category: "instruments", meaning: "Cutting (scalpel, scissors), grasping (forceps, clamps — Kelly, Crile, Allis, Babcock), retracting (Army-Navy, Richardson, Deaver), suturing (needle holders), suction (Yankauer, Frazier).", example: "The scrub tech organized the back table by category — sharps on a designated zone, then clamps, retractors, and suction set up for easy retrieval." },
  { term: "Scalpels (Knife Handles and Blades)", type: "concept", category: "instruments", meaning: "Handle #3 holds blades #10 (general skin), #11 (stab — pointed), #15 (precision — small fine cuts). Handle #4 holds larger #20–25 blades. Blades passed in a kidney basin or by hands-free technique.", example: "For the skin incision the surgeon requested a #10 blade on a #3 handle, which the scrub tech passed using hands-free technique into a basin." },
  { term: "Sutures (Absorbable vs Non-Absorbable)", type: "concept", category: "instruments", meaning: "Absorbable (chromic gut, polyglactin/Vicryl, poliglecaprone/Monocryl) — broken down by body. Non-absorbable (silk, nylon, polypropylene/Prolene) — permanent; require removal from skin. Sized 0 (largest) to 11-0 (microsurgery).", example: "The surgeon used 3-0 Vicryl absorbable for the fascial layer and 4-0 Prolene non-absorbable for the skin closure." },
  { term: "Needle Types", type: "concept", category: "instruments", meaning: "Cutting (skin, tough tissue) — triangular tip. Tapered (bowel, vessels, fascia) — round body. Body curvatures: ½ circle (general), ⅜ circle, straight (Keith — for skin). Color-coded packaging by needle type.", example: "For the abdominal closure the surgeon used a CT-1 ½-circle tapered needle on 0-PDS for the fascia — atraumatic tip appropriate for soft tissue." },
  { term: "Hemostatic Clamps (Kelly, Mosquito, Crile)", type: "concept", category: "instruments", meaning: "Mosquito (smallest, delicate bleeders), Kelly (medium curved, smooth jaws), Crile (medium, fully serrated jaws). Used to clamp bleeding vessels for ligation or cautery.", example: "The surgeon clamped the bleeding vessel with a small mosquito and the scrub tech immediately presented a 4-0 silk tie for ligation." },
  { term: "Retractors (Handheld vs Self-Retaining)", type: "concept", category: "instruments", meaning: "Handheld (Army-Navy, Richardson, Deaver, Sweetheart) require assistant to hold. Self-retaining (Weitlaner, Bookwalter, Balfour) ratchet open and hold themselves — free assistants for other tasks.", example: "The surgical assistant held the Richardson retractor exposing the abdominal cavity until the Bookwalter self-retaining retractor was set up." },
  { term: "Electrosurgery (Bovie)", type: "concept", category: "instruments", meaning: "Electric current to cut tissue or coagulate vessels. Monopolar: current passes through patient to grounding pad. Bipolar: current flows between two forceps tips — no grounding pad needed; safer near nerves and pacemakers.", example: "The surgeon used monopolar coagulation for general hemostasis but switched to bipolar forceps near the recurrent laryngeal nerve to minimize thermal injury." },

  // ── Procedures & Counts ──────────────────────────────────────
  { term: "Time Out (Universal Protocol)", type: "concept", category: "procedures-counts", meaning: "Joint Commission requirement: pause before incision to verify correct patient, correct site (marked), correct procedure, allergies, antibiotic prophylaxis, and team members. All team members must agree before proceeding.", example: "Before incision the entire team paused for time out: 'Jane Doe, MRN 12345, right total knee arthroplasty, no allergies, cefazolin given at 1230.'" },
  { term: "Surgical Counts", type: "concept", category: "procedures-counts", meaning: "Sponges, sharps, and instruments are counted before incision, before closure of each cavity, and at end of procedure. Both scrub tech and circulator count audibly together. Incorrect counts require X-ray and search.", example: "The closing count was incorrect (one missing lap sponge); the team performed a thorough search and X-ray, locating the retained sponge in the abdomen before final closure." },
  { term: "Surgical Site Infection (SSI) Prevention", type: "concept", category: "procedures-counts", meaning: "Prophylactic antibiotic within 60 min of incision (vancomycin within 120 min), clipping (not shaving) hair, chlorhexidine skin prep, normothermia, normoglycemia, minimal traffic in OR. Major patient safety target.", example: "The patient received cefazolin 30 minutes before incision per SSI prevention protocol; hair was clipped just before prep with chlorhexidine." },
  { term: "Surgical Skin Prep", type: "concept", category: "procedures-counts", meaning: "Chlorhexidine-alcohol (superior to povidone-iodine for most procedures) applied with friction in concentric circles from incision site outward; allow to dry per manufacturer instructions before draping (flammability with electrosurgery).", example: "The circulator prepped from the planned incision outward in concentric circles, allowed chlorhexidine-alcohol to dry for 3 minutes, then draping began." },
  { term: "Patient Positioning", type: "concept", category: "procedures-counts", meaning: "Supine (most common), prone (back surgery), lateral (kidney, lung), lithotomy (GYN/urology), Trendelenburg (head down, abdominal exposure), reverse Trendelenburg (head up). Pad pressure points to prevent nerve injury and pressure ulcers.", example: "For the laparoscopic appendectomy the patient was placed in supine Trendelenburg with both arms tucked — pressure points padded to prevent ulnar nerve injury." },
  { term: "Open vs Laparoscopic Surgery", type: "concept", category: "procedures-counts", meaning: "Open: traditional large incision, direct visualization. Laparoscopic: small incisions, CO2 insufflation, camera and instruments through ports. Robotic: surgeon controls instruments via console (da Vinci). MIS reduces pain, recovery, and infection.", example: "The patient's appendectomy was performed laparoscopically through three 5–12 mm ports — much faster recovery than the traditional open approach." },
  { term: "Surgical Hemostasis", type: "concept", category: "procedures-counts", meaning: "Mechanical (sutures, clips, clamps), thermal (electrosurgery, laser, harmonic scalpel — ultrasonic), chemical (epinephrine, thrombin, fibrin glue), pressure. Multiple methods often combined for difficult bleeding.", example: "Bleeding from the splenic vessel was controlled with metal clips (mechanical) and bipolar coagulation (thermal) — combined hemostasis methods." },
  { term: "Wound Classification (CDC)", type: "concept", category: "procedures-counts", meaning: "Class I (clean — uninfected, no inflammation, no tract entered). II (clean-contaminated — controlled entry of GI/respiratory). III (contaminated — open wound, gross spill). IV (dirty/infected — pre-existing infection, perforated viscera).", example: "The elective hernia repair was classified Class I (clean); a perforated appendicitis case was Class IV (dirty)." },
];'''
m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
html = html[:m.start()] + TERMS_JS + html[m.end():]
CAT = """const categoryLabel = c => ({
  'or-roles':           'OR Roles & Environment',
  'asepsis':            'Asepsis & Sterilization',
  'instruments':        'Instruments & Supplies',
  'procedures-counts':  'Procedures & Counts',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'surgical-technology';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>', '<title>HOSA Prep Hub — Surgical Technology</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>', '<h1>Surgical<br><em>Technology</em>.</h1>', 1)
html = html.replace('A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
                    'A study companion for OR roles and environment, surgical asepsis and sterilization, instruments and supplies, and operative procedures and counts — built for HOSA competitors.', 1)
html = html.replace('//  DATA — HOSA Emergency Medical Science', '//  DATA — HOSA Surgical Technology', 1)
with open(DST, 'w', encoding='utf-8') as f: f.write(html)
print(f'Wrote {DST} — {TERMS_JS.count("{ term:")} terms')
