#!/usr/bin/env python3
"""Generate occupational-therapy.html from dental-science.html template."""
import os, re

BASE = '/home/user/hosa-prep-hub'
SRC  = os.path.join(BASE, 'dental-science.html')
DST  = os.path.join(BASE, 'occupational-therapy.html')

with open(SRC, 'r', encoding='utf-8') as f:
    html = f.read()

TERMS_JS = '''const TERMS = [
  // ── Foundations of OT ───────────────────────────────────────
  { term: "Occupational Therapy (OT) Definition", type: "concept", category: "foundations", meaning: "A health profession that promotes participation in meaningful activities (occupations) to improve health, well-being, and quality of life across the lifespan. OT addresses physical, cognitive, psychosocial, and environmental factors that affect occupational performance.", example: "The OT evaluated the stroke patient's ability to dress and bathe independently — occupations central to her daily quality of life — before designing an intervention plan." },
  { term: "AOTA Occupational Profile", type: "concept", category: "foundations", meaning: "The initial step in the OT evaluation process: a client-centered summary of the client's history, patterns of daily living, interests, values, and the concerns they want to address in therapy. Guides selection of assessments and goals.", example: "During the occupational profile interview, the OT learned that returning to cooking was the patient's top priority, which directed the evaluation toward upper extremity function and kitchen safety." },
  { term: "OTPF — Occupational Therapy Practice Framework", type: "concept", category: "foundations", meaning: "AOTA's official domain and process document (4th ed., 2020); describes the domain (occupations, contexts, performance skills/patterns, client factors) and the process (evaluation → intervention → outcomes).", example: "The OT used the OTPF to structure the evaluation, identifying the client's performance patterns (disrupted routines), context (home environment), and body functions (limited ROM) relevant to the occupational profile." },
  { term: "Areas of Occupation", type: "concept", category: "foundations", meaning: "The eight categories of human activity addressed by OT: ADLs (self-care), IADLs, Health Management, Rest and Sleep, Education, Work, Play, Leisure, and Social Participation.", example: "The OT targeted IADLs — specifically meal preparation and home management — after the patient achieved independence in basic ADLs following hip replacement." },
  { term: "ADLs vs IADLs", type: "concept", category: "foundations", meaning: "ADLs (Activities of Daily Living): basic self-care — bathing, dressing, grooming, eating, toileting, functional mobility. IADLs (Instrumental ADLs): complex community tasks — cooking, driving, managing finances, home management, medication management.", example: "The patient was independent in all ADLs but needed OT intervention for IADLs: she was unable to safely manage her medications or prepare a hot meal after her mild TBI." },
  { term: "Performance Skills", type: "concept", category: "foundations", meaning: "Observable actions used during occupational performance: motor skills (positioning, manipulating, coordinating), process skills (pacing, attending, organizing), and social interaction skills (relating, speaking, taking turns).", example: "The OT observed the patient's performance skills during a cooking task: poor sequencing (process skill) and difficulty gripping the spoon (motor skill) were noted." },
  { term: "Performance Patterns", type: "concept", category: "foundations", meaning: "Habits (automatic behaviors), routines (established sequences), rituals (symbolic practices), and roles (expected behaviors in a social position) that organize and support occupational performance.", example: "The OT identified that the patient's morning routine had been entirely disrupted by the injury, causing distress; restoring that structure became a central intervention goal." },
  { term: "Client Factors", type: "concept", category: "foundations", meaning: "Attributes that reside in the client affecting function: body functions (sensory, mental, neuromuscular, cardiovascular) and body structures (organs, limbs). Distinct from occupational performance — dysfunction in client factors may impair occupation.", example: "The client factor limiting work return was decreased grip strength (body function); the OT targeted hand strengthening while simultaneously adapting tools." },
  { term: "Occupational Justice", type: "concept", category: "foundations", meaning: "The right of all people to participate in meaningful occupations regardless of disability, socioeconomic status, or marginalization. OT advocates for equitable access to occupational opportunities for all populations.", example: "The OT advocated for accessible playground equipment at the school so students with physical disabilities could participate in the same play occupations as their peers." },
  { term: "Occupational Science", type: "concept", category: "foundations", meaning: "An academic discipline (distinct from OT practice) studying the form, function, and meaning of human occupation; provides the theoretical and empirical foundation for occupational therapy.", example: "Occupational science research on how chronic pain disrupts daily routines informed the OT's intervention to help the patient re-engage in meaningful activities." },

  // ── Frames of Reference & Models ────────────────────────────
  { term: "Model of Human Occupation (MOHO)", type: "concept", category: "frames-of-reference", meaning: "Gary Kielhofner's model viewing humans as open systems with three subsystems: volition (motivation/values/interests), habituation (habits/roles), and performance capacity (mind, brain, body). Environment shapes occupational performance.", example: "Using MOHO, the OT assessed the worker's low volition (lack of interest in returning to the job) and disrupted habituation (lost work habits during sick leave) before addressing performance capacity." },
  { term: "Biomechanical Frame of Reference", type: "concept", category: "frames-of-reference", meaning: "Applied when neuromuscular systems are intact but musculoskeletal dysfunction limits motion, strength, or endurance. Interventions target ROM, muscle strength, and endurance using purposeful activity. Used with orthopaedic and burn patients.", example: "The OT used the biomechanical frame of reference to measure wrist ROM and grip strength after the distal radius fracture, then designed crafts to improve active range incrementally." },
  { term: "Neurodevelopmental Treatment (NDT/Bobath)", type: "concept", category: "frames-of-reference", meaning: "A frame of reference for neurological conditions (stroke, CP) that uses hands-on facilitation and inhibition of abnormal tone to promote normal movement patterns during functional activities, rather than compensatory strategies.", example: "Using NDT, the OT facilitated the hemiplegic patient's affected upper extremity during a reaching task, inhibiting spasticity and encouraging more normalized movement." },
  { term: "Sensory Integration (Ayres)", type: "concept", category: "frames-of-reference", meaning: "A. Jean Ayres' framework explaining how the brain organizes sensory input (tactile, proprioceptive, vestibular) into adaptive responses; sensory processing difficulties underlie problems in learning and behavior in children.", example: "The child's hypersensitivity to touch and difficulty with balance were addressed using sensory integration therapy on swings, trampolines, and textured surfaces." },
  { term: "Cognitive Rehabilitation", type: "concept", category: "frames-of-reference", meaning: "Addresses attention, memory, problem-solving, and executive function deficits using restorative (retraining specific functions) or compensatory (external aids and strategies) approaches. Used after TBI, stroke, and in dementia.", example: "The OT used compensatory cognitive strategies — calendar systems, step-by-step checklists — to help the TBI patient manage daily tasks despite residual memory deficits." },
  { term: "Kawa (River) Model", type: "concept", category: "frames-of-reference", meaning: "A culturally responsive model using the metaphor of a river where water flow = life energy/occupational flow; rocks = obstacles, driftwood = resources and assets, river walls/bottom = context. Developed for collectivist cultures.", example: "The OT used the Kawa model with the Japanese patient to explore how cultural obligations (driftwood) and family expectations (river walls) shaped her occupational performance and goals." },
  { term: "Person–Environment–Occupation (PEO) Model", type: "concept", category: "frames-of-reference", meaning: "A transactive model where occupational performance is the dynamic fit between Person (skills, roles, experiences), Environment (physical, cultural, social), and Occupation (tasks, self-care, leisure). Optimizing any component improves performance.", example: "Rather than only retraining the patient, the OT modified the environment (grab bars, raised toilet) and occupation (switching to slip-on shoes) to maximize independence." },

  // ── Evaluation & Assessment ──────────────────────────────────
  { term: "FIM (Functional Independence Measure)", type: "concept", category: "evaluation", meaning: "An 18-item standardized assessment of functional ability in self-care, sphincter control, transfers, locomotion, communication, and cognition. Scored 1–7 per item (1 = total assistance, 7 = complete independence). Used in rehabilitation settings.", example: "The patient's FIM score improved from 68 at admission to 112 at discharge, reflecting a meaningful gain in functional independence following stroke rehabilitation." },
  { term: "COPM (Canadian Occupational Performance Measure)", type: "concept", category: "evaluation", meaning: "A client-centered semi-structured interview identifying the patient's self-perceived occupational performance problems in self-care, productivity, and leisure; rated on 10-point scales for performance and satisfaction. Detects change over time.", example: "The COPM identified cooking as the patient's top priority; she rated her performance 3/10 and satisfaction 2/10 — a 2-point change post-intervention is considered clinically significant." },
  { term: "Allen Cognitive Level Screen (ACLS)", type: "concept", category: "evaluation", meaning: "A leather-lacing task that screens cognitive level on Allen's 6-level scale (1 = automatic actions, 6 = planned actions); predicts ability to live independently and learn new skills. Used in psychiatry and dementia.", example: "The patient's ACLS score of 4.2 indicated she could handle routine tasks with some supervision but could not manage complex IADL problem-solving independently." },
  { term: "Goniometry", type: "concept", category: "evaluation", meaning: "Measurement of joint range of motion using a goniometer aligned to joint landmarks; values recorded as active (AROM) or passive (PROM) motion in degrees and compared to normative values (e.g., elbow flexion normal: 150°).", example: "The OT measured 95° of active shoulder flexion — significantly below normal — and documented it on the evaluation form before designing the ROM exercise program." },
  { term: "Manual Muscle Testing (MMT)", type: "concept", category: "evaluation", meaning: "Assesses muscle strength on a 0–5 scale: 0 (no contraction), 1 (flicker), 2 (full ROM gravity-eliminated), 3 (full ROM against gravity), 4 (full ROM against some resistance), 5 (full ROM against full resistance).", example: "MMT of the wrist extensors after radial nerve injury revealed grade 2 — full ROM when gravity was eliminated but unable to lift the wrist against gravity." },
  { term: "Sensory Testing", type: "concept", category: "evaluation", meaning: "Assesses light touch (Semmes-Weinstein monofilaments), two-point discrimination, proprioception, temperature, pain, and stereognosis. Essential after peripheral nerve injury, hand surgery, and stroke. Guides rehabilitation planning.", example: "Semmes-Weinstein monofilament testing showed the patient could not detect the 4.31 filament in the fingertips — indicating diminished protective sensation after carpal tunnel release." },
  { term: "Standardized vs Non-Standardized Assessments", type: "concept", category: "evaluation", meaning: "Standardized assessments have normative data, established reliability and validity, and specific administration protocols. Non-standardized (clinical observation, interview) are flexible but cannot produce norm-referenced scores.", example: "The OT used the AMPS (standardized) for a valid ADL performance score, then supplemented with clinical observation (non-standardized) during a home visit to assess real-world safety." },

  // ── Interventions ────────────────────────────────────────────
  { term: "Therapeutic Use of Occupation", type: "concept", category: "interventions", meaning: "The hallmark of OT: using meaningful activities purposefully designed with the just-right challenge to improve occupational performance, not rote exercises. The activity must be meaningful to the client for optimal therapeutic benefit.", example: "Rather than squeezing a rubber ball, the OT had the patient who loved gardening use trowels, pots, and soil to achieve the same hand strengthening goal with greater motivation and carryover." },
  { term: "Orthotics (Splinting)", type: "concept", category: "interventions", meaning: "Custom or prefabricated devices to support, immobilize, protect, correct, or substitute for lost function. Static (no moving parts) vs dynamic (spring/elastic forces). Resting hand splint (wrist/hand injury), wrist cock-up, dynamic flexion glove.", example: "The OT fabricated a static resting hand splint from thermoplastic to immobilize the wrist in neutral during sleep, preventing further ulnar drift in the RA patient." },
  { term: "Adaptive Equipment and Assistive Technology", type: "concept", category: "interventions", meaning: "Modified tools or devices enabling participation despite impairment. Low-tech (built-up handle, dressing stick, button hook, sock aid, universal cuff) to high-tech (power wheelchair, environmental control unit, AAC device, eye-gaze software).", example: "The OT prescribed a dressing stick and long-handled shoe horn so the bilateral hip replacement patient could dress independently while following total hip precautions." },
  { term: "Environmental Modifications (Home Modification)", type: "concept", category: "interventions", meaning: "Structural or equipment changes to the home or community to reduce barriers and support independence: grab bars, raised toilet seat, ramp, shower seat, removal of throw rugs, lever door handles, stair lift.", example: "The home evaluation identified fall hazards; the OT recommended grab bars in the bathroom, removal of throw rugs, and improved lighting — reducing re-fall risk for the elderly patient." },
  { term: "Energy Conservation and Work Simplification", type: "concept", category: "interventions", meaning: "Strategies for people with fatigue-limiting conditions (MS, heart failure, cancer, COPD) to maintain occupational participation: planning, pacing, prioritizing, positioning, and using adaptive equipment to reduce energy expenditure.", example: "The OT taught the CHF patient to prepare meals while seated, gather all supplies before starting, and rest between tasks — halving energy expenditure for meal preparation." },
  { term: "Joint Protection Principles", type: "concept", category: "interventions", meaning: "Techniques for clients with arthritis or joint instability: reduce joint stress, avoid static postures, use larger and stronger joints, distribute load, maintain joint in optimal alignment, use assistive devices. Prevents deformity progression.", example: "The OT instructed the RA patient to carry bags on forearms rather than in the finger flexors, and use a jar opener rather than twisting — reducing MCP joint stress." },
  { term: "Transfer Training", type: "concept", category: "interventions", meaning: "Teaching safe movement between surfaces (bed to wheelchair, chair to toilet) using stand-pivot, slide board, mechanical lift, or squat-pivot technique depending on patient's weight-bearing status and strength. Includes caregiver training.", example: "The OT trained the patient and her husband in a two-person stand-pivot transfer to the wheelchair using a gait belt, ensuring safety after the T10 spinal cord injury." },
  { term: "Cognitive-Behavioral Strategies in OT", type: "concept", category: "interventions", meaning: "OTs use behavioral approaches to address maladaptive patterns, increase participation, and modify environments: habit training, activity scheduling, errorless learning, graded task assignment, and self-monitoring logs.", example: "For the patient with depression who had stopped all leisure activities, the OT used activity scheduling to gradually reintroduce meaningful occupations, starting with 10-minute daily tasks." },
  { term: "Occupational Therapy in Mental Health", type: "concept", category: "interventions", meaning: "OT addresses psychosocial function through occupation: role development, social skills groups, coping strategies, sensory modulation, vocational rehabilitation, and community integration for clients with schizophrenia, mood disorders, or PTSD.", example: "The inpatient OT co-led a daily living skills group, where patients with schizophrenia practiced meal planning and grocery budgeting to prepare for community discharge." },
];'''

m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
if not m: raise SystemExit('TERMS not found')
html = html[:m.start()] + TERMS_JS + html[m.end():]

CAT = """const categoryLabel = c => ({
  'foundations':        'Foundations of OT',
  'frames-of-reference':'Frames of Reference & Models',
  'evaluation':         'Evaluation & Assessment',
  'interventions':      'Interventions',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)

html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'occupational-therapy';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>',
                    '<title>HOSA Prep Hub — Occupational Therapy</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>',
                    '<h1>Occupational<br><em>Therapy</em>.</h1>', 1)
html = html.replace(
    'A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
    'A study companion for OT foundations, frames of reference and practice models, evaluation and assessment, and therapeutic interventions — built for HOSA competitors.',
    1
)
html = html.replace('//  DATA — HOSA Emergency Medical Science',
                    '//  DATA — HOSA Occupational Therapy', 1)

with open(DST, 'w', encoding='utf-8') as f:
    f.write(html)

count = TERMS_JS.count('{ term:')
print(f'Wrote {DST} — {count} terms')
