#!/usr/bin/env python3
"""Generate pain-management.html from dental-science.html template."""
import os, re
BASE = '/home/user/hosa-prep-hub'
SRC, DST = os.path.join(BASE, 'dental-science.html'), os.path.join(BASE, 'pain-management.html')
with open(SRC, 'r', encoding='utf-8') as f: html = f.read()
TERMS_JS = '''const TERMS = [
  // ── Pain Physiology & Types ──────────────────────────────────
  { term: "Nociceptive vs Neuropathic Pain", type: "concept", category: "physiology-types", meaning: "Nociceptive: tissue damage stimulating nociceptors. Somatic (skin, bone, muscle — well-localized, sharp). Visceral (organs — poorly localized, cramping, referred). Neuropathic: nerve damage/dysfunction — burning, shooting, paresthesias.", example: "The diabetic patient's bilateral foot burning and shooting pain was neuropathic; gabapentin and duloxetine were chosen over NSAIDs." },
  { term: "Acute vs Chronic Pain", type: "concept", category: "physiology-types", meaning: "Acute: warning function, <3 months, identifiable cause, responds to typical analgesics. Chronic: pain persisting >3 months, may outlast tissue injury, often poorly responsive to opioids alone, requires multimodal approach.", example: "The patient's 6-month low back pain after disc herniation transitioned from acute to chronic; multimodal management with PT, gabapentin, and CBT was started." },
  { term: "Pain Pathways (Ascending)", type: "concept", category: "physiology-types", meaning: "Nociceptors → 1st-order neuron (peripheral nerve) → dorsal horn → 2nd-order neuron crosses → spinothalamic tract → thalamus → 3rd-order to cortex (sensory, emotional, cognitive components). Modulated by descending pathways (PAG → RVM).", example: "Acetaminophen reduces pain centrally; opioids work on multiple pathway levels including descending modulation." },
  { term: "Gate Control Theory", type: "concept", category: "physiology-types", meaning: "Spinal cord 'gate' modulates pain transmission. Non-painful inputs (rubbing, TENS) close the gate, reducing pain transmission to brain. Explains why rubbing an injury reduces pain — and basis for TENS therapy.", example: "TENS unit applied to the chronic low back pain patient's lumbar paraspinals reduced pain by activating non-painful Aβ fibers per gate control theory." },
  { term: "Pain Assessment Scales", type: "concept", category: "physiology-types", meaning: "Numeric Rating Scale (NRS 0-10) for adults. Visual Analog Scale (VAS). Wong-Baker FACES for children, nonverbal. Behavioral scales (FLACC, CPOT) for unable-to-self-report. Document location, quality, radiation, triggers, alleviators, timing, severity.", example: "The patient rated pain 8/10 sharp right flank radiating to groin — characteristic of ureterolithiasis, captured fully with NRS." },

  // ── Non-Opioid Analgesics ────────────────────────────────────
  { term: "Acetaminophen", type: "concept", category: "non-opioid", meaning: "Centrally acting analgesic and antipyretic; mechanism still debated. Max 4 g/day in healthy adults (3 g if liver disease/alcohol). Hepatotoxic in overdose — N-acetylcysteine is antidote. No anti-inflammatory effect.", example: "The patient with mild OA pain chose acetaminophen first-line; total daily dose was limited to 3 g due to mild liver enzyme elevation." },
  { term: "NSAIDs", type: "concept", category: "non-opioid", meaning: "Block COX-1 and/or COX-2 → reduce prostaglandins → analgesia, anti-inflammatory, antipyretic. Ibuprofen, naproxen, celecoxib (COX-2 selective). Side effects: GI bleeding, renal injury, hypertension, CV events. Avoid in CKD, peptic ulcer, advanced age.", example: "The young patient's acute ankle sprain was treated with naproxen for both pain and inflammation; gastroprotection added if prolonged use needed." },
  { term: "Gabapentinoids (Gabapentin, Pregabalin)", type: "concept", category: "non-opioid", meaning: "Bind α2δ subunit of voltage-gated calcium channels, reducing excitatory neurotransmitter release. First-line for neuropathic pain (diabetic neuropathy, post-herpetic neuralgia). Side effects: sedation, dizziness, edema. Renal dose adjustment needed.", example: "The patient's post-herpetic neuralgia improved significantly with gabapentin titrated to 1800 mg/day in divided doses." },
  { term: "Antidepressants for Pain", type: "concept", category: "non-opioid", meaning: "TCAs (amitriptyline, nortriptyline): neuropathic pain, headaches; anticholinergic side effects. SNRIs (duloxetine, venlafaxine): diabetic neuropathy, fibromyalgia, chronic musculoskeletal pain. Mechanism: enhance descending inhibition.", example: "The diabetic patient's painful peripheral neuropathy responded to duloxetine 60 mg daily — analgesic effect at lower dose than for depression." },
  { term: "Topical Analgesics", type: "concept", category: "non-opioid", meaning: "Lidocaine patch (post-herpetic neuralgia, focal neuropathic). Capsaicin (depletes substance P from C fibers — chronic neuropathy, OA). Topical NSAIDs (diclofenac gel — knee/hand OA, avoiding systemic side effects).", example: "The elderly patient's knee OA was treated with topical diclofenac gel, achieving relief without systemic NSAID side effects." },

  // ── Opioids & Interventional ─────────────────────────────────
  { term: "Opioid Pharmacology", type: "concept", category: "opioids-interventional", meaning: "Act at mu (analgesia, euphoria, respiratory depression), kappa, and delta opioid receptors. Examples: morphine, oxycodone, hydrocodone, fentanyl, hydromorphone. Side effects: sedation, constipation, nausea, dependence, tolerance, respiratory depression.", example: "The post-surgical patient received oxycodone for moderate-severe pain; bowel regimen was started simultaneously to prevent opioid-induced constipation." },
  { term: "Opioid Equianalgesic Dosing", type: "concept", category: "opioids-interventional", meaning: "Conversion table relating doses of different opioids. Morphine 10 mg IV ≈ 30 mg PO ≈ oxycodone 20 mg PO ≈ hydromorphone 1.5 mg IV. Reduce by 25-50% when switching due to incomplete cross-tolerance.", example: "Converting from oxycodone 20 mg q4h PO to fentanyl patch required calculating total daily morphine equivalents — fentanyl 50 mcg/hr was selected with breakthrough oxycodone." },
  { term: "Opioid Tolerance, Dependence, Addiction", type: "concept", category: "opioids-interventional", meaning: "Tolerance: physiological — need more drug for same effect (normal with chronic use). Dependence: physiological — withdrawal on cessation. Addiction (use disorder): compulsive use despite harm. Pseudoaddiction: undertreated pain mimicking addiction behaviors.", example: "The cancer patient on chronic morphine developed tolerance requiring dose escalation — this is normal physiology, not addiction." },
  { term: "Naloxone", type: "concept", category: "opioids-interventional", meaning: "Pure mu-opioid antagonist that reverses opioid effects, especially respiratory depression. IV/IM/intranasal. 0.4 mg IV initially; titrate. Short half-life (30-90 min) — may need repeated dosing as opioid effects outlast naloxone. Distributed as Narcan for overdose prevention.", example: "The overdose patient's apnea and pinpoint pupils responded to naloxone 0.4 mg IV; repeat doses were needed given the long half-life of methadone." },
  { term: "Opioid Use Disorder (OUD)", type: "concept", category: "opioids-interventional", meaning: "DSM-5 disorder; criteria include loss of control, continued use despite harm, tolerance, withdrawal. Treated with medication-assisted treatment: methadone (full agonist), buprenorphine (partial agonist), naltrexone (antagonist). Behavioral therapy adjunctive.", example: "The patient with OUD chose buprenorphine-naloxone for medication-assisted treatment — partial agonist with ceiling effect reduced overdose risk." },
  { term: "Multimodal Analgesia", type: "concept", category: "opioids-interventional", meaning: "Combining different analgesic mechanisms for synergy and opioid sparing: NSAID + acetaminophen + gabapentin + regional block + opioid as needed. Standard of care for surgical pain to reduce opioid use and side effects.", example: "ERAS (Enhanced Recovery After Surgery) protocols use multimodal analgesia — scheduled acetaminophen + NSAID + gabapentin + regional block — minimizing opioid requirements." },
  { term: "Interventional Pain Procedures", type: "concept", category: "opioids-interventional", meaning: "Epidural steroid injection (radiculopathy). Facet joint injection/RFA (axial low back pain). Sympathetic blocks. Spinal cord stimulators (failed back surgery syndrome, CRPS). Intrathecal pumps (cancer pain). Trigger point injections (myofascial pain).", example: "The patient's L5 radiculopathy from disc herniation improved with epidural steroid injection, avoiding surgical intervention." },
  { term: "Cancer Pain Management (WHO Ladder)", type: "concept", category: "opioids-interventional", meaning: "Step 1 (mild): non-opioid (acetaminophen, NSAID) ± adjuvant. Step 2 (moderate): weak opioid (codeine, tramadol) + step 1. Step 3 (severe): strong opioid (morphine, fentanyl) + step 1. Adjuvants throughout: gabapentinoids, antidepressants, steroids.", example: "The metastatic cancer patient's severe bone pain was managed with morphine SR + breakthrough morphine IR + scheduled NSAID + gabapentin — full WHO step 3." },
];'''
m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
html = html[:m.start()] + TERMS_JS + html[m.end():]
CAT = """const categoryLabel = c => ({
  'physiology-types':       'Pain Physiology & Types',
  'non-opioid':             'Non-Opioid Analgesics',
  'opioids-interventional': 'Opioids & Interventional',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'pain-management';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>', '<title>HOSA Prep Hub — Pain Management</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>', '<h1>Pain<br><em>Management</em>.</h1>', 1)
html = html.replace('A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
                    'A study companion for pain physiology and types, non-opioid analgesics, and opioids and interventional pain procedures — built for HOSA competitors.', 1)
html = html.replace('//  DATA — HOSA Emergency Medical Science', '//  DATA — HOSA Pain Management', 1)
with open(DST, 'w', encoding='utf-8') as f: f.write(html)
print(f'Wrote {DST} — {TERMS_JS.count("{ term:")} terms')
