#!/usr/bin/env python3
"""Generate global-health.html from dental-science.html template."""
import os, re
BASE = '/home/user/hosa-prep-hub'
SRC, DST = os.path.join(BASE, 'dental-science.html'), os.path.join(BASE, 'global-health.html')
with open(SRC, 'r', encoding='utf-8') as f: html = f.read()
TERMS_JS = '''const TERMS = [
  // ── Global Burden of Disease ──────────────────────────────────
  { term: "Global Burden of Disease (GBD) & DALYs", type: "concept", category: "burden", meaning: "DALY (Disability-Adjusted Life Year): sum of years of life lost (YLL) + years lived with disability (YLD). Measures health loss from disease, injury, and risk factors across countries. Major GBD causes: ischemic heart disease, stroke, lower respiratory infections, neonatal disorders, COPD, diarrheal disease.", example: "Malaria's global burden of 250 million DALYs annually concentrated in sub-Saharan Africa illustrates how disease can be measured beyond mortality alone." },
  { term: "Social Determinants of Health (SDOH)", type: "concept", category: "burden", meaning: "Non-medical factors shaping health outcomes: income, education, employment, housing, food security, transportation, neighborhood safety, social support. WHO Healthy People 2030 framework. Address SDOH to reduce health disparities and achieve health equity.", example: "The community health worker's screening for food insecurity and housing instability addressed SDOH — connecting patients to resources that medication alone could not fix." },
  { term: "Health Equity & Disparities", type: "concept", category: "burden", meaning: "Health equity: everyone has a fair opportunity to achieve optimal health. Disparities: preventable differences in health outcomes across race/ethnicity, income, gender, geography. Root causes: structural racism, poverty, historical policy. Measured by infant mortality, life expectancy, chronic disease prevalence by demographic.", example: "Black women's 3-fold higher maternal mortality rate in the US compared to white women represents a profound health disparity rooted in structural inequity." },

  // ── Major Global Diseases ──────────────────────────────────────
  { term: "Malaria", type: "concept", category: "global-diseases", meaning: "Plasmodium falciparum (most lethal), P. vivax, P. malariae, P. ovale. Transmitted by female Anopheles mosquito. Symptoms: cyclic fevers, chills, anemia, splenomegaly. Diagnosed by thick/thin blood smear or rapid antigen test. Treated with artemisinin-based combination therapy (ACT). Prevention: bed nets, indoor residual spraying, chemoprophylaxis.", example: "The traveler to sub-Saharan Africa with cyclic fevers on day 10 had P. falciparum on blood smear; artemether-lumefantrine was started for uncomplicated malaria." },
  { term: "Tuberculosis (Global Perspective)", type: "concept", category: "global-diseases", meaning: "World's leading infectious disease killer. 10 million new cases/year; 1.5 million deaths. High-burden countries: India, Indonesia, China, Philippines, Pakistan. Drug-resistant TB (MDR-TB, XDR-TB) is a major crisis requiring second-line drugs (bedaquiline). WHO End TB Strategy targets 90% reduction by 2030.", example: "The global MDR-TB crisis — driven by incomplete treatment courses — led WHO to fast-track bedaquiline approval, offering new hope for previously untreatable strains." },
  { term: "Neglected Tropical Diseases (NTDs)", type: "concept", category: "global-diseases", meaning: "17+ diseases affecting >1 billion people in tropical/subtropical low-income countries: lymphatic filariasis, schistosomiasis, onchocerciasis, trachoma, soil-transmitted helminths (roundworm, hookworm, whipworm), Chagas disease, leishmaniasis. Mass drug administration (MDA) is primary control strategy.", example: "The WHO's mass drug administration of albendazole and ivermectin in Nigeria reduced lymphatic filariasis burden by 70% over 10 years." },
  { term: "HIV/AIDS Global Burden", type: "concept", category: "global-diseases", meaning: "39 million people living with HIV globally; 70% in sub-Saharan Africa. UNAIDS 95-95-95 targets: 95% of PLHIV know status, 95% of those on ART, 95% of those virally suppressed. PrEP (tenofovir-emtricitabine) prevents transmission. PMTCT (prevention of mother-to-child transmission) has cut pediatric HIV dramatically.", example: "Rwanda's 93-95-93 HIV cascade achievement — using community health workers, mobile testing, and differentiated care — demonstrates what focused investment can accomplish." },

  // ── Global Health Systems & Policy ────────────────────────────
  { term: "Universal Health Coverage (UHC)", type: "concept", category: "systems-policy", meaning: "All people access essential health services without financial hardship. Measured by service coverage index and catastrophic health expenditure. WHO SDG 3.8. Approaches: single payer (UK NHS), social health insurance (Germany), mixed (US). Low-income countries: community health workers, primary care focus, GAVI vaccines.", example: "Thailand's UHC scheme expanded access to antiretrovirals and essential surgery — reducing catastrophic health expenditure from 5% to 1% of households in a decade." },
  { term: "Maternal and Child Health (MCH) Globally", type: "concept", category: "systems-policy", meaning: "Leading causes of maternal death: hemorrhage, hypertensive disorders, sepsis, unsafe abortion, embolism. Leading causes of under-5 mortality: pneumonia, diarrhea, neonatal conditions, malaria, undernutrition (underlies 45% of deaths). Interventions: skilled birth attendants, antenatal care, ORS, vaccines, exclusive breastfeeding.", example: "Bangladesh's success in reducing under-5 mortality 70% through community-based oral rehydration therapy and vaccine programs became a model for low-income country MCH." },
  { term: "One Health Approach", type: "concept", category: "systems-policy", meaning: "Human, animal, and environmental health are interconnected. 75% of emerging infectious diseases are zoonotic (SARS-CoV-2, Ebola, avian influenza, rabies, Nipah). One Health addresses antimicrobial resistance, food safety, vector control across sectors. Requires collaboration between medicine, veterinary science, and ecology.", example: "The Nipah virus outbreak in Bangladesh was traced to bats → date palm sap → humans — a One Health investigation combining epidemiology, wildlife biology, and public health." },
  { term: "Humanitarian & Disaster Health", type: "concept", category: "systems-policy", meaning: "Sphere Standards guide humanitarian response: food, water (15L/person/day), sanitation (1 latrine per 20 people), shelter, healthcare. WASH (water, sanitation, hygiene) prevents infectious disease outbreaks. Priority interventions: measles vaccination, therapeutic feeding, trauma care. Mental health and psychosocial support (MHPSS) critical.", example: "The refugee camp outbreak of acute watery diarrhea was controlled by chlorinating the water supply and deploying oral cholera vaccine — a WASH and vaccination response." },
  { term: "Antimicrobial Resistance (AMR) Global Crisis", type: "concept", category: "systems-policy", meaning: "700,000 deaths/year attributable to AMR; projected 10 million by 2050. ESKAPE pathogens most concerning. Drivers: antibiotic overuse in humans and livestock, poor sanitation, lack of new antibiotics. WHO Global Action Plan: reduce use, improve surveillance, develop new antibiotics, promote vaccines.", example: "India's open antibiotic market driving carbapenem-resistant Klebsiella across South Asia illustrates how AMR requires international governance beyond national borders." },
];'''
m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
html = html[:m.start()] + TERMS_JS + html[m.end():]
CAT = """const categoryLabel = c => ({
  'burden':         'Global Burden of Disease',
  'global-diseases':'Major Global Diseases',
  'systems-policy': 'Global Health Systems & Policy',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'global-health';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>', '<title>HOSA Prep Hub — Global Health</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>', '<h1>Global<br><em>Health</em>.</h1>', 1)
html = html.replace('A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
                    'A study companion for global burden of disease and health equity, major global diseases including malaria and TB and HIV, global health systems including UHC and MCH, and the One Health approach and antimicrobial resistance — built for HOSA competitors.', 1)
html = html.replace('//  DATA — HOSA Emergency Medical Science', '//  DATA — HOSA Global Health', 1)
with open(DST, 'w', encoding='utf-8') as f: f.write(html)
print(f'Wrote {DST} — {TERMS_JS.count("{ term:")} terms')
