#!/usr/bin/env python3
"""Generate medical-microbiology.html from dental-science.html template."""
import os, re

BASE = '/home/user/hosa-prep-hub'
SRC  = os.path.join(BASE, 'dental-science.html')
DST  = os.path.join(BASE, 'medical-microbiology.html')

with open(SRC, 'r', encoding='utf-8') as f:
    html = f.read()

TERMS_JS = '''const TERMS = [
  // ── Bacteria ─────────────────────────────────────────────────
  { term: "Gram Stain", type: "concept", category: "bacteria", meaning: "A differential stain that classifies bacteria by cell wall composition. Gram-positive bacteria retain crystal violet (purple) due to a thick peptidoglycan layer; gram-negative bacteria are decolorized and counterstained pink with safranin due to a thin peptidoglycan layer and outer membrane.", example: "The CSF Gram stain showed gram-negative diplococci, consistent with Neisseria meningitidis." },
  { term: "Staphylococcus aureus", type: "concept", category: "bacteria", meaning: "A gram-positive coccus in grape-like clusters; catalase-positive and coagulase-positive. Causes skin infections, abscesses, endocarditis, pneumonia, food poisoning, and toxic shock syndrome. MRSA strains are methicillin-resistant.", example: "The patient's wound culture grew gram-positive cocci in clusters, identified as S. aureus by coagulase positivity; sensitivities showed MRSA." },
  { term: "Streptococcus pyogenes (Group A Strep)", type: "concept", category: "bacteria", meaning: "A gram-positive coccus in chains; beta-hemolytic on blood agar, bacitracin-sensitive. Causes strep throat, scarlet fever, impetigo, necrotizing fasciitis, and post-infectious rheumatic fever and acute glomerulonephritis.", example: "The child's throat culture grew beta-hemolytic, bacitracin-sensitive colonies — S. pyogenes — confirming streptococcal pharyngitis." },
  { term: "Streptococcus pneumoniae", type: "concept", category: "bacteria", meaning: "A gram-positive lancet-shaped diplococcus; alpha-hemolytic, optochin-sensitive, bile-soluble. Most common cause of community-acquired pneumonia, otitis media, sinusitis, and adult bacterial meningitis. Polysaccharide capsule is the key virulence factor.", example: "The sputum Gram stain showed lancet-shaped gram-positive diplococci, and alpha-hemolytic optochin-sensitive growth confirmed S. pneumoniae." },
  { term: "Escherichia coli", type: "concept", category: "bacteria", meaning: "A gram-negative rod; lactose-fermenting on MacConkey (pink colonies). Most common cause of UTI. Pathogenic strains include EHEC O157:H7 (bloody diarrhea, HUS), ETEC (traveler's diarrhea), and EIEC.", example: "The urine culture grew >100,000 CFU/mL of lactose-fermenting gram-negative rods, identified as E. coli — the cause of the patient's UTI." },
  { term: "Mycobacterium tuberculosis", type: "concept", category: "bacteria", meaning: "An acid-fast bacillus with a waxy mycolic-acid cell wall — does NOT stain well on Gram. Identified by Ziehl-Neelsen stain (bright red on blue background) and slow growth on Lowenstein-Jensen medium. Causes pulmonary and disseminated tuberculosis.", example: "The patient's sputum AFB smear showed bright red rods on Ziehl-Neelsen staining; PCR confirmed M. tuberculosis." },
  { term: "Clostridium difficile", type: "concept", category: "bacteria", meaning: "A gram-positive, spore-forming anaerobe; produces toxins A and B that cause pseudomembranous colitis. Often follows antibiotic use (especially clindamycin, fluoroquinolones). Diagnosed by stool toxin EIA or PCR.", example: "After 10 days of clindamycin the patient developed profuse watery diarrhea; stool PCR was positive for C. difficile toxin B." },
  { term: "Neisseria meningitidis", type: "concept", category: "bacteria", meaning: "A gram-negative diplococcus (kidney-bean shape); oxidase-positive, grows on chocolate agar. Causes meningococcal meningitis and meningococcemia (purpura fulminans, Waterhouse-Friderichsen syndrome). Vaccine-preventable.", example: "The college student's CSF Gram stain showed gram-negative diplococci; he was immediately started on ceftriaxone for suspected N. meningitidis meningitis." },
  { term: "Helicobacter pylori", type: "concept", category: "bacteria", meaning: "A gram-negative, curved/spiral rod; urease-positive. Colonizes gastric mucosa and causes most peptic ulcers and gastric MALT lymphoma. Diagnosed by urea breath test, stool antigen, or biopsy.", example: "The patient's duodenal ulcer biopsy showed curved gram-negative rods, urease test positive — H. pylori; triple therapy was started." },
  { term: "Treponema pallidum", type: "concept", category: "bacteria", meaning: "A spirochete; cannot be Gram stained or cultured routinely. Causes syphilis with three stages: primary (chancre), secondary (rash, condyloma lata), tertiary (gummas, cardiovascular, neurosyphilis). Diagnosed by VDRL/RPR (nontreponemal) and FTA-ABS (treponemal) serology.", example: "The patient's RPR was reactive at 1:64 and FTA-ABS confirmed prior infection; the painless penile ulcer was a primary syphilitic chancre." },
  { term: "Bacterial Cell Wall (Peptidoglycan)", type: "concept", category: "bacteria", meaning: "A polymer of NAG and NAM cross-linked by short peptides; provides cell rigidity and shape. Gram-positives have thick peptidoglycan; gram-negatives have a thin layer plus an outer membrane with LPS (endotoxin). Beta-lactam antibiotics inhibit synthesis.", example: "Penicillin binds penicillin-binding proteins and blocks peptidoglycan cross-linking — bacteria lyse from osmotic pressure." },
  { term: "Endotoxin (LPS)", type: "concept", category: "bacteria", meaning: "Lipopolysaccharide in the outer membrane of gram-negative bacteria; released when bacteria lyse. Lipid A triggers massive cytokine release (TNF-α, IL-1, IL-6), causing fever, hypotension, and septic shock.", example: "The patient's septic shock was attributed to gram-negative bacteremia — LPS released into the bloodstream triggered a cytokine storm and refractory hypotension." },

  // ── Viruses ──────────────────────────────────────────────────
  { term: "DNA vs RNA Viruses", type: "concept", category: "viruses", meaning: "DNA viruses (mostly double-stranded) replicate in the nucleus (except poxviruses); examples: herpesviruses, adenovirus, HPV, HBV. RNA viruses replicate in the cytoplasm (except influenza, retroviruses); examples: HIV, influenza, hepatitis A/C/E, rhinovirus, SARS-CoV-2.", example: "Influenza A is an RNA virus that replicates in the cytoplasm but requires nuclear entry for genome segmentation — an exception among RNA viruses." },
  { term: "Influenza Virus", type: "concept", category: "viruses", meaning: "A segmented (8 segments), negative-sense RNA virus (Orthomyxoviridae); surface antigens hemagglutinin (HA) and neuraminidase (NA) define subtypes (e.g., H1N1, H3N2). Antigenic drift (mutation) → seasonal flu; antigenic shift (reassortment) → pandemics.", example: "The 2009 H1N1 pandemic arose from antigenic shift — reassortment between swine, avian, and human influenza viruses." },
  { term: "Herpes Simplex Virus (HSV)", type: "concept", category: "viruses", meaning: "An enveloped DNA virus with two types: HSV-1 (oral, herpetic gingivostomatitis, encephalitis) and HSV-2 (genital). Establishes lifelong latency in sensory neuron ganglia, reactivating periodically. Treated with acyclovir.", example: "The patient's painful vesicular oral lesions and positive Tzanck smear with multinucleated giant cells confirmed HSV-1 reactivation." },
  { term: "Human Immunodeficiency Virus (HIV)", type: "concept", category: "viruses", meaning: "An enveloped retrovirus (Lentivirus); infects CD4+ T cells via the CD4 receptor and CCR5/CXCR4 coreceptors. Reverse transcribes RNA into DNA integrated into host genome. AIDS defined by CD4 < 200 or AIDS-defining illness.", example: "The patient's CD4 count of 145 with Pneumocystis pneumonia met AIDS criteria; ART was started immediately." },
  { term: "Hepatitis Viruses A–E", type: "concept", category: "viruses", meaning: "HAV (RNA, fecal-oral, acute only). HBV (DNA, blood/sex, acute + chronic, vaccine available). HCV (RNA, blood, mostly chronic). HDV (incomplete RNA virus, requires HBV coinfection). HEV (RNA, fecal-oral, severe in pregnancy).", example: "The patient's HBsAg-positive and IgM anti-HBc-positive serology indicated acute hepatitis B; HBV-DNA was elevated and ALT was 1200." },
  { term: "Human Papillomavirus (HPV)", type: "concept", category: "viruses", meaning: "A non-enveloped DNA virus; over 100 types. Low-risk types (6, 11) cause genital warts; high-risk types (16, 18) cause >70% of cervical cancers, plus anal, oropharyngeal, and penile cancers. Vaccine prevents major oncogenic types.", example: "The patient's abnormal Pap smear with HPV-16 positivity prompted colposcopy, which identified high-grade dysplasia." },
  { term: "SARS-CoV-2", type: "concept", category: "viruses", meaning: "An enveloped, positive-sense RNA virus (Betacoronavirus); enters cells via ACE2 receptor using spike (S) protein. Causes COVID-19 ranging from asymptomatic to severe ARDS and multi-organ failure. Variants (Alpha, Delta, Omicron) emerged via mutation.", example: "The patient's positive SARS-CoV-2 PCR and bilateral ground-glass opacities on CT confirmed COVID-19 pneumonia." },
  { term: "Varicella-Zoster Virus (VZV)", type: "concept", category: "viruses", meaning: "An enveloped DNA herpesvirus; primary infection causes chickenpox (varicella) with disseminated vesicular rash; reactivation from dorsal root ganglia causes shingles (herpes zoster) in a dermatomal distribution.", example: "The 68-year-old's painful, vesicular rash limited to the T8 dermatome on one side was characteristic of VZV reactivation as shingles." },
  { term: "Epstein-Barr Virus (EBV)", type: "concept", category: "viruses", meaning: "An enveloped DNA herpesvirus infecting B lymphocytes via CD21. Causes infectious mononucleosis (fever, pharyngitis, lymphadenopathy, splenomegaly) and is associated with Burkitt lymphoma, Hodgkin disease, and nasopharyngeal carcinoma.", example: "The college student's atypical lymphocytes on smear and positive monospot heterophile antibody test confirmed EBV mononucleosis." },
  { term: "Antiviral Mechanisms", type: "concept", category: "viruses", meaning: "Acyclovir (HSV/VZV): activated by viral thymidine kinase, inhibits viral DNA polymerase. Oseltamivir (flu): neuraminidase inhibitor. NRTIs (HIV): chain terminators. Remdesivir (SARS-CoV-2): RNA-dependent RNA polymerase inhibitor.", example: "Oseltamivir was started within 48 hours of symptom onset, blocking the influenza neuraminidase and reducing viral release from infected cells." },

  // ── Fungi & Parasites ────────────────────────────────────────
  { term: "Candida albicans", type: "concept", category: "fungi-parasites", meaning: "A dimorphic yeast; commensal on skin and mucosa, becomes pathogenic with antibiotic use, diabetes, or immunosuppression. Causes oral thrush, vulvovaginal candidiasis, esophagitis, and invasive candidemia.", example: "The diabetic patient's white plaques on the tongue that scraped off easily were oral thrush from C. albicans overgrowth." },
  { term: "Aspergillus", type: "concept", category: "fungi-parasites", meaning: "A ubiquitous mold with septate hyphae branching at 45° angles. Causes allergic bronchopulmonary aspergillosis (ABPA), aspergilloma (fungus ball in cavity), and invasive aspergillosis in immunocompromised patients.", example: "The neutropenic leukemia patient's halo sign on chest CT and positive galactomannan confirmed invasive aspergillosis; voriconazole was started." },
  { term: "Pneumocystis jirovecii", type: "concept", category: "fungi-parasites", meaning: "An atypical fungus that causes Pneumocystis pneumonia (PCP) in immunocompromised hosts, especially AIDS patients with CD4 < 200. Bilateral ground-glass infiltrates; diagnosed by induced sputum or BAL with silver stain.", example: "The HIV patient with CD4 of 80 presented with dry cough, hypoxia, and bilateral ground-glass infiltrates — TMP-SMX was started empirically for PCP." },
  { term: "Plasmodium (Malaria)", type: "concept", category: "fungi-parasites", meaning: "Protozoan parasites transmitted by Anopheles mosquitoes; five species infect humans. P. falciparum is most severe (cerebral malaria, blackwater fever). Diagnosed by thick and thin blood smears.", example: "The patient returning from sub-Saharan Africa presented with cyclical fevers; thin blood smear showed P. falciparum ring forms in red cells." },
  { term: "Toxoplasma gondii", type: "concept", category: "fungi-parasites", meaning: "A protozoan parasite; cats are the definitive host. Acquired by ingesting oocysts or undercooked meat. Causes congenital toxoplasmosis (intracranial calcifications, chorioretinitis) and reactivation encephalitis in AIDS patients.", example: "The AIDS patient with CD4 of 50 had multiple ring-enhancing brain lesions on MRI; positive Toxoplasma IgG supported reactivation encephalitis." },
  { term: "Giardia lamblia", type: "concept", category: "fungi-parasites", meaning: "A flagellated protozoan acquired from contaminated water (campers, daycare). Causes greasy, foul-smelling, non-bloody diarrhea with bloating and weight loss. Diagnosed by stool antigen testing or trophozoites/cysts on microscopy.", example: "The backpacker returned with prolonged greasy diarrhea and bloating; stool antigen test was positive for G. lamblia." },
  { term: "Entamoeba histolytica", type: "concept", category: "fungi-parasites", meaning: "An invasive protozoan causing amebic dysentery (bloody diarrhea) and liver abscesses. Diagnosed by stool microscopy showing trophozoites with ingested RBCs, antigen tests, or serology.", example: "The patient from Mexico with right upper quadrant pain and bloody stools had an anchovy-paste liver abscess; serology confirmed E. histolytica." },
  { term: "Helminths Overview", type: "concept", category: "fungi-parasites", meaning: "Multicellular parasitic worms: nematodes (roundworms — Ascaris, hookworm, pinworm), cestodes (tapeworms — Taenia), trematodes (flukes — Schistosoma). Eosinophilia is a common laboratory clue.", example: "The patient's pruritus ani and tape test positive for pinworm eggs confirmed Enterobius vermicularis; mebendazole was prescribed." },

  // ── Antimicrobials ───────────────────────────────────────────
  { term: "Beta-Lactam Antibiotics", type: "concept", category: "antimicrobials", meaning: "Penicillins, cephalosporins, carbapenems, and monobactams; share a beta-lactam ring that binds penicillin-binding proteins to inhibit peptidoglycan cross-linking. Beta-lactamases (e.g., penicillinase, ESBL) cause resistance; clavulanate inhibits some.", example: "The strep throat was treated with amoxicillin — a beta-lactam that binds PBPs and disrupts S. pyogenes cell wall synthesis." },
  { term: "Vancomycin", type: "concept", category: "antimicrobials", meaning: "A glycopeptide that binds the D-Ala-D-Ala terminal of peptidoglycan precursors, preventing cross-linking. Used IV for severe gram-positive infections (MRSA, severe C. diff oral). Resistance: VRE alters target to D-Ala-D-Lac.", example: "The bacteremic patient with MRSA endocarditis was started on IV vancomycin with target trough levels of 15–20 µg/mL." },
  { term: "Aminoglycosides", type: "concept", category: "antimicrobials", meaning: "Gentamicin, tobramycin, amikacin; bind the 30S ribosomal subunit, causing misreading of mRNA and bactericidal effect against aerobic gram-negatives. Synergistic with beta-lactams. Side effects: nephrotoxicity, ototoxicity.", example: "The patient's gram-negative sepsis was treated with piperacillin-tazobactam plus gentamicin for synergistic coverage." },
  { term: "Fluoroquinolones", type: "concept", category: "antimicrobials", meaning: "Ciprofloxacin, levofloxacin, moxifloxacin; inhibit DNA gyrase and topoisomerase IV, preventing bacterial DNA replication. Broad-spectrum. Side effects: tendinopathy, QT prolongation, aortic dissection risk, C. diff colitis.", example: "The patient's pyelonephritis was treated with ciprofloxacin, which inhibits E. coli DNA gyrase and is well-concentrated in urinary tissue." },
  { term: "Macrolides", type: "concept", category: "antimicrobials", meaning: "Azithromycin, clarithromycin, erythromycin; bind the 50S ribosomal subunit, inhibiting protein synthesis. Used for atypical pneumonias (Mycoplasma, Chlamydia, Legionella) and as alternatives in penicillin allergy.", example: "The patient with walking pneumonia was treated with azithromycin, effective against Mycoplasma pneumoniae which lacks a cell wall." },
  { term: "Tetracyclines and Doxycycline", type: "concept", category: "antimicrobials", meaning: "Bind 30S ribosomal subunit and block tRNA binding. Used for atypicals, rickettsial diseases, Lyme, acne. Contraindicated in pregnancy and children <8 (tooth staining). Side effects: photosensitivity, esophagitis.", example: "Doxycycline was prescribed for the suspected Rocky Mountain spotted fever; treatment was started empirically before serology returned." },
  { term: "Trimethoprim-Sulfamethoxazole (TMP-SMX)", type: "concept", category: "antimicrobials", meaning: "Sequential inhibition of folate synthesis: SMX blocks dihydropteroate synthase, TMP blocks dihydrofolate reductase. Used for UTI, PCP prophylaxis/treatment, and MRSA skin infections. Hyperkalemia and Stevens-Johnson are risks.", example: "The HIV patient on PCP prophylaxis took daily TMP-SMX; both folate synthesis steps blocked Pneumocystis growth." },
  { term: "Antibiotic Resistance Mechanisms", type: "concept", category: "antimicrobials", meaning: "Major mechanisms: (1) enzymatic inactivation (beta-lactamases), (2) altered target (PBP2a in MRSA, ribosomal mutation), (3) decreased permeability (porin loss), (4) efflux pumps, (5) bypass pathways (folate auxotrophy).", example: "MRSA's resistance arises from the mecA gene encoding PBP2a, an altered target with low affinity for beta-lactam antibiotics." },
  { term: "Minimum Inhibitory Concentration (MIC)", type: "concept", category: "antimicrobials", meaning: "The lowest concentration of an antibiotic that prevents visible bacterial growth in vitro; used with CLSI breakpoints to categorize the organism as susceptible (S), intermediate (I), or resistant (R).", example: "The patient's E. coli had a ciprofloxacin MIC of 0.06 µg/mL — well below the susceptibility breakpoint of 0.25, so treatment was likely to succeed." },
  { term: "Antibiotic Stewardship", type: "concept", category: "antimicrobials", meaning: "Coordinated programs to optimize antibiotic use — right drug, dose, duration — to improve patient outcomes, minimize toxicity, and slow emergence of resistance. Includes de-escalation and IV-to-PO conversion.", example: "The stewardship team de-escalated empiric vancomycin to nafcillin once cultures grew methicillin-sensitive S. aureus, narrowing coverage and reducing resistance pressure." },

  // ── Laboratory Diagnosis ─────────────────────────────────────
  { term: "Blood Culture Collection", type: "concept", category: "lab-diagnosis", meaning: "Two sets of cultures (one aerobic and one anaerobic bottle each) drawn from separate venipuncture sites within 60 minutes, BEFORE antibiotics; chlorhexidine prep prevents contamination. 20–30 mL per bottle for optimal yield.", example: "The septic patient had two sets of blood cultures drawn from different arms before vancomycin and piperacillin-tazobactam were started." },
  { term: "MacConkey Agar", type: "concept", category: "lab-diagnosis", meaning: "A selective and differential medium with bile salts and crystal violet (inhibits gram-positives) and lactose with neutral red indicator. Lactose fermenters (E. coli, Klebsiella, Enterobacter) appear pink; non-fermenters (Salmonella, Shigella, Pseudomonas) appear colorless.", example: "The stool culture on MacConkey showed colorless colonies — non-lactose-fermenting — later identified as Salmonella by biochemical testing." },
  { term: "Blood Agar (Hemolysis Patterns)", type: "concept", category: "lab-diagnosis", meaning: "Differential medium showing hemolytic reactions: alpha (partial, green halo — S. pneumoniae, viridans strep); beta (complete clearing — S. pyogenes, S. agalactiae); gamma (none — Enterococcus).", example: "The blood agar plate showed beta-hemolysis around the colonies — clear halos — consistent with Group A or B streptococcus." },
  { term: "Catalase and Coagulase Tests", type: "concept", category: "lab-diagnosis", meaning: "Catalase distinguishes staphylococci (positive — bubbles in H2O2) from streptococci (negative). Coagulase distinguishes S. aureus (positive — fibrin clot) from coagulase-negative staphylococci (S. epidermidis, S. saprophyticus).", example: "The gram-positive cocci in clusters were catalase-positive — Staphylococcus — and coagulase-positive, confirming S. aureus." },
  { term: "PCR and Nucleic Acid Amplification", type: "concept", category: "lab-diagnosis", meaning: "Amplifies microbial DNA/RNA exponentially via thermal cycling, detecting low-copy pathogens within hours. Used for SARS-CoV-2, influenza, gonorrhea/chlamydia, MRSA screening, and viral load monitoring.", example: "The patient's nasopharyngeal swab PCR detected SARS-CoV-2 RNA at a cycle threshold of 22 — a high viral load." },
  { term: "Antibiotic Susceptibility Testing", type: "concept", category: "lab-diagnosis", meaning: "Methods to determine which antibiotics will inhibit growth: disk diffusion (Kirby-Bauer — zone of inhibition measured), broth microdilution (MIC quantitative), and Etest (gradient strip giving MIC).", example: "The Kirby-Bauer disk diffusion test for E. coli showed a 28 mm zone around ciprofloxacin, well above the 21 mm susceptible breakpoint." },
  { term: "Acid-Fast Stain (Ziehl-Neelsen)", type: "concept", category: "lab-diagnosis", meaning: "Carbol fuchsin penetrates mycolic-acid-rich walls of mycobacteria and Nocardia; acid-alcohol decolorizes other bacteria; methylene blue counterstain. AFB appear red on blue background.", example: "The sputum smear with bright red rods on Ziehl-Neelsen stain was reported as 'AFB positive', and PCR confirmed M. tuberculosis." },
  { term: "Serology and Antibody Testing", type: "concept", category: "lab-diagnosis", meaning: "Detects host immune response (IgM = acute, IgG = past/chronic). Used when culture is impractical (Treponema, EBV, HIV, hepatitis viruses). Four-fold rise in paired titers confirms acute infection.", example: "The hepatitis A IgM was positive — diagnostic of acute HAV — while IgG indicated prior exposure or vaccination." },

  // ── Infection Control ────────────────────────────────────────
  { term: "Standard Precautions", type: "concept", category: "infection-control", meaning: "Apply to all patients regardless of suspected infection: hand hygiene, gloves with body fluid contact, gowns/masks/eye protection when splashes are anticipated, safe injection practices, and sharps disposal.", example: "The nurse donned gloves and a gown before changing the patient's surgical drain, applying Standard Precautions for any blood/body fluid contact." },
  { term: "Transmission-Based Precautions", type: "concept", category: "infection-control", meaning: "Added to Standard Precautions for specific pathogens: Contact (MRSA, C. diff — gown, gloves); Droplet (influenza, pertussis — surgical mask within 6 ft); Airborne (TB, measles, varicella — N95 + negative-pressure room).", example: "The TB patient was placed on Airborne Precautions in a negative-pressure room, and staff wore fit-tested N95 respirators on entry." },
  { term: "Hand Hygiene", type: "concept", category: "infection-control", meaning: "Alcohol-based hand rub is preferred unless hands are visibly soiled or after C. difficile exposure (use soap and water — alcohol does not kill spores). 'Five moments': before patient, before aseptic task, after fluid risk, after patient, after surroundings.", example: "After leaving the C. diff isolation room, the nurse washed hands with soap and water — alcohol-based rub cannot kill C. difficile spores." },
  { term: "Healthcare-Associated Infections (HAIs)", type: "concept", category: "infection-control", meaning: "Infections acquired ≥48 hours after admission; common types: CAUTI (catheter-associated UTI), CLABSI (central line bloodstream infection), SSI (surgical site infection), VAP (ventilator-associated pneumonia). Major patient-safety target.", example: "The patient's day-5 fever with positive blood cultures from the central line tip identified CLABSI; the line was removed and vancomycin started." },
  { term: "Sterilization vs Disinfection", type: "concept", category: "infection-control", meaning: "Sterilization eliminates all microbes including spores (autoclave, ethylene oxide, gas plasma — for critical items like surgical instruments). Disinfection kills most pathogens but not all spores (high-level: glutaraldehyde for endoscopes; low-level: quaternary ammonium for surfaces).", example: "Surgical instruments were autoclaved at 121°C, 15 psi, for 30 minutes — true sterilization required for critical items entering sterile tissues." },
  { term: "Outbreak Investigation", type: "concept", category: "infection-control", meaning: "Steps: confirm outbreak, define a case, count cases, describe by person/place/time (epidemic curve), hypothesize source, test hypothesis (often case-control), implement control measures, communicate findings.", example: "An epidemic curve was constructed for the cluster of S. aureus surgical infections, pointing to a common operating room as the probable source." },
  { term: "Vaccination and Herd Immunity", type: "concept", category: "infection-control", meaning: "Vaccines induce active immunity via antigen exposure. Herd immunity — when a sufficient proportion of a population is immune, susceptible individuals are protected indirectly. Threshold varies by R0 (measles ~95%, polio ~80%).", example: "Measles outbreaks have re-emerged in communities where vaccination rates fell below the ~95% herd immunity threshold for highly contagious R0 = 12–18 measles virus." },
];'''

m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
if not m: raise SystemExit('TERMS not found')
html = html[:m.start()] + TERMS_JS + html[m.end():]

CAT = """const categoryLabel = c => ({
  'bacteria':         'Bacteria',
  'viruses':          'Viruses',
  'fungi-parasites':  'Fungi & Parasites',
  'antimicrobials':   'Antimicrobials',
  'lab-diagnosis':    'Laboratory Diagnosis',
  'infection-control':'Infection Control',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)

html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'medical-microbiology';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>',
                    '<title>HOSA Prep Hub — Medical Microbiology</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>',
                    '<h1>Medical<br><em>Microbiology</em>.</h1>', 1)
html = html.replace(
    'A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
    'A study companion for bacteria, viruses, fungi and parasites, antimicrobial agents, laboratory diagnosis, and infection control — built for HOSA competitors.',
    1
)
html = html.replace('//  DATA — HOSA Emergency Medical Science',
                    '//  DATA — HOSA Medical Microbiology', 1)

with open(DST, 'w', encoding='utf-8') as f:
    f.write(html)

count = TERMS_JS.count('{ term:')
print(f'Wrote {DST} — {count} terms')
