#!/usr/bin/env python3
"""Generate sleep-medicine.html from dental-science.html template."""
import os, re
BASE = '/home/user/hosa-prep-hub'
SRC, DST = os.path.join(BASE, 'dental-science.html'), os.path.join(BASE, 'sleep-medicine.html')
with open(SRC, 'r', encoding='utf-8') as f: html = f.read()
TERMS_JS = '''const TERMS = [
  // ── Sleep Physiology ─────────────────────────────────────────
  { term: "Sleep Stages (NREM and REM)", type: "concept", category: "physiology", meaning: "NREM stages: N1 (light, drowsy, 5%), N2 (light, sleep spindles, K-complexes, 50%), N3 (deep, slow-wave, restorative, 20%). REM: dreaming, muscle atonia, rapid eye movements, increased brain activity (~25%). Cycles ~90 min, 4-6/night.", example: "The patient's polysomnography showed reduced N3 (slow-wave) sleep, contributing to feeling unrefreshed despite adequate sleep time." },
  { term: "Circadian Rhythm", type: "concept", category: "physiology", meaning: "~24-hour cycle regulated by suprachiasmatic nucleus, entrained by light (especially blue light) suppressing melatonin. Disrupted by shift work, jet lag, blue-light exposure. Melatonin secretion begins ~2 hours before habitual sleep.", example: "The shift worker's circadian misalignment was treated with strategic light exposure and melatonin to advance sleep timing." },
  { term: "Sleep Architecture and Aging", type: "concept", category: "physiology", meaning: "Sleep needs: newborns 14-17h, adults 7-9h, elderly 7-8h. With aging: more time in N1/N2 (light sleep), less N3 (deep) and REM, more nighttime awakenings, earlier wake times.", example: "The elderly patient's complaint of poor sleep reflected age-related architecture changes — total sleep time was adequate but quality was reduced." },
  { term: "Polysomnography (PSG)", type: "concept", category: "physiology", meaning: "Gold-standard overnight sleep study measuring EEG, EOG, EMG, ECG, oximetry, airflow, respiratory effort, leg movements. Identifies sleep architecture, apneas, periodic limb movements. Performed in sleep lab; home tests for uncomplicated OSA suspicion.", example: "The patient's polysomnography revealed 35 apnea events per hour, classifying severe obstructive sleep apnea." },

  // ── Sleep-Disordered Breathing ───────────────────────────────
  { term: "Obstructive Sleep Apnea (OSA)", type: "concept", category: "breathing", meaning: "Recurrent upper airway collapse during sleep → hypoxemia, sleep fragmentation. Symptoms: loud snoring, witnessed apneas, daytime sleepiness. AHI: mild 5-14, moderate 15-29, severe ≥30. Treated with CPAP, weight loss, oral appliances, surgery.", example: "The patient's AHI of 42 with daytime sleepiness confirmed severe OSA; CPAP at 8 cm H2O eliminated apneas and improved Epworth score from 18 to 6." },
  { term: "Central Sleep Apnea", type: "concept", category: "breathing", meaning: "Absence of respiratory effort during sleep (vs OSA where effort continues against obstruction). Causes: heart failure (Cheyne-Stokes), high altitude, opioids, brainstem disease. Treated with adaptive servo-ventilation (ASV) or BPAP.", example: "The CHF patient's Cheyne-Stokes breathing pattern with central apneas on PSG was treated with ASV ventilation." },
  { term: "CPAP (Continuous Positive Airway Pressure)", type: "concept", category: "breathing", meaning: "Mainstay treatment for OSA. Constant pressure (usually 5-20 cm H2O) splints airway open during sleep. Improves AHI, daytime alertness, blood pressure, cardiovascular outcomes. Adherence challenging — proper fit and education improve success.", example: "After 2 weeks of CPAP therapy at 9 cm H2O the patient's Epworth Sleepiness Scale dropped from 16 to 6 — clinically significant improvement." },
  { term: "Mallampati Score and Airway Assessment", type: "concept", category: "breathing", meaning: "Mallampati classification (I-IV) based on visibility of oropharyngeal structures predicts difficult intubation and OSA risk. Class III-IV (only soft palate or hard palate visible) suggests increased OSA risk. Neck circumference >17 inches (men) also predictive.", example: "The patient's Mallampati IV airway, neck circumference 18.5 inches, and history of snoring led to home sleep test confirming OSA." },

  // ── Insomnia & Other Sleep Disorders ─────────────────────────
  { term: "Insomnia Disorder", type: "concept", category: "other-disorders", meaning: "Difficulty initiating or maintaining sleep, or early awakening, with daytime impairment, ≥3 nights/week for ≥3 months. First-line treatment: cognitive behavioral therapy for insomnia (CBT-I). Medications (zolpidem, trazodone, suvorexant) for short-term use.", example: "The patient's 6 months of difficulty falling asleep with daytime fatigue and irritability met chronic insomnia criteria; CBT-I was the first-line treatment." },
  { term: "Sleep Hygiene", type: "concept", category: "other-disorders", meaning: "Behavioral practices supporting sleep: consistent sleep/wake times, dark and cool bedroom, no screens before bed, no caffeine/alcohol/heavy meals close to bedtime, exercise (but not late), bed only for sleep/sex.", example: "The patient's improved sleep with sleep hygiene measures (consistent bedtime, no phone in bed, blackout curtains) avoided need for sleep medication." },
  { term: "Restless Legs Syndrome (RLS)", type: "concept", category: "other-disorders", meaning: "Uncomfortable leg sensations with urge to move, worse evening/night, relieved by movement. May be primary or secondary (iron deficiency, pregnancy, CKD, neuropathy). Check ferritin; iron supplementation if low. Dopamine agonists (pramipexole), gabapentin for severe.", example: "The patient's RLS symptoms resolved after iron supplementation increased ferritin from 25 to 80 ng/mL — secondary to iron deficiency." },
  { term: "Narcolepsy", type: "concept", category: "other-disorders", meaning: "Excessive daytime sleepiness with rapid REM onset. Type 1: with cataplexy (sudden muscle weakness with emotion) — low CSF orexin/hypocretin. Multiple Sleep Latency Test (MSLT) shows mean sleep latency <8 min plus ≥2 REM onsets. Treated with modafinil, stimulants, sodium oxybate.", example: "The patient's daytime sleep attacks plus knee-buckling laughter (cataplexy) and MSLT confirming sleep-onset REM diagnosed type 1 narcolepsy." },
  { term: "Parasomnias", type: "concept", category: "other-disorders", meaning: "Abnormal behaviors during sleep. NREM parasomnias (sleepwalking, night terrors): partial arousal from deep sleep, no memory, common in children. REM behavior disorder: acting out dreams from loss of REM atonia; in elderly — high association with future Parkinson/Lewy body disease.", example: "The 70-year-old's nighttime kicking and yelling during dreams was REM sleep behavior disorder; clonazepam reduced episodes." },
  { term: "Shift Work Disorder", type: "concept", category: "other-disorders", meaning: "Insomnia and/or excessive sleepiness from working during normal sleep hours. Disrupts circadian rhythm. Strategies: strategic napping, bright light during shift, dark/quiet sleep environment, modafinil for sleepiness, melatonin for sleep.", example: "The night-shift nurse's persistent fatigue and difficulty sleeping during the day improved with blackout curtains, modafinil during shift, and melatonin." },
  { term: "Jet Lag", type: "concept", category: "other-disorders", meaning: "Circadian misalignment from rapid time-zone travel; symptoms: insomnia, fatigue, GI upset, cognitive impairment. Worse traveling east. Strategies: pre-travel sleep adjustment, light exposure timing, melatonin, brief naps, hydration.", example: "After flying 8 time zones east the patient used melatonin 0.5 mg at destination bedtime plus morning light exposure to accelerate adjustment." },
];'''
m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
html = html[:m.start()] + TERMS_JS + html[m.end():]
CAT = """const categoryLabel = c => ({
  'physiology':      'Sleep Physiology',
  'breathing':       'Sleep-Disordered Breathing',
  'other-disorders': 'Insomnia & Other Sleep Disorders',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'sleep-medicine';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>', '<title>HOSA Prep Hub — Sleep Medicine</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>', '<h1>Sleep<br><em>Medicine</em>.</h1>', 1)
html = html.replace('A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
                    'A study companion for sleep physiology and architecture, sleep-disordered breathing and CPAP, and insomnia and other sleep disorders — built for HOSA competitors.', 1)
html = html.replace('//  DATA — HOSA Emergency Medical Science', '//  DATA — HOSA Sleep Medicine', 1)
with open(DST, 'w', encoding='utf-8') as f: f.write(html)
print(f'Wrote {DST} — {TERMS_JS.count("{ term:")} terms')
