#!/usr/bin/env python3
"""Generate infectious-disease.html from dental-science.html template."""
import os, re
BASE = '/home/user/hosa-prep-hub'
SRC, DST = os.path.join(BASE, 'dental-science.html'), os.path.join(BASE, 'infectious-disease.html')
with open(SRC, 'r', encoding='utf-8') as f: html = f.read()
TERMS_JS = '''const TERMS = [
  // ── Sepsis & Bacteremia ──────────────────────────────────────
  { term: "SIRS, Sepsis, Septic Shock", type: "concept", category: "sepsis", meaning: "SIRS: 2+ of temp >38/<36, HR >90, RR >20, WBC >12K/<4K. Sepsis (Sepsis-3): life-threatening organ dysfunction caused by dysregulated host response — SOFA score change ≥2. Septic shock: sepsis with vasopressors needed + lactate >2.", example: "The patient's lactate 4.2, MAP 58 requiring norepinephrine met septic shock criteria; broad-spectrum antibiotics and fluids were initiated within 1 hour." },
  { term: "Sepsis Bundle (Hour-1)", type: "concept", category: "sepsis", meaning: "Within 1 hour: measure lactate, draw blood cultures BEFORE antibiotics, give broad-spectrum antibiotics, 30 mL/kg crystalloid for hypotension or lactate ≥4, start vasopressors if hypotension persists. Reduces mortality.", example: "The septic patient received cultures, ceftriaxone, 2L LR within 45 minutes; norepinephrine was started when MAP remained <65 after fluids." },
  { term: "Bacteremia and Blood Cultures", type: "concept", category: "sepsis", meaning: "Two sets (one aerobic + one anaerobic each) from separate venipuncture sites BEFORE antibiotics; chlorhexidine prep prevents skin contamination. 20-30 mL per bottle for optimal yield. Repeat in endocarditis until clearance.", example: "The patient with persistent fever had two sets of blood cultures drawn from different sites before vancomycin and cefepime were started." },
  { term: "Empirical Antibiotic Selection", type: "concept", category: "sepsis", meaning: "Broad-spectrum coverage based on likely source and local resistance: community-acquired sepsis (ceftriaxone), hospital-acquired (cefepime or pip-tazo), neutropenic (cefepime), suspected MRSA (add vancomycin), suspected anaerobes (metronidazole).", example: "The hospital-acquired pneumonia with septic shock received vancomycin + piperacillin-tazobactam — covering MRSA and Pseudomonas pending cultures." },

  // ── Common Clinical Infections ───────────────────────────────
  { term: "Urinary Tract Infection (UTI)", type: "concept", category: "common-infections", meaning: "Uncomplicated cystitis: dysuria, frequency, urgency. Pyelonephritis: flank pain, fever, vomiting. E. coli most common. Uncomplicated UTI: nitrofurantoin, TMP-SMX, fosfomycin. Pyelonephritis: fluoroquinolone or ceftriaxone.", example: "The patient's dysuria and frequency with positive urinalysis was treated with nitrofurantoin 100 mg BID for 5 days — first-line uncomplicated UTI." },
  { term: "Community-Acquired Pneumonia (CAP)", type: "concept", category: "common-infections", meaning: "S. pneumoniae most common. CURB-65 scoring guides admission. Outpatient: amoxicillin or doxycycline. Inpatient: ceftriaxone + azithromycin. Severe: add coverage for Pseudomonas/MRSA based on risk factors.", example: "The patient's CURB-65 of 1 supported outpatient management; amoxicillin-clavulanate was prescribed for community-acquired pneumonia." },
  { term: "Skin & Soft Tissue Infections (Cellulitis)", type: "concept", category: "common-infections", meaning: "Cellulitis: erythema, warmth, swelling, tenderness — S. pyogenes and S. aureus most common. Treated with cephalexin (group A strep) or clindamycin/TMP-SMX (MRSA coverage). Abscess: I&D + antibiotics if surrounding cellulitis.", example: "The patient's leg cellulitis without fluctuance was treated with oral cephalexin for 5-7 days; rapid improvement confirmed adequate coverage." },
  { term: "C. difficile Colitis", type: "concept", category: "common-infections", meaning: "Toxin-producing C. difficile causing pseudomembranous colitis after antibiotics. Watery diarrhea, abdominal pain, fever. Diagnosed by stool toxin PCR or EIA. Treated with oral vancomycin or fidaxomicin; fecal transplant for recurrent.", example: "The patient's profuse diarrhea after clindamycin tested positive for C. difficile toxin; oral vancomycin 125 mg QID was initiated." },
  { term: "Endocarditis (Infective)", type: "concept", category: "common-infections", meaning: "Infection of cardiac valves. Causes: Viridans strep (native valve, dental procedures), S. aureus (IV drug use, prosthetic), Enterococcus, HACEK organisms. Duke criteria for diagnosis. 4-6 weeks IV antibiotics; surgery for valve dysfunction.", example: "The IV drug user's fever, new murmur, and tricuspid vegetation on echo with positive S. aureus blood cultures confirmed endocarditis." },
  { term: "Meningitis (Bacterial)", type: "concept", category: "common-infections", meaning: "S. pneumoniae most common adult; N. meningitidis in young; Listeria in elderly/immunocompromised. Fever, neck stiffness, altered mental status, photophobia. LP for diagnosis. Empiric: vancomycin + ceftriaxone + dexamethasone (± ampicillin for Listeria).", example: "The college student's fever, neck stiffness, and CSF showing high neutrophils received empiric vancomycin + ceftriaxone + dexamethasone." },

  // ── Special Populations & Opportunistic ──────────────────────
  { term: "HIV/AIDS Opportunistic Infections", type: "concept", category: "special-populations", meaning: "CD4 thresholds guide prophylaxis: <200 → PCP (TMP-SMX); <100 → toxoplasma (TMP-SMX); <50 → MAC (azithromycin). Common: PCP, candidiasis (oral/esophageal), Kaposi sarcoma, CMV retinitis, cryptococcal meningitis.", example: "The HIV patient with CD4 of 80 was started on TMP-SMX for both PCP and toxoplasmosis prophylaxis along with ART." },
  { term: "Tuberculosis", type: "concept", category: "special-populations", meaning: "M. tuberculosis transmitted via airborne droplets. Latent TB infection (LTBI): positive PPD/IGRA, no symptoms. Active TB: cough, fever, night sweats, weight loss, hemoptysis. Treated with RIPE (rifampin, isoniazid, pyrazinamide, ethambutol) 6 mo.", example: "The patient's positive IGRA without active symptoms or radiographic findings was diagnosed as LTBI; isoniazid 9 months was prescribed." },
  { term: "Hepatitis Viruses", type: "concept", category: "special-populations", meaning: "HAV: fecal-oral, acute only, vaccine. HBV: blood/sex, chronic possible, vaccine. HCV: blood, mostly chronic, curable with DAAs (sofosbuvir-velpatasvir). HDV: requires HBV. HEV: fecal-oral, severe in pregnancy.", example: "The HCV-positive patient achieved sustained virologic response with 12 weeks of sofosbuvir-velpatasvir — cure of chronic hepatitis C." },
  { term: "Sexually Transmitted Infections (STIs)", type: "concept", category: "special-populations", meaning: "Chlamydia (most common bacterial STI, often asymptomatic — azithromycin or doxycycline). Gonorrhea (purulent discharge — ceftriaxone). Syphilis (3 stages — penicillin G). Genital herpes (HSV-2 — acyclovir/valacyclovir). HPV (vaccine prevents).", example: "The patient's positive urine NAAT for both gonorrhea and chlamydia was treated with ceftriaxone 500 mg IM plus doxycycline 100 mg BID × 7 days." },
  { term: "Travel Medicine and Vaccines", type: "concept", category: "special-populations", meaning: "Pre-travel assessment: destination-specific vaccines (yellow fever, typhoid, hepatitis A, meningococcal), malaria prophylaxis (chloroquine, doxycycline, atovaquone-proguanil), traveler's diarrhea prevention, altitude considerations.", example: "The patient traveling to sub-Saharan Africa received yellow fever vaccine, atovaquone-proguanil for malaria prophylaxis, and counseling on water precautions." },
  { term: "Healthcare-Associated Infections (HAIs)", type: "concept", category: "special-populations", meaning: "Major patient safety issue: CAUTI (catheter-associated UTI), CLABSI (central line bloodstream infection), VAP (ventilator-associated pneumonia), SSI (surgical site infection), C. difficile. Prevented by bundles, hand hygiene, antibiotic stewardship.", example: "The ICU's bundle implementation reduced CLABSI rates by 60% — daily line necessity review, chlorhexidine bathing, full barrier precautions during insertion." },
  { term: "Antimicrobial Stewardship", type: "concept", category: "special-populations", meaning: "Coordinated efforts to optimize antibiotic use: right drug, dose, duration. Reduces resistance, C. difficile, adverse events. Strategies: de-escalation, IV-to-PO conversion, formulary restriction, audit and feedback.", example: "The stewardship team de-escalated empiric vancomycin to nafcillin once cultures grew MSSA — narrower spectrum reduced resistance pressure." },
];'''
m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
html = html[:m.start()] + TERMS_JS + html[m.end():]
CAT = """const categoryLabel = c => ({
  'sepsis':              'Sepsis & Bacteremia',
  'common-infections':   'Common Clinical Infections',
  'special-populations': 'Special Populations & Opportunistic',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'infectious-disease';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>', '<title>HOSA Prep Hub — Infectious Disease</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>', '<h1>Infectious<br><em>Disease</em>.</h1>', 1)
html = html.replace('A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
                    'A study companion for sepsis and bacteremia, common clinical infections including UTI and pneumonia and cellulitis, and special populations including HIV and TB and STIs — built for HOSA competitors.', 1)
html = html.replace('//  DATA — HOSA Emergency Medical Science', '//  DATA — HOSA Infectious Disease', 1)
with open(DST, 'w', encoding='utf-8') as f: f.write(html)
print(f'Wrote {DST} — {TERMS_JS.count("{ term:")} terms')
