#!/usr/bin/env python3
"""Generate trauma-critical-care.html from dental-science.html template."""
import os, re
BASE = '/home/user/hosa-prep-hub'
SRC, DST = os.path.join(BASE, 'dental-science.html'), os.path.join(BASE, 'trauma-critical-care.html')
with open(SRC, 'r', encoding='utf-8') as f: html = f.read()
TERMS_JS = '''const TERMS = [
  // ── Trauma Resuscitation (ATLS) ──────────────────────────────
  { term: "Primary Survey (ABCDE)", type: "concept", category: "trauma-resuscitation", meaning: "ATLS approach: Airway with C-spine protection, Breathing (rate/effort, breath sounds), Circulation (pulse, BP, control bleeding), Disability (GCS, pupils), Exposure (full body, prevent hypothermia). Identify and treat life threats simultaneously.", example: "The trauma patient's primary survey identified airway obstruction; rapid intubation with in-line C-spine stabilization preceded further evaluation." },
  { term: "Secondary Survey", type: "concept", category: "trauma-resuscitation", meaning: "Comprehensive head-to-toe examination after life threats addressed. AMPLE history (Allergies, Medications, PMH, Last meal, Events). Detailed exam: head, neck, chest, abdomen, pelvis, GU, MSK, neuro, log roll for back exam.", example: "The secondary survey revealed a previously missed scapular fracture and posterior thigh wound — found during log roll." },
  { term: "FAST Exam", type: "concept", category: "trauma-resuscitation", meaning: "Focused Assessment with Sonography for Trauma: bedside US examining pericardial, perihepatic (Morison pouch), perisplenic, pelvic spaces for free fluid suggesting hemoperitoneum or hemopericardium. Rapid, non-invasive, can be repeated.", example: "The hypotensive trauma patient's positive FAST showed free fluid in Morison pouch — emergent OR for laparotomy revealed splenic laceration." },
  { term: "Hemorrhagic Shock Classification", type: "concept", category: "trauma-resuscitation", meaning: "Class I: <15% blood loss (750 mL), normal vitals. Class II: 15-30% (750-1500), tachycardia, narrow pulse pressure. Class III: 30-40%, hypotension. Class IV: >40%, severe shock, may be irreversible. Massive transfusion at Class III-IV.", example: "The trauma patient's HR 130, BP 88/68, and decreased urine output indicated Class III hemorrhagic shock; massive transfusion protocol was activated." },
  { term: "Massive Transfusion Protocol (MTP)", type: "concept", category: "trauma-resuscitation", meaning: "1:1:1 ratio of packed RBCs : plasma : platelets approximating whole blood. Initiated for major hemorrhage (>10 units in 24 hr or >4 in 1 hr predicted). Tranexamic acid within 3 hours improves survival. Avoid crystalloid overload — damage control resuscitation.", example: "The penetrating trauma patient required MTP — 6 units PRBC + 6 FFP + 1 platelet pheresis + TXA — for hemorrhagic shock from hepatic injury." },

  // ── Shock & Resuscitation ────────────────────────────────────
  { term: "Shock Classification", type: "concept", category: "shock", meaning: "Distributive (septic, anaphylactic, neurogenic — vasodilation). Cardiogenic (pump failure — AMI, HF). Hypovolemic (volume loss — hemorrhage, dehydration). Obstructive (PE, tamponade, tension pneumo). Each has distinct hemodynamic profile.", example: "The patient's warm extremities, low SVR, normal/high cardiac output, and infection source identified distributive shock from sepsis." },
  { term: "Tension Pneumothorax", type: "concept", category: "shock", meaning: "Air entering pleural space with one-way valve → progressive collapse + mediastinal shift → impaired venous return → obstructive shock. Diagnosis CLINICAL: tracheal deviation, absent breath sounds, hyperresonance, JVD, hypotension. Treat IMMEDIATELY with needle decompression — do NOT wait for CXR.", example: "The trauma patient's tracheal deviation, absent left breath sounds, and hypotension prompted immediate left 2nd ICS midclavicular needle decompression — clinical diagnosis." },
  { term: "Cardiac Tamponade (Beck Triad)", type: "concept", category: "shock", meaning: "Pericardial fluid compresses heart → impaired filling → obstructive shock. Beck triad: hypotension, distended neck veins (JVD), muffled heart sounds. Pulsus paradoxus. Treat with pericardiocentesis — emergency.", example: "The penetrating chest trauma patient's Beck triad and FAST showing pericardial effusion was treated with emergent subxiphoid pericardiocentesis." },
  { term: "Pulmonary Embolism (Massive)", type: "concept", category: "shock", meaning: "Saddle or major branch obstruction causing acute right heart failure and obstructive shock. Sudden dyspnea, hypotension, hypoxia. CT pulmonary angiography for stable patients; massive PE with hemodynamic collapse → thrombolysis or thrombectomy.", example: "The post-op patient's syncope and refractory hypotension with massive saddle PE on CTPA was treated with alteplase thrombolysis." },
  { term: "Vasopressors and Inotropes", type: "concept", category: "shock", meaning: "Norepinephrine: first-line for septic shock (α and β1). Epinephrine: anaphylaxis, ROSC. Vasopressin: adjunct in refractory septic shock. Dopamine: bradycardia with hypotension. Dobutamine: cardiogenic shock (β1 inotrope). Phenylephrine: pure α (perioperative).", example: "The septic shock patient on norepinephrine 0.5 mcg/kg/min still had MAP 60; vasopressin 0.04 U/min was added for catecholamine-sparing effect." },
  { term: "Crystalloid vs Colloid Resuscitation", type: "concept", category: "shock", meaning: "Crystalloids (LR, NS): cheap, effective, first-line. Balanced solutions (LR, Plasmalyte) preferred over NS in large volumes (NS causes hyperchloremic acidosis). Colloids (albumin) not superior to crystalloids for most resuscitation; useful in cirrhosis/SBP and large-volume paracentesis.", example: "The septic shock patient received 30 mL/kg LR — balanced crystalloid — within the first hour per Surviving Sepsis guidelines." },

  // ── ICU Concepts ─────────────────────────────────────────────
  { term: "ARDS (Acute Respiratory Distress Syndrome)", type: "concept", category: "icu", meaning: "Acute non-cardiogenic pulmonary edema: bilateral infiltrates, PaO2/FiO2 ≤300 (mild) /≤200 (moderate) /≤100 (severe), no cardiogenic cause. Treated with low-tidal-volume ventilation (6 mL/kg IBW), high PEEP, prone positioning, conservative fluids.", example: "The septic patient's PaO2/FiO2 of 95 with bilateral infiltrates met severe ARDS criteria; lung-protective ventilation and prone positioning were initiated." },
  { term: "Mechanical Ventilation Basics", type: "concept", category: "icu", meaning: "Modes: Assist-Control (AC) — set RR + VT, full breath each trigger. SIMV — synchronized mandatory + spontaneous. Pressure Support (PSV) — augments spontaneous breaths, used for weaning. Settings: RR, VT, FiO2, PEEP, pressure support.", example: "The ARDS patient was placed on AC: VT 360 mL (6 mL/kg PBW), RR 22, FiO2 60%, PEEP 14 — lung-protective settings." },
  { term: "Sedation in the ICU", type: "concept", category: "icu", meaning: "Lightest sedation that allows tolerance of ventilator. Propofol (rapid on/off, propofol infusion syndrome risk), dexmedetomidine (alpha-2 — sedation without respiratory depression), midazolam (longer-acting). Daily sedation interruption (SAT) reduces ventilator days.", example: "The patient on propofol underwent daily SAT — sedation paused — to assess readiness for spontaneous breathing trial." },
  { term: "DVT Prophylaxis", type: "concept", category: "icu", meaning: "All ICU patients require VTE prophylaxis: pharmacologic (enoxaparin 40 mg SQ daily or heparin 5000 U SQ TID) unless bleeding risk; mechanical (sequential compression devices) if pharmacologic contraindicated. Reduces PE/DVT mortality.", example: "The ICU patient with normal coagulation received enoxaparin 40 mg SQ daily plus SCDs for VTE prophylaxis." },
  { term: "Stress Ulcer Prophylaxis", type: "concept", category: "icu", meaning: "Critically ill patients are at risk of stress-related GI bleeding. PPI (pantoprazole) or H2 blocker (famotidine) reduces risk. Indicated for mechanical ventilation >48 hr, coagulopathy, or other major risk factors.", example: "The mechanically ventilated patient received pantoprazole 40 mg IV daily for stress ulcer prophylaxis." },
  { term: "Sepsis Recognition (qSOFA)", type: "concept", category: "icu", meaning: "Quick SOFA bedside criteria: altered mental status, SBP ≤100, RR ≥22. ≥2 of 3 suggests sepsis with high mortality risk. Full SOFA (CV, resp, renal, hepatic, coag, GCS) used in ICU.", example: "The ED patient's HR 110, RR 26, AMS, and SBP 92 met qSOFA criteria — sepsis suspected; lactate and cultures were drawn." },
  { term: "Acute Kidney Injury in ICU", type: "concept", category: "icu", meaning: "Common in critically ill (~50%); prerenal (shock, dehydration), intrinsic (ATN from ischemia, contrast, drugs), postrenal (obstruction). Manage with volume optimization, avoid nephrotoxins, dose adjustment; CRRT for severe cases with hemodynamic instability.", example: "The septic shock patient's oliguric AKI required CRRT — provided slower fluid removal with less hemodynamic instability than intermittent hemodialysis." },
  { term: "Family Communication in ICU", type: "concept", category: "icu", meaning: "Frequent family meetings essential. Updates on diagnosis, prognosis, goals of care discussions. Code status clarification. Family presence during resuscitation increasingly supported. Cultural and spiritual considerations included.", example: "The ICU team held a goals-of-care meeting with the patient's family — clarifying poor prognosis, transitioning to comfort care, and arranging family bedside time." },
];'''
m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
html = html[:m.start()] + TERMS_JS + html[m.end():]
CAT = """const categoryLabel = c => ({
  'trauma-resuscitation': 'Trauma Resuscitation (ATLS)',
  'shock':                'Shock & Resuscitation',
  'icu':                  'ICU Concepts',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)
html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'trauma-critical-care';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>', '<title>HOSA Prep Hub — Trauma &amp; Critical Care</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>', '<h1>Trauma &amp;<br><em>Critical Care</em>.</h1>', 1)
html = html.replace('A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
                    'A study companion for trauma resuscitation and ATLS principles, shock and resuscitation, and core ICU concepts including ARDS, mechanical ventilation, and sepsis — built for HOSA competitors.', 1)
html = html.replace('//  DATA — HOSA Emergency Medical Science', '//  DATA — HOSA Trauma & Critical Care', 1)
with open(DST, 'w', encoding='utf-8') as f: f.write(html)
print(f'Wrote {DST} — {TERMS_JS.count("{ term:")} terms')
