import re, os

BASE = r'C:\Users\iamtk\Downloads\correct-source'

TERMS_JS = r"""const TERMS = [
  { term: "Biohazard", type: "concept", category: "lab-safety", meaning: "A biological agent or condition that presents a risk to human health; biohazard materials require special handling, labeling, and disposal.", example: "Blood specimens are transported in sealed biohazard bags to prevent spills and exposure." },
  { term: "Standard Precautions (Lab)", type: "concept", category: "lab-safety", meaning: "The practice of treating all biological specimens as potentially infectious regardless of source or apparent diagnosis.", example: "Gloves are worn when handling every patient specimen, even if the patient has no known infectious disease." },
  { term: "Safety Data Sheet (SDS)", type: "concept", category: "lab-safety", meaning: "A standardized document providing information on a chemical's properties, hazards, safe handling, storage, and emergency response procedures.", example: "Before using hydrochloric acid, the technician reviews the SDS to understand proper storage and spill response." },
  { term: "Fume Hood", type: "concept", category: "lab-safety", meaning: "A ventilated laboratory enclosure that draws air away from the worker, preventing inhalation of volatile chemicals or infectious aerosols.", example: "Volatile reagents and fungal cultures are handled inside a fume hood to protect the technician." },
  { term: "Autoclave", type: "concept", category: "lab-safety", meaning: "A device that uses pressurized steam at 121 degrees Celsius to sterilize instruments, media, and biohazardous waste by destroying all microorganisms.", example: "Used culture plates are autoclaved before disposal to kill all viable organisms." },
  { term: "Personal Protective Equipment (Lab PPE)", type: "concept", category: "lab-safety", meaning: "Gloves, lab coat, eye protection, and closed-toe shoes required when working with biological specimens, chemicals, or hazardous materials.", example: "Splash goggles are required when centrifuging specimens that may generate aerosols." },
  { term: "Chain of Custody", type: "concept", category: "lab-safety", meaning: "A documented trail tracking a specimen from collection through analysis, ensuring its integrity and legal admissibility throughout the testing process.", example: "Forensic and drug testing specimens require strict chain of custody documentation at every transfer." },
  { term: "Specimen Integrity", type: "concept", category: "lab-safety", meaning: "The suitability of a specimen for the intended analysis; compromised by hemolysis, lipemia, icterus, improper volume, or incorrect storage conditions.", example: "A hemolyzed specimen may cause falsely elevated potassium results, requiring a recollect." },
  { term: "Calibration", type: "concept", category: "lab-safety", meaning: "The process of standardizing a laboratory instrument or method against known reference materials to ensure measurements are accurate and traceable.", example: "A glucometer is calibrated daily with a control solution before patient testing begins." },
  { term: "Centrifuge", type: "concept", category: "lab-safety", meaning: "A laboratory instrument that uses centrifugal force to separate components of a specimen by density; specimens must be balanced to prevent rotor damage.", example: "Blood specimens are centrifuged at 1500 to 2000 RPM for 10 minutes to separate serum from cells." },
  { term: "Phlebotomy", type: "procedure", category: "lab-safety", meaning: "The process of drawing blood from a patient for laboratory testing; requires correct tube selection, order of draw, and labeling at the bedside.", example: "The correct order of draw prevents anticoagulant carryover: blood cultures, citrate, SST, heparin, EDTA." },
  { term: "Order of Draw", type: "concept", category: "lab-safety", meaning: "The standardized sequence for filling multiple blood collection tubes during a single venipuncture to prevent additive cross-contamination.", example: "EDTA tubes for CBC are drawn after serum separator and heparin tubes in the order of draw." },

  { term: "Bacteria", type: "concept", category: "microbiology", meaning: "Single-celled prokaryotic organisms classified by shape (cocci, bacilli, spirilla), arrangement, and Gram stain reaction; cause a wide range of human infections.", example: "Staphylococcus aureus is a Gram-positive coccus that causes skin infections, pneumonia, and sepsis." },
  { term: "Gram Stain", type: "procedure", category: "microbiology", meaning: "The most fundamental differential staining technique in microbiology, classifying bacteria as Gram-positive (purple) or Gram-negative (pink/red) based on cell wall composition.", example: "A Gram stain of a wound swab reveals Gram-negative rods, guiding initial antibiotic selection." },
  { term: "Gram-Positive Bacteria", type: "concept", category: "microbiology", meaning: "Bacteria with a thick peptidoglycan cell wall that retains crystal violet dye, appearing purple under microscopy; examples include Staphylococcus and Streptococcus.", example: "Streptococcus pneumoniae is a Gram-positive diplococcus and a common cause of bacterial pneumonia." },
  { term: "Gram-Negative Bacteria", type: "concept", category: "microbiology", meaning: "Bacteria with a thin peptidoglycan layer and an outer lipopolysaccharide membrane that does not retain crystal violet, appearing pink after safranin counterstain.", example: "Escherichia coli is a Gram-negative rod that is the most common cause of urinary tract infections." },
  { term: "Culture Media", type: "concept", category: "microbiology", meaning: "Nutrient preparations used to grow, isolate, and identify microorganisms; types include blood agar (general), MacConkey (Gram-negative selective), and chocolate agar.", example: "Blood agar is used to detect hemolysis patterns that help identify streptococcal species." },
  { term: "Sensitivity Testing", type: "procedure", category: "microbiology", meaning: "Laboratory testing (antibiogram or disk diffusion) to determine which antimicrobial agents effectively inhibit growth of an isolated pathogen.", example: "Sensitivity testing guides the physician to prescribe the most effective antibiotic for a MRSA infection." },
  { term: "Acid-Fast Bacilli (AFB) Stain", type: "procedure", category: "microbiology", meaning: "A special staining technique that identifies mycobacteria, including Mycobacterium tuberculosis, which retain carbol fuchsin dye despite acid-alcohol decolorization.", example: "Three consecutive AFB sputum smears are collected to evaluate a patient for active pulmonary tuberculosis." },
  { term: "Virus", type: "concept", category: "microbiology", meaning: "An obligate intracellular pathogen composed of nucleic acid (DNA or RNA) enclosed in a protein capsid; requires a host cell to replicate.", example: "Influenza A is an RNA virus that causes seasonal respiratory illness and occasional pandemics." },
  { term: "Fungi", type: "concept", category: "microbiology", meaning: "Eukaryotic organisms including unicellular yeasts and multicellular molds; can cause superficial or systemic infections, especially in immunocompromised patients.", example: "Candida albicans is a yeast that causes oral thrush and vaginal candidiasis." },
  { term: "Minimum Inhibitory Concentration (MIC)", type: "concept", category: "microbiology", meaning: "The lowest concentration of an antimicrobial agent that visibly inhibits growth of a specific microorganism in vitro; guides antibiotic dosing.", example: "A low MIC indicates the organism is highly susceptible to that antibiotic." },
  { term: "Normal Flora", type: "concept", category: "microbiology", meaning: "Microorganisms that normally colonize the human body without causing disease; can become pathogenic if displaced to a non-native site.", example: "E. coli is normal flora in the colon but causes UTI when it colonizes the urethra." },
  { term: "Biofilm", type: "concept", category: "microbiology", meaning: "A structured community of microorganisms encased in a self-produced extracellular matrix that adheres to surfaces and shows dramatically increased antibiotic resistance.", example: "Biofilms on urinary catheters and orthopedic implants are a major cause of persistent healthcare infections." },
  { term: "Colony Forming Unit (CFU)", type: "concept", category: "microbiology", meaning: "A measure of the number of viable microorganisms in a sample based on the ability to form a visible colony on culture media.", example: "A urine culture with greater than 100,000 CFU/mL of a single organism confirms a urinary tract infection." },

  { term: "Complete Blood Count (CBC)", type: "concept", category: "hematology", meaning: "A fundamental blood test measuring red blood cells, white blood cells, hemoglobin, hematocrit, mean corpuscular volume, and platelet count.", example: "A CBC is ordered to evaluate fatigue, infection, bleeding, or to monitor chemotherapy effects." },
  { term: "Hemoglobin", type: "concept", category: "hematology", meaning: "The iron-containing protein within red blood cells that binds and transports oxygen from the lungs to tissues and carries carbon dioxide back for exhalation.", example: "A hemoglobin below 12 g/dL in women indicates anemia and prompts further evaluation." },
  { term: "Hematocrit", type: "concept", category: "hematology", meaning: "The percentage of total blood volume occupied by packed red blood cells; normal is approximately 38 to 52 percent in men and 36 to 48 percent in women.", example: "A hematocrit of 28 percent in a post-surgical patient suggests significant blood loss." },
  { term: "WBC Differential", type: "concept", category: "hematology", meaning: "The percentage breakdown of the five white blood cell types: neutrophils, lymphocytes, monocytes, eosinophils, and basophils; used to characterize infection or disease.", example: "A left shift (increased immature neutrophils) on the differential indicates a severe bacterial infection." },
  { term: "Neutrophil", type: "concept", category: "hematology", meaning: "The most abundant leukocyte and the primary first-responder to bacterial infection; characterized by a segmented, multilobed nucleus.", example: "Neutrophilia (elevated neutrophils) is typical of acute bacterial infections." },
  { term: "Lymphocyte", type: "concept", category: "hematology", meaning: "A white blood cell central to adaptive immunity; T lymphocytes mediate cell-mediated immunity and B lymphocytes produce antibodies.", example: "Lymphocytosis with atypical lymphocytes on peripheral smear is characteristic of infectious mononucleosis." },
  { term: "Erythrocyte (RBC)", type: "concept", category: "hematology", meaning: "A biconcave, anucleate red blood cell that carries hemoglobin; produced in red bone marrow and survives approximately 120 days in circulation.", example: "Microcytic, hypochromic RBCs on peripheral smear are characteristic of iron-deficiency anemia." },
  { term: "Platelet (Thrombocyte)", type: "concept", category: "hematology", meaning: "A small anucleate cell fragment derived from megakaryocytes that initiates hemostasis by forming a platelet plug at sites of vascular injury.", example: "A platelet count below 50,000/microL significantly increases surgical bleeding risk." },
  { term: "Anemia", type: "condition", category: "hematology", meaning: "A reduction in hemoglobin, hematocrit, or red blood cell count resulting in decreased oxygen-carrying capacity; classified by RBC size and hemoglobin content.", example: "Iron-deficiency anemia is the most common anemia worldwide, presenting with fatigue and pallor." },
  { term: "Leukocytosis", type: "condition", category: "hematology", meaning: "An elevated white blood cell count above 11,000 cells per microliter; typically indicates infection, inflammation, tissue necrosis, or hematologic malignancy.", example: "A WBC of 18,000 in a febrile patient suggests significant bacterial infection." },
  { term: "Thrombocytopenia", type: "condition", category: "hematology", meaning: "A platelet count below 150,000 per microliter; causes increased bleeding risk and can result from decreased production, increased destruction, or sequestration.", example: "Immune thrombocytopenic purpura causes platelet destruction by autoantibodies." },
  { term: "Blood Typing (ABO/Rh)", type: "procedure", category: "hematology", meaning: "The classification of blood by ABO antigens on red cell surfaces and presence or absence of Rh factor; critical for safe blood transfusion and organ transplant.", example: "Type O negative blood is the universal donor because it lacks A, B, and Rh antigens." },
  { term: "Coagulation Studies (PT/INR)", type: "procedure", category: "hematology", meaning: "Prothrombin time and International Normalized Ratio measure the extrinsic coagulation pathway; used to monitor warfarin therapy and assess bleeding disorders.", example: "A patient on warfarin has an INR checked regularly to maintain therapeutic anticoagulation." },

  { term: "Urinalysis (UA)", type: "procedure", category: "urinalysis", meaning: "A comprehensive examination of urine physical characteristics, chemical composition, and microscopic elements used as a routine diagnostic screening test.", example: "A UA is ordered on admission to screen for urinary tract infection, kidney disease, and diabetes." },
  { term: "Specific Gravity", type: "concept", category: "urinalysis", meaning: "A measure of urine concentration comparing its density to water; reflects the kidney's ability to concentrate or dilute urine; normal range is 1.001 to 1.035.", example: "Very high specific gravity indicates dehydration; very low suggests diabetes insipidus or over-hydration." },
  { term: "Urine pH", type: "concept", category: "urinalysis", meaning: "The acidity or alkalinity of urine on a scale of 4.5 to 8.0; influenced by diet, medications, acid-base disorders, and kidney function.", example: "An alkaline urine pH above 7.0 in a UTI patient suggests urease-producing bacteria like Proteus." },
  { term: "Proteinuria", type: "condition", category: "urinalysis", meaning: "Abnormal loss of protein in the urine indicating damage to the glomerular filtration membrane; a hallmark of kidney disease, hypertension, and diabetic nephropathy.", example: "Persistent 2+ protein on dipstick prompts a 24-hour urine collection to quantify proteinuria." },
  { term: "Glucosuria", type: "condition", category: "urinalysis", meaning: "The presence of glucose in the urine, occurring when blood glucose exceeds the renal threshold of approximately 180 mg/dL; a common finding in uncontrolled diabetes.", example: "A patient with glucosuria and polyuria is evaluated for diabetes mellitus." },
  { term: "Hematuria", type: "condition", category: "urinalysis", meaning: "The presence of red blood cells in the urine; classified as gross (visible to the naked eye) or microscopic (detected only on UA).", example: "Microscopic hematuria in a 60-year-old smoker warrants evaluation for bladder cancer." },
  { term: "Ketonuria", type: "condition", category: "urinalysis", meaning: "The presence of ketone bodies in the urine resulting from fat metabolism; occurs in diabetic ketoacidosis, prolonged fasting, or very low carbohydrate diets.", example: "Large ketones on dipstick combined with high glucose suggests diabetic ketoacidosis." },
  { term: "Leukocyte Esterase", type: "concept", category: "urinalysis", meaning: "A dipstick test detecting the enzyme released by neutrophils in urine; a positive result indicates pyuria and possible urinary tract infection.", example: "Positive leukocyte esterase combined with positive nitrite strongly suggests a bacterial UTI." },
  { term: "Urinary Casts", type: "concept", category: "urinalysis", meaning: "Cylindrical microscopic structures formed from protein or cellular material in kidney tubules; type indicates specific pathology (RBC casts suggest glomerulonephritis).", example: "Waxy casts in urine indicate advanced chronic kidney disease." },
  { term: "Dipstick Analysis", type: "procedure", category: "urinalysis", meaning: "A rapid semi-quantitative colorimetric test strip used to screen urine for pH, protein, glucose, ketones, blood, nitrites, bilirubin, and leukocyte esterase.", example: "Dipstick urinalysis provides results in under two minutes as a first-line screening tool." },
  { term: "Clean-Catch Midstream Specimen", type: "procedure", category: "urinalysis", meaning: "A urine collection technique using perineal cleaning and discarding the initial urinary stream to minimize contamination from skin flora.", example: "A clean-catch specimen is required for culture to distinguish true infection from contamination." },

  { term: "Basic Metabolic Panel (BMP)", type: "concept", category: "clinical-chemistry", meaning: "A group of eight blood tests measuring glucose, electrolytes (sodium, potassium, chloride, bicarbonate), blood urea nitrogen, creatinine, and calcium.", example: "A BMP is ordered to assess a patient's kidney function, blood sugar, and acid-base status." },
  { term: "Blood Urea Nitrogen (BUN)", type: "concept", category: "clinical-chemistry", meaning: "A measure of urea in the blood reflecting protein metabolism and kidney filtration; elevated in kidney failure, dehydration, and high protein intake.", example: "A BUN of 42 mg/dL with elevated creatinine indicates reduced kidney function." },
  { term: "Creatinine", type: "concept", category: "clinical-chemistry", meaning: "A waste product of muscle creatine metabolism excreted by the kidneys; elevated serum creatinine is a sensitive indicator of decreased kidney filtration.", example: "Creatinine rising from 0.9 to 2.4 mg/dL post-operatively signals acute kidney injury." },
  { term: "Electrolytes", type: "concept", category: "clinical-chemistry", meaning: "Ionized minerals in the blood including sodium, potassium, chloride, and bicarbonate that regulate fluid balance, nerve impulse transmission, and muscle contraction.", example: "Electrolytes are monitored closely in patients receiving IV fluids or diuretics." },
  { term: "Liver Function Tests (LFTs)", type: "concept", category: "clinical-chemistry", meaning: "A panel of blood tests including ALT, AST, ALP, bilirubin, albumin, and total protein used to detect liver cell damage, inflammation, or impaired synthetic function.", example: "Elevated ALT and AST with jaundice suggest hepatocellular injury from hepatitis or drug toxicity." },
  { term: "Lipid Panel", type: "concept", category: "clinical-chemistry", meaning: "A fasting blood test measuring total cholesterol, LDL (low-density lipoprotein), HDL (high-density lipoprotein), and triglycerides to assess cardiovascular risk.", example: "An LDL above 190 mg/dL indicates a significant cardiovascular risk requiring statin therapy." },
  { term: "Hemoglobin A1c (HbA1c)", type: "concept", category: "clinical-chemistry", meaning: "Glycated hemoglobin reflecting average blood glucose concentration over the preceding 2 to 3 months; used to diagnose and monitor diabetes mellitus.", example: "An HbA1c of 7.5 percent in a diabetic patient indicates blood glucose is above target." },
  { term: "Troponin", type: "concept", category: "clinical-chemistry", meaning: "A cardiac contractile protein released into the bloodstream when myocardial cells are damaged; the most sensitive and specific biomarker for acute myocardial infarction.", example: "Serial troponin measurements over 3 to 6 hours are used to confirm or rule out a heart attack." },
  { term: "Point-of-Care Testing (POCT)", type: "concept", category: "clinical-chemistry", meaning: "Diagnostic testing performed at or near the patient rather than in a central laboratory to deliver faster results and guide immediate clinical decisions.", example: "Bedside glucose monitoring and rapid influenza tests are common examples of point-of-care testing." },
  { term: "Thyroid-Stimulating Hormone (TSH)", type: "concept", category: "clinical-chemistry", meaning: "A pituitary hormone that regulates thyroid function; elevated TSH indicates hypothyroidism, while low TSH indicates hyperthyroidism.", example: "A TSH of 12 mIU/L in a fatigued patient with weight gain confirms hypothyroidism." },
  { term: "Bilirubin", type: "concept", category: "clinical-chemistry", meaning: "A yellow pigment produced from hemoglobin breakdown; elevated serum bilirubin causes jaundice and indicates hemolysis, liver disease, or bile duct obstruction.", example: "A newborn with total bilirubin above 20 mg/dL receives phototherapy to prevent kernicterus." },

  { term: "Quality Control (QC)", type: "concept", category: "quality-control", meaning: "A system of procedures and controls ensuring that laboratory test results are accurate, precise, and reliable through routine testing of known control specimens.", example: "Two levels of QC are run each day to verify the chemistry analyzer is performing correctly." },
  { term: "Accuracy", type: "concept", category: "quality-control", meaning: "The closeness of a measured test result to the true or accepted reference value; assessed using calibrators and reference materials.", example: "A method with high accuracy produces results that consistently match the true concentration." },
  { term: "Precision", type: "concept", category: "quality-control", meaning: "The reproducibility of repeated measurements under the same conditions; a precise method gives consistent results even if they are not accurate.", example: "Running the same QC sample ten times and getting nearly identical values demonstrates high precision." },
  { term: "Reference Interval", type: "concept", category: "quality-control", meaning: "The range of values expected in 95 percent of a healthy reference population; used to determine whether a patient result is within normal limits.", example: "A sodium result of 148 mEq/L is above the reference interval of 136 to 145, indicating hypernatremia." },
  { term: "False Positive", type: "concept", category: "quality-control", meaning: "A test result that indicates the presence of a disease or condition when it is actually absent; leads to unnecessary treatment or anxiety.", example: "A false positive HIV antibody test requires confirmatory testing before diagnosis." },
  { term: "False Negative", type: "concept", category: "quality-control", meaning: "A test result that indicates absence of a disease or condition when it is actually present; potentially dangerous if treatment is withheld.", example: "A false negative rapid strep test in a symptomatic child may result in untreated strep throat." },
  { term: "Proficiency Testing", type: "concept", category: "quality-control", meaning: "An external quality assurance program in which laboratories analyze blinded specimens from an accrediting agency and compare results to peer laboratories.", example: "CLIA requires laboratories to participate in proficiency testing programs to maintain certification." },
  { term: "Delta Check", type: "concept", category: "quality-control", meaning: "A comparison of a patient's current laboratory result with their most recent previous result to identify implausible changes that may indicate an error.", example: "A potassium jump from 4.0 to 6.8 mEq/L triggers a delta check and a specimen recollect." },
];"""

src = os.path.join(BASE, 'sports-medicine.html')
dst = os.path.join(BASE, 'biomedical-lab-science.html')

with open(src, 'r', encoding='utf-8') as f:
    c = f.read()

c = c.replace('<title>HOSA Prep Hub — Sports Medicine</title>',
              '<title>HOSA Prep Hub — Biomedical Laboratory Science</title>')
c = c.replace('Category 13 — Sports Medicine',
              'Category 14 — Biomedical Laboratory Science')
c = c.replace('Athletic Injury &amp;<br><em>Sports Medicine</em>.',
              'Lab Science &amp;<br><em>Diagnostics</em>.')
c = c.replace(
    'A study companion for sports injuries, injury assessment, musculoskeletal anatomy, treatment techniques, rehabilitation principles, and medical conditions in athletes — built for HOSA competitors preparing for the Sports Medicine competitive event.',
    'A study companion for laboratory safety, microbiology, hematology, urinalysis, clinical chemistry, and quality control — built for HOSA competitors preparing for the Biomedical Laboratory Science competitive event.'
)
c = c.replace('The HOSA Sports Medicine Examination',
              'The HOSA Biomedical Laboratory Science Examination')
c = c.replace(
    "A timed assessment modeled on competition conditions. You'll be shown sports medicine concepts drawn from all topic areas — injury types, assessment techniques, anatomy, treatment, rehabilitation, and medical conditions in athletes. Select the correct definition. No retries, no feedback until the end.",
    "A timed assessment modeled on competition conditions. You'll be shown biomedical laboratory science concepts from all topic areas — lab safety, microbiology, hematology, urinalysis, clinical chemistry, and quality control. Select the correct definition. No retries, no feedback until the end."
)
c = c.replace("const DB_PATH = 'sports-medicine'",
              "const DB_PATH = 'biomedical-lab-science'")
c = re.sub(r'const TERMS = \[.*?\];', TERMS_JS, c, count=1, flags=re.DOTALL)
c = c.replace(
    """const categoryLabel = c => ({
  'injuries': 'Sports Injuries',
  'assessment': 'Injury Assessment',
  'anatomy': 'Musculoskeletal Anatomy',
  'treatment': 'Treatment Techniques',
  'rehabilitation': 'Rehabilitation',
  'conditions': 'Medical Conditions',
})[c] || c;""",
    """const categoryLabel = c => ({
  'lab-safety': 'Lab Safety & Specimens',
  'microbiology': 'Microbiology',
  'hematology': 'Hematology',
  'urinalysis': 'Urinalysis',
  'clinical-chemistry': 'Clinical Chemistry',
  'quality-control': 'Quality Control',
})[c] || c;"""
)

with open(dst, 'w', encoding='utf-8') as f:
    f.write(c)

print(f'biomedical-lab-science.html written ({len(c):,} chars)')
