#!/usr/bin/env python3
"""Generate pharmacy-science.html from dental-science.html template."""
import os, re

BASE = '/home/user/hosa-prep-hub'
SRC  = os.path.join(BASE, 'dental-science.html')
DST  = os.path.join(BASE, 'pharmacy-science.html')

with open(SRC, 'r', encoding='utf-8') as f:
    html = f.read()

TERMS_JS = '''const TERMS = [
  // ── Prescription & Dispensing ────────────────────────────────
  { term: "Anatomy of a Prescription", type: "concept", category: "prescription", meaning: "Required elements: prescriber info and DEA #, patient info, date, drug name and strength, dosage form, quantity (Disp.), Sig (directions to patient), refills, generic substitution permission, prescriber signature.", example: "The Rx read 'Amoxicillin 500 mg caps, Disp #21, Sig: 1 cap PO TID x 7 days, Refills 0' — every required element was complete and legible." },
  { term: "Sig Codes (Latin Abbreviations)", type: "concept", category: "prescription", meaning: "Pharmacy Latin abbreviations: PO (by mouth), PR (rectally), IM (intramuscular), IV (intravenous), SC/SQ (subcutaneous); QD/daily, BID (twice daily), TID, QID, HS (bedtime), AC (before meals), PC (after meals), PRN (as needed).", example: "Sig: '1 tab PO BID PC' was interpreted by the pharmacist as 'take one tablet by mouth twice daily after meals'." },
  { term: "ISMP Do-Not-Use Abbreviations", type: "concept", category: "prescription", meaning: "Error-prone abbreviations the Institute for Safe Medication Practices and Joint Commission ban: U (write 'unit'), IU (write 'international unit'), QD/QOD (write 'daily/every other day'), trailing zero (1.0 mg), naked decimal (.5 mg → write 0.5 mg).", example: "The handwritten order for '10U insulin' was rejected and the prescriber asked to rewrite 'units' to prevent confusion with '100' or '40'." },
  { term: "Generic vs Brand Name", type: "concept", category: "prescription", meaning: "The generic name (e.g., ibuprofen) is the nonproprietary name; the brand (Advil, Motrin) is the trademarked manufacturer name. Generics must demonstrate bioequivalence (AB rating in Orange Book) to substitute for the brand.", example: "The prescriber wrote 'Lipitor 20 mg' — the pharmacist dispensed AB-rated generic atorvastatin since the patient had not selected 'dispense as written.'" },
  { term: "DAW (Dispense As Written)", type: "concept", category: "prescription", meaning: "Codes indicating whether generic substitution is allowed: DAW 0 (substitution allowed), DAW 1 (prescriber wants brand), DAW 2 (patient requests brand). DAW 1 typically requires a clinical justification.", example: "The prescription marked DAW 1 specified brand-name Synthroid; the pharmacist dispensed brand-only and noted the prescriber's preference." },
  { term: "Controlled Substance Schedules", type: "concept", category: "prescription", meaning: "DEA Schedule I: no medical use, high abuse (heroin, LSD). Schedule II: highest medical, high abuse (oxycodone, fentanyl, amphetamines) — no refills, written or e-Rx. III–V: progressively lower abuse, refills allowed up to 5 in 6 months.", example: "The Schedule II prescription for oxycodone was written for 30 tabs with no refills, in compliance with DEA requirements for CII medications." },
  { term: "Refill Rules", type: "concept", category: "prescription", meaning: "Schedule II: no refills (new Rx required each time). Schedule III–V: up to 5 refills within 6 months. Non-controlled: usually 1 year refills if authorized. Early refill rules vary by state and insurance.", example: "The patient's hydrocodone (Schedule II) prescription could not be refilled — a new written or electronic prescription was required from the prescriber." },
  { term: "NDC (National Drug Code)", type: "concept", category: "prescription", meaning: "An FDA-assigned 10–11 digit numeric identifier on every drug product, structured as labeler-product-package code; required on prescription labels and used in billing and inventory.", example: "The pharmacy verified the NDC on the lisinopril bottle (0093-1037-01) matched the dispensing label before bagging the prescription." },
  { term: "Prescription Label Requirements", type: "concept", category: "prescription", meaning: "Federal law requires pharmacy name and address, prescription number, date, patient name, prescriber, drug name and strength, directions for use, quantity, refills, expiration/beyond-use date, and warning labels (auxiliary).", example: "The dispensing label included all required elements; an auxiliary warning sticker reading 'TAKE WITH FOOD' was applied to the metformin bottle." },
  { term: "Beyond-Use Date (BUD)", type: "concept", category: "prescription", meaning: "The date after which a dispensed or compounded product should not be used; differs from manufacturer's expiration date. USP <795> sets BUDs for non-sterile compounds; <797> for sterile compounds.", example: "The compounded oral suspension had a BUD of 14 days from the date of compounding, labeled clearly on the prescription bottle." },

  // ── Pharmacology & Drug Classes ──────────────────────────────
  { term: "ACE Inhibitors", type: "concept", category: "drug-classes", meaning: "Block angiotensin-converting enzyme, reducing angiotensin II and aldosterone. Drugs end in -pril (lisinopril, enalapril). Indications: hypertension, heart failure, post-MI, diabetic nephropathy. Side effects: dry cough, hyperkalemia, angioedema, teratogenic.", example: "The diabetic patient's lisinopril was renoprotective; the persistent dry cough was a known ACE inhibitor side effect from elevated bradykinin." },
  { term: "Beta-Blockers", type: "concept", category: "drug-classes", meaning: "Block beta-adrenergic receptors. Drugs end in -olol. Cardioselective (B1 only): metoprolol, atenolol. Non-selective: propranolol, nadolol. Indications: HTN, angina, post-MI, heart failure (specific agents), arrhythmias. Caution in asthma/COPD.", example: "Metoprolol succinate was selected for the COPD patient because it is cardioselective and less likely to provoke bronchospasm than propranolol." },
  { term: "Statins (HMG-CoA Reductase Inhibitors)", type: "concept", category: "drug-classes", meaning: "Inhibit the rate-limiting enzyme of cholesterol synthesis, reducing LDL by 20–60%. Drugs end in -statin (atorvastatin, rosuvastatin). Side effects: myalgia, rhabdomyolysis (rare), hepatotoxicity. CK monitored if muscle pain.", example: "The patient was started on atorvastatin 40 mg; a follow-up lipid panel showed LDL dropping from 165 to 95 mg/dL." },
  { term: "SSRIs", type: "concept", category: "drug-classes", meaning: "Selective serotonin reuptake inhibitors increase synaptic serotonin. Examples: fluoxetine, sertraline, escitalopram. Used for depression, anxiety, OCD. Side effects: sexual dysfunction, GI upset, hyponatremia (SIADH), serotonin syndrome with MAOIs.", example: "The patient's anxiety improved on sertraline 50 mg daily after 4–6 weeks; full antidepressant effect requires sustained dosing." },
  { term: "Benzodiazepines", type: "concept", category: "drug-classes", meaning: "Enhance GABA-A receptor function, producing anxiolysis, sedation, muscle relaxation, anticonvulsant effect. Examples: lorazepam, alprazolam, diazepam, midazolam. High abuse potential (Schedule IV); reversed by flumazenil.", example: "The patient in status epilepticus received IV lorazepam 4 mg, terminating seizures within 90 seconds via GABA potentiation." },
  { term: "Opioid Analgesics", type: "concept", category: "drug-classes", meaning: "Act at mu, kappa, and delta opioid receptors. Examples: morphine, hydromorphone, oxycodone, fentanyl. Schedule II. Side effects: respiratory depression, constipation, nausea, pruritus, dependence. Reversed by naloxone.", example: "The post-op patient's respiratory rate dropped to 6/min on morphine PCA; naloxone 0.4 mg IV restored respiratory drive within 2 minutes." },
  { term: "Anticoagulants", type: "concept", category: "drug-classes", meaning: "Warfarin (vitamin K antagonist, monitored by INR), heparin (potentiates antithrombin III, monitored by aPTT), LMWH (enoxaparin), DOACs (apixaban, rivaroxaban — factor Xa inhibitors; dabigatran — direct thrombin inhibitor).", example: "The patient's atrial fibrillation was managed with apixaban — a factor Xa inhibitor — avoiding the INR monitoring required with warfarin." },
  { term: "Insulin Types and Onset", type: "concept", category: "drug-classes", meaning: "Rapid-acting (lispro, aspart — onset 15 min, peak 1–2 h, duration 3–4 h). Short (regular). Intermediate (NPH). Long-acting (glargine, detemir — flat, 24 h). Choice based on prandial vs basal coverage.", example: "The type 1 diabetic used insulin glargine once nightly for basal coverage and insulin lispro before meals for postprandial control." },
  { term: "Bronchodilators", type: "concept", category: "drug-classes", meaning: "Beta-2 agonists (albuterol — short; salmeterol, formoterol — long); anticholinergics (ipratropium — short; tiotropium — long); methylxanthines (theophylline). Used for asthma and COPD; SABAs for acute relief, LABAs/LAMAs for maintenance.", example: "The asthmatic patient used an albuterol rescue inhaler for acute symptoms and inhaled corticosteroid plus formoterol daily for maintenance." },
  { term: "Antibiotics by Class", type: "concept", category: "drug-classes", meaning: "Penicillins (amoxicillin), cephalosporins (cefazolin, ceftriaxone), macrolides (azithromycin), fluoroquinolones (ciprofloxacin), tetracyclines (doxycycline), sulfonamides (TMP-SMX), aminoglycosides (gentamicin), glycopeptides (vancomycin).", example: "Empiric coverage for community-acquired pneumonia combined ceftriaxone (cephalosporin) and azithromycin (macrolide) to cover both typical and atypical organisms." },

  // ── Pharmacokinetics & Dynamics ──────────────────────────────
  { term: "Pharmacokinetics (ADME)", type: "concept", category: "kinetics", meaning: "How the body affects a drug: Absorption (rate/extent reaching systemic circulation), Distribution (tissue partitioning, protein binding), Metabolism (mostly hepatic CYP450), Excretion (mostly renal). Determines onset, duration, and clearance.", example: "The CYP3A4 inhibitor caused decreased metabolism of the patient's calcium channel blocker — a pharmacokinetic interaction increasing drug levels and hypotension risk." },
  { term: "Pharmacodynamics", type: "concept", category: "kinetics", meaning: "How a drug affects the body: receptor binding, dose-response relationships, efficacy (maximum effect), potency (dose for given effect), therapeutic index (TD50/ED50 — wider is safer).", example: "Warfarin has a narrow therapeutic index, so small dose changes cause large INR swings — requiring frequent monitoring to maintain efficacy without bleeding." },
  { term: "First-Pass Metabolism", type: "concept", category: "kinetics", meaning: "Hepatic and gut wall metabolism of orally administered drugs before they reach systemic circulation, reducing bioavailability. Drugs with high first-pass effect (morphine, propranolol, nitroglycerin) often require higher PO doses or alternative routes.", example: "Sublingual nitroglycerin bypasses first-pass hepatic metabolism, achieving rapid systemic effects for acute angina that oral nitrates could not." },
  { term: "Half-Life (t½)", type: "concept", category: "kinetics", meaning: "Time required for plasma concentration to decrease by 50%. Approximately 5 half-lives are needed to reach steady state with regular dosing or to eliminate a drug after stopping. Determines dosing interval.", example: "Amiodarone has a half-life of 30–100 days — full steady state takes months and discontinuation effects persist for weeks." },
  { term: "Bioavailability (F)", type: "concept", category: "kinetics", meaning: "The fraction of an administered dose reaching systemic circulation unchanged. IV bioavailability = 100% by definition; oral bioavailability is reduced by incomplete absorption and first-pass metabolism. Important in generic substitution.", example: "The oral bioavailability of propranolol is only 25% due to extensive first-pass metabolism, requiring much higher PO than IV doses." },
  { term: "CYP450 Drug Interactions", type: "concept", category: "kinetics", meaning: "Hepatic cytochrome P450 enzymes (especially CYP3A4, 2D6, 2C9, 2C19) metabolize most drugs. Inducers (rifampin, phenytoin, carbamazepine) speed metabolism (↓ drug levels); inhibitors (grapefruit juice, ketoconazole, ritonavir) slow it (↑ levels, toxicity).", example: "Grapefruit juice inhibited CYP3A4 metabolism of the patient's simvastatin, doubling drug levels and triggering myopathy." },
  { term: "Therapeutic Drug Monitoring", type: "concept", category: "kinetics", meaning: "Measuring drug levels to optimize dosing for narrow-therapeutic-index drugs: digoxin, lithium, phenytoin, warfarin (INR), vancomycin (trough), aminoglycosides (peak/trough). Levels drawn at specified times relative to dosing.", example: "The vancomycin trough was drawn 30 minutes before the fourth dose; the level of 18 µg/mL was within the 15–20 µg/mL target range." },
  { term: "Loading Dose vs Maintenance Dose", type: "concept", category: "kinetics", meaning: "A loading dose rapidly achieves therapeutic concentration (used for drugs with long half-lives like amiodarone or digoxin); a maintenance dose replaces what is eliminated each interval to keep steady state.", example: "The patient received an amiodarone loading dose of 1 g over 24 hours before transitioning to the 200 mg daily maintenance dose." },
  { term: "Renal Dose Adjustment", type: "concept", category: "kinetics", meaning: "Renally cleared drugs require dose reduction or interval extension in kidney disease, guided by CrCl (Cockcroft-Gault) or eGFR. Examples: vancomycin, aminoglycosides, gabapentin, metformin, many DOACs.", example: "The patient's CrCl of 25 mL/min required apixaban dose reduction from 5 mg BID to 2.5 mg BID per renal-dosing guidelines." },

  // ── Compounding & Calculations ───────────────────────────────
  { term: "Sterile Compounding (USP <797>)", type: "concept", category: "compounding", meaning: "Standards for preparing sterile preparations (IV admixtures, eye drops, injections); requires ISO 5 primary engineering control (laminar airflow hood) within an ISO 7 buffer area, gowning, and proper aseptic technique.", example: "The pharmacy technician donned shoe covers, gown, mask, and gloves before entering the ISO 7 cleanroom to compound the chemotherapy IV under the ISO 5 hood." },
  { term: "Non-Sterile Compounding (USP <795>)", type: "concept", category: "compounding", meaning: "Standards for preparing non-sterile products (capsules, ointments, oral suspensions); requires a clean designated area, calibrated equipment, master formulation records, and assignment of beyond-use dates by preparation type.", example: "The compounded ibuprofen 100 mg/mL oral suspension was prepared per the master formulation record, assigned a 14-day BUD, and labeled accordingly." },
  { term: "Hazardous Drug Handling (USP <800>)", type: "concept", category: "compounding", meaning: "Standards for safe handling of hazardous drugs (chemotherapy, hormones, antivirals) to protect personnel; requires negative-pressure containment, closed-system drug-transfer devices (CSTDs), chemo gowns, double gloves, and N95 or PAPR.", example: "The technician compounded the doxorubicin chemotherapy in a negative-pressure containment hood, using a CSTD to prevent aerosolization and contamination." },
  { term: "Ratio and Proportion Calculation", type: "concept", category: "compounding", meaning: "Pharmacy math basics: if X mg is in Y mL, what dose is in Z mL? Set up X/Y = ?/Z. Used for liquid dosing, dilution, and IV rate calculations. Always verify units before solving.", example: "Amoxicillin 250 mg/5 mL: how many mL for a 400 mg dose? 250/5 = 400/x; x = 8 mL." },
  { term: "Alligation", type: "concept", category: "compounding", meaning: "Method for mixing two strengths of the same active ingredient to achieve a desired intermediate strength. Uses an alligation 'tic-tac-toe' grid showing parts of each stock required.", example: "To prepare 70% alcohol from 95% and 50% stock: alligation gives parts (70−50)=20 of 95% and (95−70)=25 of 50%, ratio 20:25." },
  { term: "IV Drip Rate Calculation", type: "concept", category: "compounding", meaning: "mL/hr or gtt/min from a desired dose/time. Example: 1000 mL over 8 hr = 125 mL/hr; or with 15 gtt/mL tubing, 125 mL/hr × 15 / 60 = 31 gtt/min. Always include drop factor for manual sets.", example: "1 L NS to infuse over 4 hours with 20 gtt/mL tubing: 250 mL/hr × 20/60 = 83 gtt/min." },
  { term: "Body Surface Area (BSA) Dosing", type: "concept", category: "compounding", meaning: "BSA (m²) is used for chemotherapy and pediatric dosing because it correlates better than weight with drug clearance. Mosteller formula: √[(height cm × weight kg) / 3600]. Doses expressed as mg/m² × BSA.", example: "A chemotherapy order for 60 mg/m² doxorubicin in a 1.7 m² patient calculated to 102 mg per cycle." },
  { term: "Weight-Based Dosing", type: "concept", category: "compounding", meaning: "Drugs dosed by patient weight (mg/kg), especially in pediatrics and for narrow-therapeutic-index drugs. Use total or ideal body weight depending on the agent (lean body weight for aminoglycosides in obesity).", example: "Vancomycin 15 mg/kg in a 72 kg patient = 1080 mg, rounded to 1000 mg per institutional protocol." },

  // ── Regulation, Safety & Ethics ──────────────────────────────
  { term: "FDA Drug Approval Process", type: "concept", category: "regulation", meaning: "Phases: preclinical (animal studies, IND application) → Phase 1 (safety in healthy volunteers) → Phase 2 (efficacy in small patient group) → Phase 3 (large RCT) → NDA submission → FDA review → approval and post-marketing (Phase 4) surveillance.", example: "The new monoclonal antibody completed Phase 3 trials before NDA submission; post-marketing Phase 4 will monitor real-world safety." },
  { term: "Black Box Warning", type: "concept", category: "regulation", meaning: "The strongest FDA-mandated label warning, highlighting risks of serious or life-threatening adverse effects. Examples: SSRIs (suicidality in young patients), warfarin (bleeding), fluoroquinolones (tendon rupture, aortic dissection).", example: "The patient was counseled on the SSRI black box warning for increased suicidality in adults under 25, especially in the first weeks of treatment." },
  { term: "REMS (Risk Evaluation and Mitigation Strategy)", type: "concept", category: "regulation", meaning: "FDA-required program for drugs with significant risk; may include medication guides, enrollment, certification of prescribers/pharmacies, and laboratory monitoring. Examples: isotretinoin (iPLEDGE), clozapine, opioid REMS.", example: "Isotretinoin prescriptions required iPLEDGE REMS enrollment, with monthly negative pregnancy tests and pharmacist verification before dispensing." },
  { term: "Pregnancy Categories (Now PLLR)", type: "concept", category: "regulation", meaning: "The Pregnancy and Lactation Labeling Rule (PLLR, 2015) replaced A/B/C/D/X categories with narrative labels summarizing risk in pregnancy, lactation, and reproductive potential — more clinically useful.", example: "The new isotretinoin label under PLLR describes a high risk of fetal teratogenicity, replacing the former Category X classification." },
  { term: "HIPAA in the Pharmacy", type: "concept", category: "regulation", meaning: "Pharmacies are covered entities. PHI may be used for treatment, payment, and operations without specific authorization, but disclosures to third parties require patient consent. Counseling must occur in a private area.", example: "The pharmacist counseled the patient about a new medication in the private consultation area, protecting PHI per HIPAA standards." },
  { term: "OBRA-90 Patient Counseling", type: "concept", category: "regulation", meaning: "The Omnibus Budget Reconciliation Act of 1990 requires pharmacists to offer counseling on new prescriptions; topics include name and purpose, route, dose, duration, side effects, missed doses, and storage.", example: "Per OBRA-90, the pharmacist offered counseling on the patient's new amlodipine prescription, covering side effects, missed dose instructions, and food interactions." },
  { term: "Medication Errors and Safety", type: "concept", category: "regulation", meaning: "Categorized A–I by NCC MERP (A = no harm circumstance, I = error contributing to death). Common causes: look-alike sound-alike drugs, illegible handwriting, dose miscalculation, wrong route. Prevention: barcode scanning, tall man lettering, automated dispensing.", example: "Bar-code medication administration caught a near-miss: hydrALAZINE was scanned when hydrOXYzine was ordered — tall man lettering and BCMA prevented the error." },
  { term: "Drug Recalls (FDA Classes)", type: "concept", category: "regulation", meaning: "Class I (most serious, life-threatening — e.g., contaminated heparin), Class II (temporary or reversible harm), Class III (unlikely to cause adverse effect). The pharmacy quarantines recalled stock and notifies affected patients.", example: "After a Class II recall of a specific lisinopril lot, the pharmacy pulled remaining stock and contacted patients who had received that lot." },
  { term: "Pharmacy Technician Scope", type: "concept", category: "regulation", meaning: "Technicians may receive and process prescriptions, count and label medications, manage inventory, and bill insurance under pharmacist supervision. They may NOT counsel patients, verify prescriptions, transfer controlled prescriptions, or take phone orders for controlled substances.", example: "When the patient asked the technician for advice on which OTC medication to choose, the tech directed them to the pharmacist — counseling is outside the technician scope of practice." },
];'''

m = re.search(r'const TERMS = \[.*?^\];', html, re.DOTALL | re.MULTILINE)
if not m: raise SystemExit('TERMS not found')
html = html[:m.start()] + TERMS_JS + html[m.end():]

CAT = """const categoryLabel = c => ({
  'prescription':  'Prescription & Dispensing',
  'drug-classes':  'Drug Classes',
  'kinetics':      'Pharmacokinetics & Dynamics',
  'compounding':   'Compounding & Calculations',
  'regulation':    'Regulation, Safety & Ethics',
})[c] || c;"""
html = re.sub(r"const categoryLabel = c => \(\{[^}]+\}\)\[c\] \|\| c;", CAT, html, count=1, flags=re.DOTALL)

html = html.replace("const DB_PATH = 'dental-science';", "const DB_PATH = 'pharmacy-science';", 1)
html = html.replace('<title>HOSA Prep Hub — Dental Science</title>',
                    '<title>HOSA Prep Hub — Pharmacy Science</title>', 1)
html = html.replace('<h1>Dental<br><em>Science</em>.</h1>',
                    '<h1>Pharmacy<br><em>Science</em>.</h1>', 1)
html = html.replace(
    'A study companion for Dental anatomy, oral diseases, preventive dentistry, restorative procedures, dental materials, and infection control — built for HOSA competitors.',
    'A study companion for prescriptions and dispensing, drug classes, pharmacokinetics, compounding and calculations, and pharmacy regulation and safety — built for HOSA competitors.',
    1
)
html = html.replace('//  DATA — HOSA Emergency Medical Science',
                    '//  DATA — HOSA Pharmacy Science', 1)

with open(DST, 'w', encoding='utf-8') as f:
    f.write(html)

count = TERMS_JS.count('{ term:')
print(f'Wrote {DST} — {count} terms')
