# -*- coding: utf-8 -*-
"""Event content, batch A.

Definitions are one short sentence and carry no examples — the fuller
wording goes in `detail`, and `example` stays its own field.
"""

SPECS = []

# ═══════════════════════════════════════════════════════════════════
#  Parliamentary Procedure
# ═══════════════════════════════════════════════════════════════════
SPECS.append(dict(
    slug='parliamentary-procedure',
    name='Parliamentary Procedure',
    eyebrow='Leadership Event — Parliamentary Procedure',
    h1_lead='Order of Business &',
    h1_em='Parliamentary Procedure',
    subtitle='A study companion for motions, the order of precedence, voting, officers and minutes — '
             'built for HOSA competitors preparing for the Parliamentary Procedure competitive event.',
    test_blurb='parliamentary terms and rules from Robert’s Rules of Order',
    topics='Main and secondary motions, order of precedence, debate, voting methods, quorum, officers, minutes',
    tips=[
        'Learn the order of precedence cold. Most test questions are really asking "is this motion in order right now?"',
        'Know which motions are debatable, which are amendable, and which need a second. Those three flags decide most answers.',
        'Two-thirds votes exist to take away rights: closing debate, limiting debate, suspending the rules, objecting to consideration.',
        'A majority is more than half of those voting, not half the members present. Abstentions are not votes.',
        'Point of order, parliamentary inquiry, point of information and point of personal privilege get mixed up constantly. Learn the difference.',
        'Practice the script. Competition scores delivery of the chair’s exact wording as much as the rule itself.',
    ],
    categories=[
        ('motions',   'Motions'),
        ('precedence','Order of Precedence'),
        ('voting',    'Voting & Debate'),
        ('officers',  'Officers & Duties'),
        ('meetings',  'Meetings & Minutes'),
        ('terms',     'Core Terms'),
    ],
    terms=[
        # ── Motions ──────────────────────────────────────────────
        dict(term='Main Motion', category='motions',
             meaning='A motion that brings new business before the assembly.',
             detail='Lowest in precedence; only in order when no other motion is pending. Requires a second, is debatable and amendable, and passes by majority vote.',
             example='"I move that our chapter fund four State registrations from the bake-sale account."'),
        dict(term='Second', category='motions',
             meaning='A second member indicating the motion is worth the assembly’s time.',
             detail='Does not mean the seconder agrees — only that discussion should proceed. Without a second, most motions die immediately.',
             example='The chair asks "Is there a second?" and a member responds "Second."'),
        dict(term='Subsidiary Motion', category='motions',
             meaning='A motion that changes or disposes of the main motion while it is pending.',
             detail='Seven of them, ranked by precedence: postpone indefinitely, amend, commit, postpone definitely, limit debate, previous question, lay on the table.',
             example='Moving to amend a budget motion before voting on it is a subsidiary motion.'),
        dict(term='Privileged Motion', category='motions',
             meaning='An urgent motion unrelated to pending business that outranks everything else.',
             detail='In ascending order: call for orders of the day, raise a question of privilege, recess, adjourn, fix the time to which to adjourn.',
             example='Moving to adjourn interrupts debate on a main motion because it is privileged.'),
        dict(term='Incidental Motion', category='motions',
             meaning='A motion about procedure that must be settled before business continues.',
             detail='Has no fixed rank — it takes precedence over whatever question gave rise to it. Includes point of order, appeal, suspend the rules, division of the assembly.',
             example='A point of order about an improper amendment is decided before debate resumes.'),
        dict(term='Amend', category='motions',
             meaning='A motion to change the wording of a pending motion.',
             detail='Three methods: insert or add, strike out, or strike out and insert. Requires a second, is debatable if the motion it amends is, and needs a majority.',
             example='"I move to amend by striking out ‘four’ and inserting ‘six’."'),
        dict(term='Amendment of the Second Degree', category='motions',
             meaning='An amendment to a pending amendment.',
             detail='Only two degrees are allowed — you cannot amend an amendment to an amendment. The second-degree amendment is voted on first.',
             example='Amending a proposed dollar figure that was itself an amendment to the original motion.'),
        dict(term='Commit (Refer)', category='motions',
             meaning='A motion to send a question to a committee for study.',
             detail='Used when the assembly needs more information or private discussion. Should specify which committee, its size, and when it reports back.',
             example='"I move to refer the fundraiser proposal to the finance committee to report at our next meeting."'),
        dict(term='Postpone Definitely', category='motions',
             meaning='A motion to delay a question to a stated later time.',
             detail='Also called postpone to a certain time. Debatable, amendable as to the time, and requires a majority. The question returns automatically as unfinished business.',
             example='"I move to postpone the vote on dues until the October meeting."'),
        dict(term='Postpone Indefinitely', category='motions',
             meaning='A motion to kill a main motion without taking a direct vote on it.',
             detail='Lowest-ranking subsidiary motion. Debate on it can go into the merits of the main motion, which makes it useful for testing support.',
             example='A member unsure a proposal will fail moves to postpone indefinitely to avoid a recorded defeat.'),
        dict(term='Lay on the Table', category='motions',
             meaning='A motion to set a question aside temporarily for something urgent.',
             detail='Not debatable, not amendable, majority vote. Frequently misused to kill motions — that is what postpone indefinitely is for.',
             example='Tabling a report so the assembly can hear a guest speaker who must leave.'),
        dict(term='Take from the Table', category='motions',
             meaning='A motion to resume consideration of a question that was laid on the table.',
             detail='Not debatable, not amendable, majority vote. Must be done in the same session or the next one, or the motion dies.',
             example='After the speaker finishes, a member moves to take the report from the table.'),
        dict(term='Previous Question', category='motions',
             meaning='A motion to end debate immediately and vote.',
             detail='Not debatable, not amendable, requires a two-thirds vote because it cuts off members’ right to speak. Calling out "question!" is not a proper motion.',
             example='"I move the previous question" — if two-thirds agree, the assembly votes at once.'),
        dict(term='Limit or Extend Debate', category='motions',
             meaning='A motion to change how long members may speak on a question.',
             detail='Two-thirds vote, since it alters normal debate rights. Can cap total time, cap speeches, or extend beyond the usual limits.',
             example='"I move that debate be limited to ten minutes."'),
        dict(term='Reconsider', category='motions',
             meaning='A motion to bring a decided question back for another vote.',
             detail='Must be made by someone on the prevailing side, and on the same day or the next day of the session. Debatable if the motion it applies to was.',
             example='A member who voted yes learns new information and moves to reconsider.'),
        dict(term='Rescind', category='motions',
             meaning='A motion to cancel something the assembly adopted earlier.',
             detail='Requires a two-thirds vote, a majority of the entire membership, or a majority with previous notice. Cannot undo action already carried out.',
             example='Rescinding a previously approved purchase that has not yet been made.'),
        dict(term='Ratify', category='motions',
             meaning='A motion to approve, after the fact, an action already taken.',
             detail='Used when an officer acted without authority in an emergency. Only valid for actions the assembly could have authorized in advance.',
             example='Ratifying an emergency equipment purchase the treasurer made between meetings.'),
        dict(term='Withdraw a Motion', category='motions',
             meaning='A request by the mover to remove their motion from consideration.',
             detail='Before the chair states the question, the mover may withdraw freely. After that it belongs to the assembly and needs general consent or a majority.',
             example='"I request permission to withdraw my motion."'),
        dict(term='Division of the Question', category='motions',
             meaning='A motion to split a motion into parts voted on separately.',
             detail='Only in order when each part can stand alone as a complete proposition. Incidental, majority vote.',
             example='Splitting "buy uniforms and hire a bus" so members can approve one without the other.'),
        dict(term='Division of the Assembly', category='motions',
             meaning='A demand for a standing count when a voice vote sounded too close.',
             detail='A single member may demand it without a second and without a vote. It forces a rising vote but not a count unless ordered.',
             example='A member calls "Division!" after an uncertain voice vote.'),

        # ── Order of Precedence ──────────────────────────────────
        dict(term='Order of Precedence', category='precedence',
             meaning='The ranking that decides which motion may be made while another is pending.',
             detail='A motion is in order only if it ranks higher than the one on the floor. Privileged outrank subsidiary, which outrank the main motion.',
             example='Moving to recess is in order during debate on an amendment because recess ranks higher.'),
        dict(term='Pending Question', category='precedence',
             meaning='The motion currently before the assembly and awaiting a vote.',
             detail='The immediately pending question is the one most recently stated by the chair and the next to be voted on.',
             example='With a main motion and an amendment on the floor, the amendment is immediately pending.'),
        dict(term='Precedence of Privileged Motions', category='precedence',
             meaning='Fix the time to which to adjourn, adjourn, recess, question of privilege, orders of the day.',
             detail='Listed highest to lowest. Each may be moved while any lower-ranking motion is pending.',
             example='Adjourn outranks recess, so it may be moved while a recess motion is pending.'),
        dict(term='Precedence of Subsidiary Motions', category='precedence',
             meaning='Lay on the table, previous question, limit debate, postpone definitely, commit, amend, postpone indefinitely.',
             detail='Listed highest to lowest. Amend ranks only above postpone indefinitely, which is why amendments are usually disposed of first.',
             example='Previous question may be moved while an amendment is pending because it ranks higher.'),
        dict(term='Renewal of a Motion', category='precedence',
             meaning='Making a motion again after it was already disposed of.',
             detail='Generally a motion cannot be renewed during the same session unless something has changed the parliamentary situation.',
             example='A motion to adjourn may be renewed after business has progressed.'),

        # ── Voting & Debate ──────────────────────────────────────
        dict(term='Majority Vote', category='voting',
             meaning='More than half of the votes cast, ignoring abstentions and blanks.',
             detail='The default requirement for most motions. Not the same as a majority of members present or of the whole membership.',
             example='With 20 present and 14 voting, 8 yes votes carry the motion.'),
        dict(term='Two-Thirds Vote', category='voting',
             meaning='At least two-thirds of the votes cast, required when a motion takes away members’ rights.',
             detail='Needed for previous question, limiting debate, suspending the rules, objection to consideration, and rescinding without notice.',
             example='With 30 voting, 20 yes votes are needed to close debate.'),
        dict(term='Plurality Vote', category='voting',
             meaning='The largest number of votes when three or more choices split the field.',
             detail='Does not elect anyone unless the bylaws specifically authorize it, because a plurality can be far short of a majority.',
             example='In a three-way race, 40% can be a plurality without being a majority.'),
        dict(term='General Consent', category='voting',
             meaning='Adopting something without a formal vote when nobody objects.',
             detail='Also called unanimous consent. The chair asks if there is any objection; a single objection forces a regular vote. Saves time on routine matters.',
             example='"If there is no objection, the minutes will stand approved as read."'),
        dict(term='Voice Vote (Viva Voce)', category='voting',
             meaning='A vote taken by calling for ayes and noes aloud.',
             detail='The fastest method and the default for most questions. The chair judges the result by volume, subject to a demand for division.',
             example='"All those in favor say aye. Those opposed, no."'),
        dict(term='Rising Vote', category='voting',
             meaning='A vote taken by having members stand.',
             detail='Used for two-thirds votes, when a voice vote is inconclusive, or on demand for division. May be counted if the chair orders or the assembly votes to.',
             example='The chair calls for a rising vote to verify a close voice vote.'),
        dict(term='Ballot Vote', category='voting',
             meaning='A secret written vote.',
             detail='Protects members from pressure, so it is standard for elections and sensitive questions. Required whenever the bylaws say so.',
             example='Officer elections are held by ballot so members can vote freely.'),
        dict(term='Roll Call Vote', category='voting',
             meaning='A vote in which each member’s name is called and their vote recorded.',
             detail='Creates a public record of how each person voted, so it suits bodies accountable to constituents. Entered in full in the minutes.',
             example='A state board takes a roll call vote so the record shows each member’s position.'),
        dict(term='Debate', category='voting',
             meaning='Formal discussion of a pending motion after the chair has stated it.',
             detail='Members must be recognized before speaking, address the chair rather than each other, and confine remarks to the pending question.',
             example='"The chair recognizes the member from Brewer High School."'),
        dict(term='Ten-Minute Rule', category='voting',
             meaning='The default limit of ten minutes per speech in debate.',
             detail='A member may also speak twice on the same question per day, but not a second time until everyone wishing to speak once has done so.',
             example='A member who has spoken twice on a motion cannot be recognized again on it.'),
        dict(term='Germane', category='voting',
             meaning='Closely related to the question at hand.',
             detail='Amendments must be germane to the motion they modify, and debate must be germane to the pending question. The chair rules on it.',
             example='An amendment about parking is not germane to a motion about uniforms.'),
        dict(term='Tie Vote', category='voting',
             meaning='An equal split, which defeats the motion because it lacks a majority.',
             detail='A presiding officer who is a member may vote to create or break a tie, but normally votes only when it changes the outcome.',
             example='A 10-10 vote fails; the chair may then vote aye to carry it.'),

        # ── Officers & Duties ────────────────────────────────────
        dict(term='Presiding Officer (Chair)', category='officers',
             meaning='The officer who runs the meeting and rules on procedure.',
             detail='Recognizes speakers, states and puts questions, enforces order, and remains impartial. Refers to themselves as "the chair", not "I".',
             example='"The chair rules the amendment out of order as not germane."'),
        dict(term='President', category='officers',
             meaning='The chief officer of the organization, who normally presides.',
             detail='Also represents the organization externally and is usually an ex officio member of committees except the nominating committee.',
             example='The chapter president opens the meeting and calls it to order.'),
        dict(term='Vice President', category='officers',
             meaning='The officer who presides when the president is absent or steps down.',
             detail='Automatically succeeds to the presidency if that office becomes vacant, unless the bylaws say otherwise.',
             example='The vice president takes the chair when the president speaks in debate.'),
        dict(term='Secretary', category='officers',
             meaning='The officer who keeps the minutes and custody of the records.',
             detail='Also reads documents to the assembly, keeps the membership roll, and calls the meeting to order in the absence of both president and vice president.',
             example='The secretary reads the minutes of the previous meeting.'),
        dict(term='Treasurer', category='officers',
             meaning='The officer responsible for the organization’s funds and financial reports.',
             detail='Reports at meetings and submits books for audit. The treasurer’s report is filed, not adopted, unless it is an audited annual report.',
             example='"The treasurer’s report shows a balance of $842.16 and will be filed for audit."'),
        dict(term='Parliamentarian', category='officers',
             meaning='An adviser who counsels the chair on procedure.',
             detail='Advises only — the chair makes every ruling. A member serving as parliamentarian traditionally does not vote except by ballot.',
             example='The chair pauses to consult the parliamentarian on whether a motion is in order.'),
        dict(term='Ex Officio', category='officers',
             meaning='Membership held by virtue of holding another office.',
             detail='Carries the same rights as any other member, including the right to vote, unless the bylaws limit it. Not counted in quorum if not under the organization’s authority.',
             example='The president serves ex officio on the fundraising committee.'),
        dict(term='Sergeant-at-Arms', category='officers',
             meaning='The officer who maintains order and manages the meeting room.',
             detail='Seats members and guests, distributes materials, and assists the chair in preserving decorum.',
             example='The sergeant-at-arms verifies that only voting members are seated in the delegate section.'),

        # ── Meetings & Minutes ───────────────────────────────────
        dict(term='Quorum', category='meetings',
             meaning='The minimum number of members who must be present to transact business.',
             detail='Set by the bylaws; without one, the only valid actions are to fix a time to meet again, adjourn, recess, or take measures to obtain a quorum.',
             example='A chapter with a quorum of 15 cannot vote on dues with 12 members present.'),
        dict(term='Order of Business', category='meetings',
             meaning='The standard sequence a meeting follows.',
             detail='Call to order, reading and approval of minutes, reports of officers, reports of committees, special orders, unfinished business, new business, announcements, adjournment.',
             example='Committee reports come before new business in the standard order.'),
        dict(term='Call to Order', category='meetings',
             meaning='The chair’s declaration that the meeting has formally begun.',
             detail='Requires a quorum. Business conducted before the call to order has no standing.',
             example='"The regular meeting of the chapter will come to order."'),
        dict(term='Minutes', category='meetings',
             meaning='The official written record of what a body did at a meeting.',
             detail='Record actions, not discussion: motions, movers, and results. Opinions, debate and the secretary’s commentary do not belong in them.',
             example='The minutes note that the motion carried, not who argued against it.'),
        dict(term='Approval of Minutes', category='meetings',
             meaning='Accepting the previous meeting’s record, usually by general consent.',
             detail='Corrections are handled as they arise. Once approved, the minutes can only be changed by a motion to amend something previously adopted.',
             example='"Are there any corrections to the minutes? Hearing none, the minutes are approved."'),
        dict(term='Unfinished Business', category='meetings',
             meaning='Questions carried over because the previous meeting adjourned before disposing of them.',
             detail='Often miscalled "old business". The chair introduces these items automatically; no motion is needed to bring them up.',
             example='A motion postponed to this meeting comes up under unfinished business.'),
        dict(term='New Business', category='meetings',
             meaning='The portion of the meeting where members introduce new main motions.',
             detail='The chair asks whether there is any new business; members must be recognized before making a motion.',
             example='"Is there any new business?" — a member rises and is recognized.'),
        dict(term='Agenda', category='meetings',
             meaning='The planned sequence of items for a specific meeting.',
             detail='Once adopted by the assembly it becomes binding, and changing it requires a two-thirds vote to suspend the rules.',
             example='The chapter adopts the agenda at the start of its annual business meeting.'),
        dict(term='Adjourn', category='meetings',
             meaning='A motion to close the meeting.',
             detail='Privileged and generally not debatable when another meeting is already scheduled. Business not finished carries over as unfinished business.',
             example='"I move to adjourn." — "Second." — the chair puts the question at once.'),
        dict(term='Recess', category='meetings',
             meaning='A motion for a short intermission after which the meeting resumes.',
             detail='Privileged when made while business is pending; amendable as to length. The meeting resumes exactly where it left off.',
             example='"I move that we recess for ten minutes."'),
        dict(term='Session vs Meeting', category='meetings',
             meaning='A meeting is a single gathering; a session is a series of connected meetings on one agenda.',
             detail='The distinction matters because motions like reconsider and take from the table are limited to the same session.',
             example='A three-day conference is one session made up of many meetings.'),

        # ── Core Terms ───────────────────────────────────────────
        dict(term='Robert’s Rules of Order', category='terms',
             meaning='The parliamentary authority most U.S. organizations adopt.',
             detail='First published by Henry M. Robert in 1876. Newly Revised (RONR) is the current edition and the standard for HOSA competition.',
             example='The chapter bylaws name RONR as its parliamentary authority.'),
        dict(term='Bylaws', category='terms',
             meaning='The governing rules that define an organization’s structure and procedures.',
             detail='Outrank the parliamentary authority and cannot be suspended unless they themselves allow it. Amending them usually needs notice and a two-thirds vote.',
             example='The bylaws set the quorum, so the assembly cannot lower it by majority vote.'),
        dict(term='Standing Rule', category='terms',
             meaning='A rule about administrative detail rather than parliamentary procedure.',
             detail='Adopted by majority vote and suspendable by majority for the duration of a session.',
             example='A standing rule that meetings begin at 3:30 can be suspended for one meeting.'),
        dict(term='Point of Order', category='terms',
             meaning='A member’s claim that the rules are being violated.',
             detail='Requires no second and interrupts a speaker. Must be raised promptly, at the time of the breach. The chair rules on it.',
             example='"Point of order — the amendment is not germane to the motion."'),
        dict(term='Appeal', category='terms',
             meaning='A motion challenging the chair’s ruling and sending it to the assembly.',
             detail='Needs a second, is usually debatable, and a majority or tie sustains the chair’s decision.',
             example='"I appeal from the decision of the chair."'),
        dict(term='Parliamentary Inquiry', category='terms',
             meaning='A question to the chair about procedure.',
             detail='Asks what is in order or how to accomplish something, not about facts. The chair answers as an opinion, not a binding ruling.',
             example='"Parliamentary inquiry — would a motion to refer be in order now?"'),
        dict(term='Point of Information', category='terms',
             meaning='A request for facts relevant to the pending business.',
             detail='Directed through the chair, never member to member. Called "request for information" in the current edition to avoid confusion.',
             example='"Point of information — what is the current balance in that account?"'),
        dict(term='Question of Privilege', category='terms',
             meaning='A request concerning the comfort, safety or rights of the assembly or a member.',
             detail='Privileged, so it may interrupt business. Covers noise, temperature, an inaudible speaker, or a personal accusation.',
             example='"Question of privilege — we cannot hear the speaker at the back of the room."'),
        dict(term='Suspend the Rules', category='terms',
             meaning='A motion to set aside a rule temporarily to do something otherwise not allowed.',
             detail='Two-thirds vote. Bylaws and fundamental principles of parliamentary law cannot be suspended.',
             example='"I move to suspend the rules and take up the scholarship motion out of order."'),
        dict(term='Obtaining the Floor', category='terms',
             meaning='Being recognized by the chair before speaking or making a motion.',
             detail='A member rises, addresses the chair, and waits for recognition. The member who made the motion has first claim in debate.',
             example='A member stands and says "Mr. President" before being recognized.'),
        dict(term='Putting the Question', category='terms',
             meaning='The chair’s act of taking the vote on a pending motion.',
             detail='The chair restates the motion, calls for the affirmative, then the negative, then announces the result and the effect.',
             example='"The ayes have it and the motion is adopted. We will fund four registrations."'),
        dict(term='Out of Order', category='terms',
             meaning='Not permissible at this moment under the rules.',
             detail='A motion can be out of order because of precedence, because it is not germane, or because the member has not been recognized.',
             example='A main motion made while an amendment is pending is out of order.'),
    ],
))


# ═══════════════════════════════════════════════════════════════════
#  CPR & First Aid
# ═══════════════════════════════════════════════════════════════════
SPECS.append(dict(
    slug='cpr-first-aid',
    name='CPR & First Aid',
    eyebrow='Emergency Preparedness Event — CPR & First Aid',
    h1_lead='Basic Life Support &',
    h1_em='First Aid',
    subtitle='A study companion for the chain of survival, adult and pediatric CPR, AED use, choking, '
             'bleeding control and medical emergencies — built for HOSA competitors preparing for the '
             'CPR and First Aid competitive event.',
    test_blurb='CPR, AED and first-aid concepts',
    topics='Chain of survival, compressions and ventilation, AED, choking, bleeding control, shock, burns, medical emergencies',
    tips=[
        'Memorize the numbers: 100–120 compressions a minute, at least 2 inches deep for adults, 30:2 with one rescuer.',
        'Compression depth and full recoil matter more than anything else. Leaning on the chest between compressions is the most common scored error.',
        'Know the pediatric differences cold: depth is one third of chest diameter, and two rescuers switch to 15:2.',
        'The AED goes on as soon as it arrives. Do not delay a shock to finish a cycle.',
        'For bleeding, direct pressure first, then a tourniquet high and tight if it will not stop. Tourniquets are no longer a last resort.',
        'Stroke and heart attack questions hinge on recognition, not treatment. Learn FAST and the atypical presentations in women and people with diabetes.',
    ],
    categories=[
        ('chain',    'Chain of Survival'),
        ('cpr',      'CPR Technique'),
        ('aed',      'AED & Defibrillation'),
        ('airway',   'Airway & Choking'),
        ('bleeding', 'Bleeding & Trauma'),
        ('medical',  'Medical Emergencies'),
        ('env',      'Environmental & Burns'),
    ],
    terms=[
        # ── Chain of Survival ────────────────────────────────────
        dict(term='Chain of Survival', category='chain',
             meaning='The sequence of actions that gives a cardiac arrest victim the best chance of living.',
             detail='Out-of-hospital links: recognition and activation, early CPR, rapid defibrillation, advanced resuscitation, post-arrest care, recovery.',
             example='A bystander who calls 911 and starts compressions has completed the first two links.'),
        dict(term='Sudden Cardiac Arrest', category='chain',
             meaning='An abrupt loss of heart function with no pulse and no normal breathing.',
             detail='Usually caused by ventricular fibrillation. Distinct from a heart attack, which is a blocked artery and where the victim is typically awake.',
             example='A collapsed player who is unresponsive and not breathing normally is in cardiac arrest.'),
        dict(term='Agonal Breathing', category='chain',
             meaning='Irregular gasping in the first minutes of cardiac arrest, which is not effective breathing.',
             detail='Mistaking it for normal breathing is a leading reason bystanders fail to start CPR. Treat gasping as no breathing.',
             example='A victim taking occasional noisy gasps still needs immediate compressions.'),
        dict(term='Activating EMS', category='chain',
             meaning='Calling 911 and sending for an AED as the first action for an unresponsive adult.',
             detail='Alone with a phone, put it on speaker and stay with the victim. For a child with a likely respiratory cause and no phone, give two minutes of CPR first.',
             example='"You in the red shirt — call 911 and bring the AED from the front office."'),
        dict(term='Bystander CPR', category='chain',
             meaning='Resuscitation started by a lay rescuer before EMS arrives.',
             detail='Roughly doubles or triples survival. Survival falls about 7 to 10 percent for every minute without it.',
             example='A coach starting compressions within seconds buys minutes of viability.'),
        dict(term='Hands-Only CPR', category='chain',
             meaning='Continuous chest compressions with no rescue breaths, for untrained bystanders.',
             detail='Recommended for adult victims of witnessed sudden collapse. Compressions alone are far better than hesitating over mouth-to-mouth.',
             example='An untrained bystander pushes hard and fast in the center of the chest until EMS arrives.'),
        dict(term='Good Samaritan Law', category='chain',
             meaning='Legal protection for someone giving reasonable emergency aid in good faith.',
             detail='Covers volunteers acting within their training and without gross negligence or expectation of payment. Details vary by state.',
             example='A student who performs CPR correctly on a stranger is protected from ordinary liability.'),
        dict(term='Implied Consent', category='chain',
             meaning='The legal presumption that an unresponsive person would want life-saving care.',
             detail='A responsive adult must give express consent; you must ask permission and identify yourself. Refusal must be honored.',
             example='You may treat an unconscious victim without asking, because consent is implied.'),
        dict(term='Scene Safety', category='chain',
             meaning='Confirming the area is safe before approaching a victim.',
             detail='Always the first step. A rescuer who becomes a second victim helps nobody. Check traffic, fire, electricity, water and violence.',
             example='Before helping at a crash, check for oncoming traffic and leaking fuel.'),

        # ── CPR Technique ────────────────────────────────────────
        dict(term='Compression Rate', category='cpr',
             meaning='100 to 120 chest compressions per minute.',
             detail='Faster than 120 reduces filling time and lowers output; slower than 100 reduces perfusion. Both harm survival.',
             example='Compressing to the beat of "Stayin’ Alive" keeps the rate in range.'),
        dict(term='Compression Depth (Adult)', category='cpr',
             meaning='At least 2 inches, and no more than about 2.4 inches.',
             detail='Too shallow fails to generate blood flow; excessive depth risks injury. Depth is the most commonly missed quality measure.',
             example='A rescuer pushing only an inch deep is not perfusing the brain.'),
        dict(term='Chest Recoil', category='cpr',
             meaning='Letting the chest return fully to its normal position between compressions.',
             detail='Incomplete recoil raises pressure inside the chest and cuts venous return, so the heart refills less. Leaning on the chest is the usual cause.',
             example='The rescuer lifts their weight completely between pushes without losing hand position.'),
        dict(term='Compression-to-Ventilation Ratio', category='cpr',
             meaning='30 compressions to 2 breaths for a single rescuer at any age.',
             detail='Two rescuers use 15:2 for infants and children. With an advanced airway, compressions are continuous with a breath every 6 seconds.',
             example='A lone rescuer on a child still uses 30:2.'),
        dict(term='Hand Position (Adult)', category='cpr',
             meaning='The heel of one hand on the lower half of the sternum, the other hand on top.',
             detail='Fingers interlaced and lifted off the ribs, arms straight, shoulders directly over the hands so the push comes from the hips.',
             example='The rescuer locks their elbows and uses body weight rather than arm strength.'),
        dict(term='Pediatric CPR Depth', category='cpr',
             meaning='About one third of the depth of the chest — roughly 2 inches in a child, 1.5 inches in an infant.',
             detail='Children may be compressed with one or two hands depending on size. Infants get two fingers, or two thumbs encircling the chest with two rescuers.',
             example='On an infant, two thumbs on the sternum just below the nipple line.'),
        dict(term='Chest Compression Fraction', category='cpr',
             meaning='The share of resuscitation time actually spent compressing the chest.',
             detail='Target is at least 60 percent, ideally above 80. Every pause drops coronary perfusion pressure, which takes several compressions to rebuild.',
             example='Charging the AED while compressions continue preserves the fraction.'),
        dict(term='Rescuer Switch', category='cpr',
             meaning='Changing compressors about every 2 minutes, in under 10 seconds.',
             detail='Quality falls measurably after a minute or two even though rescuers do not feel tired. Switch during rhythm analysis to avoid a pause.',
             example='Two rescuers swap roles each time the AED analyzes.'),
        dict(term='Rescue Breath', category='cpr',
             meaning='A breath given over about one second, just enough to make the chest rise.',
             detail='Over-ventilating forces air into the stomach and raises chest pressure, reducing blood return to the heart.',
             example='The rescuer watches for chest rise rather than blowing as hard as possible.'),
        dict(term='Head-Tilt Chin-Lift', category='cpr',
             meaning='The standard maneuver to open the airway of a victim with no suspected spinal injury.',
             detail='One hand on the forehead tilts the head back; the fingers of the other lift the bony part of the chin. Lifts the tongue off the back of the throat.',
             example='Before giving breaths, the rescuer tilts the head and lifts the chin.'),
        dict(term='Jaw-Thrust Maneuver', category='cpr',
             meaning='Opening the airway without moving the neck, for suspected spinal injury.',
             detail='Fingers behind the angles of the jaw push it forward. If it fails to open the airway, use head-tilt chin-lift — the airway takes priority.',
             example='A diver pulled from shallow water gets a jaw thrust rather than a head tilt.'),
        dict(term='Recovery Position', category='cpr',
             meaning='Rolling a breathing, unresponsive victim onto their side to protect the airway.',
             detail='Lets fluid drain and keeps the tongue forward. Not used if trauma is suspected or if CPR may be needed.',
             example='An unresponsive but normally breathing overdose victim is placed on their side.'),
        dict(term='Pulse Check', category='cpr',
             meaning='A check of no more than 10 seconds before starting compressions.',
             detail='Carotid in adults and children, brachial in infants. Lay rescuers skip it entirely — uncertainty means start CPR.',
             example='Unsure whether there is a pulse after 10 seconds, the rescuer begins compressions.'),

        # ── AED ──────────────────────────────────────────────────
        dict(term='Automated External Defibrillator', category='aed',
             meaning='A device that analyzes heart rhythm and delivers a shock when one is needed.',
             detail='Will only shock ventricular fibrillation and pulseless ventricular tachycardia. It cannot shock a heart that has stopped entirely.',
             example='The AED announces "shock advised" and the rescuer clears the victim.'),
        dict(term='Ventricular Fibrillation', category='aed',
             meaning='Chaotic electrical activity in which the heart quivers and pumps no blood.',
             detail='The most common initial rhythm in witnessed adult cardiac arrest, and the one defibrillation is designed to correct.',
             example='An AED shocks a collapsed runner in ventricular fibrillation back into a rhythm.'),
        dict(term='Asystole', category='aed',
             meaning='A complete absence of electrical activity in the heart.',
             detail='Not shockable. The AED will advise no shock and prompt continued CPR, which is the only treatment available to a lay rescuer.',
             example='The AED says "no shock advised" and the rescuer resumes compressions immediately.'),
        dict(term='Pad Placement (Adult)', category='aed',
             meaning='One pad below the right collarbone, the other on the left side below the armpit.',
             detail='This anterolateral position runs current through the heart. Pads must not touch each other or overlap.',
             example='The rescuer bares the chest and places pads per the diagram on the packaging.'),
        dict(term='Pediatric AED Pads', category='aed',
             meaning='Attenuated pads that reduce the shock energy, used for children under eight or under 25 kg.',
             detail='If none are available, adult pads are used rather than withholding the shock — front and back if they would otherwise touch.',
             example='On a small child the rescuer places one pad on the chest and one on the back.'),
        dict(term='Clearing the Victim', category='aed',
             meaning='Ensuring nobody is touching the victim before a shock is delivered.',
             detail='The rescuer looks head to toe and states it aloud. Contact risks injuring a rescuer and distorts analysis.',
             example='"I’m clear, you’re clear, everybody clear" before pressing the shock button.'),
        dict(term='AED Special Situations', category='aed',
             meaning='Water, medication patches, implanted devices and chest hair each change how pads are applied.',
             detail='Move the victim off standing water and dry the chest, remove patches with a gloved hand, place pads an inch from an implant, and shave dense hair.',
             example='A victim pulled from a pool is dragged clear and the chest wiped before pads go on.'),
        dict(term='Time to Defibrillation', category='aed',
             meaning='The strongest predictor of survival in shockable cardiac arrest.',
             detail='Survival drops roughly 7 to 10 percent per minute without defibrillation. Effective CPR slows that decline.',
             example='A school with an AED in the gym can shock within two minutes of collapse.'),

        # ── Airway & Choking ─────────────────────────────────────
        dict(term='Foreign Body Airway Obstruction', category='airway',
             meaning='Blockage of the airway by an object, usually food.',
             detail='Mild obstruction lets the victim cough forcefully — encourage coughing. Severe means no air movement and demands immediate action.',
             example='A diner who cannot speak or cough clutches their throat.'),
        dict(term='Universal Choking Sign', category='airway',
             meaning='Hands clutched to the throat, signaling a blocked airway.',
             detail='Confirm by asking "Are you choking?" A victim who cannot speak, cough or breathe needs abdominal thrusts at once.',
             example='The rescuer asks, gets a nod, and begins thrusts.'),
        dict(term='Abdominal Thrusts', category='airway',
             meaning='Inward and upward thrusts above the navel to expel an airway obstruction.',
             detail='Also called the Heimlich maneuver. Continue until the object clears or the victim becomes unresponsive, at which point start CPR.',
             example='The rescuer stands behind the victim, fist above the navel, and pulls sharply inward and up.'),
        dict(term='Chest Thrusts', category='airway',
             meaning='Thrusts on the sternum, used instead of abdominal thrusts for pregnant or obese victims.',
             detail='Hand position matches CPR compressions. Used whenever the rescuer cannot get their arms around the abdomen.',
             example='A visibly pregnant choking victim receives chest thrusts.'),
        dict(term='Infant Choking Relief', category='airway',
             meaning='Five back blows followed by five chest thrusts, repeated.',
             detail='The infant is held face down along the forearm with the head lower than the body. Abdominal thrusts are never used on infants.',
             example='Five slaps between the shoulder blades, then five two-finger chest thrusts.'),
        dict(term='Unresponsive Choking Victim', category='airway',
             meaning='A choking victim who collapses and needs CPR started immediately.',
             detail='Each time the airway is opened for breaths, look in the mouth and remove an object only if you can see it. Never sweep blindly.',
             example='The rescuer lowers the victim to the floor and begins compressions.'),
        dict(term='Barrier Device', category='airway',
             meaning='A mask or face shield placed between rescuer and victim for rescue breaths.',
             detail='Reduces infection risk. A pocket mask with a one-way valve is more effective than a flat shield.',
             example='A responder uses a pocket mask to ventilate a stranger.'),

        # ── Bleeding & Trauma ────────────────────────────────────
        dict(term='Direct Pressure', category='bleeding',
             meaning='Firm, continuous pressure on a wound, and the first treatment for any external bleeding.',
             detail='Applied with a gloved hand over a clean dressing. Add dressings on top rather than lifting to check.',
             example='The rescuer presses hard on a bleeding forearm and does not release.'),
        dict(term='Tourniquet', category='bleeding',
             meaning='A constricting band placed on a limb to stop life-threatening bleeding.',
             detail='Applied 2 to 3 inches above the wound, never over a joint, tightened until bleeding stops. Note the time and never loosen it.',
             example='A deep thigh laceration spurting blood gets a tourniquet high and tight.'),
        dict(term='Hemostatic Dressing', category='bleeding',
             meaning='Gauze treated with a clotting agent, packed into wounds a tourniquet cannot reach.',
             detail='Used for junctional bleeding at the neck, armpit or groin. Packed firmly into the wound with three minutes of pressure.',
             example='A responder packs a groin wound with hemostatic gauze.'),
        dict(term='Shock (Hypoperfusion)', category='bleeding',
             meaning='Inadequate blood flow to the tissues, which is life-threatening.',
             detail='Signs are pale cool clammy skin, rapid weak pulse, rapid breathing, thirst, anxiety and altered mental status.',
             example='A trauma victim turning pale with a racing pulse is going into shock.'),
        dict(term='Treating Shock', category='bleeding',
             meaning='Lay the victim flat, control bleeding, keep them warm and call EMS.',
             detail='Nothing by mouth. Routine leg elevation is no longer recommended; do not move a victim with suspected spinal injury.',
             example='The rescuer covers the victim with a blanket and monitors breathing until EMS arrives.'),
        dict(term='Impaled Object', category='bleeding',
             meaning='An object embedded in the body, which is stabilized in place rather than removed.',
             detail='Removing it can release tamponade and cause severe bleeding. Bulky dressings are built around it to prevent movement.',
             example='A shard of glass in the abdomen is padded and secured, not pulled out.'),
        dict(term='Amputation Care', category='bleeding',
             meaning='Control the bleeding first, then preserve the severed part cool and dry.',
             detail='Wrap the part in sterile gauze, seal it in a bag, and place that on ice. Never let it touch ice directly or soak in water.',
             example='A severed fingertip is bagged and placed on ice for transport with the patient.'),
        dict(term='Spinal Motion Restriction', category='bleeding',
             meaning='Keeping the head and neck still when spinal injury is suspected.',
             detail='Indicated after falls, diving injuries, vehicle crashes, or any head trauma with altered consciousness or neck pain.',
             example='A rescuer holds a fallen gymnast’s head steady until EMS arrives.'),
        dict(term='RICE', category='bleeding',
             meaning='Rest, ice, compression and elevation for a closed soft-tissue injury.',
             detail='Ice for 20 minutes at a time with a barrier against the skin. Used for sprains, strains and bruises, not open wounds.',
             example='An ankle sprain is wrapped, iced and elevated on the sideline.'),
        dict(term='Splinting', category='bleeding',
             meaning='Immobilizing a suspected fracture, including the joints above and below.',
             detail='Check circulation, sensation and movement before and after. Splint in the position found if there is any resistance.',
             example='A forearm fracture is splinted from above the elbow to below the wrist.'),

        # ── Medical Emergencies ──────────────────────────────────
        dict(term='Heart Attack (Myocardial Infarction)', category='medical',
             meaning='A blocked coronary artery starving heart muscle of blood.',
             detail='Chest pressure, pain radiating to arm or jaw, shortness of breath, nausea, sweating. Women, older adults and people with diabetes often present atypically.',
             example='A man with crushing chest pressure and a sweaty pallor is having a heart attack.'),
        dict(term='Aspirin for Chest Pain', category='medical',
             meaning='Chewing 162 to 325 mg of aspirin during a suspected heart attack.',
             detail='Slows clot growth. Given only to a responsive adult with no aspirin allergy and no bleeding disorder, after calling 911.',
             example='The rescuer has the victim chew two baby aspirin while waiting for the ambulance.'),
        dict(term='Stroke', category='medical',
             meaning='Interrupted blood flow to part of the brain, from a clot or a bleed.',
             detail='Treatment is extremely time-dependent, so the time the victim was last known well matters as much as the symptoms.',
             example='A woman whose face droops mid-sentence is having a stroke.'),
        dict(term='FAST', category='medical',
             meaning='Face drooping, Arm weakness, Speech difficulty, Time to call 911.',
             detail='The standard stroke screen. BE-FAST adds Balance and Eyes for posterior strokes that FAST misses.',
             example='A bystander notices one-sided arm drift and calls 911 immediately.'),
        dict(term='Anaphylaxis', category='medical',
             meaning='A rapid, life-threatening allergic reaction affecting breathing and circulation.',
             detail='Hives, swelling of lips and tongue, wheeze, throat tightness, and falling blood pressure. Can develop within minutes of exposure.',
             example='A student stung by a bee develops facial swelling and cannot breathe.'),
        dict(term='Epinephrine Auto-Injector', category='medical',
             meaning='A device delivering a fixed dose of epinephrine into the outer thigh.',
             detail='Given through clothing if needed, held in place per the manufacturer’s instructions. Always call 911 — symptoms can return as it wears off.',
             example='The rescuer presses the auto-injector firmly into the mid-outer thigh.'),
        dict(term='Asthma Attack', category='medical',
             meaning='Narrowed airways causing wheeze, cough and difficulty breathing.',
             detail='Help the victim use their own inhaler, sitting upright and leaning forward. Inability to speak a full sentence signals a severe attack.',
             example='A player sits forward on the bench and uses a rescue inhaler.'),
        dict(term='Hypoglycemia', category='medical',
             meaning='Low blood sugar causing shakiness, confusion, sweating and irritability.',
             detail='A responsive victim who can swallow gets 15 to 20 grams of fast sugar. Unresponsive means nothing by mouth and a 911 call.',
             example='A diabetic student who becomes confused is given juice or glucose tablets.'),
        dict(term='Seizure Care', category='medical',
             meaning='Protect the head, clear the area, time it, and never restrain or put anything in the mouth.',
             detail='Afterward, place them on their side. Call 911 if it lasts over five minutes, repeats, or the person is pregnant, injured or does not wake.',
             example='The rescuer slides a jacket under the person’s head and moves a chair away.'),
        dict(term='Fainting (Syncope)', category='medical',
             meaning='A brief loss of consciousness from a temporary drop in blood flow to the brain.',
             detail='Lay the victim flat and check breathing. Any faint that does not resolve quickly should be treated as cardiac arrest until proven otherwise.',
             example='A student who faints during a blood draw is laid down and recovers in seconds.'),
        dict(term='Poisoning', category='medical',
             meaning='Harm from a swallowed, inhaled, injected or absorbed substance.',
             detail='Call Poison Control at 1-800-222-1222. Do not induce vomiting, and bring the container to the hospital.',
             example='A parent calls Poison Control after a toddler swallows cleaning fluid.'),
        dict(term='Opioid Overdose', category='medical',
             meaning='Depressed breathing and unresponsiveness from opioid use, reversible with naloxone.',
             detail='Pinpoint pupils and slow or absent breathing. Give naloxone, call 911, and start rescue breathing or CPR as needed.',
             example='A bystander administers intranasal naloxone and begins rescue breaths.'),

        # ── Environmental & Burns ────────────────────────────────
        dict(term='Superficial Burn', category='env',
             meaning='A burn involving only the epidermis, red and painful with no blisters.',
             detail='Formerly called first degree. Cool with running water for 10 to 20 minutes and cover loosely. Heals in about a week without scarring.',
             example='A mild sunburn is a superficial burn.'),
        dict(term='Partial-Thickness Burn', category='env',
             meaning='A burn through the epidermis into the dermis, with blisters and severe pain.',
             detail='Formerly second degree. Do not break blisters. Cool with water, cover with a non-stick dressing, and seek care if large or on the face, hands, feet or genitals.',
             example='A scald from boiling water that raises blisters.'),
        dict(term='Full-Thickness Burn', category='env',
             meaning='A burn destroying all skin layers, appearing white, leathery or charred.',
             detail='Formerly third degree. Often painless at the center because nerve endings are destroyed. Always an emergency; cover with a dry sterile dressing.',
             example='A flame burn with a dry white center and painful edges.'),
        dict(term='Rule of Nines', category='env',
             meaning='A method of estimating burned body surface area in multiples of nine percent.',
             detail='Adult: head 9, each arm 9, each leg 18, front torso 18, back torso 18, genitals 1. Proportions differ in children, whose heads are larger.',
             example='A burn covering one whole arm and the chest is about 27 percent.'),
        dict(term='Heat Exhaustion', category='env',
             meaning='Heavy sweating, weakness, nausea and cool clammy skin from heat and fluid loss.',
             detail='Move to a cool place, loosen clothing, give cool fluids if alert. Untreated it can progress to heat stroke.',
             example='A player who feels dizzy and nauseated at halftime is moved into the shade.'),
        dict(term='Heat Stroke', category='env',
             meaning='A core temperature above about 104°F with altered mental status — a true emergency.',
             detail='Skin may be hot and dry or still sweaty. Call 911 and begin aggressive cooling; cold-water immersion is the fastest method.',
             example='A confused runner who stops sweating is placed in an ice bath while EMS is called.'),
        dict(term='Hypothermia', category='env',
             meaning='A core temperature below 95°F, causing shivering that gives way to confusion.',
             detail='Remove wet clothing, insulate, and warm the trunk first. Handle gently — rough movement can trigger a fatal arrhythmia.',
             example='A hiker found shivering and slurring words is wrapped in dry blankets.'),
        dict(term='Frostbite', category='env',
             meaning='Freezing of skin and deeper tissue, most often on fingers, toes, ears and nose.',
             detail='Rewarm in water around 100 to 104°F only if refreezing will not happen. Never rub the area or use dry heat.',
             example='Frozen fingers are placed in warm, not hot, water.'),
        dict(term='Anatomical Splinting for Sprains', category='env',
             meaning='Securing an injured limb to the body or an adjacent limb for support.',
             detail='Useful when no rigid splint is available. Check circulation before and after securing.',
             example='An injured finger is buddy-taped to the one beside it.'),
    ],
))
