# -*- coding: utf-8 -*-
"""Event content, batch D."""

SPECS = []

# ═══════════════════════════════════════════════════════════════════
#  Addiction Medicine
# ═══════════════════════════════════════════════════════════════════
SPECS.append(dict(
    slug='addiction-medicine',
    name='Addiction Medicine',
    eyebrow='Health Science — Addiction Medicine',
    h1_lead='Substance Use &',
    h1_em='Addiction Medicine',
    subtitle='A study companion for the neurobiology of addiction, substance classes, withdrawal, '
             'screening, treatment and harm reduction — built for HOSA competitors and students '
             'entering behavioral health careers.',
    test_blurb='addiction, withdrawal and treatment concepts',
    topics='Reward pathway, substance classes, intoxication and withdrawal, screening tools, treatment, harm reduction',
    tips=[
        'Alcohol and benzodiazepine withdrawal can kill. Opioid withdrawal is miserable but rarely fatal. That distinction is heavily tested.',
        'Know the DSM-5 framing: one substance use disorder graded mild, moderate or severe by how many of 11 criteria are met.',
        'Tolerance, dependence and addiction are three different things. Physical dependence alone is not addiction.',
        'Learn the medications for opioid use disorder — methadone, buprenorphine, naltrexone — and how each one works.',
        'CAGE, AUDIT and CRAFFT each screen a different population. CRAFFT is the adolescent tool.',
        'Harm reduction questions test whether you understand that reducing death comes before requiring abstinence.',
    ],
    categories=[
        ('neuro',     'Neurobiology'),
        ('substances','Substance Classes'),
        ('withdrawal','Intoxication & Withdrawal'),
        ('screening', 'Screening & Diagnosis'),
        ('treatment', 'Treatment'),
        ('harm',      'Harm Reduction & Policy'),
    ],
    terms=[
        # ── Neurobiology ─────────────────────────────────────────
        dict(term='Mesolimbic Reward Pathway', category='neuro',
             meaning='The dopamine circuit from the ventral tegmental area to the nucleus accumbens.',
             detail='Normally reinforces survival behaviors. Nearly every addictive drug raises dopamine here, directly or indirectly.',
             example='Stimulants flood the nucleus accumbens with dopamine.'),
        dict(term='Dopamine', category='neuro',
             meaning='The neurotransmitter central to reward, motivation and reinforcement learning.',
             detail='Signals that something was better than expected. Drugs produce a surge no natural reward matches, which reshapes what feels worth pursuing.',
             example='A dopamine surge marks the drug as more important than food or company.'),
        dict(term='Tolerance', category='neuro',
             meaning='Needing more of a substance to get the same effect.',
             detail='From receptor downregulation and faster metabolism. Develops at different rates for different effects, which is why overdose risk rises.',
             example='A patient needs a steadily higher dose for the same relief.'),
        dict(term='Physical Dependence', category='neuro',
             meaning='Physiological adaptation such that stopping causes withdrawal.',
             detail='Not the same as addiction. Patients on long-term opioids or beta blockers can be dependent without any addiction.',
             example='A pain patient has withdrawal on abrupt discontinuation but no drug-seeking.'),
        dict(term='Addiction', category='neuro',
             meaning='Compulsive use that continues despite harm, with loss of control over use.',
             detail='A chronic, relapsing brain disorder. Defined by behavior and consequences, not by dose or dependence.',
             example='Someone keeps using after losing a job and a relationship over it.'),
        dict(term='Cross-Tolerance', category='neuro',
             meaning='Tolerance to one drug conferring tolerance to another in the same class.',
             detail='Why benzodiazepines treat alcohol withdrawal — both act on GABA receptors.',
             example='A heavy drinker needs unusually high benzodiazepine doses.'),
        dict(term='Prefrontal Cortex in Addiction', category='neuro',
             meaning='The region governing judgment and impulse control, which is impaired in addiction.',
             detail='Not fully mature until the mid-twenties, which is part of why early use predicts later disorder.',
             example='Impaired prefrontal control makes stopping harder than intention alone.'),
        dict(term='Craving', category='neuro',
             meaning='An intense urge to use, often triggered by cues rather than by withdrawal.',
             detail='Conditioned to people, places and objects. Cue-triggered craving is a leading cause of relapse long after detox.',
             example='Passing a familiar street corner triggers a strong urge.'),
        dict(term='Neuroplasticity in Recovery', category='neuro',
             meaning='The brain’s capacity to remodel circuits, which underlies recovery.',
             detail='Reward and control circuits partially normalize with sustained abstinence, though it takes months to years.',
             example='Cognitive function improves steadily over a year of abstinence.'),

        # ── Substance Classes ────────────────────────────────────
        dict(term='Central Nervous System Depressant', category='substances',
             meaning='A drug that slows brain activity, usually by enhancing GABA.',
             detail='Alcohol, benzodiazepines and barbiturates. Combining them multiplies respiratory depression risk.',
             example='Alcohol taken with a benzodiazepine causes dangerous sedation.'),
        dict(term='Alcohol', category='substances',
             meaning='A depressant that enhances GABA and inhibits glutamate signaling.',
             detail='One standard drink is 14 grams of pure alcohol. Long-term use damages the liver, pancreas, heart and brain.',
             example='A 12-ounce beer, 5 ounces of wine and 1.5 ounces of spirits are each one standard drink.'),
        dict(term='Benzodiazepines', category='substances',
             meaning='Prescription depressants used for anxiety, seizures and sedation.',
             detail='High dependence potential, especially with daily use beyond a few weeks. Withdrawal can cause seizures.',
             example='Long-term daily alprazolam use produces marked dependence.'),
        dict(term='Opioids', category='substances',
             meaning='Drugs acting at mu receptors to relieve pain and produce euphoria.',
             detail='Heroin, fentanyl, oxycodone, morphine, methadone. Respiratory depression is the mechanism of overdose death.',
             example='Illicitly manufactured fentanyl now drives most overdose deaths.'),
        dict(term='Fentanyl', category='substances',
             meaning='A synthetic opioid roughly 50 to 100 times more potent than morphine.',
             detail='Its potency means a few milligrams can be lethal, and inconsistent mixing makes street supply unpredictable.',
             example='A counterfeit pill contains an unknown and possibly fatal amount.'),
        dict(term='Stimulants', category='substances',
             meaning='Drugs that increase dopamine and norepinephrine, raising alertness and heart rate.',
             detail='Cocaine, methamphetamine, prescription amphetamines. Overdose presents as hyperthermia, agitation and cardiac events.',
             example='Cocaine blocks dopamine reuptake in the synapse.'),
        dict(term='Cannabis', category='substances',
             meaning='A drug acting on cannabinoid receptors, with THC as the main psychoactive component.',
             detail='Legal status varies by state. Heavy adolescent use is linked to cognitive effects and psychosis risk in susceptible people.',
             example='Modern products contain far higher THC concentrations than decades ago.'),
        dict(term='Hallucinogens', category='substances',
             meaning='Drugs that distort perception, mainly through serotonin receptor activity.',
             detail='LSD, psilocybin, mescaline. Low physical dependence, but risk of dangerous behavior during intoxication.',
             example='A user experiences visual distortion and altered time perception.'),
        dict(term='Dissociatives', category='substances',
             meaning='Drugs producing detachment from the body and environment, acting at NMDA receptors.',
             detail='Ketamine, PCP and dextromethorphan. PCP intoxication can produce violent agitation and analgesia.',
             example='A dissociated patient feels separated from their own body.'),
        dict(term='Inhalants', category='substances',
             meaning='Volatile substances inhaled for a rapid, short-lived high.',
             detail='Solvents, aerosols, nitrites. Can cause sudden sniffing death from cardiac sensitization on first use.',
             example='A young teen inhaling aerosol propellant collapses suddenly.'),
        dict(term='Nicotine', category='substances',
             meaning='A stimulant acting at nicotinic acetylcholine receptors, with very high dependence potential.',
             detail='Delivered by cigarettes, vapes and pouches. Tobacco remains the leading preventable cause of death.',
             example='Vaping delivers nicotine with rapid absorption and strong reinforcement.'),
        dict(term='Polysubstance Use', category='substances',
             meaning='Using more than one substance, together or in a pattern.',
             detail='Complicates withdrawal and greatly raises overdose risk, especially opioids with depressants.',
             example='Combining opioids and benzodiazepines multiplies respiratory risk.'),

        # ── Intoxication & Withdrawal ────────────────────────────
        dict(term='Alcohol Withdrawal', category='withdrawal',
             meaning='Symptoms beginning 6 to 24 hours after the last drink, which can be fatal.',
             detail='Tremor, anxiety, sweating, tachycardia, then seizures at 12 to 48 hours and delirium tremens at 48 to 96.',
             example='A heavy drinker admitted for surgery develops tremor overnight.'),
        dict(term='Delirium Tremens', category='withdrawal',
             meaning='Severe alcohol withdrawal with confusion, hallucinations and autonomic instability.',
             detail='Onset 48 to 96 hours after the last drink. Mortality is significant untreated; benzodiazepines are the treatment.',
             example='A patient becomes disoriented with fever and severe tremor on day three.'),
        dict(term='CIWA-Ar', category='withdrawal',
             meaning='A ten-item scale scoring alcohol withdrawal severity to guide medication.',
             detail='Supports symptom-triggered dosing, which uses less medication than fixed schedules.',
             example='Benzodiazepine is given whenever the CIWA score crosses a threshold.'),
        dict(term='Benzodiazepine Withdrawal', category='withdrawal',
             meaning='Withdrawal that mirrors alcohol withdrawal and can also cause seizures.',
             detail='Onset depends on half-life. Managed by slow tapering, never abrupt discontinuation.',
             example='A long-term user is tapered over months rather than stopped.'),
        dict(term='Opioid Withdrawal', category='withdrawal',
             meaning='A flu-like syndrome that is severely unpleasant but rarely life-threatening.',
             detail='Muscle aches, nausea, diarrhea, yawning, dilated pupils, piloerection, anxiety. Dehydration is the main danger.',
             example='A patient in withdrawal has dilated pupils and goosebumps.'),
        dict(term='COWS', category='withdrawal',
             meaning='The Clinical Opiate Withdrawal Scale, scoring severity to time buprenorphine induction.',
             detail='Buprenorphine given too early precipitates worse withdrawal, so a minimum score is required first.',
             example='Induction waits until the COWS score reaches a defined threshold.'),
        dict(term='Precipitated Withdrawal', category='withdrawal',
             meaning='Abrupt severe withdrawal triggered by giving an antagonist or partial agonist too soon.',
             detail='Buprenorphine displaces full agonists from the receptor. Avoided by waiting for established withdrawal.',
             example='Buprenorphine given too early causes sudden severe symptoms.'),
        dict(term='Stimulant Withdrawal', category='withdrawal',
             meaning='A crash of fatigue, hypersomnia, increased appetite and depressed mood.',
             detail='Not medically dangerous, but depression and suicidal thinking can be severe. No approved medication exists.',
             example='A user sleeps for two days and wakes profoundly depressed.'),
        dict(term='Opioid Overdose', category='withdrawal',
             meaning='Respiratory depression and unresponsiveness from excess opioid at the mu receptor.',
             detail='Pinpoint pupils, slow or absent breathing, blue lips. Reversible with naloxone.',
             example='A responder finds shallow breathing and constricted pupils.'),
        dict(term='Naloxone', category='withdrawal',
             meaning='An opioid antagonist that reverses overdose within minutes.',
             detail='Given intranasally or by injection. Shorter-acting than fentanyl, so repeat doses and EMS are still required.',
             example='A bystander administers nasal naloxone and calls 911.'),
        dict(term='Wernicke Encephalopathy', category='withdrawal',
             meaning='Acute thiamine deficiency causing confusion, ataxia and eye movement abnormalities.',
             detail='Seen in chronic alcohol use. Thiamine must be given before glucose or the deficiency worsens.',
             example='Thiamine is given first to a malnourished patient with alcohol use.'),
        dict(term='Korsakoff Syndrome', category='withdrawal',
             meaning='Chronic memory impairment with confabulation from untreated thiamine deficiency.',
             detail='Often follows Wernicke encephalopathy and is largely irreversible, which makes prevention essential.',
             example='A patient invents plausible details to fill memory gaps.'),

        # ── Screening & Diagnosis ────────────────────────────────
        dict(term='Substance Use Disorder', category='screening',
             meaning='A problematic pattern of use meeting at least 2 of 11 DSM-5 criteria in a year.',
             detail='Graded mild at 2 to 3 criteria, moderate at 4 to 5, severe at 6 or more. DSM-5 merged abuse and dependence into one diagnosis.',
             example='A patient meeting seven criteria has a severe disorder.'),
        dict(term='DSM-5 Criteria Clusters', category='screening',
             meaning='Impaired control, social impairment, risky use, and pharmacological criteria.',
             detail='The 11 criteria group into these four. Tolerance and withdrawal alone do not establish a disorder in someone taking prescribed medication.',
             example='Continued use despite relationship conflict is social impairment.'),
        dict(term='CAGE Questionnaire', category='screening',
             meaning='A four-question alcohol screen asking about cutting down, annoyance, guilt and eye-openers.',
             detail='Two or more yes answers is a positive screen. Fast but insensitive to hazardous drinking short of dependence.',
             example='A patient answers yes to guilt and to a morning drink.'),
        dict(term='AUDIT', category='screening',
             meaning='A ten-item WHO screen covering alcohol consumption, dependence and harm.',
             detail='More sensitive than CAGE for risky drinking. AUDIT-C is a three-question consumption-only short form.',
             example='A primary care visit includes an AUDIT-C screen.'),
        dict(term='CRAFFT', category='screening',
             meaning='The standard adolescent substance-use screen.',
             detail='Car, Relax, Alone, Forget, Friends, Trouble. Validated for ages 12 to 21.',
             example='A pediatrician screens a 15-year-old with CRAFFT.'),
        dict(term='SBIRT', category='screening',
             meaning='Screening, Brief Intervention and Referral to Treatment.',
             detail='A public health approach in general medical settings. Brief intervention is effective for risky use short of disorder.',
             example='An ED screens every patient and offers a brief conversation.'),
        dict(term='Stages of Change', category='screening',
             meaning='Precontemplation, contemplation, preparation, action, maintenance.',
             detail='The transtheoretical model. Matching the intervention to the stage works better than pushing action too early.',
             example='A patient in contemplation is weighing reasons to change.'),
        dict(term='Motivational Interviewing', category='screening',
             meaning='A collaborative counseling style that draws out a person’s own reasons for change.',
             detail='Express empathy, develop discrepancy, roll with resistance, support self-efficacy. Confrontation reliably backfires.',
             example='A counselor asks what the patient values that drinking interferes with.'),
        dict(term='Urine Drug Screen', category='screening',
             meaning='An immunoassay detecting recent substance use.',
             detail='Prone to false positives and negatives; confirmation uses mass spectrometry. Many synthetic opioids are not detected.',
             example='A positive screen is confirmed before any clinical decision.'),
        dict(term='Dual Diagnosis', category='screening',
             meaning='A substance use disorder co-occurring with another psychiatric disorder.',
             detail='Very common. Treating only one side predicts relapse, so integrated treatment is standard.',
             example='Depression and alcohol use disorder are treated together.'),

        # ── Treatment ────────────────────────────────────────────
        dict(term='Medication for Opioid Use Disorder', category='treatment',
             meaning='Treatment with methadone, buprenorphine or naltrexone alongside counseling.',
             detail='Roughly halves mortality. The term replaced "medication-assisted treatment", which implied medication was secondary.',
             example='A patient starts buprenorphine and attends weekly counseling.'),
        dict(term='Methadone', category='treatment',
             meaning='A long-acting full opioid agonist that prevents withdrawal and craving.',
             detail='Dispensed through licensed opioid treatment programs. Strong evidence for retention, with QT prolongation as a risk.',
             example='A patient attends a clinic daily for observed dosing.'),
        dict(term='Buprenorphine', category='treatment',
             meaning='A partial opioid agonist with a ceiling effect that limits respiratory depression.',
             detail='Prescribable in office settings, which widens access. Often combined with naloxone to deter injection.',
             example='A physician prescribes buprenorphine-naloxone films.'),
        dict(term='Naltrexone', category='treatment',
             meaning='An opioid antagonist that blocks the effect of opioids and reduces alcohol craving.',
             detail='Requires full detoxification first or it precipitates withdrawal. Monthly injection improves adherence.',
             example='A patient receives a monthly extended-release injection.'),
        dict(term='Acamprosate', category='treatment',
             meaning='A medication that reduces alcohol craving by modulating glutamate signaling.',
             detail='Started after abstinence begins. Safe in liver disease, which makes it useful where naltrexone is not.',
             example='A patient with cirrhosis is given acamprosate rather than naltrexone.'),
        dict(term='Disulfiram', category='treatment',
             meaning='A medication causing an unpleasant reaction if alcohol is consumed.',
             detail='Blocks aldehyde dehydrogenase, producing flushing, nausea and palpitations. Works only with supervised adherence.',
             example='A patient in a supervised program takes daily disulfiram.'),
        dict(term='Cognitive Behavioral Therapy', category='treatment',
             meaning='Therapy identifying triggers and building skills to respond without using.',
             detail='Strong evidence across substances. Includes functional analysis, coping skills and relapse prevention planning.',
             example='A patient maps high-risk situations and plans responses.'),
        dict(term='Contingency Management', category='treatment',
             meaning='Providing tangible rewards for verified abstinence.',
             detail='The most effective behavioral treatment for stimulant use disorder, where no medication is approved.',
             example='Negative urine screens earn escalating vouchers.'),
        dict(term='Twelve-Step Facilitation', category='treatment',
             meaning='Structured encouragement to engage with a mutual-help fellowship.',
             detail='Evidence supports facilitated engagement. Participation is voluntary and not a substitute for medication.',
             example='A counselor helps a patient attend their first meeting.'),
        dict(term='Levels of Care', category='treatment',
             meaning='A continuum from outpatient through intensive outpatient, residential and inpatient.',
             detail='ASAM criteria match level to severity, withdrawal risk, environment and readiness.',
             example='A patient steps down from residential to intensive outpatient.'),
        dict(term='Relapse Prevention', category='treatment',
             meaning='Planning to recognize warning signs and respond before a lapse becomes a return to use.',
             detail='Relapse is common in chronic disease and signals a need to adjust treatment, not evidence of failure.',
             example='A patient identifies early warning signs and a call list.'),
        dict(term='Recovery', category='treatment',
             meaning='A process of change toward improved health, self-direction and a full life.',
             detail='Defined by function and wellbeing, not only by abstinence. Recovery capital includes housing, work and relationships.',
             example='Stable housing and employment support sustained recovery.'),

        # ── Harm Reduction & Policy ──────────────────────────────
        dict(term='Harm Reduction', category='harm',
             meaning='Reducing the harms of drug use without requiring abstinence first.',
             detail='Grounded in the view that a person must survive to recover. Includes naloxone distribution, syringe services and testing.',
             example='Distributing naloxone to people who use drugs and their families.'),
        dict(term='Syringe Services Program', category='harm',
             meaning='A program providing sterile injection equipment and safe disposal.',
             detail='Reduces HIV and hepatitis C transmission and does not increase drug use. Often a route into treatment.',
             example='Participants exchange used syringes and receive referrals.'),
        dict(term='Fentanyl Test Strips', category='harm',
             meaning='Strips that detect fentanyl in a drug sample before use.',
             detail='Let people adjust behavior when a supply is contaminated. Legal status varies by state.',
             example='A user tests a sample and finds fentanyl in a stimulant.'),
        dict(term='Good Samaritan Overdose Law', category='harm',
             meaning='A law shielding people who call for help at an overdose from certain drug charges.',
             detail='Addresses fear of arrest, the leading reason bystanders do not call. Coverage varies widely by state.',
             example='A friend calls 911 knowing the law protects them.'),
        dict(term='Naloxone Standing Order', category='harm',
             meaning='A prescription allowing pharmacies to dispense naloxone without an individual prescription.',
             detail='In place in every state, though pharmacy stocking and cost still limit access.',
             example='A parent obtains naloxone directly from a pharmacist.'),
        dict(term='Stigma', category='harm',
             meaning='Negative attitudes that mark people who use drugs as blameworthy.',
             detail='Measurably reduces treatment seeking and quality of care. Person-first language is part of countering it.',
             example='Saying "person with a substance use disorder" rather than "addict".'),
        dict(term='Prescription Drug Monitoring Program', category='harm',
             meaning='A state database tracking dispensed controlled substances.',
             detail='Lets prescribers see a patient’s history and identify risky combinations before prescribing.',
             example='A prescriber checks the database before writing for opioids.'),
        dict(term='Opioid Stewardship', category='harm',
             meaning='Institutional practices that keep opioid prescribing appropriate.',
             detail='Multimodal analgesia, limited supply for acute pain, and safe storage and disposal counseling.',
             example='A surgeon prescribes three days of opioids after a minor procedure.'),
        dict(term='Adverse Childhood Experiences', category='harm',
             meaning='Childhood trauma exposures that raise the lifetime risk of substance use disorder.',
             detail='Abuse, neglect and household dysfunction. Risk rises with the number of exposures in a dose-response pattern.',
             example='A patient with a high ACE score is screened for trauma-informed care.'),
    ],
))


# ═══════════════════════════════════════════════════════════════════
#  Cell Biology & Histology
# ═══════════════════════════════════════════════════════════════════
SPECS.append(dict(
    slug='cell-biology-histology',
    name='Cell Biology & Histology',
    eyebrow='Health Science — Cell Biology & Histology',
    h1_lead='Cells, Tissues &',
    h1_em='Histology',
    subtitle='A study companion for organelles, the cell membrane, the cell cycle, the four tissue types '
             'and microscopy — built for HOSA competitors preparing for Biomedical Laboratory Science '
             'and Anatomy events.',
    test_blurb='cell structure, tissue and microscopy concepts',
    topics='Organelles, membrane transport, cell cycle and mitosis, epithelial, connective, muscle and nervous tissue, staining',
    tips=[
        'Match organelle to function. Most questions are really "which structure does this job?"',
        'Learn the four tissue types and one defining feature of each. Epithelium is avascular and sits on a basement membrane.',
        'Epithelium is named by layers and then shape: simple or stratified, then squamous, cuboidal or columnar.',
        'Know which transport needs ATP. Diffusion and osmosis do not; the sodium-potassium pump does.',
        'Interphase is G1, S and G2 — it is not a phase of mitosis. PMAT is the mitotic sequence.',
        'H&E is the workhorse stain: hematoxylin turns nuclei blue-purple, eosin turns cytoplasm pink.',
    ],
    categories=[
        ('organelles','Organelles'),
        ('membrane',  'Membrane & Transport'),
        ('cycle',     'Cell Cycle & Division'),
        ('epithelial','Epithelial Tissue'),
        ('connective','Connective Tissue'),
        ('excitable', 'Muscle & Nervous Tissue'),
        ('micro',     'Microscopy & Staining'),
    ],
    terms=[
        # ── Organelles ───────────────────────────────────────────
        dict(term='Nucleus', category='organelles',
             meaning='The organelle holding the cell’s DNA and directing its activity.',
             detail='Bounded by a double membrane with pores. Contains chromatin and one or more nucleoli.',
             example='Mature red blood cells lose their nucleus to carry more hemoglobin.'),
        dict(term='Nucleolus', category='organelles',
             meaning='A dense region inside the nucleus where ribosomes are assembled.',
             detail='Not membrane-bound. Prominent in cells producing large amounts of protein.',
             example='Plasma cells have a conspicuous nucleolus.'),
        dict(term='Ribosome', category='organelles',
             meaning='The structure that translates messenger RNA into protein.',
             detail='Free ribosomes make proteins for use inside the cell; those on rough ER make proteins for export or membranes.',
             example='Free ribosomes synthesize cytoplasmic enzymes.'),
        dict(term='Rough Endoplasmic Reticulum', category='organelles',
             meaning='Membrane sheets studded with ribosomes that make and fold exported proteins.',
             detail='Continuous with the nuclear envelope. Abundant in secretory cells.',
             example='Pancreatic acinar cells are packed with rough ER.'),
        dict(term='Smooth Endoplasmic Reticulum', category='organelles',
             meaning='Membrane tubules that make lipids, metabolize drugs and store calcium.',
             detail='No ribosomes. Abundant in liver cells and in cells producing steroid hormones.',
             example='Hepatocytes use smooth ER to detoxify drugs.'),
        dict(term='Golgi Apparatus', category='organelles',
             meaning='Stacked membranes that modify, sort and package proteins for delivery.',
             detail='Receives vesicles from the ER on the cis face and releases them from the trans face.',
             example='The Golgi adds sugars to a protein before secretion.'),
        dict(term='Mitochondrion', category='organelles',
             meaning='The organelle that produces most of the cell’s ATP by aerobic respiration.',
             detail='Double membrane with inner folds called cristae. Has its own DNA, inherited maternally.',
             example='Cardiac muscle cells are dense with mitochondria.'),
        dict(term='Lysosome', category='organelles',
             meaning='A vesicle of digestive enzymes that breaks down waste and worn organelles.',
             detail='Its enzymes work in an acidic interior. Inherited enzyme deficiencies cause storage diseases.',
             example='A macrophage digests bacteria inside lysosomes.'),
        dict(term='Peroxisome', category='organelles',
             meaning='A vesicle that breaks down fatty acids and neutralizes hydrogen peroxide.',
             detail='Uses catalase to convert peroxide to water and oxygen. Numerous in liver and kidney.',
             example='Peroxisomes handle very-long-chain fatty acid breakdown.'),
        dict(term='Cytoskeleton', category='organelles',
             meaning='A protein framework giving the cell shape, movement and internal transport.',
             detail='Microfilaments of actin, intermediate filaments for tensile strength, and microtubules of tubulin.',
             example='Microtubules form the spindle that separates chromosomes.'),
        dict(term='Centrosome', category='organelles',
             meaning='The organizing center for microtubules, containing a pair of centrioles.',
             detail='Duplicates before division and organizes the mitotic spindle from opposite poles.',
             example='Centrosomes migrate to opposite poles during prophase.'),
        dict(term='Cilia and Flagella', category='organelles',
             meaning='Motile surface projections built from a 9+2 microtubule arrangement.',
             detail='Cilia are short and numerous and move fluid across a surface; a flagellum is long and propels the cell.',
             example='Ciliated airway cells sweep mucus toward the throat.'),
        dict(term='Microvilli', category='organelles',
             meaning='Non-motile finger-like projections that increase absorptive surface area.',
             detail='Supported by actin filaments. Appear together as a brush border.',
             example='Intestinal cells carry a dense brush border of microvilli.'),
        dict(term='Cytoplasm and Cytosol', category='organelles',
             meaning='Cytoplasm is everything between membrane and nucleus; cytosol is its fluid alone.',
             detail='Cytoplasm includes the organelles suspended in the cytosol.',
             example='Glycolysis takes place in the cytosol.'),

        # ── Membrane & Transport ─────────────────────────────────
        dict(term='Phospholipid Bilayer', category='membrane',
             meaning='The double layer of phospholipids forming the cell membrane.',
             detail='Hydrophilic heads face the water on each side and hydrophobic tails face inward, making it selectively permeable.',
             example='Small non-polar molecules cross the bilayer freely.'),
        dict(term='Fluid Mosaic Model', category='membrane',
             meaning='The model describing the membrane as a fluid bilayer with proteins drifting within it.',
             detail='Cholesterol modulates fluidity; glycoproteins and glycolipids form the outer glycocalyx.',
             example='Membrane proteins move laterally within the bilayer.'),
        dict(term='Integral Membrane Protein', category='membrane',
             meaning='A protein embedded within the bilayer, often spanning it completely.',
             detail='Forms channels, carriers and receptors. Removing one requires disrupting the membrane.',
             example='An ion channel spans the full thickness of the membrane.'),
        dict(term='Simple Diffusion', category='membrane',
             meaning='Movement of a substance down its concentration gradient without energy or a protein.',
             detail='Passive. Rate depends on gradient steepness, molecular size and lipid solubility.',
             example='Oxygen diffuses from alveolar air into blood.'),
        dict(term='Facilitated Diffusion', category='membrane',
             meaning='Passive movement down a gradient through a channel or carrier protein.',
             detail='No ATP, but it saturates once every transporter is occupied, unlike simple diffusion.',
             example='Glucose enters cells through a GLUT transporter.'),
        dict(term='Osmosis', category='membrane',
             meaning='Diffusion of water across a selectively permeable membrane.',
             detail='Water moves toward higher solute concentration. Aquaporins speed it in kidney and other tissues.',
             example='Water moves into a cell placed in distilled water.'),
        dict(term='Tonicity', category='membrane',
             meaning='How a solution affects cell volume: isotonic, hypotonic or hypertonic.',
             detail='Cells swell and may lyse in hypotonic solution and shrink in hypertonic solution.',
             example='Normal saline is isotonic to red blood cells.'),
        dict(term='Active Transport', category='membrane',
             meaning='Movement of a substance against its gradient, using ATP.',
             detail='Primary active transport hydrolyzes ATP directly; secondary transport uses a gradient another pump created.',
             example='The sodium-potassium pump moves ions against their gradients.'),
        dict(term='Sodium-Potassium Pump', category='membrane',
             meaning='A pump moving three sodium ions out and two potassium ions in per ATP.',
             detail='Maintains the resting membrane potential and consumes a large share of a cell’s energy.',
             example='Neurons rely on it to restore gradients after firing.'),
        dict(term='Endocytosis', category='membrane',
             meaning='Taking material into the cell by engulfing it in a membrane vesicle.',
             detail='Phagocytosis for solids, pinocytosis for fluid, and receptor-mediated endocytosis for specific molecules.',
             example='A neutrophil phagocytoses a bacterium.'),
        dict(term='Exocytosis', category='membrane',
             meaning='Releasing material by fusing a vesicle with the cell membrane.',
             detail='How cells secrete hormones, enzymes and neurotransmitters, and how membrane is recycled.',
             example='A neuron releases neurotransmitter into the synapse.'),

        # ── Cell Cycle & Division ────────────────────────────────
        dict(term='Cell Cycle', category='cycle',
             meaning='The sequence a cell passes through from one division to the next.',
             detail='Interphase (G1, S, G2) then mitosis and cytokinesis. Cells may exit to a resting G0 state.',
             example='Neurons remain permanently in G0.'),
        dict(term='Interphase', category='cycle',
             meaning='The growth and DNA replication phase between divisions.',
             detail='G1 growth, S phase replication, G2 preparation. Takes up most of the cycle and is not part of mitosis.',
             example='A cell spends most of its life in interphase.'),
        dict(term='S Phase', category='cycle',
             meaning='The phase in which DNA is replicated.',
             detail='Each chromosome ends as two identical sister chromatids joined at a centromere.',
             example='DNA content doubles during S phase.'),
        dict(term='Prophase', category='cycle',
             meaning='The first stage of mitosis, where chromatin condenses into visible chromosomes.',
             detail='The nuclear envelope breaks down, the nucleolus disappears, and the spindle begins to form.',
             example='Chromosomes first become visible in prophase.'),
        dict(term='Metaphase', category='cycle',
             meaning='The stage in which chromosomes align along the cell’s equator.',
             detail='Spindle fibers attach at kinetochores. A checkpoint blocks progress until every chromosome is attached.',
             example='Chromosomes line up in a single plane at metaphase.'),
        dict(term='Anaphase', category='cycle',
             meaning='The stage in which sister chromatids separate toward opposite poles.',
             detail='Failure to separate correctly causes nondisjunction and an abnormal chromosome number.',
             example='Chromatids are pulled apart by shortening spindle fibers.'),
        dict(term='Telophase', category='cycle',
             meaning='The final stage of mitosis, where nuclear envelopes reform around each set.',
             detail='Chromosomes decondense and nucleoli reappear. Cytokinesis usually overlaps it.',
             example='Two nuclei become visible at telophase.'),
        dict(term='Cytokinesis', category='cycle',
             meaning='Division of the cytoplasm into two daughter cells.',
             detail='An actin ring pinches animal cells into a cleavage furrow.',
             example='A cleavage furrow deepens until the cells separate.'),
        dict(term='Meiosis', category='cycle',
             meaning='Two rounds of division producing four haploid gametes from one diploid cell.',
             detail='Crossing over in prophase I and independent assortment generate genetic variation.',
             example='Meiosis produces sperm and egg cells.'),
        dict(term='Apoptosis', category='cycle',
             meaning='Programmed cell death that removes cells without inflammation.',
             detail='The cell shrinks and fragments into bodies that phagocytes clear. Distinct from necrosis, which is injury-driven and inflammatory.',
             example='Webbing between fetal fingers is removed by apoptosis.'),
        dict(term='Cell Cycle Checkpoints', category='cycle',
             meaning='Control points that halt the cycle until conditions are correct.',
             detail='G1, G2 and spindle checkpoints. p53 arrests the cycle for repair, which is why its loss is common in cancer.',
             example='DNA damage triggers arrest at the G1 checkpoint.'),
        dict(term='Stem Cell', category='cycle',
             meaning='An unspecialized cell able to divide and to differentiate into other cell types.',
             detail='Totipotent, pluripotent, multipotent or unipotent by how many fates remain available.',
             example='Bone marrow stem cells produce every blood cell line.'),

        # ── Epithelial Tissue ────────────────────────────────────
        dict(term='Epithelial Tissue', category='epithelial',
             meaning='Tissue covering surfaces, lining cavities and forming glands.',
             detail='Avascular, sits on a basement membrane, has a free surface, and regenerates rapidly.',
             example='The skin surface and the gut lining are both epithelium.'),
        dict(term='Basement Membrane', category='epithelial',
             meaning='The layer anchoring epithelium to the connective tissue beneath.',
             detail='Made of basal lamina and reticular lamina. Invasion through it is what distinguishes invasive carcinoma.',
             example='Carcinoma in situ has not breached the basement membrane.'),
        dict(term='Simple Squamous Epithelium', category='epithelial',
             meaning='A single layer of flat cells suited to diffusion and filtration.',
             detail='Forms alveoli, capillary endothelium and the serous membranes lining body cavities.',
             example='Alveolar walls allow gas exchange across one thin layer.'),
        dict(term='Simple Cuboidal Epithelium', category='epithelial',
             meaning='A single layer of cube-shaped cells specialized for secretion and absorption.',
             detail='Lines kidney tubules and small ducts, and covers the thyroid follicles and ovary surface.',
             example='Kidney tubules are lined with simple cuboidal cells.'),
        dict(term='Simple Columnar Epithelium', category='epithelial',
             meaning='A single layer of tall cells for absorption and secretion.',
             detail='Often bears microvilli and goblet cells. Lines the stomach and intestines.',
             example='The small intestine lining is simple columnar with a brush border.'),
        dict(term='Pseudostratified Columnar Epithelium', category='epithelial',
             meaning='A single layer that looks layered because nuclei sit at different heights.',
             detail='Every cell touches the basement membrane. The ciliated form with goblet cells lines the airways.',
             example='The trachea is lined with ciliated pseudostratified epithelium.'),
        dict(term='Stratified Squamous Epithelium', category='epithelial',
             meaning='Many layers of cells, flattened at the surface, built to resist abrasion.',
             detail='Keratinized in the epidermis, non-keratinized in the mouth, esophagus and vagina.',
             example='The esophagus is lined with non-keratinized stratified squamous epithelium.'),
        dict(term='Transitional Epithelium', category='epithelial',
             meaning='Epithelium that changes shape as an organ stretches.',
             detail='Also called urothelium. Surface cells are dome-shaped when relaxed and flatten when distended.',
             example='The bladder lining flattens as it fills.'),
        dict(term='Glandular Epithelium', category='epithelial',
             meaning='Epithelium specialized for secretion, forming exocrine and endocrine glands.',
             detail='Exocrine glands secrete through ducts; endocrine glands release hormones into the blood.',
             example='Sweat glands are exocrine; the thyroid is endocrine.'),
        dict(term='Cell Junctions', category='epithelial',
             meaning='Structures binding adjacent cells and controlling what passes between them.',
             detail='Tight junctions seal, desmosomes anchor, and gap junctions let ions and small molecules pass.',
             example='Tight junctions prevent leakage between intestinal cells.'),

        # ── Connective Tissue ────────────────────────────────────
        dict(term='Connective Tissue', category='connective',
             meaning='Tissue of scattered cells in an extracellular matrix that supports and binds.',
             detail='The most abundant tissue type. Matrix composition determines whether it is fluid, soft or solid.',
             example='Bone, blood and fat are all connective tissue.'),
        dict(term='Extracellular Matrix', category='connective',
             meaning='The ground substance and fibers surrounding connective tissue cells.',
             detail='Its makeup gives each tissue its properties, from liquid plasma to mineralized bone.',
             example='Cartilage matrix is firm and gel-like.'),
        dict(term='Collagen Fiber', category='connective',
             meaning='A strong, flexible protein fiber providing tensile strength.',
             detail='The most abundant protein in the body. Tendon and ligament are dense with it.',
             example='Tendons are packed with parallel collagen bundles.'),
        dict(term='Elastic Fiber', category='connective',
             meaning='A fiber of elastin that stretches and recoils.',
             detail='Lets tissue return to shape after deformation. Prominent in large arteries, lung and skin.',
             example='The aorta recoils between heartbeats.'),
        dict(term='Fibroblast', category='connective',
             meaning='The cell that produces connective tissue fibers and ground substance.',
             detail='The principal cell of loose and dense connective tissue and central to wound repair.',
             example='Fibroblasts lay down collagen in a healing wound.'),
        dict(term='Areolar Connective Tissue', category='connective',
             meaning='Loose tissue with scattered fibers that cushions and holds organs in place.',
             detail='The most widespread connective tissue. Its open spaces let fluid accumulate, producing edema.',
             example='Areolar tissue underlies epithelium throughout the body.'),
        dict(term='Adipose Tissue', category='connective',
             meaning='Connective tissue of fat-storing cells that insulates, cushions and stores energy.',
             detail='White adipose stores energy; brown adipose generates heat and is prominent in infants.',
             example='Subcutaneous fat insulates the body.'),
        dict(term='Dense Regular Connective Tissue', category='connective',
             meaning='Tightly packed parallel collagen bundles built to resist pull in one direction.',
             detail='Forms tendons and ligaments. Poorly vascularized, which is why these structures heal slowly.',
             example='A tendon transmits muscle force to bone.'),
        dict(term='Cartilage', category='connective',
             meaning='Firm, flexible connective tissue with chondrocytes in lacunae.',
             detail='Avascular and slow to heal. Hyaline covers joints, elastic forms the ear, fibrocartilage forms discs.',
             example='Hyaline cartilage covers the ends of long bones.'),
        dict(term='Bone Tissue', category='connective',
             meaning='Connective tissue with a mineralized matrix, arranged as compact or spongy bone.',
             detail='Osteocytes sit in lacunae within osteons. Continuously remodeled by osteoblasts and osteoclasts.',
             example='Compact bone forms the shaft of a long bone.'),
        dict(term='Blood', category='connective',
             meaning='Connective tissue with a fluid matrix called plasma.',
             detail='Classed as connective tissue because its cells are suspended in an extracellular matrix.',
             example='Red cells, white cells and platelets are suspended in plasma.'),

        # ── Muscle & Nervous Tissue ──────────────────────────────
        dict(term='Skeletal Muscle', category='excitable',
             meaning='Striated, multinucleated muscle under voluntary control.',
             detail='Attaches to bone and contracts quickly. Nuclei sit at the periphery of each long fiber.',
             example='The biceps is skeletal muscle.'),
        dict(term='Cardiac Muscle', category='excitable',
             meaning='Striated, involuntary muscle found only in the heart.',
             detail='Branched cells with one or two central nuclei joined by intercalated discs, which let the heart contract as a unit.',
             example='Intercalated discs coordinate the heartbeat.'),
        dict(term='Smooth Muscle', category='excitable',
             meaning='Non-striated, involuntary muscle in the walls of hollow organs.',
             detail='Spindle-shaped cells with a single central nucleus. Contracts slowly and sustains tone.',
             example='Smooth muscle moves food along the intestine.'),
        dict(term='Sarcomere', category='excitable',
             meaning='The repeating contractile unit of striated muscle, running Z line to Z line.',
             detail='Overlapping actin and myosin produce the striations. Sliding filaments shorten it during contraction.',
             example='Sarcomeres shorten as actin slides over myosin.'),
        dict(term='Neuron', category='excitable',
             meaning='The excitable cell that transmits electrical signals in the nervous system.',
             detail='Dendrites receive, the cell body integrates, and the axon conducts the signal away.',
             example='A motor neuron carries a signal from spinal cord to muscle.'),
        dict(term='Neuroglia', category='excitable',
             meaning='Supporting cells of nervous tissue that outnumber neurons.',
             detail='Astrocytes, oligodendrocytes, microglia and ependymal cells centrally; Schwann and satellite cells peripherally.',
             example='Astrocytes help maintain the blood-brain barrier.'),
        dict(term='Myelin Sheath', category='excitable',
             meaning='A fatty insulating layer around axons that speeds conduction.',
             detail='Made by oligodendrocytes centrally and Schwann cells peripherally. Gaps are nodes of Ranvier.',
             example='Signals jump between nodes, conducting far faster.'),
        dict(term='Synapse', category='excitable',
             meaning='The junction where a neuron passes a signal to another cell.',
             detail='Neurotransmitter crosses the synaptic cleft to receptors on the target membrane.',
             example='Acetylcholine crosses the neuromuscular junction.'),

        # ── Microscopy & Staining ────────────────────────────────
        dict(term='Compound Light Microscope', category='micro',
             meaning='A microscope using visible light and two lens systems to magnify a specimen.',
             detail='Total magnification is ocular times objective. Standard for routine histology.',
             example='A 10x ocular with a 40x objective gives 400x.'),
        dict(term='Resolution', category='micro',
             meaning='The smallest distance at which two points can still be told apart.',
             detail='Limited by wavelength, which is why electron microscopes resolve far more detail than light.',
             example='Light microscopy resolves to about 0.2 micrometers.'),
        dict(term='Electron Microscope', category='micro',
             meaning='A microscope using an electron beam to resolve fine structure.',
             detail='TEM shows internal detail in thin sections; SEM shows surface topography in three dimensions.',
             example='TEM reveals the cristae inside a mitochondrion.'),
        dict(term='Oil Immersion', category='micro',
             meaning='Placing oil between the slide and the objective to improve resolution at high power.',
             detail='Matches the refractive index of glass so less light is lost. Used at 100x.',
             example='A blood smear is examined under oil immersion.'),
        dict(term='Fixation', category='micro',
             meaning='Preserving tissue to stop decay and hold structure in place.',
             detail='Formalin is the usual fixative. Poor fixation cannot be corrected later in processing.',
             example='A biopsy is placed in formalin immediately.'),
        dict(term='Microtome', category='micro',
             meaning='An instrument that cuts embedded tissue into very thin sections.',
             detail='Routine sections are about 4 to 5 micrometers, thin enough to transmit light.',
             example='Paraffin-embedded tissue is sectioned before staining.'),
        dict(term='Hematoxylin and Eosin', category='micro',
             meaning='The routine histology stain that colors nuclei blue-purple and cytoplasm pink.',
             detail='Hematoxylin is basic and binds acidic nuclear material; eosin is acidic and binds basic cytoplasmic proteins.',
             example='H&E is the default stain on nearly every biopsy.'),
        dict(term='Special Stains', category='micro',
             meaning='Stains that highlight a particular structure or organism.',
             detail='PAS for glycogen and fungi, trichrome for collagen, silver for reticulin, Congo red for amyloid.',
             example='Congo red shows apple-green birefringence in amyloid.'),
        dict(term='Immunohistochemistry', category='micro',
             meaning='Using labeled antibodies to locate a specific protein in tissue.',
             detail='Central to classifying tumors and choosing targeted treatment.',
             example='Staining for a receptor guides breast cancer therapy.'),
        dict(term='Frozen Section', category='micro',
             meaning='Rapid diagnosis on tissue frozen rather than embedded in paraffin.',
             detail='Available in minutes during surgery, at the cost of poorer morphology.',
             example='A surgeon waits on a frozen section to check a margin.'),
    ],
))
