# -*- coding: utf-8 -*-
"""Event content, batch C."""

SPECS = []

# ═══════════════════════════════════════════════════════════════════
#  Medical Coding & Billing
# ═══════════════════════════════════════════════════════════════════
SPECS.append(dict(
    slug='medical-coding-billing',
    name='Medical Coding & Billing',
    eyebrow='Health Professions — Medical Coding & Billing',
    h1_lead='Claims, Codes &',
    h1_em='Medical Billing',
    subtitle='A study companion for ICD-10-CM, CPT and HCPCS coding, the revenue cycle, insurance plans, '
             'claims and compliance — built for HOSA competitors and students entering health '
             'information careers.',
    test_blurb='coding, billing and reimbursement concepts',
    topics='ICD-10-CM, CPT, HCPCS, modifiers, the revenue cycle, payers, claims and denials, compliance',
    tips=[
        'Know which code set answers which question: ICD-10-CM is why, CPT is what was done, HCPCS Level II is what was supplied.',
        'Medical necessity is the link between the diagnosis and the procedure. Most denials are really a necessity problem.',
        'Learn the common modifiers cold — 25, 59, 51, 50, 26 and TC come up constantly.',
        'Never code from the alphabetic index alone. Always verify in the tabular list.',
        'Upcoding and unbundling are fraud, not shortcuts. Know the difference between fraud and abuse.',
        'Follow a claim end to end: registration, charge capture, coding, submission, adjudication, payment, appeal.',
    ],
    categories=[
        ('icd',      'ICD-10-CM Diagnosis'),
        ('cpt',      'CPT Procedures'),
        ('hcpcs',    'HCPCS & Modifiers'),
        ('cycle',    'Revenue Cycle'),
        ('payers',   'Insurance & Payers'),
        ('compliance','Compliance & Fraud'),
    ],
    terms=[
        # ── ICD-10-CM ────────────────────────────────────────────
        dict(term='ICD-10-CM', category='icd',
             meaning='The U.S. code set for reporting diagnoses and reasons for a visit.',
             detail='Clinical Modification of the WHO classification. Codes are three to seven characters, always starting with a letter.',
             example='E11.9 reports type 2 diabetes without complications.'),
        dict(term='Alphabetic Index', category='icd',
             meaning='The index that points a coder to a candidate diagnosis code.',
             detail='Never the final answer. The code must be verified in the tabular list, where exclusions and required detail appear.',
             example='A coder looks up "fracture, femur" in the index, then confirms in the tabular list.'),
        dict(term='Tabular List', category='icd',
             meaning='The numeric listing where a diagnosis code is verified before use.',
             detail='Carries instructional notes, exclusions and character requirements that the index does not show.',
             example='The tabular list reveals a required seventh character for the encounter type.'),
        dict(term='Seventh Character', category='icd',
             meaning='A final character on injury and some obstetric codes indicating the encounter type.',
             detail='A is initial encounter, D is subsequent, S is sequela. A placeholder X fills empty positions so it lands in position seven.',
             example='S52.501A reports an initial encounter for a right radius fracture.'),
        dict(term='Placeholder X', category='icd',
             meaning='A filler character holding an empty position so later characters keep their place.',
             detail='Required when a code needs a seventh character but has fewer than six of its own.',
             example='T36.0X5A uses X to reach the seventh character.'),
        dict(term='Laterality', category='icd',
             meaning='The coded side of the body a condition affects.',
             detail='ICD-10-CM distinguishes right, left, bilateral and unspecified. Unspecified is usually a claim-quality problem.',
             example='H25.11 reports an age-related cataract of the right eye.'),
        dict(term='Principal Diagnosis', category='icd',
             meaning='The condition chiefly responsible for an inpatient admission, established after study.',
             detail='Determines the DRG and therefore the payment. Distinct from the first-listed diagnosis used in outpatient coding.',
             example='Chest pain on arrival that proves to be an MI makes the MI the principal diagnosis.'),
        dict(term='Comorbidity', category='icd',
             meaning='A pre-existing condition that affects the care given during an episode.',
             detail='Reported alongside the principal diagnosis. Affects severity scoring and reimbursement.',
             example='Diabetes coded alongside a surgical admission.'),
        dict(term='Sequela', category='icd',
             meaning='A residual condition remaining after the acute phase of an illness or injury.',
             detail='Coded with the residual condition first, then the cause with seventh character S. No time limit applies.',
             example='Hemiplegia coded as a sequela of a prior stroke.'),
        dict(term='Z Code', category='icd',
             meaning='A code for an encounter that is not a current illness or injury.',
             detail='Covers screenings, well visits, status conditions, aftercare and exposure. Sometimes the only diagnosis reported.',
             example='Z00.00 reports a general adult medical examination without abnormal findings.'),
        dict(term='Excludes1 Note', category='icd',
             meaning='An instruction that two codes can never be reported together.',
             detail='Means "not coded here" — the conditions are mutually exclusive. Violating it is a common denial cause.',
             example='A congenital form and an acquired form of the same condition cannot both be coded.'),
        dict(term='Excludes2 Note', category='icd',
             meaning='An instruction that a condition is not included here but may be coded alongside.',
             detail='Means "not included here". Both codes may be reported together when both conditions are present.',
             example='Two related conditions are reported together under an Excludes2 note.'),
        dict(term='Code First', category='icd',
             meaning='An instruction to sequence an underlying condition before the manifestation.',
             detail='Etiology and manifestation pairs must appear in that order or the claim is rejected.',
             example='The underlying diabetes is coded before its retinal manifestation.'),
        dict(term='Specificity', category='icd',
             meaning='Coding to the highest level of detail the documentation supports.',
             detail='Reporting an unspecified code when detail exists is both a compliance risk and a common denial reason.',
             example='Coding the specific fracture site rather than "unspecified femur fracture".'),

        # ── CPT ──────────────────────────────────────────────────
        dict(term='CPT', category='cpt',
             meaning='The AMA code set reporting procedures and services performed.',
             detail='Current Procedural Terminology. Five-digit numeric codes, updated annually, forming HCPCS Level I.',
             example='99213 reports an established-patient office visit.'),
        dict(term='Category I Code', category='cpt',
             meaning='A five-digit CPT code for a widely performed, FDA-approved procedure.',
             detail='The main body of CPT, organized into six sections from Evaluation and Management through Medicine.',
             example='27447 reports a total knee arthroplasty.'),
        dict(term='Category II Code', category='cpt',
             meaning='An optional tracking code for performance measurement.',
             detail='Four digits followed by F. Carries no payment; used for quality reporting.',
             example='A Category II code records that blood pressure was documented.'),
        dict(term='Category III Code', category='cpt',
             meaning='A temporary code for an emerging technology or procedure.',
             detail='Four digits followed by T. Used while evidence accumulates; must be reported instead of an unlisted code when one exists.',
             example='A new device procedure is reported with a Category III code.'),
        dict(term='Evaluation and Management', category='cpt',
             meaning='The CPT section covering visits and consultations rather than procedures.',
             detail='Level is now selected by medical decision making or total time, rather than by counting history and exam elements.',
             example='A 30-minute established-patient visit selected on time.'),
        dict(term='Medical Decision Making', category='cpt',
             meaning='The complexity driving an E/M level, from the problems, data and risk involved.',
             detail='Four levels: straightforward, low, moderate, high. Two of the three elements must meet the level.',
             example='A new problem with prescription management supports moderate complexity.'),
        dict(term='Global Surgical Package', category='cpt',
             meaning='The services bundled into a surgery’s payment, including routine follow-up.',
             detail='Covers the operation, local anesthesia, and typical post-op care for 0, 10 or 90 days depending on the procedure.',
             example='A routine wound check after a 90-day global surgery is not billed separately.'),
        dict(term='Add-On Code', category='cpt',
             meaning='A code reported only alongside a primary procedure.',
             detail='Marked with a plus sign, never billed alone, and exempt from modifier 51.',
             example='An additional vertebral level reported with a spinal fusion.'),
        dict(term='Unlisted Procedure Code', category='cpt',
             meaning='A code used when no specific CPT code describes the service.',
             detail='Requires a report describing the work. Always the last resort, after checking Category III codes.',
             example='A novel technique with no assigned code is billed as unlisted with documentation.'),
        dict(term='Bundling', category='cpt',
             meaning='Payment for several related services under one code.',
             detail='Governed by National Correct Coding Initiative edits, which name code pairs that cannot be billed together.',
             example='A surgical approach is bundled into the main procedure.'),

        # ── HCPCS & Modifiers ────────────────────────────────────
        dict(term='HCPCS Level II', category='hcpcs',
             meaning='Codes for supplies, drugs, equipment and transport that CPT does not cover.',
             detail='One letter followed by four digits, maintained by CMS.',
             example='E0110 reports a pair of forearm crutches.'),
        dict(term='Modifier', category='hcpcs',
             meaning='A two-character suffix adding detail without changing the code’s meaning.',
             detail='Reports laterality, distinct service, reduced service or professional versus technical component. Wrong modifiers are a top denial cause.',
             example='A modifier shows a procedure was performed on the left side.'),
        dict(term='Modifier 25', category='hcpcs',
             meaning='A significant, separately identifiable E/M service on the same day as a procedure.',
             detail='Heavily audited. The visit must be documented as distinct work beyond the usual pre-procedure evaluation.',
             example='A full evaluation for a new problem on the day a minor procedure is performed.'),
        dict(term='Modifier 59', category='hcpcs',
             meaning='A distinct procedural service that would otherwise appear bundled.',
             detail='Used for a different session, site or encounter. The X modifiers are more specific replacements.',
             example='Two procedures at separate anatomic sites reported on the same day.'),
        dict(term='Modifier 51', category='hcpcs',
             meaning='Multiple procedures performed at the same session.',
             detail='Appended to the lower-valued procedures, which are typically paid at a reduced rate. Never used on add-on codes.',
             example='A second procedure in the same operative session.'),
        dict(term='Modifier 50', category='hcpcs',
             meaning='A bilateral procedure performed on both sides in one session.',
             detail='Reported once with the modifier rather than on two lines, unless the payer directs otherwise.',
             example='Bilateral carpal tunnel release reported on one line.'),
        dict(term='Modifiers 26 and TC', category='hcpcs',
             meaning='The professional component and the technical component of a service.',
             detail='26 is the physician’s interpretation; TC is the equipment and staff. Together they equal the global service.',
             example='A radiologist bills 26 while the imaging center bills TC.'),
        dict(term='Modifier 22', category='hcpcs',
             meaning='Increased procedural service beyond what the code normally describes.',
             detail='Requires documentation of the additional work and usually triggers manual review.',
             example='A procedure substantially complicated by extensive scarring.'),
        dict(term='NDC', category='hcpcs',
             meaning='The National Drug Code identifying a specific drug product.',
             detail='Eleven digits identifying labeler, product and package. Often required alongside a HCPCS J code.',
             example='An injected drug is billed with both a J code and its NDC.'),

        # ── Revenue Cycle ────────────────────────────────────────
        dict(term='Revenue Cycle', category='cycle',
             meaning='Every administrative step from scheduling a patient to collecting final payment.',
             detail='Registration, insurance verification, charge capture, coding, claim submission, adjudication, payment posting, collections.',
             example='A clinic tracks days in accounts receivable as a revenue cycle measure.'),
        dict(term='Charge Capture', category='cycle',
             meaning='Recording every billable service so nothing performed goes unbilled.',
             detail='Missed charges are lost revenue that no later step recovers.',
             example='A supply used in a procedure is logged at the point of care.'),
        dict(term='Superbill', category='cycle',
             meaning='An itemized form listing the services and diagnoses for one encounter.',
             detail='The source document that becomes the claim. Sometimes given to patients for out-of-network reimbursement.',
             example='A provider marks the visit level and diagnosis on the superbill.'),
        dict(term='CMS-1500', category='cycle',
             meaning='The standard paper claim form for professional and outpatient services.',
             detail='Its electronic equivalent is the 837P. Used by physicians and non-institutional providers.',
             example='A physician office submits a CMS-1500 for an office visit.'),
        dict(term='UB-04', category='cycle',
             meaning='The standard claim form used by institutional providers like hospitals.',
             detail='Also called CMS-1450; the electronic version is the 837I. Uses revenue codes alongside procedure codes.',
             example='A hospital submits a UB-04 for an inpatient stay.'),
        dict(term='Clean Claim', category='cycle',
             meaning='A claim with no errors that can be processed without additional information.',
             detail='Clean claim rate is a core revenue cycle metric, because every rework cycle costs money and delays payment.',
             example='A claim paid on first submission with no follow-up.'),
        dict(term='Adjudication', category='cycle',
             meaning='The payer’s process of deciding how much to pay on a claim.',
             detail='Checks eligibility, benefits, medical necessity and coding edits, then pays, reduces or denies.',
             example='A claim is adjudicated and paid at the contracted rate.'),
        dict(term='Explanation of Benefits', category='cycle',
             meaning='A statement to the patient explaining what the payer covered and what they owe.',
             detail='Not a bill. The provider’s equivalent is the remittance advice.',
             example='An EOB shows the allowed amount, plan payment and patient responsibility.'),
        dict(term='Remittance Advice', category='cycle',
             meaning='The payer’s explanation to the provider of payments and adjustments.',
             detail='Carries adjustment reason codes explaining every reduction. Posted against the patient account.',
             example='An 835 file posts payments automatically to the practice system.'),
        dict(term='Denial', category='cycle',
             meaning='A payer’s refusal to pay a claim as submitted.',
             detail='Common causes are eligibility, missing authorization, medical necessity, timely filing and coding errors. Many are appealable.',
             example='A claim is denied for lack of prior authorization.'),
        dict(term='Appeal', category='cycle',
             meaning='A formal request that a payer reconsider a denial.',
             detail='Must be filed within the payer’s deadline with supporting documentation. Levels escalate to external review.',
             example='A practice appeals a necessity denial with the physician’s notes.'),
        dict(term='Accounts Receivable', category='cycle',
             meaning='Money owed to a provider for services already delivered.',
             detail='Tracked by age. Balances over 90 days are much less likely to be collected.',
             example='A practice reviews its A/R aging report weekly.'),
        dict(term='Timely Filing Limit', category='cycle',
             meaning='The deadline for submitting a claim after the date of service.',
             detail='Ranges from 90 days to a year by payer. Missing it usually makes the balance unbillable to the patient too.',
             example='A claim submitted 200 days later is denied for timely filing.'),
        dict(term='Write-Off', category='cycle',
             meaning='A balance removed from a patient account and never collected.',
             detail='Contractual write-offs are the negotiated discount; adjustments for bad debt or charity are tracked separately.',
             example='The difference between charge and allowed amount is written off contractually.'),

        # ── Insurance & Payers ───────────────────────────────────
        dict(term='Premium', category='payers',
             meaning='The recurring amount paid to keep insurance coverage in force.',
             detail='Paid regardless of whether care is used, usually monthly and often shared with an employer.',
             example='An employee pays part of a monthly premium through payroll deduction.'),
        dict(term='Deductible', category='payers',
             meaning='The amount a patient pays each year before the plan begins paying.',
             detail='Resets annually. Preventive services are often exempt.',
             example='A patient with a $2,000 deductible pays the first $2,000 of covered care.'),
        dict(term='Copayment', category='payers',
             meaning='A fixed amount a patient pays for a specific service.',
             detail='Collected at the time of service and usually independent of the deductible.',
             example='A $30 copay for a specialist visit.'),
        dict(term='Coinsurance', category='payers',
             meaning='A percentage of the allowed amount the patient pays after the deductible.',
             detail='Continues until the out-of-pocket maximum is reached.',
             example='An 80/20 plan leaves the patient 20 percent of the allowed amount.'),
        dict(term='Out-of-Pocket Maximum', category='payers',
             meaning='The annual ceiling on what a patient pays for covered in-network care.',
             detail='Once reached, the plan pays 100 percent of covered services for the rest of the year. Premiums do not count toward it.',
             example='After reaching the maximum, further covered visits cost the patient nothing.'),
        dict(term='Allowed Amount', category='payers',
             meaning='The maximum a payer will recognize for a service under its contract.',
             detail='Payment and patient responsibility are both calculated from it, not from the billed charge.',
             example='A $300 charge with a $180 allowed amount yields a $120 contractual write-off.'),
        dict(term='Prior Authorization', category='payers',
             meaning='Payer approval obtained before a service is delivered.',
             detail='Required for many imaging studies, surgeries and drugs. Missing it is one of the most preventable denials.',
             example='An MRI is authorized before it is scheduled.'),
        dict(term='Medical Necessity', category='payers',
             meaning='The requirement that a service be appropriate for the diagnosis reported.',
             detail='The link between the ICD-10-CM code and the CPT code. Without it, even a correctly coded claim is denied.',
             example='A payer denies a scan because the diagnosis does not support it.'),
        dict(term='Medicare', category='payers',
             meaning='The federal program covering people 65 and older and some with disabilities.',
             detail='Part A hospital, Part B medical, Part C Advantage plans, Part D drugs.',
             example='An inpatient stay is billed to Medicare Part A.'),
        dict(term='Medicaid', category='payers',
             meaning='A joint federal and state program covering low-income individuals and families.',
             detail='Eligibility and benefits vary by state. Always the payer of last resort when other coverage exists.',
             example='A state Medicaid program covers a child’s well visits.'),
        dict(term='Coordination of Benefits', category='payers',
             meaning='Rules deciding which plan pays first when a patient has more than one.',
             detail='The primary plan pays to its limit, then the secondary considers the balance. Total payment cannot exceed the allowed amount.',
             example='A child covered by both parents is sequenced by the birthday rule.'),
        dict(term='Capitation', category='payers',
             meaning='A fixed payment per enrolled patient per month regardless of services used.',
             detail='Shifts financial risk to the provider and rewards prevention.',
             example='A group receives a set amount per member per month.'),
        dict(term='Fee-for-Service', category='payers',
             meaning='Payment for each individual service delivered.',
             detail='Rewards volume, which is why payers have shifted toward value-based and bundled arrangements.',
             example='Each office visit and test generates a separate charge.'),

        # ── Compliance & Fraud ───────────────────────────────────
        dict(term='Upcoding', category='compliance',
             meaning='Reporting a higher-paying code than the documentation supports.',
             detail='Fraud when done knowingly. Detected by comparing a provider’s code distribution to peers.',
             example='Billing a high-complexity visit for a brief problem-focused encounter.'),
        dict(term='Unbundling', category='compliance',
             meaning='Billing separately for services that should be reported under one code.',
             detail='Blocked by Correct Coding Initiative edits; deliberate unbundling is fraud.',
             example='Billing each component of a panel that has a single code.'),
        dict(term='Fraud vs Abuse', category='compliance',
             meaning='Fraud is knowing deception for gain; abuse is practice inconsistent with sound standards.',
             detail='Intent separates them. Both can carry repayment, penalties and exclusion.',
             example='Billing for a service never provided is fraud; routinely over-ordering tests may be abuse.'),
        dict(term='False Claims Act', category='compliance',
             meaning='The federal law imposing penalties for knowingly submitting false claims.',
             detail='Allows whistleblower suits with a share of recovery, and treble damages plus per-claim penalties.',
             example='A practice repays multiples of the amount falsely billed.'),
        dict(term='Anti-Kickback Statute', category='compliance',
             meaning='A law barring payment in exchange for referrals of federally funded care.',
             detail='Criminal statute requiring intent, with safe harbors for legitimate arrangements.',
             example='Paying a physician for each patient sent to an imaging center.'),
        dict(term='Stark Law', category='compliance',
             meaning='A law prohibiting physician referrals to entities they have a financial interest in.',
             detail='Strict liability for designated health services — intent is irrelevant.',
             example='Referring to a lab the physician partly owns, absent an exception.'),
        dict(term='HIPAA', category='compliance',
             meaning='The law protecting the privacy and security of health information.',
             detail='Also standardized electronic transactions. Coders and billers see PHI constantly and are bound by the minimum necessary rule.',
             example='A biller accesses only the records needed to work a claim.'),
        dict(term='Minimum Necessary Standard', category='compliance',
             meaning='The rule that only the least information needed for a task may be used or disclosed.',
             detail='Does not apply to treatment between providers, but does apply to billing and operations.',
             example='A claim includes only the codes needed, not the full chart.'),
        dict(term='Compliance Program', category='compliance',
             meaning='An organization’s system for preventing and detecting billing violations.',
             detail='Seven elements: standards, oversight, training, communication, auditing, enforcement and corrective action.',
             example='A clinic audits a sample of coded charts each quarter.'),
        dict(term='Audit Trail', category='compliance',
             meaning='A record of who accessed or changed information and when.',
             detail='Required by HIPAA security rules and used to investigate inappropriate access.',
             example='An audit log shows a staff member opened a record with no treatment relationship.'),
        dict(term='Advance Beneficiary Notice', category='compliance',
             meaning='A Medicare notice telling a patient a service may not be covered.',
             detail='Signed before the service, it makes the patient financially responsible. Without it the provider absorbs the cost.',
             example='A patient signs an ABN before a screening Medicare may not cover.'),
    ],
))


# ═══════════════════════════════════════════════════════════════════
#  Biostatistics & Research Methods
# ═══════════════════════════════════════════════════════════════════
SPECS.append(dict(
    slug='biostatistics-research',
    name='Biostatistics & Research',
    eyebrow='Health Science — Biostatistics & Research Methods',
    h1_lead='Evidence, Data &',
    h1_em='Research Methods',
    subtitle='A study companion for study design, sampling, descriptive and inferential statistics, '
             'diagnostic testing and research ethics — built for HOSA competitors and students '
             'reading medical literature.',
    test_blurb='biostatistics and research-design concepts',
    topics='Study designs, sampling, bias, descriptive statistics, hypothesis testing, diagnostic accuracy, research ethics',
    tips=[
        'Learn the evidence hierarchy in order. A question about "strongest evidence" is almost always answered by systematic review or RCT.',
        'Randomization controls confounding, blinding controls measurement bias. Know which problem each one solves.',
        'A p-value tells you about compatibility with the null hypothesis, not about effect size or importance.',
        'Sensitivity rules disease OUT when negative; specificity rules it IN when positive. SnNout and SpPin.',
        'Predictive values depend on prevalence. Sensitivity and specificity do not.',
        'Correlation is not causation. Look for temporality, dose-response and biological plausibility before believing a causal claim.',
    ],
    categories=[
        ('design',   'Study Design'),
        ('sampling', 'Sampling & Bias'),
        ('descript', 'Descriptive Statistics'),
        ('inference','Inference & Testing'),
        ('diagnos',  'Diagnostic Accuracy'),
        ('ethics',   'Research Ethics'),
    ],
    terms=[
        # ── Study Design ─────────────────────────────────────────
        dict(term='Hierarchy of Evidence', category='design',
             meaning='The ranking of study designs by how well they support causal claims.',
             detail='Systematic reviews and meta-analyses, then randomized trials, cohort, case-control, cross-sectional, case series, expert opinion.',
             example='A guideline cites a meta-analysis over a single observational study.'),
        dict(term='Randomized Controlled Trial', category='design',
             meaning='An experiment assigning participants to treatment or control by chance.',
             detail='The strongest single-study design for causation, because randomization balances known and unknown confounders.',
             example='Patients are randomized to a new drug or placebo.'),
        dict(term='Cohort Study', category='design',
             meaning='An observational study following exposed and unexposed groups forward for outcomes.',
             detail='Can be prospective or retrospective. Yields incidence and relative risk, but is costly and slow for rare outcomes.',
             example='Smokers and non-smokers are followed for twenty years.'),
        dict(term='Case-Control Study', category='design',
             meaning='An observational study comparing people with a disease to those without, looking backward at exposure.',
             detail='Efficient for rare diseases and yields an odds ratio. Vulnerable to recall and selection bias.',
             example='People with a rare cancer are compared with matched controls.'),
        dict(term='Cross-Sectional Study', category='design',
             meaning='A study measuring exposure and outcome at the same moment.',
             detail='Gives prevalence and is quick and cheap, but cannot establish which came first.',
             example='A one-time survey of blood pressure and exercise habits.'),
        dict(term='Systematic Review', category='design',
             meaning='A structured synthesis of all studies meeting pre-set criteria on a question.',
             detail='Defines the search, inclusion criteria and quality appraisal in advance, which is what separates it from a narrative review.',
             example='A review pools every trial of a drug for one indication.'),
        dict(term='Meta-Analysis', category='design',
             meaning='A statistical combination of results from multiple studies into one estimate.',
             detail='Increases precision but inherits the flaws of its inputs. Heterogeneity must be assessed before pooling.',
             example='A forest plot shows each trial and the pooled effect.'),
        dict(term='Crossover Trial', category='design',
             meaning='A trial in which each participant receives both treatments in sequence.',
             detail='Each person is their own control, which reduces variability. Needs a washout period and a stable condition.',
             example='Participants take drug A for six weeks, wash out, then take drug B.'),
        dict(term='Placebo', category='design',
             meaning='An inactive treatment given so participants cannot tell which group they are in.',
             detail='Controls for the placebo effect and for the natural course of illness.',
             example='A control group receives an identical-looking inactive tablet.'),
        dict(term='Blinding', category='design',
             meaning='Keeping participants, investigators or assessors unaware of group assignment.',
             detail='Single, double or triple. Prevents expectation from shaping either behavior or measurement.',
             example='Neither the patient nor the physician knows which tablet was given.'),
        dict(term='Intention-to-Treat Analysis', category='design',
             meaning='Analyzing participants in the group they were assigned to, regardless of what they did.',
             detail='Preserves randomization and gives a realistic estimate of effectiveness in practice.',
             example='Participants who stopped the drug are still counted in the treatment group.'),
        dict(term='Control Group', category='design',
             meaning='The comparison group that does not receive the intervention under study.',
             detail='Without one, improvement cannot be separated from natural recovery or regression to the mean.',
             example='A trial compares a new therapy with standard care.'),

        # ── Sampling & Bias ──────────────────────────────────────
        dict(term='Population vs Sample', category='sampling',
             meaning='The population is everyone of interest; the sample is the subset actually studied.',
             detail='Statistics describe the sample and are used to infer about the population.',
             example='500 surveyed students represent a district of 12,000.'),
        dict(term='Simple Random Sample', category='sampling',
             meaning='A sample in which every member of the population has an equal chance of selection.',
             detail='The benchmark for representativeness, but often impractical without a complete list.',
             example='Names drawn at random from a full enrollment roster.'),
        dict(term='Stratified Sampling', category='sampling',
             meaning='Dividing a population into subgroups and sampling within each.',
             detail='Guarantees representation of small subgroups that simple random sampling might miss.',
             example='Sampling separately from each grade level.'),
        dict(term='Convenience Sampling', category='sampling',
             meaning='Sampling whoever is easiest to reach.',
             detail='Fast and cheap but rarely representative, so findings generalize poorly.',
             example='Surveying students in one class because it was available.'),
        dict(term='Selection Bias', category='sampling',
             meaning='Systematic error from how participants entered the study.',
             detail='Makes the sample unrepresentative, so results do not apply to the intended population.',
             example='Recruiting only from a specialty clinic overstates severity.'),
        dict(term='Recall Bias', category='sampling',
             meaning='Systematic error from differences in how accurately groups remember the past.',
             detail='Especially problematic in case-control studies, where people with disease search their memory harder.',
             example='Parents of ill children recall exposures more thoroughly than controls.'),
        dict(term='Observer Bias', category='sampling',
             meaning='Systematic error introduced by an investigator’s expectations.',
             detail='Controlled by blinding outcome assessors and using objective measures.',
             example='A researcher expecting improvement scores ambiguous findings favorably.'),
        dict(term='Confounding', category='sampling',
             meaning='Distortion of an association by a third factor related to both exposure and outcome.',
             detail='Addressed by randomization, restriction, matching, stratification or multivariable adjustment.',
             example='Age confounds a link between gray hair and heart disease.'),
        dict(term='Effect Modification', category='sampling',
             meaning='When the size of an effect genuinely differs across levels of another variable.',
             detail='Unlike confounding, this is a real finding to report, not a bias to remove.',
             example='A drug works well in younger patients and poorly in older ones.'),
        dict(term='Attrition Bias', category='sampling',
             meaning='Systematic error from participants dropping out unevenly across groups.',
             detail='Differential loss breaks the comparability randomization created.',
             example='Side effects cause more dropouts in the treatment arm.'),
        dict(term='Sample Size and Power', category='sampling',
             meaning='Power is the probability of detecting a real effect, and it rises with sample size.',
             detail='Conventionally set at 80 percent. Underpowered studies miss true effects and produce unstable estimates.',
             example='A trial is sized to detect a 10 percent difference with 80 percent power.'),

        # ── Descriptive Statistics ───────────────────────────────
        dict(term='Mean', category='descript',
             meaning='The arithmetic average of a set of values.',
             detail='Uses every value, so it is sensitive to outliers and skew. Best for symmetric distributions.',
             example='Average length of stay across all admissions.'),
        dict(term='Median', category='descript',
             meaning='The middle value when observations are ordered.',
             detail='Resistant to outliers, which makes it the better summary for skewed data like income or length of stay.',
             example='Median wait time is reported because a few long waits skew the mean.'),
        dict(term='Mode', category='descript',
             meaning='The most frequently occurring value.',
             detail='The only measure of central tendency usable with categorical data.',
             example='The most common blood type in a sample.'),
        dict(term='Standard Deviation', category='descript',
             meaning='A measure of how far values typically fall from the mean.',
             detail='In a normal distribution about 68 percent of values lie within one, 95 within two, 99.7 within three.',
             example='A small standard deviation means results cluster tightly.'),
        dict(term='Range and Interquartile Range', category='descript',
             meaning='The range is max minus min; the IQR is the middle 50 percent of values.',
             detail='IQR resists outliers and is what a box plot displays as the box.',
             example='A box plot shows the IQR with whiskers to the extremes.'),
        dict(term='Normal Distribution', category='descript',
             meaning='A symmetric bell-shaped distribution where mean, median and mode coincide.',
             detail='Underpins many statistical tests. Real biological data often approximate it.',
             example='Adult height follows an approximately normal distribution.'),
        dict(term='Skew', category='descript',
             meaning='Asymmetry in a distribution, with a tail extending to one side.',
             detail='Right skew pulls the mean above the median; left skew pulls it below.',
             example='Hospital costs are right-skewed by a few very expensive stays.'),
        dict(term='Incidence', category='descript',
             meaning='The rate of new cases arising in a population over a period.',
             detail='Measures risk of developing disease, which is what a cohort study estimates.',
             example='New diabetes diagnoses per 1,000 people per year.'),
        dict(term='Prevalence', category='descript',
             meaning='The proportion of a population that has a condition at a point in time.',
             detail='Reflects both incidence and duration, so a long-lasting disease accumulates prevalence.',
             example='The share of adults currently living with asthma.'),
        dict(term='Relative Risk', category='descript',
             meaning='The ratio of risk in the exposed group to risk in the unexposed.',
             detail='Calculated from cohort studies and trials. A value of 1 means no association.',
             example='A relative risk of 2.0 means twice the risk among the exposed.'),
        dict(term='Odds Ratio', category='descript',
             meaning='The ratio of the odds of exposure among cases to the odds among controls.',
             detail='The measure available from case-control studies. Approximates relative risk when the outcome is rare.',
             example='An odds ratio of 3.0 in a case-control study of a rare cancer.'),
        dict(term='Number Needed to Treat', category='descript',
             meaning='How many patients must be treated for one to benefit.',
             detail='The reciprocal of the absolute risk reduction. Translates a trial result into something clinically meaningful.',
             example='A 5 percent absolute reduction gives an NNT of 20.'),
        dict(term='Absolute vs Relative Risk Reduction', category='descript',
             meaning='Absolute is the difference in risk; relative is that difference as a proportion of baseline.',
             detail='Relative reduction sounds larger and is often quoted for that reason. Absolute reflects real benefit.',
             example='2 percent to 1 percent is a 1 point absolute but 50 percent relative reduction.'),

        # ── Inference & Testing ──────────────────────────────────
        dict(term='Null Hypothesis', category='inference',
             meaning='The default claim that there is no difference or no association.',
             detail='Statistical tests assess evidence against it. It is rejected or not rejected, never proven.',
             example='The null states the new drug works no better than placebo.'),
        dict(term='P-Value', category='inference',
             meaning='The probability of a result at least this extreme if the null hypothesis were true.',
             detail='Not the probability the hypothesis is true, and not a measure of effect size or importance.',
             example='p = 0.03 means such a result would be uncommon under the null.'),
        dict(term='Statistical Significance', category='inference',
             meaning='A result whose p-value falls below a threshold chosen in advance, usually 0.05.',
             detail='An arbitrary convention. Statistically significant is not the same as clinically meaningful.',
             example='A tiny difference can be significant in a very large study.'),
        dict(term='Confidence Interval', category='inference',
             meaning='A range of values consistent with the data at a stated confidence level.',
             detail='More informative than a p-value because it shows both the estimate and its precision.',
             example='A relative risk of 1.8 with an interval from 1.2 to 2.7.'),
        dict(term='Type I Error', category='inference',
             meaning='Rejecting a null hypothesis that is actually true — a false positive.',
             detail='Its probability is alpha, conventionally 0.05. Multiple comparisons inflate it.',
             example='Concluding a drug works when it does not.'),
        dict(term='Type II Error', category='inference',
             meaning='Failing to reject a null hypothesis that is actually false — a false negative.',
             detail='Its probability is beta; power is 1 minus beta. Usually caused by too small a sample.',
             example='Missing a real benefit because the trial was too small.'),
        dict(term='T-Test', category='inference',
             meaning='A test comparing the means of two groups.',
             detail='Paired for matched observations, unpaired for independent groups. Assumes roughly normal data.',
             example='Comparing average blood pressure between two treatment arms.'),
        dict(term='ANOVA', category='inference',
             meaning='A test comparing means across three or more groups.',
             detail='Analysis of variance. A significant result says at least one group differs, so post-hoc tests identify which.',
             example='Comparing outcomes across three dose levels.'),
        dict(term='Chi-Square Test', category='inference',
             meaning='A test of association between categorical variables.',
             detail='Compares observed counts with those expected under independence. Needs adequate expected cell counts.',
             example='Testing whether recovery differs by treatment group.'),
        dict(term='Correlation Coefficient', category='inference',
             meaning='A number from -1 to +1 describing the strength and direction of a linear relationship.',
             detail='Measures association only. A strong correlation never establishes causation by itself.',
             example='A coefficient of 0.85 between height and weight.'),
        dict(term='Regression Analysis', category='inference',
             meaning='A model estimating how an outcome changes with one or more predictors.',
             detail='Multivariable regression adjusts for confounders. Logistic regression handles binary outcomes.',
             example='Predicting blood pressure from age, weight and sodium intake.'),
        dict(term='Bradford Hill Criteria', category='inference',
             meaning='Considerations used to judge whether an association is likely causal.',
             detail='Strength, consistency, specificity, temporality, dose-response, plausibility, coherence, experiment, analogy. Temporality is the only requirement.',
             example='A dose-response gradient strengthens a causal argument.'),

        # ── Diagnostic Accuracy ──────────────────────────────────
        dict(term='Sensitivity', category='diagnos',
             meaning='The proportion of people with a disease that a test correctly identifies.',
             detail='A highly sensitive test has few false negatives, so a negative result rules disease out.',
             example='A screening test detects 95 of 100 true cases.'),
        dict(term='Specificity', category='diagnos',
             meaning='The proportion of people without a disease that a test correctly clears.',
             detail='A highly specific test has few false positives, so a positive result rules disease in.',
             example='A confirmatory test correctly clears 99 of 100 healthy people.'),
        dict(term='SnNout and SpPin', category='diagnos',
             meaning='A sensitive test with a negative result rules out; a specific test with a positive rules in.',
             detail='The standard mnemonic for choosing between screening and confirmatory tests.',
             example='A negative high-sensitivity screen effectively excludes the condition.'),
        dict(term='Positive Predictive Value', category='diagnos',
             meaning='The probability that someone with a positive test truly has the disease.',
             detail='Depends heavily on prevalence. The same test has a low PPV in a low-prevalence population.',
             example='In rare disease screening, most positives are false positives.'),
        dict(term='Negative Predictive Value', category='diagnos',
             meaning='The probability that someone with a negative test truly lacks the disease.',
             detail='Also prevalence-dependent, and highest when the disease is uncommon.',
             example='A negative result in a low-risk population is highly reassuring.'),
        dict(term='False Positive', category='diagnos',
             meaning='A positive test result in someone who does not have the condition.',
             detail='Causes anxiety, cost and unnecessary follow-up. More common when prevalence is low.',
             example='An abnormal screen that a biopsy later clears.'),
        dict(term='False Negative', category='diagnos',
             meaning='A negative test result in someone who does have the condition.',
             detail='More dangerous than a false positive because it produces false reassurance and delays care.',
             example='A missed case on an insensitive screening test.'),
        dict(term='ROC Curve', category='diagnos',
             meaning='A plot of sensitivity against the false positive rate across every possible cutoff.',
             detail='The area under it summarizes discrimination, from 0.5 for chance to 1.0 for perfect.',
             example='An AUC of 0.92 indicates strong discrimination.'),
        dict(term='Screening vs Diagnostic Test', category='diagnos',
             meaning='Screening finds disease in people without symptoms; diagnosis confirms it in those suspected.',
             detail='Screening favors sensitivity and low cost; diagnosis favors specificity and accuracy.',
             example='A mammogram screens; a biopsy diagnoses.'),
        dict(term='Lead-Time Bias', category='diagnos',
             meaning='Apparent longer survival caused only by diagnosing earlier, not by living longer.',
             detail='Makes screening look effective when it is not. Controlled by comparing mortality rather than survival time.',
             example='Earlier detection lengthens measured survival without delaying death.'),
        dict(term='Reliability vs Validity', category='diagnos',
             meaning='Reliability is consistency on repetition; validity is measuring the right thing.',
             detail='A measure can be reliably wrong. Validity requires reliability but not the reverse.',
             example='A scale consistently 5 pounds heavy is reliable but not valid.'),

        # ── Research Ethics ──────────────────────────────────────
        dict(term='Informed Consent', category='ethics',
             meaning='A participant’s voluntary agreement after understanding a study’s risks and benefits.',
             detail='Requires disclosure, comprehension and voluntariness, and the right to withdraw at any time.',
             example='A participant signs after the procedures and risks are explained.'),
        dict(term='Institutional Review Board', category='ethics',
             meaning='A committee that reviews research involving humans before it begins.',
             detail='Weighs risk against benefit, checks consent, and protects vulnerable groups. Approval is required before enrollment.',
             example='A protocol is approved by the IRB before recruiting.'),
        dict(term='Belmont Report', category='ethics',
             meaning='The 1979 report establishing respect for persons, beneficence and justice.',
             detail='Written after the Tuskegee study and the foundation of U.S. human-subjects regulation.',
             example='Fair subject selection follows the justice principle.'),
        dict(term='Vulnerable Populations', category='ethics',
             meaning='Groups needing extra protection because their consent may be compromised.',
             detail='Children, prisoners, pregnant people, people with cognitive impairment and economically disadvantaged groups.',
             example='A study enrolling minors requires parental permission and child assent.'),
        dict(term='Equipoise', category='ethics',
             meaning='Genuine uncertainty about which trial arm is better.',
             detail='The ethical precondition for randomization. If one treatment is known to be superior, randomizing is unjustifiable.',
             example='A trial stops early when one arm proves clearly better.'),
        dict(term='Data Safety Monitoring Board', category='ethics',
             meaning='An independent group reviewing accumulating trial data for harm or clear benefit.',
             detail='Can recommend stopping a trial early for safety, futility or overwhelming efficacy.',
             example='A board halts a trial after excess adverse events.'),
        dict(term='Conflict of Interest', category='ethics',
             meaning='A financial or personal interest that could bias research conduct or reporting.',
             detail='Managed by disclosure, independent analysis, and sometimes recusal.',
             example='An author discloses funding from the drug’s manufacturer.'),
        dict(term='Publication Bias', category='ethics',
             meaning='The tendency for positive results to be published more often than negative ones.',
             detail='Distorts meta-analyses toward benefit. Trial registration exists to counter it.',
             example='A funnel plot reveals missing small negative studies.'),
        dict(term='Clinical Trial Phases', category='ethics',
             meaning='Phase I safety, Phase II efficacy, Phase III comparison, Phase IV post-marketing.',
             detail='Sample size grows with each phase. Phase IV detects rare harms only visible in large populations.',
             example='A drug reaches Phase III to compare against standard care.'),
    ],
))
