# -*- coding: utf-8 -*-
"""Event content, batch E."""

SPECS = []

# ═══════════════════════════════════════════════════════════════════
#  Exercise Physiology
# ═══════════════════════════════════════════════════════════════════
SPECS.append(dict(
    slug='exercise-physiology',
    name='Exercise Physiology',
    eyebrow='Health Science — Exercise Physiology',
    h1_lead='Energy Systems &',
    h1_em='Exercise Physiology',
    subtitle='A study companion for energy systems, muscle physiology, cardiorespiratory response, '
             'training principles and exercise testing — built for HOSA competitors in athletic '
             'training and health science pathways.',
    test_blurb='exercise physiology and training concepts',
    topics='ATP energy systems, muscle fiber types, cardiorespiratory response, training principles, testing, environment and nutrition',
    tips=[
        'Learn the three energy systems by duration: phosphagen for seconds, glycolytic for up to about two minutes, oxidative beyond that.',
        'VO2 max is the single best measure of aerobic fitness. Know how it is measured and what raises it.',
        'Type I fibers are slow, aerobic and fatigue-resistant; Type II are fast, glycolytic and powerful.',
        'Cardiac output equals heart rate times stroke volume. Almost every cardiovascular question comes back to that equation.',
        'The FITT principle and progressive overload structure most programming questions.',
        'Know the ACSM adult guideline: 150 minutes of moderate or 75 of vigorous activity a week, plus two resistance sessions.',
    ],
    categories=[
        ('energy',   'Energy Systems'),
        ('muscle',   'Muscle Physiology'),
        ('cardio',   'Cardiorespiratory'),
        ('training', 'Training Principles'),
        ('testing',  'Assessment & Testing'),
        ('applied',  'Environment & Nutrition'),
    ],
    terms=[
        # ── Energy Systems ───────────────────────────────────────
        dict(term='ATP', category='energy',
             meaning='The molecule cells break down to release energy for contraction.',
             detail='Stores in muscle last only a few seconds, so all three energy systems exist to resynthesize it.',
             example='Splitting ATP to ADP powers the myosin cross-bridge.'),
        dict(term='Phosphagen System', category='energy',
             meaning='The immediate energy system using stored ATP and creatine phosphate.',
             detail='Dominant for roughly the first 10 seconds. No oxygen and no lactate, but a very small capacity.',
             example='A maximal sprint start runs on the phosphagen system.'),
        dict(term='Creatine Phosphate', category='energy',
             meaning='A stored compound that rapidly rebuilds ATP from ADP.',
             detail='Depleted within seconds of maximal effort and restored in a few minutes of rest.',
             example='Recovery between heavy sets restores creatine phosphate.'),
        dict(term='Glycolysis', category='energy',
             meaning='The breakdown of glucose to pyruvate in the cytosol, producing ATP without oxygen.',
             detail='Fast but inefficient — two ATP per glucose. Dominant for efforts of about 30 seconds to two minutes.',
             example='A 400-metre run relies heavily on glycolysis.'),
        dict(term='Lactate', category='energy',
             meaning='A product of rapid glycolysis that can be reused as fuel.',
             detail='Not the cause of muscle soreness. It is shuttled to the heart, liver and other muscle and oxidized.',
             example='Blood lactate rises sharply during hard intervals.'),
        dict(term='Lactate Threshold', category='energy',
             meaning='The intensity at which lactate begins accumulating faster than it is cleared.',
             detail='A better predictor of endurance performance than VO2 max, and highly trainable.',
             example='Trained runners hold a higher pace before lactate climbs.'),
        dict(term='Oxidative System', category='energy',
             meaning='The aerobic system producing ATP from carbohydrate and fat using oxygen.',
             detail='Slow to ramp up but nearly unlimited in capacity, and dominant beyond about two minutes.',
             example='A marathon is fuelled almost entirely aerobically.'),
        dict(term='Krebs Cycle', category='energy',
             meaning='The mitochondrial cycle oxidizing acetyl-CoA to produce NADH and FADH2.',
             detail='Feeds the electron transport chain, where most ATP is actually generated.',
             example='Acetyl-CoA from fat and carbohydrate enters the Krebs cycle.'),
        dict(term='Electron Transport Chain', category='energy',
             meaning='The inner-membrane chain that uses electrons to generate most cellular ATP.',
             detail='Oxygen is the final electron acceptor, which is why aerobic capacity limits sustained work.',
             example='Roughly 34 ATP per glucose come from this stage.'),
        dict(term='EPOC', category='energy',
             meaning='Elevated oxygen consumption after exercise, above resting levels.',
             detail='Excess post-exercise oxygen consumption, formerly called oxygen debt. Restores phosphagens and clears metabolites.',
             example='Breathing stays elevated for minutes after hard intervals.'),
        dict(term='Respiratory Exchange Ratio', category='energy',
             meaning='The ratio of carbon dioxide produced to oxygen consumed, showing which fuel is burning.',
             detail='About 0.70 for pure fat and 1.00 for pure carbohydrate. Rises with intensity.',
             example='An RER near 1.0 indicates carbohydrate is the main fuel.'),

        # ── Muscle Physiology ────────────────────────────────────
        dict(term='Sliding Filament Theory', category='muscle',
             meaning='The model in which actin slides over myosin to shorten the sarcomere.',
             detail='Filaments do not shorten themselves; the overlap increases. Requires ATP and calcium.',
             example='The sarcomere shortens while filament lengths stay the same.'),
        dict(term='Excitation-Contraction Coupling', category='muscle',
             meaning='The sequence linking a nerve impulse to calcium release and contraction.',
             detail='The action potential travels T-tubules, the sarcoplasmic reticulum releases calcium, and troponin exposes binding sites.',
             example='Calcium release lets myosin bind actin.'),
        dict(term='Motor Unit', category='muscle',
             meaning='One motor neuron and every muscle fiber it controls.',
             detail='Small units allow fine control; large ones produce force. Recruited smallest first under the size principle.',
             example='Eye muscles have very small motor units.'),
        dict(term='Type I Fiber', category='muscle',
             meaning='A slow-twitch fiber that is aerobic and highly fatigue-resistant.',
             detail='Rich in mitochondria, capillaries and myoglobin, which gives it a red appearance.',
             example='Postural muscles are dominated by Type I fibers.'),
        dict(term='Type II Fiber', category='muscle',
             meaning='A fast-twitch fiber producing high force but fatiguing quickly.',
             detail='Type IIa is intermediate and somewhat oxidative; Type IIx is the most powerful and least fatigue-resistant.',
             example='Sprinters carry a high proportion of Type II fibers.'),
        dict(term='Muscle Hypertrophy', category='muscle',
             meaning='An increase in muscle size from enlargement of existing fibers.',
             detail='Driven by mechanical tension, metabolic stress and muscle damage, plus adequate protein and recovery.',
             example='Progressive resistance training thickens muscle fibers.'),
        dict(term='Muscle Atrophy', category='muscle',
             meaning='Loss of muscle size from disuse, ageing or illness.',
             detail='Begins within days of immobilization. Even minimal loading slows it substantially.',
             example='A limb in a cast loses measurable size in two weeks.'),
        dict(term='Concentric Contraction', category='muscle',
             meaning='A contraction in which the muscle shortens while producing force.',
             detail='The lifting phase of a movement. Produces less force than eccentric at the same speed.',
             example='The upward phase of a biceps curl.'),
        dict(term='Eccentric Contraction', category='muscle',
             meaning='A contraction in which the muscle lengthens under load.',
             detail='Produces the most force and the most muscle damage, and drives delayed onset soreness.',
             example='Lowering a weight slowly under control.'),
        dict(term='Isometric Contraction', category='muscle',
             meaning='A contraction producing force with no change in muscle length.',
             detail='Useful where movement is limited, but strength gains are specific to the joint angle trained.',
             example='Holding a plank position.'),
        dict(term='Delayed Onset Muscle Soreness', category='muscle',
             meaning='Muscle pain peaking 24 to 72 hours after unfamiliar exercise.',
             detail='Caused by microscopic damage and inflammation, mostly from eccentric work. Not caused by lactate.',
             example='Soreness peaks two days after a first heavy session.'),
        dict(term='Rate Coding', category='muscle',
             meaning='Increasing force by firing motor units more frequently.',
             detail='Works alongside recruitment. Much of early strength gain is neural rather than structural.',
             example='Strength rises in the first weeks before muscles visibly grow.'),

        # ── Cardiorespiratory ────────────────────────────────────
        dict(term='Cardiac Output', category='cardio',
             meaning='The volume of blood the heart pumps per minute.',
             detail='Heart rate times stroke volume. Rises several-fold from rest to maximal exercise.',
             example='70 bpm times 70 mL gives about 4.9 L per minute at rest.'),
        dict(term='Stroke Volume', category='cardio',
             meaning='The volume of blood ejected by the left ventricle each beat.',
             detail='Determined by preload, afterload and contractility. Endurance training raises it markedly.',
             example='A trained athlete has a much larger resting stroke volume.'),
        dict(term='VO2 Max', category='cardio',
             meaning='The maximum rate at which the body can use oxygen during exercise.',
             detail='Expressed in mL per kg per minute. The standard measure of aerobic capacity, limited mainly by cardiac output.',
             example='An elite endurance athlete may exceed 70 mL/kg/min.'),
        dict(term='Maximum Heart Rate', category='cardio',
             meaning='The highest heart rate achievable during maximal effort.',
             detail='Often estimated as 220 minus age, but that formula carries a large error and testing is more accurate.',
             example='A 17-year-old’s estimated maximum is about 203 bpm.'),
        dict(term='Heart Rate Reserve', category='cardio',
             meaning='The difference between maximum and resting heart rate.',
             detail='Used in the Karvonen formula to set training intensity, which accounts for resting fitness.',
             example='Target = resting + percentage of reserve.'),
        dict(term='Bradycardia of Training', category='cardio',
             meaning='A low resting heart rate resulting from endurance training.',
             detail='Stroke volume rises so fewer beats are needed. A sign of adaptation, not of disease.',
             example='A trained cyclist has a resting rate in the forties.'),
        dict(term='A-VO2 Difference', category='cardio',
             meaning='The difference in oxygen content between arterial and venous blood.',
             detail='Shows how much oxygen tissues extracted. Widens with training as capillary density and mitochondria increase.',
             example='Trained muscle extracts more oxygen per unit of blood.'),
        dict(term='Minute Ventilation', category='cardio',
             meaning='The volume of air moved in and out of the lungs each minute.',
             detail='Tidal volume times respiratory rate. Rises first by depth, then by rate as intensity climbs.',
             example='Ventilation increases from about 6 L/min at rest to over 100 at maximum.'),
        dict(term='Ventilatory Threshold', category='cardio',
             meaning='The intensity at which ventilation rises disproportionately to oxygen uptake.',
             detail='A non-invasive marker approximating lactate threshold, detectable during a graded test.',
             example='Breathing becomes notably harder past the threshold.'),
        dict(term='Blood Pressure Response to Exercise', category='cardio',
             meaning='Systolic pressure rises with intensity while diastolic stays roughly level.',
             detail='A falling systolic pressure during increasing work is abnormal and a reason to stop the test.',
             example='Systolic climbs steadily through a graded treadmill test.'),
        dict(term='Blood Redistribution', category='cardio',
             meaning='The shift of blood flow toward working muscle during exercise.',
             detail='Muscle may receive over 80 percent of cardiac output, while flow to the gut and kidneys drops sharply.',
             example='Digestion slows during hard exercise as flow is diverted.'),

        # ── Training Principles ──────────────────────────────────
        dict(term='Progressive Overload', category='training',
             meaning='Gradually increasing demand so the body keeps adapting.',
             detail='The foundational training principle. Without added stress, adaptation plateaus.',
             example='Adding weight or repetitions each week.'),
        dict(term='Specificity', category='training',
             meaning='Adaptations occur in the systems and movements that are actually trained.',
             detail='Training must resemble the target activity in energy system, movement pattern and speed.',
             example='Swim training improves swimming more than running does.'),
        dict(term='Reversibility', category='training',
             meaning='Fitness gained is lost when training stops.',
             detail='Aerobic adaptations decline within two to four weeks; strength is retained somewhat longer.',
             example='A month off noticeably reduces endurance.'),
        dict(term='FITT Principle', category='training',
             meaning='Frequency, Intensity, Time and Type — the variables of a training program.',
             detail='Adjusting any one of them changes the training stimulus.',
             example='Adding a fourth session raises frequency.'),
        dict(term='Periodization', category='training',
             meaning='Planned variation of training across a season to peak at the right time.',
             detail='Organized into macrocycles, mesocycles and microcycles, alternating load and recovery.',
             example='Volume drops and intensity rises as competition approaches.'),
        dict(term='Overtraining Syndrome', category='training',
             meaning='Prolonged performance decline from training stress exceeding recovery.',
             detail='Fatigue, mood disturbance, sleep problems, elevated resting heart rate and frequent illness. Recovery takes weeks to months.',
             example='An athlete’s times worsen despite training harder.'),
        dict(term='Supercompensation', category='training',
             meaning='The rebound above baseline that follows recovery from a training stress.',
             detail='Training again at the peak of the rebound drives progress; training too soon accumulates fatigue instead.',
             example='Performance peaks a few days after a hard block.'),
        dict(term='One-Repetition Maximum', category='training',
             meaning='The heaviest load that can be lifted once with correct form.',
             detail='Used to prescribe intensity as a percentage. Can be estimated from submaximal sets for safety.',
             example='Training at 80 percent of a 1RM for strength.'),
        dict(term='Rating of Perceived Exertion', category='training',
             meaning='A subjective scale of how hard exercise feels.',
             detail='The Borg scale runs 6 to 20; the modified scale 0 to 10. Useful when heart rate is affected by medication.',
             example='A patient on beta blockers uses RPE to gauge intensity.'),
        dict(term='Warm-Up', category='training',
             meaning='Gradual activity raising muscle temperature and blood flow before training.',
             detail='Dynamic movement outperforms static stretching, which can briefly reduce power output.',
             example='Light jogging and leg swings before sprinting.'),
        dict(term='Cool-Down', category='training',
             meaning='Light activity after exercise that lets heart rate and blood flow return gradually.',
             detail='Prevents venous pooling and the dizziness that can follow an abrupt stop.',
             example='Walking for five minutes after a hard run.'),
        dict(term='Physical Activity Guidelines', category='training',
             meaning='150 minutes of moderate or 75 of vigorous aerobic activity weekly, plus two resistance sessions.',
             detail='The ACSM and U.S. guideline for adults. Additional benefit continues beyond the minimum.',
             example='Five 30-minute brisk walks meet the aerobic minimum.'),

        # ── Assessment & Testing ─────────────────────────────────
        dict(term='Graded Exercise Test', category='testing',
             meaning='A test with progressively increasing workload to assess capacity and response.',
             detail='Run on a treadmill or cycle with ECG and blood pressure monitoring. May be maximal or submaximal.',
             example='A Bruce protocol treadmill test with ECG.'),
        dict(term='Bruce Protocol', category='testing',
             meaning='A standard treadmill protocol raising speed and grade every three minutes.',
             detail='Widely used for clinical stress testing, with published equations to estimate VO2 max.',
             example='A patient progresses through successive three-minute stages.'),
        dict(term='Submaximal Test', category='testing',
             meaning='A test estimating aerobic capacity without pushing to maximum effort.',
             detail='Safer and simpler than a maximal test, at the cost of accuracy. Assumes a linear heart rate response.',
             example='The YMCA cycle test estimates VO2 max submaximally.'),
        dict(term='Body Composition', category='testing',
             meaning='The proportion of the body that is fat mass versus fat-free mass.',
             detail='More informative than weight alone. Measured by skinfolds, bioelectrical impedance, hydrostatic weighing or DXA.',
             example='Two people of the same weight can differ greatly in body fat.'),
        dict(term='Body Mass Index', category='testing',
             meaning='Weight in kilograms divided by height in metres squared.',
             detail='A population screening tool, not a measure of body composition. Misclassifies muscular individuals.',
             example='A muscular athlete may register as overweight by BMI.'),
        dict(term='Skinfold Measurement', category='testing',
             meaning='Estimating body fat by measuring subcutaneous fat thickness with calipers.',
             detail='Inexpensive but technique-dependent. Sites and formulas differ by sex and age.',
             example='A three-site skinfold protocol estimates body fat percentage.'),
        dict(term='Flexibility Testing', category='testing',
             meaning='Assessment of range of motion at a joint.',
             detail='The sit-and-reach is common but joint-specific; goniometry measures a specific joint angle.',
             example='A sit-and-reach assesses hamstring and low back flexibility.'),
        dict(term='Muscular Endurance Test', category='testing',
             meaning='A test of how many repetitions or how long a muscle group can sustain work.',
             detail='Push-up and curl-up tests are standard field measures, distinct from tests of maximal strength.',
             example='Counting push-ups to fatigue.'),
        dict(term='PAR-Q', category='testing',
             meaning='A short screening questionnaire identifying who should see a clinician before exercising.',
             detail='Seven questions covering heart conditions, chest pain, dizziness, joint problems and medication.',
             example='A positive answer prompts medical clearance before testing.'),
        dict(term='Contraindications to Exercise Testing', category='testing',
             meaning='Conditions that make an exercise test unsafe to perform.',
             detail='Absolute contraindications prohibit testing; relative ones require judgment and monitoring. Unstable angina and uncontrolled arrhythmia are absolute.',
             example='A recent myocardial infarction is an absolute contraindication.'),

        # ── Environment & Nutrition ──────────────────────────────
        dict(term='Thermoregulation in Exercise', category='applied',
             meaning='Maintaining core temperature as working muscle generates heat.',
             detail='Sweat evaporation is the main route. Humidity impairs it, which is why humid heat is more dangerous.',
             example='Sweating cools the body only when the sweat evaporates.'),
        dict(term='Dehydration and Performance', category='applied',
             meaning='Fluid loss of about 2 percent of body weight measurably impairs performance.',
             detail='Reduces plasma volume and stroke volume and raises heart rate and core temperature.',
             example='A 150-pound athlete losing 3 pounds is already impaired.'),
        dict(term='Hyponatremia', category='applied',
             meaning='Dangerously low blood sodium, usually from drinking too much plain water.',
             detail='Seen in long endurance events. Confusion, nausea and seizures. Prevented by drinking to thirst with electrolytes.',
             example='A marathoner who over-drinks water develops hyponatremia.'),
        dict(term='Heat Acclimatization', category='applied',
             meaning='Adaptation to heat over one to two weeks of gradual exposure.',
             detail='Plasma volume expands and sweating begins earlier and more dilute. Most of the benefit appears within ten days.',
             example='Preseason practices build heat tolerance gradually.'),
        dict(term='Altitude and Performance', category='applied',
             meaning='Reduced oxygen pressure at altitude lowers aerobic performance.',
             detail='Acclimatization raises red cell mass over weeks. Live-high train-low seeks the benefit without the training cost.',
             example='Endurance times slow noticeably at 8,000 feet.'),
        dict(term='Carbohydrate Loading', category='applied',
             meaning='Raising muscle glycogen before a long event by increasing carbohydrate intake.',
             detail='Useful for continuous efforts beyond about 90 minutes, paired with reduced training.',
             example='A runner increases carbohydrate intake in the days before a marathon.'),
        dict(term='Glycogen', category='applied',
             meaning='The stored form of carbohydrate in muscle and liver.',
             detail='Muscle glycogen fuels the working muscle; liver glycogen maintains blood glucose. Depletion causes the marathon wall.',
             example='Depleted glycogen forces a sharp drop in pace.'),
        dict(term='Protein Requirements for Athletes', category='applied',
             meaning='Roughly 1.2 to 2.0 grams per kilogram of body weight per day.',
             detail='Above the general recommendation. Timing matters less than reaching the daily total.',
             example='A 70 kg athlete targets 84 to 140 grams daily.'),
        dict(term='Female Athlete Triad', category='applied',
             meaning='Low energy availability, menstrual dysfunction and low bone density.',
             detail='Now understood within Relative Energy Deficiency in Sport, which affects all athletes. Underfuelling is the driver.',
             example='An athlete with irregular cycles is screened for low energy availability.'),
        dict(term='Ergogenic Aid', category='applied',
             meaning='A substance or method intended to improve performance.',
             detail='Few have good evidence. Creatine and caffeine do; most supplements do not, and some are contaminated.',
             example='Creatine supplementation supports short high-intensity work.'),
    ],
))


# ═══════════════════════════════════════════════════════════════════
#  Occupational Health & Safety
# ═══════════════════════════════════════════════════════════════════
SPECS.append(dict(
    slug='occupational-health-safety',
    name='Occupational Health & Safety',
    eyebrow='Health Science — Occupational Health & Safety',
    h1_lead='Workplace Hazards &',
    h1_em='Occupational Safety',
    subtitle='A study companion for OSHA standards, bloodborne pathogens, hazard communication, '
             'ergonomics and workplace safety — built for HOSA competitors and anyone entering a '
             'clinical workplace.',
    test_blurb='occupational health and workplace safety concepts',
    topics='OSHA, bloodborne pathogens, hazard communication, PPE, ergonomics, radiation and chemical safety, emergency action',
    tips=[
        'Know the hierarchy of controls in order: elimination, substitution, engineering, administrative, PPE. PPE is always last.',
        'The Bloodborne Pathogens Standard is 29 CFR 1910.1030. Exposure control plan, engineering controls, PPE, hepatitis B vaccine, post-exposure follow-up.',
        'Standard precautions treat every patient’s blood and body fluids as infectious — no exceptions.',
        'Never recap a needle. Sharps injuries are the most preventable exposure in healthcare.',
        'Hazard Communication now follows GHS: pictograms, signal words, and a 16-section safety data sheet.',
        'Learn ALARA and the three exposure controls for radiation: time, distance and shielding.',
    ],
    categories=[
        ('osha',     'OSHA & Regulation'),
        ('bbp',      'Bloodborne Pathogens'),
        ('hazcom',   'Hazard Communication'),
        ('ppe',      'PPE & Controls'),
        ('ergo',     'Ergonomics & Injury'),
        ('physical', 'Physical & Chemical Hazards'),
        ('emergency','Emergency Preparedness'),
    ],
    terms=[
        # ── OSHA & Regulation ────────────────────────────────────
        dict(term='OSHA', category='osha',
             meaning='The federal agency that sets and enforces workplace safety standards.',
             detail='Created by the Occupational Safety and Health Act of 1970. Conducts inspections and issues citations.',
             example='An OSHA inspector reviews a hospital’s exposure control plan.'),
        dict(term='General Duty Clause', category='osha',
             meaning='The requirement that employers keep the workplace free of recognized serious hazards.',
             detail='Section 5(a)(1). Lets OSHA cite a hazard for which no specific standard exists.',
             example='A heat hazard is cited under the general duty clause.'),
        dict(term='NIOSH', category='osha',
             meaning='The federal research institute that studies workplace hazards and recommends limits.',
             detail='Part of the CDC. Its recommendations are advisory; OSHA sets enforceable limits.',
             example='NIOSH certifies respirators such as the N95.'),
        dict(term='Permissible Exposure Limit', category='osha',
             meaning='The legal maximum airborne concentration of a substance a worker may be exposed to.',
             detail='Usually an eight-hour time-weighted average. Some substances also carry short-term and ceiling limits.',
             example='A PEL caps the average concentration across a shift.'),
        dict(term='OSHA 300 Log', category='osha',
             meaning='The record employers keep of work-related injuries and illnesses.',
             detail='Recordable events involve death, days away, restricted duty, transfer, medical treatment beyond first aid, or loss of consciousness.',
             example='A needlestick requiring treatment is entered on the log.'),
        dict(term='Right to Know', category='osha',
             meaning='A worker’s right to information about hazardous chemicals they may be exposed to.',
             detail='The basis for hazard communication: labels, safety data sheets and training before assignment.',
             example='An employee may request the safety data sheet for any chemical used.'),
        dict(term='Whistleblower Protection', category='osha',
             meaning='Protection from retaliation for reporting a safety concern.',
             detail='Employers may not fire, demote or discipline a worker for filing a complaint. Complaints are time-limited.',
             example='An employee reports an unsafe practice without fear of discipline.'),
        dict(term='Joint Commission', category='osha',
             meaning='The accrediting body that surveys healthcare organizations for safety and quality.',
             detail='Separate from OSHA. Its National Patient Safety Goals drive much hospital safety practice.',
             example='A hospital prepares for a Joint Commission survey.'),
        dict(term='Safety Culture', category='osha',
             meaning='Shared attitudes and practices that make safety a genuine organizational priority.',
             detail='A just culture distinguishes human error from reckless behavior, so people report near misses instead of hiding them.',
             example='Staff report a near miss without fear of blame.'),

        # ── Bloodborne Pathogens ─────────────────────────────────
        dict(term='Bloodborne Pathogens Standard', category='bbp',
             meaning='The OSHA rule protecting workers from infectious material in blood.',
             detail='29 CFR 1910.1030. Requires an exposure control plan, engineering controls, PPE, training, hepatitis B vaccine and follow-up.',
             example='Every clinical employer must maintain a written exposure control plan.'),
        dict(term='Bloodborne Pathogen', category='bbp',
             meaning='A disease-causing organism carried in blood.',
             detail='Hepatitis B, hepatitis C and HIV are the main occupational concerns.',
             example='A needlestick raises the risk of hepatitis B transmission.'),
        dict(term='Standard Precautions', category='bbp',
             meaning='Treating every patient’s blood and body fluids as potentially infectious.',
             detail='Replaced universal precautions by extending to all body fluids except sweat. Applied regardless of diagnosis.',
             example='Gloves are worn for every blood draw.'),
        dict(term='Exposure Control Plan', category='bbp',
             meaning='The written plan describing how an employer eliminates or minimizes exposure.',
             detail='Reviewed annually and updated for new technology. Must be accessible to employees.',
             example='A clinic updates its plan after adopting safety-engineered needles.'),
        dict(term='Occupational Exposure Incident', category='bbp',
             meaning='Contact with blood or other infectious material through broken skin, mucous membrane or injection.',
             detail='Requires immediate washing, prompt reporting, source testing where possible, and medical follow-up.',
             example='A splash to the eye during a procedure is an exposure incident.'),
        dict(term='Post-Exposure Prophylaxis', category='bbp',
             meaning='Treatment given after an exposure to prevent infection.',
             detail='HIV prophylaxis ideally starts within hours. No prophylaxis exists for hepatitis C, which is monitored instead.',
             example='Antiretrovirals are started within hours of a high-risk stick.'),
        dict(term='Hepatitis B Vaccine', category='bbp',
             meaning='The vaccine employers must offer at no cost to at-risk employees.',
             detail='Offered within ten working days of assignment. Declining requires a signed declination, and it can be requested later.',
             example='A new phlebotomist is offered the series before starting.'),
        dict(term='Sharps Safety', category='bbp',
             meaning='Practices preventing needlestick injury, including never recapping a used needle.',
             detail='Safety-engineered devices, immediate disposal in a puncture-resistant container, and never overfilling it.',
             example='A needle is activated and dropped straight into the sharps container.'),
        dict(term='Sharps Container', category='bbp',
             meaning='A puncture-resistant, leak-proof, labeled container for used sharps.',
             detail='Replaced at about three quarters full. Never reach in or press contents down.',
             example='A container is closed and replaced before it overfills.'),
        dict(term='Regulated Medical Waste', category='bbp',
             meaning='Waste that could release infectious material if handled or compressed.',
             detail='Liquid or semi-liquid blood, contaminated sharps, pathological waste. Placed in labeled biohazard containers.',
             example='A blood-saturated dressing goes in a biohazard bag.'),
        dict(term='Biohazard Symbol', category='bbp',
             meaning='The universal orange-red symbol marking infectious material.',
             detail='Required on containers, refrigerators and bags holding regulated waste or specimens.',
             example='A specimen refrigerator carries a biohazard label.'),
        dict(term='Tuberculosis Precautions', category='bbp',
             meaning='Airborne precautions using a negative-pressure room and a fitted respirator.',
             detail='A surgical mask is not sufficient. Requires an N95 or better with annual fit testing.',
             example='Staff don a fit-tested N95 before entering the room.'),

        # ── Hazard Communication ─────────────────────────────────
        dict(term='Hazard Communication Standard', category='hazcom',
             meaning='The OSHA rule requiring workers be informed about hazardous chemicals.',
             detail='29 CFR 1910.1200, aligned with the Globally Harmonized System since 2012.',
             example='Every chemical in a lab carries a compliant label.'),
        dict(term='Globally Harmonized System', category='hazcom',
             meaning='The international system standardizing chemical classification and labeling.',
             detail='Brought consistent pictograms, signal words and a 16-section safety data sheet.',
             example='The same pictogram means the same hazard worldwide.'),
        dict(term='Safety Data Sheet', category='hazcom',
             meaning='A 16-section document describing a chemical’s hazards and safe handling.',
             detail='Replaced the MSDS. Sections cover identification, hazards, first aid, firefighting, handling, exposure controls and toxicology.',
             example='An employee checks section 4 for first-aid measures.'),
        dict(term='Signal Word', category='hazcom',
             meaning='Either "Danger" for severe hazards or "Warning" for less severe ones.',
             detail='Only one appears on a label, reflecting the most severe hazard classified.',
             example='A corrosive acid label carries the word Danger.'),
        dict(term='GHS Pictogram', category='hazcom',
             meaning='A red-bordered diamond symbol showing a chemical hazard class.',
             detail='Nine pictograms including flame, corrosion, skull and crossbones, health hazard and biohazard.',
             example='The corrosion pictogram shows liquid burning a hand and surface.'),
        dict(term='Secondary Container Labeling', category='hazcom',
             meaning='The requirement that a chemical poured into another container be labeled.',
             detail='Must show the identity and hazards. Unlabeled containers are among the most common citations.',
             example='A spray bottle of diluted disinfectant carries its own label.'),
        dict(term='Chemical Hygiene Plan', category='hazcom',
             meaning='The written plan protecting workers in a laboratory setting.',
             detail='Required by the Laboratory Standard. Names a chemical hygiene officer and sets procedures and exposure controls.',
             example='A lab designates a chemical hygiene officer.'),
        dict(term='Spill Response', category='hazcom',
             meaning='Contain, protect, notify and clean up according to the chemical and the volume.',
             detail='Only trained staff with proper PPE handle a spill; larger ones are evacuated and referred to a response team.',
             example='A small disinfectant spill is absorbed and disposed of by trained staff.'),

        # ── PPE & Controls ───────────────────────────────────────
        dict(term='Hierarchy of Controls', category='ppe',
             meaning='Elimination, substitution, engineering, administrative controls, then PPE.',
             detail='Ranked by effectiveness. PPE is last because it depends on correct use every single time.',
             example='A safety-engineered needle is an engineering control.'),
        dict(term='Engineering Control', category='ppe',
             meaning='A physical change that removes or isolates a hazard.',
             detail='Sharps containers, self-sheathing needles, fume hoods, negative-pressure rooms. Protects everyone without relying on behavior.',
             example='A fume hood captures vapors at the source.'),
        dict(term='Administrative Control', category='ppe',
             meaning='A change to policy, scheduling or procedure that reduces exposure.',
             detail='Rotation, training, signage and limiting time in a hazardous area. Depends on compliance.',
             example='Staff rotate out of a high-noise area.'),
        dict(term='Personal Protective Equipment', category='ppe',
             meaning='Equipment worn to protect against a hazard, provided free by the employer.',
             detail='Gloves, gowns, masks, eye protection and respirators. The last line of defence, not the first.',
             example='A gown and face shield are worn for a splash-risk procedure.'),
        dict(term='Donning and Doffing Sequence', category='ppe',
             meaning='Putting PPE on and taking it off in an order that avoids self-contamination.',
             detail='Don gown, mask, goggles, gloves. Doff gloves, goggles, gown, mask — with hand hygiene between steps.',
             example='Gloves come off first because they are the most contaminated.'),
        dict(term='N95 Respirator', category='ppe',
             meaning='A respirator filtering at least 95 percent of airborne particles.',
             detail='Requires medical clearance, annual fit testing and a seal check each time. Facial hair breaks the seal.',
             example='A worker performs a seal check before entering an isolation room.'),
        dict(term='Fit Testing', category='ppe',
             meaning='Testing that a specific respirator model and size seals on a specific person.',
             detail='Required before first use and annually. A user seal check before each use is not a substitute.',
             example='A qualitative fit test uses a bitter aerosol.'),
        dict(term='Glove Selection', category='ppe',
             meaning='Matching glove material to the task and the chemical involved.',
             detail='Latex risks allergy; nitrile resists many chemicals; vinyl is for low-risk tasks. No glove resists everything.',
             example='Nitrile gloves are chosen for handling chemotherapy agents.'),
        dict(term='Latex Allergy', category='ppe',
             meaning='A hypersensitivity to natural rubber latex proteins.',
             detail='Ranges from contact dermatitis to anaphylaxis. Most facilities have moved to latex-free environments.',
             example='A latex-free cart is used for a sensitized patient.'),
        dict(term='Hand Hygiene', category='ppe',
             meaning='The single most effective measure to prevent healthcare-associated infection.',
             detail='Alcohol rub unless hands are visibly soiled or spores are a concern, in which case soap and water.',
             example='Hands are cleaned before and after every patient contact.'),

        # ── Ergonomics & Injury ──────────────────────────────────
        dict(term='Ergonomics', category='ergo',
             meaning='Designing work to fit the worker rather than forcing the worker to adapt.',
             detail='Addresses posture, force, repetition and duration. Poor ergonomics drives musculoskeletal injury.',
             example='Adjusting a workstation so the screen sits at eye level.'),
        dict(term='Musculoskeletal Disorder', category='ergo',
             meaning='An injury to muscles, nerves, tendons or joints from work demands.',
             detail='Among the most common and costly workplace injuries, particularly in healthcare.',
             example='Chronic low back pain from repeated patient lifting.'),
        dict(term='Safe Patient Handling', category='ergo',
             meaning='Using equipment rather than manual lifting to move patients.',
             detail='Manual lifting is the leading cause of back injury in healthcare. No safe manual lift limit exists for an adult patient.',
             example='A ceiling lift transfers a patient from bed to chair.'),
        dict(term='Proper Body Mechanics', category='ergo',
             meaning='Using posture and leverage that protect the spine during exertion.',
             detail='Wide base, bend at the knees, keep the load close, never twist while lifting. A supplement to equipment, not a substitute.',
             example='A worker pivots their feet instead of twisting the trunk.'),
        dict(term='Repetitive Strain Injury', category='ergo',
             meaning='Tissue damage from repeated motion over time.',
             detail='Carpal tunnel syndrome, tendinitis, epicondylitis. Prevented by job rotation, rest breaks and tool redesign.',
             example='Repeated pipetting causes wrist tendinitis.'),
        dict(term='Carpal Tunnel Syndrome', category='ergo',
             meaning='Median nerve compression at the wrist causing numbness and weakness.',
             detail='Affects the thumb, index, middle and half the ring finger. Often worse at night.',
             example='A worker wakes with numb fingers after repetitive tasks.'),
        dict(term='Slips, Trips and Falls', category='ergo',
             meaning='A leading cause of workplace injury, usually preventable by housekeeping.',
             detail='Wet floors, cords, clutter and poor lighting. Prompt spill cleanup and signage are the primary controls.',
             example='A wet floor sign is placed immediately after a spill.'),
        dict(term='Workplace Violence', category='ergo',
             meaning='Threats or assault at work, a recognized hazard in healthcare.',
             detail='Healthcare workers face far higher rates than most industries. Controls include de-escalation training, alarms and staffing.',
             example='Staff complete de-escalation training for the emergency department.'),
        dict(term='Workers’ Compensation', category='ergo',
             meaning='Insurance paying medical costs and lost wages for work-related injury.',
             detail='A no-fault system: benefits do not depend on blame, and generally replace the right to sue the employer.',
             example='A nurse injured lifting a patient files a claim.'),

        # ── Physical & Chemical Hazards ──────────────────────────
        dict(term='ALARA', category='physical',
             meaning='As Low As Reasonably Achievable — the principle governing radiation exposure.',
             detail='Applied through time, distance and shielding, since no exposure level is considered entirely without risk.',
             example='A technologist steps behind a lead barrier during exposure.'),
        dict(term='Dosimeter', category='physical',
             meaning='A badge worn to record a worker’s cumulative radiation exposure.',
             detail='Worn at the collar outside the apron and read periodically. Never shared or taken home.',
             example='A radiology employee’s badge is read monthly.'),
        dict(term='Lead Shielding', category='physical',
             meaning='Protective material that absorbs scattered radiation.',
             detail='Aprons, thyroid collars and barriers. Aprons are inspected regularly for cracks that would let radiation through.',
             example='A thyroid collar is worn during fluoroscopy.'),
        dict(term='Laser Safety', category='physical',
             meaning='Controls preventing eye and skin injury from laser use.',
             detail='Wavelength-specific eyewear, controlled access, non-reflective instruments, and smoke evacuation.',
             example='Everyone in the room wears eyewear matched to the wavelength.'),
        dict(term='Surgical Smoke', category='physical',
             meaning='Plume from electrosurgery or lasers containing harmful particles.',
             detail='Can carry chemicals, viable cells and viral DNA. Controlled by local smoke evacuation, not by a surgical mask.',
             example='A smoke evacuator is used at the surgical site.'),
        dict(term='Noise-Induced Hearing Loss', category='physical',
             meaning='Permanent hearing damage from prolonged exposure to loud sound.',
             detail='OSHA requires a hearing conservation program above an 85 decibel eight-hour average.',
             example='Workers in a loud plant room wear hearing protection.'),
        dict(term='Hazardous Drug Handling', category='physical',
             meaning='Precautions for drugs that are toxic even at very low exposure levels.',
             detail='Chemotherapy agents are the main example. USP 800 requires containment ventilation, closed-system transfer devices and specific PPE.',
             example='Chemotherapy is compounded in a containment hood.'),
        dict(term='Ethylene Oxide', category='physical',
             meaning='A sterilizing gas that is a recognized carcinogen.',
             detail='Used for heat-sensitive equipment. Requires aeration, monitoring and a regulated area.',
             example='Sterilized items are aerated before handling.'),
        dict(term='Mercury and Glutaraldehyde', category='physical',
             meaning='Legacy healthcare chemicals largely replaced because of toxicity.',
             detail='Mercury thermometers gave way to digital; glutaraldehyde to safer high-level disinfectants.',
             example='A facility removes mercury devices from every unit.'),
        dict(term='Lockout/Tagout', category='physical',
             meaning='Procedures isolating energy so equipment cannot start during servicing.',
             detail='Each worker applies their own lock, and only that worker removes it.',
             example='A technician locks out a machine before clearing a jam.'),

        # ── Emergency Preparedness ───────────────────────────────
        dict(term='Emergency Action Plan', category='emergency',
             meaning='The written plan for evacuation, alarms and accounting for people.',
             detail='Required by OSHA for most employers. Covers reporting, evacuation routes, critical operations and rescue duties.',
             example='A department drills its evacuation route twice a year.'),
        dict(term='RACE', category='emergency',
             meaning='Rescue, Alarm, Contain, Extinguish or Evacuate — the fire response sequence.',
             detail='The healthcare standard. Rescue anyone in immediate danger first, then pull the alarm.',
             example='Staff move a patient clear, then pull the alarm.'),
        dict(term='Fire Extinguisher Classes', category='emergency',
             meaning='A for ordinary combustibles, B for flammable liquids, C for electrical, D for metals, K for cooking oils.',
             detail='Using the wrong class can worsen a fire — water on an electrical fire is a conduction hazard.',
             example='An ABC extinguisher covers most general areas.'),
        dict(term='Oxygen Safety', category='emergency',
             meaning='Precautions around oxygen, which accelerates combustion.',
             detail='Cylinders are secured upright, kept from heat and grease, and signed. Oxygen does not burn but makes everything else burn faster.',
             example='Cylinders are chained upright in a ventilated room.'),
        dict(term='Emergency Eyewash Station', category='emergency',
             meaning='A station providing continuous flushing for at least fifteen minutes.',
             detail='Must be within ten seconds of a hazard, unobstructed, and activated weekly to flush the line.',
             example='A worker holds their eyelids open and flushes for a full fifteen minutes.'),
        dict(term='Evacuation Route', category='emergency',
             meaning='The posted path from a work area to a safe assembly point.',
             detail='Kept clear and lit, with exits unlocked from the inside. Elevators are not used during a fire.',
             example='A floor map shows exits and the assembly point.'),
        dict(term='Code System', category='emergency',
             meaning='Overhead codes that alert staff to an emergency without alarming patients.',
             detail='Codes vary by facility, though many states have standardized them. Blue is commonly cardiac arrest, red fire.',
             example='A code is announced overhead with the location.'),
        dict(term='Incident Reporting', category='emergency',
             meaning='Documenting an injury, exposure or near miss so the cause can be addressed.',
             detail='Reported promptly regardless of severity. Near-miss reporting is what lets an organization fix a hazard before harm.',
             example='A staff member reports a near-miss sharps injury.'),
    ],
))
