# -*- coding: utf-8 -*-
"""Event content, batch B."""

SPECS = []

# ═══════════════════════════════════════════════════════════════════
#  Disaster Preparedness & CERT
# ═══════════════════════════════════════════════════════════════════
SPECS.append(dict(
    slug='disaster-preparedness',
    name='Disaster Preparedness',
    eyebrow='Emergency Preparedness Event — Disaster Preparedness',
    h1_lead='Community Response &',
    h1_em='Disaster Preparedness',
    subtitle='A study companion for the incident command system, triage, search and rescue, hazards and '
             'community response — built for HOSA competitors preparing for the CERT and Disaster '
             'Preparedness competitive events.',
    test_blurb='disaster response and CERT concepts',
    topics='Incident command, START triage, light search and rescue, hazard types, shelters, personal preparedness, psychology of disaster',
    tips=[
        'START triage is the single most tested topic. Walk, breathe, perfuse, mental status — in that order.',
        'Under ICS, one supervisor per person and a span of control of three to seven. Those two numbers show up constantly.',
        'CERT volunteers do the greatest good for the greatest number. That means you leave the immediate victim and keep triaging.',
        'Know which hazards mean evacuate and which mean shelter in place. Getting the two backwards is a scored error.',
        'Learn the size-up steps in order — rescuer safety comes before every other consideration.',
        'The Stafford Act, NIMS and the National Response Framework each cover a different layer. Do not confuse them.',
    ],
    categories=[
        ('ics',      'Incident Command'),
        ('triage',   'Triage & Medical'),
        ('sar',      'Search & Rescue'),
        ('hazards',  'Hazards & Threats'),
        ('prepare',  'Preparedness'),
        ('psych',    'Disaster Psychology'),
    ],
    terms=[
        # ── Incident Command ─────────────────────────────────────
        dict(term='Incident Command System (ICS)', category='ics',
             meaning='A standard management structure for organizing people and resources at any incident.',
             detail='Scales from a single ambulance call to a multi-state disaster. Its purpose is one chain of command when agencies that never train together must work together.',
             example='A wildfire response uses ICS so fire, EMS and police report through one structure.'),
        dict(term='Incident Commander', category='ics',
             meaning='The one person with overall authority for an incident.',
             detail='Sets objectives, approves the action plan and orders resources. Every incident has exactly one, established by the first arriving qualified responder.',
             example='The first engine captain on scene assumes command until relieved.'),
        dict(term='Unified Command', category='ics',
             meaning='Several agencies sharing command of an incident while keeping one set of objectives.',
             detail='Used when an incident crosses jurisdictions or disciplines. Each agency keeps its own authority but they produce a single action plan.',
             example='A hazardous spill on a river boundary is run under unified command by two counties.'),
        dict(term='Span of Control', category='ics',
             meaning='The number of people one supervisor can effectively direct — three to seven, ideally five.',
             detail='Exceeding it is the usual reason a response loses coordination. When a supervisor has too many reports, the structure expands.',
             example='A team leader with nine volunteers splits them into two squads.'),
        dict(term='Unity of Command', category='ics',
             meaning='The principle that every person reports to exactly one supervisor.',
             detail='Prevents conflicting orders. Distinct from unified command, which is about agencies rather than individuals.',
             example='A volunteer takes direction only from their assigned team leader.'),
        dict(term='Chain of Command', category='ics',
             meaning='The orderly line of authority within the incident organization.',
             detail='Information and orders move along it. Does not prevent people from talking directly, only from taking direction outside it.',
             example='A request for supplies moves from team leader to section chief to commander.'),
        dict(term='General Staff Sections', category='ics',
             meaning='Operations, Planning, Logistics and Finance/Administration.',
             detail='Operations does the tactical work, Planning tracks resources and writes the plan, Logistics supplies everything, Finance tracks cost.',
             example='The Logistics chief arranges water and lighting for an overnight operation.'),
        dict(term='Command Staff', category='ics',
             meaning='The Public Information Officer, Safety Officer and Liaison Officer.',
             detail='Report directly to the incident commander. The Safety Officer is the only person who can stop an unsafe operation immediately.',
             example='The Safety Officer halts roof operations when winds pick up.'),
        dict(term='Incident Action Plan', category='ics',
             meaning='The document stating objectives and tactics for one operational period.',
             detail='May be verbal on small incidents and written on large ones. Drives briefings and assignments.',
             example='The morning briefing distributes the day’s action plan to every team.'),
        dict(term='NIMS', category='ics',
             meaning='The National Incident Management System, the U.S. framework for managing incidents.',
             detail='Provides common terminology, resource typing and ICS. Adoption is a condition of federal preparedness grants.',
             example='A county adopts NIMS so its responders can integrate with federal teams.'),
        dict(term='Stafford Act', category='ics',
             meaning='The federal law allowing a presidential disaster declaration and federal aid to states.',
             detail='A governor requests the declaration after determining the event exceeds state capacity. It unlocks FEMA assistance.',
             example='After a hurricane, the governor requests a declaration under the Stafford Act.'),
        dict(term='Community Emergency Response Team', category='ics',
             meaning='Trained community volunteers who assist after a disaster until professionals arrive.',
             detail='A FEMA program covering preparedness, fire safety, light search and rescue, triage and disaster psychology.',
             example='CERT members check their own street before responding to the staging area.'),
        dict(term='Documentation in CERT', category='ics',
             meaning='Recording victims found, treatments given and areas searched.',
             detail='Written records let arriving professionals pick up where volunteers stopped, and support later reimbursement and investigation.',
             example='A team logs each room searched and every victim tagged.'),

        # ── Triage & Medical ─────────────────────────────────────
        dict(term='START Triage', category='triage',
             meaning='A rapid system that sorts mass-casualty victims in under a minute each.',
             detail='Simple Triage and Rapid Treatment. Assesses ability to walk, then respirations, perfusion and mental status, assigning one of four categories.',
             example='A responder calls out for anyone who can walk to move to a designated area.'),
        dict(term='Immediate (Red)', category='triage',
             meaning='A victim with a life-threatening but survivable injury needing care within the hour.',
             detail='Assigned for respirations over 30, capillary refill over 2 seconds or no radial pulse, or inability to follow simple commands.',
             example='An unconscious victim breathing 34 times a minute is tagged red.'),
        dict(term='Delayed (Yellow)', category='triage',
             meaning='A victim with serious injuries whose treatment can safely wait.',
             detail='Breathing, perfusing and mentally intact, but unable to walk away from the scene.',
             example='A conscious victim with an obvious leg fracture is tagged yellow.'),
        dict(term='Minor (Green)', category='triage',
             meaning='A walking wounded victim with minor injuries.',
             detail='Identified first by asking everyone who can walk to move to one area, which clears the scene and reveals who cannot.',
             example='Victims who walk to the collection point are tagged green.'),
        dict(term='Deceased / Expectant (Black)', category='triage',
             meaning='A victim not breathing after the airway is opened.',
             detail='In START, one attempt is made to open the airway. If breathing does not begin, the victim is tagged and the responder moves on.',
             example='A responder repositions the head, sees no breathing, tags black and continues.'),
        dict(term='Greatest Good for the Greatest Number', category='triage',
             meaning='The principle that mass-casualty care maximizes total survivors, not individual outcomes.',
             detail='It is why responders leave a non-breathing victim to keep triaging. Emotionally hard and the reason triage is trained in advance.',
             example='A volunteer moves past one critical victim to assess twenty more.'),
        dict(term='Triage Tag', category='triage',
             meaning='A color-coded tag marking a victim’s category and travel priority.',
             detail='Attached where it will not be lost, usually a wrist or ankle. Tear-off strips record the category as it changes.',
             example='A tag is fixed to the wrist so the category travels with the victim.'),
        dict(term='Secondary Triage', category='triage',
             meaning='Reassessment after victims reach a treatment area.',
             detail='Conditions change, so categories are re-evaluated. A yellow victim who deteriorates is upgraded to red.',
             example='A delayed victim whose breathing worsens is retagged immediate.'),
        dict(term='Treatment Area', category='triage',
             meaning='An organized location where triaged victims receive care while awaiting transport.',
             detail='Laid out by category, uphill and upwind of hazards, with clear entry and exit routes.',
             example='Red, yellow and green sections are marked with tarps of matching colors.'),
        dict(term='Head-to-Toe Assessment', category='triage',
             meaning='A systematic physical check for injuries after immediate threats are handled.',
             detail='Works down the body checking for deformity, contusions, abrasions, punctures, burns, tenderness, lacerations and swelling.',
             example='A volunteer checks the head, neck and chest before moving to the abdomen.'),
        dict(term='Three Killers in CERT Care', category='triage',
             meaning='Airway obstruction, excessive bleeding and shock.',
             detail='CERT medical operations focus on these because each is survivable with simple intervention and rapidly fatal without one.',
             example='A team opens an airway, controls bleeding and elevates for shock before moving on.'),

        # ── Search & Rescue ──────────────────────────────────────
        dict(term='Size-Up', category='sar',
             meaning='A nine-step assessment of a situation before committing to action.',
             detail='Gather facts, assess damage, consider probabilities, assess your own situation, establish priorities, make decisions, develop a plan, take action, evaluate.',
             example='A team leader circles a damaged building before deciding whether to enter.'),
        dict(term='Rescuer Safety', category='sar',
             meaning='The first priority in every operation, ahead of any victim.',
             detail='CERT teams do not enter heavily damaged structures. An injured volunteer consumes resources rather than adding them.',
             example='A team declines to enter a building with a visibly sagging roofline.'),
        dict(term='Light Damage', category='sar',
             meaning='Superficial damage with broken windows and fallen plaster, where the structure is intact.',
             detail='CERT search and rescue is limited to lightly damaged structures.',
             example='A house with cracked drywall and broken glass is safe to search.'),
        dict(term='Moderate Damage', category='sar',
             meaning='Visible large cracks, tilting walls or fallen masonry, with the structure still standing.',
             detail='CERT operations are limited here and personnel should not enter. Victims may be removed only from the perimeter.',
             example='A building with a partly collapsed chimney is left to professionals.'),
        dict(term='Heavy Damage', category='sar',
             meaning='Partial or complete collapse, with the structure unstable.',
             detail='CERT members never enter. Only trained urban search and rescue teams with shoring capability operate here.',
             example='A pancaked parking structure is cordoned off and reported.'),
        dict(term='Search Pattern', category='sar',
             meaning='A systematic route through a structure so no area is missed.',
             detail='Bottom-up or top-down, room by room, calling out and pausing to listen. Each searched area is marked.',
             example='A team works right-hand-wall through every room on a floor.'),
        dict(term='Search Markings', category='sar',
             meaning='A standard X drawn at the entry point recording who searched, when and what was found.',
             detail='Left quadrant is the team, top is time of entry, right is hazards, bottom is the number of victims found.',
             example='A single slash means a search is in progress; a completed X means the team is out.'),
        dict(term='Cribbing', category='sar',
             meaning='A stable stack of wood used to support a heavy object being lifted.',
             detail='Built up as the object rises, so it never has to be held by the lever alone. Never place any part of the body under an uncribbed load.',
             example='Rescuers add cribbing under a slab after every few inches of lift.'),
        dict(term='Leveraging', category='sar',
             meaning='Using a rigid bar and a fulcrum to raise a heavy object.',
             detail='Paired with cribbing. The longer the lever and the closer the fulcrum to the load, the more force is gained.',
             example='A pry bar over a block raises a beam enough to slide cribbing beneath it.'),
        dict(term='One-Person Drags', category='sar',
             meaning='Carries a single rescuer can use to move a victim clear of danger.',
             detail='Blanket drag, shoulder drag and ankle drag. Used only when the victim must be moved immediately.',
             example='A rescuer drags a victim by the shoulders out of a smoke-filled hallway.'),
        dict(term='Two-Person Carries', category='sar',
             meaning='Two-rescuer carries that move a victim more safely than a single-person drag.',
             detail='The chair carry and the two-person extremity carry. Safer for victim and rescuers alike whenever two people and a little time are available.',
             example='Two volunteers use a chair carry to bring a victim down a stairway.'),
        dict(term='Utility Control', category='sar',
             meaning='Shutting off gas, water and electricity to stop a secondary emergency.',
             detail='Gas is shut at the meter and only by someone who knows how; once off, only the utility should restore it.',
             example='A volunteer shuts off the main gas valve after smelling a leak.'),
        dict(term='Fire Suppression (CERT)', category='sar',
             meaning='Extinguishing only small, incipient fires with a portable extinguisher.',
             detail='Volunteers work in pairs with a backup and an escape route, and never fight a fire beyond the incipient stage.',
             example='Two members use an extinguisher on a wastebasket fire and back out together.'),
        dict(term='PASS', category='sar',
             meaning='Pull the pin, Aim at the base, Squeeze the handle, Sweep side to side.',
             detail='The operating sequence for a portable fire extinguisher. Aiming at flames rather than the base is the common error.',
             example='The volunteer pulls the pin and aims low at the burning material.'),

        # ── Hazards & Threats ────────────────────────────────────
        dict(term='Natural Hazard', category='hazards',
             meaning='A threat arising from natural processes in weather, geology or biology.',
             detail='Hurricanes, tornadoes, earthquakes, floods, wildfire and pandemics. Often predictable in location if not in timing.',
             example='A coastal county plans for hurricane storm surge every season.'),
        dict(term='Technological Hazard', category='hazards',
             meaning='A threat from failure of infrastructure or industrial processes.',
             detail='Chemical releases, power failures, dam breaches, transportation accidents and cyber attacks on critical systems.',
             example='A derailment releasing chlorine triggers a technological hazard response.'),
        dict(term='Shelter in Place', category='hazards',
             meaning='Staying inside and sealing the building when outside air is dangerous.',
             detail='Correct for chemical releases and some severe weather. Close windows, shut off ventilation, and move to an interior room.',
             example='A chemical plume downwind prompts a shelter-in-place order.'),
        dict(term='Evacuation', category='hazards',
             meaning='Moving people away from a threatened area.',
             detail='Correct for fire, flood, hurricane and structural threats. Needs routes, transport for people without vehicles, and a destination.',
             example='A wildfire advancing on a canyon community triggers evacuation.'),
        dict(term='Storm Surge', category='hazards',
             meaning='Water pushed ashore by a storm’s winds, above the normal tide.',
             detail='The deadliest part of most hurricanes. Depth, not wind category, drives evacuation zones.',
             example='A 12-foot surge floods streets a mile inland.'),
        dict(term='Earthquake Response', category='hazards',
             meaning='Drop, cover and hold on, then check for injuries and hazards after shaking stops.',
             detail='Doorways are not safer than a sturdy table. Expect aftershocks and check gas lines before using any flame.',
             example='Students drop under desks and hold on until the shaking ends.'),
        dict(term='Hazardous Material Recognition', category='hazards',
             meaning='Identifying a chemical threat from placards, labels and container shape at a distance.',
             detail='CERT volunteers observe from uphill and upwind and report; they do not approach or attempt containment.',
             example='A team reads a placard through binoculars and reports the four-digit UID.'),
        dict(term='CBRNE', category='hazards',
             meaning='Chemical, biological, radiological, nuclear and explosive threats.',
             detail='Grouped because each requires distance, isolation and specialized response rather than immediate rescue.',
             example='A suspicious package response follows CBRNE isolation protocols.'),
        dict(term='Time, Distance, Shielding', category='hazards',
             meaning='The three ways to reduce radiation exposure.',
             detail='Limit time near the source, maximize distance, and put mass between you and it. Distance is the most effective of the three.',
             example='Responders rotate crews to limit individual exposure time.'),
        dict(term='Secondary Device', category='hazards',
             meaning='An explosive placed to injure responders arriving at a first blast.',
             detail='Why responders avoid obvious staging points and search their own area before setting up.',
             example='A team sweeps a staging area before establishing a treatment point.'),
        dict(term='Pandemic', category='hazards',
             meaning='An epidemic spread across countries or continents.',
             detail='Strains health systems over months rather than hours, so preparedness focuses on surge capacity, supply chains and continuity.',
             example='A hospital activates surge staffing plans during a pandemic wave.'),

        # ── Preparedness ─────────────────────────────────────────
        dict(term='Disaster Supply Kit', category='prepare',
             meaning='Supplies to sustain a household without outside help.',
             detail='Water at one gallon per person per day, non-perishable food, light, radio, first aid, medications, sanitation and copies of documents.',
             example='A family keeps three days of supplies at home and a smaller kit in the car.'),
        dict(term='72-Hour Rule', category='prepare',
             meaning='The expectation that households be self-sufficient for at least three days.',
             detail='Many agencies now advise two weeks, since large disasters can delay aid well beyond 72 hours.',
             example='A coastal household stores fourteen days of water before hurricane season.'),
        dict(term='Family Communication Plan', category='prepare',
             meaning='An agreed plan for how a household reconnects when separated.',
             detail='Includes an out-of-area contact, since long-distance lines often work when local ones are saturated, plus two meeting points.',
             example='Each family member carries a card with the out-of-state contact’s number.'),
        dict(term='Go Bag', category='prepare',
             meaning='A portable kit ready to carry during an immediate evacuation.',
             detail='Lighter than a home kit: water, snacks, medication, documents, phone charger, cash and a change of clothes.',
             example='A go bag sits by the door during wildfire season.'),
        dict(term='Mitigation', category='prepare',
             meaning='Action taken before an event to reduce its impact.',
             detail='The first phase of emergency management. Includes building codes, levees, strapping water heaters and land-use planning.',
             example='Bolting a house to its foundation is earthquake mitigation.'),
        dict(term='Four Phases of Emergency Management', category='prepare',
             meaning='Mitigation, preparedness, response and recovery.',
             detail='A continuous cycle rather than a sequence — recovery from one event feeds mitigation for the next.',
             example='Rebuilding to a higher elevation after a flood is recovery and mitigation at once.'),
        dict(term='Emergency Operations Center', category='prepare',
             meaning='A facility where officials coordinate resources and information during an incident.',
             detail='Supports the field rather than directing tactics — the incident commander runs the scene.',
             example='The county EOC activates to coordinate shelters and supply.'),
        dict(term='Mass Care Shelter', category='prepare',
             meaning='A facility providing lodging, food and basic health services to displaced people.',
             detail='Must accommodate disabilities, service animals and medical needs. Registration tracks who is present for reunification.',
             example='A high school gym opens as a shelter after a flood.'),
        dict(term='Points of Distribution', category='prepare',
             meaning='Sites where supplies are handed directly to the public after a disaster.',
             detail='Located for traffic flow and served by a supply chain from a staging area.',
             example='Water and ice are distributed from a stadium parking lot.'),
        dict(term='Continuity of Operations', category='prepare',
             meaning='Planning that lets essential functions continue through a disruption.',
             detail='Identifies essential functions, succession of leadership, alternate facilities and vital records.',
             example='A clinic plans which services it will run from a backup site.'),

        # ── Disaster Psychology ──────────────────────────────────
        dict(term='Psychological First Aid', category='psych',
             meaning='Practical, non-intrusive support for people in the immediate aftermath of a disaster.',
             detail='Offers safety, comfort, information and connection. It is not counseling, and does not require survivors to describe the event.',
             example='A volunteer sits with a survivor, offers water, and helps them contact family.'),
        dict(term='Acute Stress Reaction', category='psych',
             meaning='A normal short-term reaction to an abnormal event.',
             detail='Disorientation, irritability, trouble sleeping, difficulty concentrating. Usually resolves with rest and support.',
             example='A survivor who cannot recall the last hour is having an acute stress reaction.'),
        dict(term='Post-Traumatic Stress Disorder', category='psych',
             meaning='Symptoms lasting more than a month after trauma, with intrusion, avoidance and hyperarousal.',
             detail='Distinguished from acute stress by duration and impairment. Needs professional treatment, not just support.',
             example='A responder still having nightmares three months later is referred for care.'),
        dict(term='Survivor Guilt', category='psych',
             meaning='Distress at having survived when others did not.',
             detail='Common among both survivors and responders. Normalizing the feeling is part of psychological first aid.',
             example='A volunteer struggles with having passed a victim they could not help.'),
        dict(term='Responder Stress Management', category='psych',
             meaning='Steps that keep rescuers functional: rotation, rest, hydration and debriefing.',
             detail='Working past exhaustion causes errors and injuries. Team leaders enforce breaks rather than leaving it to individuals.',
             example='A leader rotates a team out after two hours in heavy gear.'),
        dict(term='Rapport', category='psych',
             meaning='A relationship of trust that lets a survivor accept help.',
             detail='Built by introducing yourself, asking permission, listening more than talking, and not promising what you cannot deliver.',
             example='A volunteer kneels to eye level and asks how they can help.'),
        dict(term='Cultural Sensitivity in Disaster', category='psych',
             meaning='Adapting help to the language, customs and beliefs of those affected.',
             detail='Affects food in shelters, privacy, gender of caregivers and how bad news is delivered.',
             example='A shelter arranges a private space for prayer.'),
    ],
))


# ═══════════════════════════════════════════════════════════════════
#  Job Seeking Skills
# ═══════════════════════════════════════════════════════════════════
SPECS.append(dict(
    slug='job-seeking-skills',
    name='Job Seeking Skills',
    eyebrow='Leadership Event — Job Seeking Skills',
    h1_lead='Résumés, Interviews &',
    h1_em='Job Seeking Skills',
    subtitle='A study companion for résumés, cover letters, interviewing, professionalism and career '
             'planning — built for HOSA competitors preparing for the Job Seeking Skills and '
             'Interviewing Skills competitive events.',
    test_blurb='résumé, interview and professionalism concepts',
    topics='Résumé formats, cover letters, applications, interview types and questions, professionalism, career planning',
    tips=[
        'Know the three résumé formats and when each one helps: chronological, functional and combination.',
        'Accomplishment statements beat duty statements. Lead with a strong verb and attach a number wherever you can.',
        'The STAR method structures behavioral answers. Practice it out loud until the four parts come automatically.',
        'Never badmouth a former employer. Judges score professionalism as heavily as content.',
        'Send a thank-you within 24 hours. It is the most commonly skipped step and the easiest point to earn.',
        'Learn which interview questions are illegal — age, marital status, religion, national origin, disability, pregnancy.',
    ],
    categories=[
        ('resume',    'Résumés'),
        ('letters',   'Letters & Applications'),
        ('interview', 'Interviewing'),
        ('prof',      'Professionalism'),
        ('career',    'Career Planning'),
        ('legal',     'Employment Law'),
    ],
    terms=[
        # ── Résumés ──────────────────────────────────────────────
        dict(term='Résumé', category='resume',
             meaning='A brief written summary of a candidate’s skills, education and experience.',
             detail='One page for students and early-career applicants. Its job is to earn an interview, not to tell a whole life story.',
             example='A junior applying to a hospital volunteer program submits a one-page résumé.'),
        dict(term='Chronological Résumé', category='resume',
             meaning='A résumé listing experience in reverse order, most recent first.',
             detail='The format employers expect. Works best with steady, relevant experience and no long gaps.',
             example='A candidate with three straight years in a clinic uses a chronological format.'),
        dict(term='Functional Résumé', category='resume',
             meaning='A résumé organized by skill groups rather than by job history.',
             detail='Useful for career changers or people with gaps, but recruiters treat it with suspicion because it hides dates.',
             example='Someone returning to work after several years groups entries under skill headings.'),
        dict(term='Combination Résumé', category='resume',
             meaning='A résumé leading with a skills summary and following with a dated work history.',
             detail='Gets the benefit of a skills focus without hiding the timeline. Common for students with limited but relevant experience.',
             example='A student leads with clinical skills, then lists jobs with dates.'),
        dict(term='Curriculum Vitae', category='resume',
             meaning='A long, comprehensive academic record of education, research and publications.',
             detail='Standard for academic, research and many medical positions. Has no page limit and grows over a career.',
             example='A physician applying for a faculty post submits a CV, not a résumé.'),
        dict(term='Objective Statement', category='resume',
             meaning='A one-line statement of the position sought and what the candidate offers.',
             detail='Largely replaced by a summary of qualifications, because objectives tend to state what the applicant wants rather than what they bring.',
             example='"Seeking a patient-care technician role where two years of CNA experience add value."'),
        dict(term='Summary of Qualifications', category='resume',
             meaning='A short opening block of the candidate’s strongest, most relevant credentials.',
             detail='Three to five lines at the top. Tailored per application, since it is what a recruiter reads in the first few seconds.',
             example='A summary naming CPR certification, 200 volunteer hours and bilingual fluency.'),
        dict(term='Accomplishment Statement', category='resume',
             meaning='A bullet describing a result achieved rather than a task performed.',
             detail='Built as action verb, task, measurable result. Numbers make it credible.',
             example='"Trained 12 new volunteers, cutting onboarding time by half."'),
        dict(term='Action Verb', category='resume',
             meaning='A strong verb starting a résumé bullet.',
             detail='Coordinated, implemented, trained, streamlined. Passive phrases like "responsible for" waste the strongest position in the line.',
             example='"Coordinated a blood drive" rather than "was responsible for the blood drive."'),
        dict(term='Keyword Optimization', category='resume',
             meaning='Using the exact terms from the job posting so scanning software matches the résumé.',
             detail='Applicant tracking systems filter on literal matches, so mirror the posting’s wording rather than a synonym.',
             example='A posting asking for "phlebotomy" gets that word, not "blood draws".'),
        dict(term='Applicant Tracking System', category='resume',
             meaning='Software that stores and screens applications before a human reads them.',
             detail='Favors simple formatting — standard headings, no tables, no text in images, a common font.',
             example='A résumé built in columns loses its ordering when parsed by an ATS.'),
        dict(term='References', category='resume',
             meaning='People who can speak to a candidate’s work and character.',
             detail='Three is standard, supervisors or teachers rather than family. Always ask permission first, and supply them on request rather than on the résumé.',
             example='A student asks a clinical supervisor before listing them.'),
        dict(term='Portfolio', category='resume',
             meaning='An organized collection of work samples, certifications and evaluations.',
             detail='In HOSA competition it typically holds the résumé, certifications, letters of recommendation and evidence of service.',
             example='A competitor brings a tabbed portfolio to the interview.'),

        # ── Letters & Applications ───────────────────────────────
        dict(term='Cover Letter', category='letters',
             meaning='A one-page letter connecting a candidate’s background to a specific job.',
             detail='Three paragraphs: why this job, what you bring with evidence, and a request for an interview. Addressed to a named person where possible.',
             example='A letter opens by naming the position and where it was advertised.'),
        dict(term='Letter of Application', category='letters',
             meaning='A cover letter sent in response to an advertised opening.',
             detail='Differs from a letter of inquiry, which approaches an employer with no posted vacancy.',
             example='A candidate responds to a posted medical assistant opening.'),
        dict(term='Letter of Inquiry', category='letters',
             meaning='A letter to an employer who has not advertised a position.',
             detail='Asks about future openings and is usually followed up by phone. Reaches jobs before they are posted.',
             example='A student writes to a clinic asking about summer openings.'),
        dict(term='Block Style', category='letters',
             meaning='A business-letter format with every line flush left and no indentation.',
             detail='The standard professional format. Paragraphs are separated by a blank line rather than an indent.',
             example='A cover letter with all elements aligned to the left margin.'),
        dict(term='Salutation', category='letters',
             meaning='The greeting line of a letter.',
             detail='Use a name whenever one can be found. "Dear Hiring Manager" is acceptable; "To Whom It May Concern" reads as no effort.',
             example='"Dear Ms. Alvarez:" followed by a colon in business style.'),
        dict(term='Job Application', category='letters',
             meaning='An employer’s standard form collecting the same information from every candidate.',
             detail='Complete every field, write legibly in black ink, and never leave blanks — use N/A. Accuracy matters because it is a legal document.',
             example='An applicant writes N/A rather than leaving a line empty.'),
        dict(term='Thank-You Letter', category='letters',
             meaning='A note sent after an interview thanking the interviewer and restating interest.',
             detail='Within 24 hours. Mention something specific from the conversation, and correct or add anything you wish you had said.',
             example='An emailed note the same evening referencing a topic the interviewer raised.'),
        dict(term='Letter of Resignation', category='letters',
             meaning='Written notice that an employee is leaving, normally two weeks ahead.',
             detail='Short, positive and dated. Burning a bridge costs a reference in a field where people move between the same few employers.',
             example='A brief letter stating the last working day and thanking the employer.'),
        dict(term='Letter of Recommendation', category='letters',
             meaning='A letter from someone who can vouch for a candidate’s ability and character.',
             detail='Give the writer your résumé, the posting and plenty of notice. Specific letters carry far more weight than generic praise.',
             example='A teacher writes about a specific project the student led.'),

        # ── Interviewing ─────────────────────────────────────────
        dict(term='Screening Interview', category='interview',
             meaning='A short first interview, often by phone, that narrows the candidate pool.',
             detail='Confirms basics: availability, salary range, credentials. Brevity and clarity matter more than depth.',
             example='A recruiter calls to confirm certification and schedule availability.'),
        dict(term='Behavioral Interview', category='interview',
             meaning='An interview asking for real past examples rather than hypotheticals.',
             detail='Built on the premise that past behavior predicts future behavior. Questions begin "Tell me about a time when..."',
             example='"Tell me about a time you disagreed with a supervisor."'),
        dict(term='STAR Method', category='interview',
             meaning='Situation, Task, Action, Result — a structure for answering behavioral questions.',
             detail='Keeps answers concrete and bounded. The Result is the part candidates most often omit, and the part that scores.',
             example='A candidate names the situation, their specific action, and the measurable outcome.'),
        dict(term='Panel Interview', category='interview',
             meaning='An interview conducted by several people at once.',
             detail='Answer to the person who asked, then make eye contact with the rest. Get everyone’s name for the thank-you notes.',
             example='Three department staff interview a candidate together.'),
        dict(term='Group Interview', category='interview',
             meaning='An interview in which several candidates are assessed together.',
             detail='Tests teamwork and how you behave around competitors. Dominating the room scores as poorly as staying silent.',
             example='Four applicants work through a scenario while managers observe.'),
        dict(term='Situational Interview', category='interview',
             meaning='An interview posing hypothetical problems to see how a candidate would respond.',
             detail='Asks what you would do, where behavioral asks what you did. Reasoning aloud matters more than the specific answer.',
             example='"What would you do if a patient refused a required procedure?"'),
        dict(term='Stress Interview', category='interview',
             meaning='An interview using deliberate pressure to see how a candidate reacts.',
             detail='Rapid questions, interruptions or silence. The test is composure, so stay calm and ask for clarification.',
             example='An interviewer stays silent after an answer to see if the candidate fills the gap.'),
        dict(term='Open-Ended Question', category='interview',
             meaning='A question that cannot be answered yes or no.',
             detail='Invites an answer with substance. Good candidates also ask them, to learn something real about the role.',
             example='"What does success look like in this role after six months?"'),
        dict(term='Tell Me About Yourself', category='interview',
             meaning='The standard opener, answered in about two minutes with a professional summary.',
             detail='Present, past, future: what you do now, how you got here, why this role. Not a personal history.',
             example='A candidate covers current training, relevant experience, and why this clinic.'),
        dict(term='Questions for the Interviewer', category='interview',
             meaning='Questions a candidate prepares to ask at the end of an interview.',
             detail='Having none reads as indifference. Ask about the team, expectations and development — not pay, on a first interview.',
             example='"How is training structured for someone new to this unit?"'),
        dict(term='Mock Interview', category='interview',
             meaning='A rehearsal interview with feedback.',
             detail='The most reliable way to improve. Recording it exposes filler words and habits that feedback alone misses.',
             example='A HOSA adviser runs practice interviews before the competition.'),
        dict(term='Salary Negotiation', category='interview',
             meaning='Discussing pay once an offer has been made.',
             detail='Research the range first and let the employer name a figure where possible. Negotiate the whole package, not only salary.',
             example='A candidate asks about the range for the role before naming a number.'),

        # ── Professionalism ──────────────────────────────────────
        dict(term='Professional Dress', category='prof',
             meaning='Conservative, clean, well-fitted clothing appropriate to the workplace.',
             detail='Dress one level above the role. Minimal fragrance, covered tattoos where expected, neat hair and nails for clinical settings.',
             example='A candidate wears a suit to a hospital interview even though staff wear scrubs.'),
        dict(term='First Impression', category='prof',
             meaning='The judgment formed in the first seconds of meeting someone.',
             detail='Driven by punctuality, grooming, handshake, eye contact and posture. Hard to reverse once set.',
             example='A candidate arrives ten minutes early, stands to greet, and makes eye contact.'),
        dict(term='Nonverbal Communication', category='prof',
             meaning='Meaning conveyed by posture, gesture, expression and eye contact rather than words.',
             detail='Carries much of the message in an interview. Crossed arms, fidgeting and a downward gaze undercut a strong answer.',
             example='An interviewer reads confidence from an upright, open posture.'),
        dict(term='Active Listening', category='prof',
             meaning='Attending fully to the speaker and confirming understanding before responding.',
             detail='Shown by nodding, not interrupting, and restating the question when it is complex.',
             example='A candidate says "So you’re asking how I handle conflicting instructions?"'),
        dict(term='Work Ethic', category='prof',
             meaning='Reliability, initiative and diligence in doing the job.',
             detail='Employers rank it above technical skill for entry-level roles, because skills can be taught.',
             example='An intern who arrives early and asks for extra work demonstrates it.'),
        dict(term='Soft Skills', category='prof',
             meaning='Interpersonal abilities like communication, teamwork, adaptability and problem solving.',
             detail='Distinct from technical skills. Most often cited by healthcare employers as the gap in new hires.',
             example='A résumé shows teamwork through a documented group project result.'),
        dict(term='Digital Footprint', category='prof',
             meaning='The publicly visible record of someone’s online activity.',
             detail='Employers do look. Privacy settings, a professional profile photo and a clean public search matter before applying.',
             example='A candidate reviews their public posts before submitting applications.'),
        dict(term='Professional Networking', category='prof',
             meaning='Building relationships that lead to information, advice and opportunity.',
             detail='Most jobs are filled through connections rather than postings. Give before you ask.',
             example='A student stays in touch with a clinical supervisor after a rotation.'),
        dict(term='Elevator Pitch', category='prof',
             meaning='A 30-second self-introduction covering who you are and what you are looking for.',
             detail='Used at career fairs and chance meetings. Rehearsed enough to sound natural rather than recited.',
             example='A student introduces themselves and their goal at a hospital career fair.'),
        dict(term='Punctuality', category='prof',
             meaning='Arriving on time, which for an interview means ten to fifteen minutes early.',
             detail='Earlier than fifteen minutes is an imposition. Lateness to an interview is usually disqualifying.',
             example='A candidate parks early and waits in the car until ten minutes before.'),

        # ── Career Planning ──────────────────────────────────────
        dict(term='Self-Assessment', category='career',
             meaning='Examining your interests, values, skills and personality to guide career choices.',
             detail='Interest inventories and values exercises reduce the odds of training for work that will not suit you.',
             example='A student takes an interest inventory before choosing a health pathway.'),
        dict(term='Career Pathway', category='career',
             meaning='A sequence of education and roles leading toward an occupation.',
             detail='Health science pathways include therapeutic services, diagnostic services, health informatics, support services, and biotechnology research.',
             example='A CNA role on the way to nursing school is a step on a pathway.'),
        dict(term='Job Shadowing', category='career',
             meaning='Observing a professional at work to learn what the job actually involves.',
             detail='Cheap, short and highly informative. Often the fastest way to rule a career in or out.',
             example='A student spends a day with a respiratory therapist.'),
        dict(term='Internship', category='career',
             meaning='A temporary supervised position providing practical experience in a field.',
             detail='May be paid or unpaid, for credit or not. Frequently converts into an offer.',
             example='A summer internship in a hospital lab leads to a part-time job.'),
        dict(term='Certification', category='career',
             meaning='A credential from a professional body showing a defined standard has been met.',
             detail='Distinct from licensure, which is granted by a state and legally required to practice.',
             example='Passing the CNA exam earns a certification recognized by employers.'),
        dict(term='Licensure', category='career',
             meaning='State permission required to practice an occupation legally.',
             detail='Unlike certification, practicing without it is illegal. Requirements and reciprocity vary by state.',
             example='A nurse must hold a state license to practice in that state.'),
        dict(term='Continuing Education', category='career',
             meaning='Ongoing training required to maintain a credential.',
             detail='Measured in contact hours or CEUs and audited at renewal. Keeps practitioners current as standards change.',
             example='A therapist completes 20 contact hours before license renewal.'),
        dict(term='SMART Goal', category='career',
             meaning='A goal that is Specific, Measurable, Achievable, Relevant and Time-bound.',
             detail='Turns an intention into something you can act on and check.',
             example='"Complete CNA certification by June 1" rather than "get certified".'),
        dict(term='Transferable Skill', category='career',
             meaning='A skill that carries from one role or industry to another.',
             detail='Communication, scheduling, conflict resolution and record-keeping. The bridge for candidates changing fields.',
             example='Retail customer service transfers to front-desk patient intake.'),

        # ── Employment Law ───────────────────────────────────────
        dict(term='Equal Employment Opportunity', category='legal',
             meaning='The principle that hiring decisions must not rest on protected characteristics.',
             detail='Enforced by the EEOC. Protected classes include race, color, religion, sex, national origin, age, disability and genetic information.',
             example='An employer may not ask an applicant’s age on an application.'),
        dict(term='Illegal Interview Question', category='legal',
             meaning='A question about a protected characteristic rather than ability to do the job.',
             detail='Covers age, marital and family status, religion, national origin, disability, pregnancy and arrest record.',
             example='"Do you plan to have children?" is not a lawful question.'),
        dict(term='Americans with Disabilities Act', category='legal',
             meaning='The law barring disability discrimination and requiring reasonable accommodation.',
             detail='Employers may ask whether you can perform essential functions, with or without accommodation, but not about the disability itself.',
             example='An employer asks if the candidate can lift 50 pounds, not about a back condition.'),
        dict(term='Reasonable Accommodation', category='legal',
             meaning='A change to a job or workplace that lets a qualified person with a disability work.',
             detail='Required unless it imposes undue hardship. Modified schedules, equipment and reassignment are common.',
             example='A screen reader is provided for an employee with low vision.'),
        dict(term='At-Will Employment', category='legal',
             meaning='An arrangement in which either party may end employment at any time, for almost any reason.',
             detail='The default in most U.S. states. Cannot be used to cover discrimination or retaliation.',
             example='An employee may resign without cause, and be let go without cause.'),
        dict(term='Fair Labor Standards Act', category='legal',
             meaning='The federal law setting minimum wage, overtime and child labor rules.',
             detail='Overtime at time and a half beyond 40 hours for non-exempt employees. Sets limits on hours for workers under 18.',
             example='A 16-year-old’s hours during the school year are limited under the FLSA.'),
        dict(term='I-9 Form', category='legal',
             meaning='The federal form verifying a new hire’s identity and authorization to work.',
             detail='Completed within three days of starting. The employee chooses which acceptable documents to present.',
             example='A new employee presents a driver’s license and Social Security card.'),
        dict(term='W-4 Form', category='legal',
             meaning='The form telling an employer how much federal income tax to withhold.',
             detail='Filed at hire and updated when circumstances change. Distinct from the W-2, which reports annual earnings.',
             example='An employee updates their W-4 after a change in dependents.'),
        dict(term='Background Check', category='legal',
             meaning='Verification of a candidate’s history before employment is confirmed.',
             detail='Healthcare employers commonly check criminal record, licensure, exclusion lists and immunization status. Written consent is required.',
             example='A hospital offer is contingent on a background check and drug screen.'),
    ],
))
